[P1_Replace_Type]^private char toolTipText;^66^^^^^61^71^private String toolTipText;^[CLASS] AbstractXYAnnotation   [VARIABLES] 
[P1_Replace_Type]^private char url;^69^^^^^64^74^private String url;^[CLASS] AbstractXYAnnotation   [VARIABLES] 
[P8_Replace_Mix]^this.toolTipText = true;^75^^^^^74^77^this.toolTipText = null;^[CLASS] AbstractXYAnnotation  [METHOD] <init> [RETURN_TYPE] AbstractXYAnnotation()   [VARIABLES] String  toolTipText  url  boolean  
[P11_Insert_Donor_Statement]^this.url = null;this.toolTipText = null;^75^^^^^74^77^this.toolTipText = null;^[CLASS] AbstractXYAnnotation  [METHOD] <init> [RETURN_TYPE] AbstractXYAnnotation()   [VARIABLES] String  toolTipText  url  boolean  
[P11_Insert_Donor_Statement]^this.toolTipText = text;this.toolTipText = null;^75^^^^^74^77^this.toolTipText = null;^[CLASS] AbstractXYAnnotation  [METHOD] <init> [RETURN_TYPE] AbstractXYAnnotation()   [VARIABLES] String  toolTipText  url  boolean  
[P8_Replace_Mix]^this.url = false;^76^^^^^74^77^this.url = null;^[CLASS] AbstractXYAnnotation  [METHOD] <init> [RETURN_TYPE] AbstractXYAnnotation()   [VARIABLES] String  toolTipText  url  boolean  
[P11_Insert_Donor_Statement]^this.toolTipText = null;this.url = null;^76^^^^^74^77^this.url = null;^[CLASS] AbstractXYAnnotation  [METHOD] <init> [RETURN_TYPE] AbstractXYAnnotation()   [VARIABLES] String  toolTipText  url  boolean  
[P11_Insert_Donor_Statement]^this.url = url;this.url = null;^76^^^^^74^77^this.url = null;^[CLASS] AbstractXYAnnotation  [METHOD] <init> [RETURN_TYPE] AbstractXYAnnotation()   [VARIABLES] String  toolTipText  url  boolean  
[P12_Insert_Condition]^if  ( this.url != null )  { this.url = null; }^76^^^^^74^77^this.url = null;^[CLASS] AbstractXYAnnotation  [METHOD] <init> [RETURN_TYPE] AbstractXYAnnotation()   [VARIABLES] String  toolTipText  url  boolean  
[P5_Replace_Variable]^return url;^89^^^^^88^90^return this.toolTipText;^[CLASS] AbstractXYAnnotation  [METHOD] getToolTipText [RETURN_TYPE] String   [VARIABLES] String  toolTipText  url  boolean  
[P5_Replace_Variable]^this.toolTipText = url;^100^^^^^99^101^this.toolTipText = text;^[CLASS] AbstractXYAnnotation  [METHOD] setToolTipText [RETURN_TYPE] void   String text [VARIABLES] String  text  toolTipText  url  boolean  
[P11_Insert_Donor_Statement]^this.toolTipText = null;this.toolTipText = text;^100^^^^^99^101^this.toolTipText = text;^[CLASS] AbstractXYAnnotation  [METHOD] setToolTipText [RETURN_TYPE] void   String text [VARIABLES] String  text  toolTipText  url  boolean  
[P12_Insert_Condition]^if  ( this.toolTipText != null )  { this.toolTipText = text; }^100^^^^^99^101^this.toolTipText = text;^[CLASS] AbstractXYAnnotation  [METHOD] setToolTipText [RETURN_TYPE] void   String text [VARIABLES] String  text  toolTipText  url  boolean  
[P5_Replace_Variable]^return url;^112^^^^^111^113^return this.url;^[CLASS] AbstractXYAnnotation  [METHOD] getURL [RETURN_TYPE] String   [VARIABLES] String  text  toolTipText  url  boolean  
[P8_Replace_Mix]^return toolTipText;^112^^^^^111^113^return this.url;^[CLASS] AbstractXYAnnotation  [METHOD] getURL [RETURN_TYPE] String   [VARIABLES] String  text  toolTipText  url  boolean  
[P5_Replace_Variable]^this.url = toolTipText;^123^^^^^122^124^this.url = url;^[CLASS] AbstractXYAnnotation  [METHOD] setURL [RETURN_TYPE] void   String url [VARIABLES] String  text  toolTipText  url  boolean  
[P11_Insert_Donor_Statement]^this.url = null;this.url = url;^123^^^^^122^124^this.url = url;^[CLASS] AbstractXYAnnotation  [METHOD] setURL [RETURN_TYPE] void   String url [VARIABLES] String  text  toolTipText  url  boolean  
[P2_Replace_Operator]^if  ( info != null )  {^156^^^^^153^166^if  ( info == null )  {^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P8_Replace_Mix]^if  ( info == true )  {^156^^^^^153^166^if  ( info == null )  {^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P9_Replace_Statement]^if  ( this.url != null )  {^156^^^^^153^166^if  ( info == null )  {^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P9_Replace_Statement]^if  ( entities == null )  {^156^^^^^153^166^if  ( info == null )  {^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P9_Replace_Statement]^if  ( obj == this )  {^156^^^^^153^166^if  ( info == null )  {^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P15_Unwrap_Block]^return ;^156^157^158^^^153^166^if  ( info == null )  { return; }^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P16_Remove_Block]^^156^157^158^^^153^166^if  ( info == null )  { return; }^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P13_Insert_Block]^if  ( entities == null )  {     return ; }^156^^^^^153^166^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P13_Insert_Block]^if  ( obj ==  ( this )  )  {     return true; }^156^^^^^153^166^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P14_Delete_Statement]^^159^^^^^153^166^EntityCollection entities = info.getOwner (  ) .getEntityCollection (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P2_Replace_Operator]^if  ( entities != null )  {^160^^^^^153^166^if  ( entities == null )  {^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P8_Replace_Mix]^if  ( entities == this )  {^160^^^^^153^166^if  ( entities == null )  {^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P9_Replace_Statement]^if  ( info == null )  {^160^^^^^153^166^if  ( entities == null )  {^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P9_Replace_Statement]^if  ( this.url != null )  {^160^^^^^153^166^if  ( entities == null )  {^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P15_Unwrap_Block]^return ;^160^161^162^^^153^166^if  ( entities == null )  { return; }^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P16_Remove_Block]^^160^161^162^^^153^166^if  ( entities == null )  { return; }^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P13_Insert_Block]^if  ( info == null )  {     return ; }^160^^^^^153^166^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P13_Insert_Block]^if  ( obj ==  ( this )  )  {     return true; }^160^^^^^153^166^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P4_Replace_Constructor]^XYAnnotationEntity entity = new XYAnnotationEntity (  rendererIndex, toolTipText, urlText ) ;^163^164^^^^153^166^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, urlText ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P4_Replace_Constructor]^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot,  toolTipText, urlText ) ;^163^164^^^^153^166^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, urlText ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P4_Replace_Constructor]^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex,  urlText ) ;^163^164^^^^153^166^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, urlText ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P4_Replace_Constructor]^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText ) ;^163^164^^^^153^166^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, urlText ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P5_Replace_Variable]^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, url, urlText ) ;^163^164^^^^153^166^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, urlText ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P5_Replace_Variable]^XYAnnotationEntity entity = new XYAnnotationEntity ( toolTipText, rendererIndex, hotspot, urlText ) ;^163^164^^^^153^166^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, urlText ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P5_Replace_Variable]^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, toolTipText, rendererIndex, urlText ) ;^163^164^^^^153^166^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, urlText ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P5_Replace_Variable]^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, urlText, toolTipText ) ;^163^164^^^^153^166^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, urlText ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P5_Replace_Variable]^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, urlText, toolTipText, rendererIndex ) ;^163^164^^^^153^166^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, urlText ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P8_Replace_Mix]^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, url ) ;^163^164^^^^153^166^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, urlText ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P5_Replace_Variable]^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, urlText, urlText ) ;^163^164^^^^153^166^XYAnnotationEntity entity = new XYAnnotationEntity ( hotspot, rendererIndex, toolTipText, urlText ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P14_Delete_Statement]^^165^^^^^153^166^entities.add ( entity ) ;^[CLASS] AbstractXYAnnotation  [METHOD] addEntity [RETURN_TYPE] void   PlotRenderingInfo info Shape hotspot int rendererIndex String toolTipText String urlText [VARIABLES] XYAnnotationEntity  entity  Shape  hotspot  boolean  PlotRenderingInfo  info  EntityCollection  entities  String  text  toolTipText  url  urlText  int  rendererIndex  
[P2_Replace_Operator]^if  ( obj >= this )  {^176^^^^^175^190^if  ( obj == this )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P9_Replace_Statement]^if  ( info == null )  {^176^^^^^175^190^if  ( obj == this )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P15_Unwrap_Block]^return true;^176^177^178^^^175^190^if  ( obj == this )  { return true; }^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P16_Remove_Block]^^176^177^178^^^175^190^if  ( obj == this )  { return true; }^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P13_Insert_Block]^if  ( entities == null )  {     return ; }^176^^^^^175^190^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P13_Insert_Block]^if  ( info == null )  {     return ; }^176^^^^^175^190^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P3_Replace_Literal]^return false;^177^^^^^175^190^return true;^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P2_Replace_Operator]^if  ( ! ( obj  !=  AbstractXYAnnotation )  )  {^179^^^^^175^190^if  ( ! ( obj instanceof AbstractXYAnnotation )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P15_Unwrap_Block]^return false;^179^180^181^^^175^190^if  ( ! ( obj instanceof AbstractXYAnnotation )  )  { return false; }^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P16_Remove_Block]^^179^180^181^^^175^190^if  ( ! ( obj instanceof AbstractXYAnnotation )  )  { return false; }^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P3_Replace_Literal]^return true;^180^^^^^175^190^return false;^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P12_Insert_Condition]^if  ( ! ( obj instanceof AbstractXYAnnotation )  )  { AbstractXYAnnotation that =  ( AbstractXYAnnotation )  obj; }^182^^^^^175^190^AbstractXYAnnotation that =  ( AbstractXYAnnotation )  obj;^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.toolTipText, urlText )  )  {^183^^^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.toolTipText.toolTipText )  )  {^183^^^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal (  that.toolTipText )  )  {^183^^^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.toolTipText )  )  {^183^^^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( that, this.toolTipText.toolTipText )  )  {^183^^^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( that.toolTipText, this.toolTipText )  )  {^183^^^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P8_Replace_Mix]^if  ( !ObjectUtilities.equal ( urlText, that.toolTipText )  )  {^183^^^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P9_Replace_Statement]^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  {^183^^^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P15_Unwrap_Block]^return false;^183^184^185^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  { return false; }^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P16_Remove_Block]^^183^184^185^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  { return false; }^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P13_Insert_Block]^if  ( ! ( equal ( this.url, that.url )  )  )  {     return false; }^183^^^^^175^190^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P3_Replace_Literal]^return true;^184^^^^^175^190^return false;^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.toolTipText, url )  )  {^183^^^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText.toolTipText )  )  {^183^^^^^175^190^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P13_Insert_Block]^if  ( ! ( equal ( this.toolTipText, that.toolTipText )  )  )  {     return false; }^183^^^^^175^190^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( urlText, that.url )  )  {^186^^^^^175^190^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.url, urlText )  )  {^186^^^^^175^190^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.url.url )  )  {^186^^^^^175^190^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal (  that.url )  )  {^186^^^^^175^190^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.url )  )  {^186^^^^^175^190^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.url, that.url.url )  )  {^186^^^^^175^190^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( that.url, this.url )  )  {^186^^^^^175^190^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P9_Replace_Statement]^if  ( !ObjectUtilities.equal ( this.toolTipText, that.toolTipText )  )  {^186^^^^^175^190^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P15_Unwrap_Block]^return false;^186^187^188^^^175^190^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  { return false; }^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P16_Remove_Block]^^186^187^188^^^175^190^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  { return false; }^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P13_Insert_Block]^if  ( ! ( equal ( this.toolTipText, that.toolTipText )  )  )  {     return false; }^186^^^^^175^190^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P3_Replace_Literal]^return true;^187^^^^^175^190^return false;^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P8_Replace_Mix]^if  ( !ObjectUtilities.equal ( this.url, url )  )  {^186^^^^^175^190^if  ( !ObjectUtilities.equal ( this.url, that.url )  )  {^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P13_Insert_Block]^if  ( ! ( equal ( this.url, that.url )  )  )  {     return false; }^186^^^^^175^190^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P3_Replace_Literal]^return false;^189^^^^^175^190^return true;^[CLASS] AbstractXYAnnotation  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] AbstractXYAnnotation  that  Object  obj  String  text  toolTipText  url  urlText  boolean  
[P1_Replace_Type]^short  result = 193;^198^^^^^197^206^int result = 193;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P3_Replace_Literal]^int result = 186;^198^^^^^197^206^int result = 193;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P2_Replace_Operator]^if  ( this.toolTipText == null )  {^199^^^^^197^206^if  ( this.toolTipText != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( urlText != null )  {^199^^^^^197^206^if  ( this.toolTipText != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P6_Replace_Expression]^if  ( 37 * result + hashCode() )  {^199^^^^^197^206^if  ( this.toolTipText != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P6_Replace_Expression]^if  ( 37 * result )  {^199^^^^^197^206^if  ( this.toolTipText != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P8_Replace_Mix]^if  ( this.toolTipText != false )  {^199^^^^^197^206^if  ( this.toolTipText != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P9_Replace_Statement]^if  ( this.url != null )  {^199^^^^^197^206^if  ( this.toolTipText != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P15_Unwrap_Block]^result = (37 * result) + (this.toolTipText.hashCode());^199^200^201^^^197^206^if  ( this.toolTipText != null )  { result = 37 * result + this.toolTipText.hashCode (  ) ; }^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P16_Remove_Block]^^199^200^201^^^197^206^if  ( this.toolTipText != null )  { result = 37 * result + this.toolTipText.hashCode (  ) ; }^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P13_Insert_Block]^if  (  ( this.url )  != null )  {     result =  ( 37 * result )  +  ( hashCode (  )  ) ; }^199^^^^^197^206^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P2_Replace_Operator]^result = 37 * result + this.toolTipText.hashCode (   instanceof   ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P2_Replace_Operator]^result = 37 / result + this.toolTipText.hashCode (  ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P3_Replace_Literal]^result = 39 * result + this.toolTipText.hashCode (  ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^result = 37 * result + urlText.hashCode (  ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^result = 37 * this.toolTipText + result.hashCode (  ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P7_Replace_Invocation]^result = 37 * result + this.toolTipText .hashCode (  )  ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P8_Replace_Mix]^result = 37 % 2 * result + this.toolTipText.hashCode (  ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P11_Insert_Donor_Statement]^result = 37 * result + this.url.hashCode (  ) ;result = 37 * result + this.toolTipText.hashCode (  ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P13_Insert_Block]^if  (  ( this.toolTipText )  != null )  {     result =  ( 37 * result )  +  ( hashCode (  )  ) ; }^200^^^^^197^206^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P14_Delete_Statement]^^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P2_Replace_Operator]^result = 37 * result + this.toolTipText.hashCode (  ==  ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P2_Replace_Operator]^result = 37 + result + this.toolTipText.hashCode (  ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P3_Replace_Literal]^result = result * result + this.toolTipText.hashCode (  ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^result = 37 * result + url.hashCode (  ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P8_Replace_Mix]^result = 37 - 3 * result + this.toolTipText.hashCode (  ) ;^200^^^^^197^206^result = 37 * result + this.toolTipText.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P2_Replace_Operator]^if  ( this.url == null )  {^202^^^^^197^206^if  ( this.url != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^if  ( url != null )  {^202^^^^^197^206^if  ( this.url != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P6_Replace_Expression]^if  ( 37 * result + hashCode() )  {^202^^^^^197^206^if  ( this.url != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P6_Replace_Expression]^if  ( 37 * result )  {^202^^^^^197^206^if  ( this.url != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P8_Replace_Mix]^if  ( this.url != false )  {^202^^^^^197^206^if  ( this.url != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P9_Replace_Statement]^if  ( this.toolTipText != null )  {^202^^^^^197^206^if  ( this.url != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P9_Replace_Statement]^if  ( info == null )  {^202^^^^^197^206^if  ( this.url != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P9_Replace_Statement]^if  ( entities == null )  {^202^^^^^197^206^if  ( this.url != null )  {^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P15_Unwrap_Block]^result = (37 * result) + (this.url.hashCode());^202^203^204^^^197^206^if  ( this.url != null )  { result = 37 * result + this.url.hashCode (  ) ; }^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P16_Remove_Block]^^202^203^204^^^197^206^if  ( this.url != null )  { result = 37 * result + this.url.hashCode (  ) ; }^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P13_Insert_Block]^if  (  ( this.toolTipText )  != null )  {     result =  ( 37 * result )  +  ( hashCode (  )  ) ; }^202^^^^^197^206^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P2_Replace_Operator]^result = 37 * result + this.url.hashCode (  <  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P2_Replace_Operator]^result = 37 / result + this.url.hashCode (  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P3_Replace_Literal]^result = 28 * result + this.url.hashCode (  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^result = 37 * result + url.hashCode (  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P5_Replace_Variable]^result = 37 * this.url + result.hashCode (  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P7_Replace_Invocation]^result = 37 * result + this.url .hashCode (  )  ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P8_Replace_Mix]^result = 37 % 4 * result + this.url.hashCode (  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P11_Insert_Donor_Statement]^result = 37 * result + this.toolTipText.hashCode (  ) ;result = 37 * result + this.url.hashCode (  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P13_Insert_Block]^if  (  ( this.url )  != null )  {     result =  ( 37 * result )  +  ( hashCode (  )  ) ; }^203^^^^^197^206^[Delete]^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P8_Replace_Mix]^result = 37 * result + urlText.hashCode (  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P14_Delete_Statement]^^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P2_Replace_Operator]^result = 37 * result + this.url.hashCode (  <=  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P2_Replace_Operator]^result = 37 + result + this.url.hashCode (  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P3_Replace_Literal]^result = 29 * result + this.url.hashCode (  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
[P8_Replace_Mix]^result = 37 >> 4 * result + this.url.hashCode (  ) ;^203^^^^^197^206^result = 37 * result + this.url.hashCode (  ) ;^[CLASS] AbstractXYAnnotation  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] int  result  String  text  toolTipText  url  urlText  boolean  
