[P3_Replace_Literal]^return true;^29^^^^^28^30^return false;^[CLASS] ExposeAnnotationDeserializationExclusionStrategy  [METHOD] shouldSkipClass [RETURN_TYPE] boolean   Class<?> clazz [VARIABLES] boolean  Class  clazz  
[P8_Replace_Mix]^Expose annotation = f.getAnnotation ( Expose.null ) ;^33^^^^^32^38^Expose annotation = f.getAnnotation ( Expose.class ) ;^[CLASS] ExposeAnnotationDeserializationExclusionStrategy  [METHOD] shouldSkipField [RETURN_TYPE] boolean   FieldAttributes f [VARIABLES] boolean  Expose  annotation  FieldAttributes  f  
[P5_Replace_Variable]^Expose annotation = f.getAnnotation ( Expose.4 ) ;^33^^^^^32^38^Expose annotation = f.getAnnotation ( Expose.class ) ;^[CLASS] ExposeAnnotationDeserializationExclusionStrategy  [METHOD] shouldSkipField [RETURN_TYPE] boolean   FieldAttributes f [VARIABLES] boolean  Expose  annotation  FieldAttributes  f  
[P14_Delete_Statement]^^33^^^^^32^38^Expose annotation = f.getAnnotation ( Expose.class ) ;^[CLASS] ExposeAnnotationDeserializationExclusionStrategy  [METHOD] shouldSkipField [RETURN_TYPE] boolean   FieldAttributes f [VARIABLES] boolean  Expose  annotation  FieldAttributes  f  
[P2_Replace_Operator]^if  ( annotation != null )  {^34^^^^^32^38^if  ( annotation == null )  {^[CLASS] ExposeAnnotationDeserializationExclusionStrategy  [METHOD] shouldSkipField [RETURN_TYPE] boolean   FieldAttributes f [VARIABLES] boolean  Expose  annotation  FieldAttributes  f  
[P8_Replace_Mix]^if  ( annotation == this )  {^34^^^^^32^38^if  ( annotation == null )  {^[CLASS] ExposeAnnotationDeserializationExclusionStrategy  [METHOD] shouldSkipField [RETURN_TYPE] boolean   FieldAttributes f [VARIABLES] boolean  Expose  annotation  FieldAttributes  f  
[P15_Unwrap_Block]^return true;^34^35^36^^^32^38^if  ( annotation == null )  { return true; }^[CLASS] ExposeAnnotationDeserializationExclusionStrategy  [METHOD] shouldSkipField [RETURN_TYPE] boolean   FieldAttributes f [VARIABLES] boolean  Expose  annotation  FieldAttributes  f  
[P16_Remove_Block]^^34^35^36^^^32^38^if  ( annotation == null )  { return true; }^[CLASS] ExposeAnnotationDeserializationExclusionStrategy  [METHOD] shouldSkipField [RETURN_TYPE] boolean   FieldAttributes f [VARIABLES] boolean  Expose  annotation  FieldAttributes  f  
[P3_Replace_Literal]^return false;^35^^^^^32^38^return true;^[CLASS] ExposeAnnotationDeserializationExclusionStrategy  [METHOD] shouldSkipField [RETURN_TYPE] boolean   FieldAttributes f [VARIABLES] boolean  Expose  annotation  FieldAttributes  f  
[P14_Delete_Statement]^^37^^^^^32^38^return !annotation.deserialize (  ) ;^[CLASS] ExposeAnnotationDeserializationExclusionStrategy  [METHOD] shouldSkipField [RETURN_TYPE] boolean   FieldAttributes f [VARIABLES] boolean  Expose  annotation  FieldAttributes  f  
