[P1_Replace_Type]^private static final  short  serialVersionUID = -600593412366385072L;^57^^^^^52^62^private static final long serialVersionUID = -600593412366385072L;^[CLASS] DatasetRenderingOrder   [VARIABLES] 
[P8_Replace_Mix]^private static final long serialVersionUID  = null ;^57^^^^^52^62^private static final long serialVersionUID = -600593412366385072L;^[CLASS] DatasetRenderingOrder   [VARIABLES] 
[P3_Replace_Literal]^public static final DatasetRenderingOrder FORWARD = new DatasetRenderingOrder ( "tRenderingatasetRenderingOrder.FORWARD" ) ;^63^64^^^^63^64^public static final DatasetRenderingOrder FORWARD = new DatasetRenderingOrder ( "DatasetRenderingOrder.FORWARD" ) ;^[CLASS] DatasetRenderingOrder   [VARIABLES] 
[P3_Replace_Literal]^public static final DatasetRenderingOrder REVERSE = new DatasetRenderingOrder ( "natasetRenderingOrder.REVERSE" ) ;^70^71^^^^70^71^public static final DatasetRenderingOrder REVERSE = new DatasetRenderingOrder ( "DatasetRenderingOrder.REVERSE" ) ;^[CLASS] DatasetRenderingOrder   [VARIABLES] 
[P1_Replace_Type]^private char name;^74^^^^^69^79^private String name;^[CLASS] DatasetRenderingOrder   [VARIABLES] 
[P8_Replace_Mix]^this.name =  null;^82^^^^^81^83^this.name = name;^[CLASS] DatasetRenderingOrder  [METHOD] <init> [RETURN_TYPE] String)   String name [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  String  name  boolean  long  serialVersionUID  
[P5_Replace_Variable]^return name;^91^^^^^90^92^return this.name;^[CLASS] DatasetRenderingOrder  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  String  name  boolean  long  serialVersionUID  
[P2_Replace_Operator]^if  ( this <= o )  {^104^^^^^102^118^if  ( this == o )  {^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P15_Unwrap_Block]^return true;^104^105^106^^^102^118^if  ( this == o )  { return true; }^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P16_Remove_Block]^^104^105^106^^^102^118^if  ( this == o )  { return true; }^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P3_Replace_Literal]^return false;^105^^^^^102^118^return true;^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P2_Replace_Operator]^if  ( ! ( o  <=  DatasetRenderingOrder )  )  {^107^^^^^102^118^if  ( ! ( o instanceof DatasetRenderingOrder )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^if  (  ( o instanceof DatasetRenderingOrder )  )  {^107^^^^^102^118^if  ( ! ( o instanceof DatasetRenderingOrder )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P15_Unwrap_Block]^return false;^107^108^109^^^102^118^if  ( ! ( o instanceof DatasetRenderingOrder )  )  { return false; }^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P16_Remove_Block]^^107^108^109^^^102^118^if  ( ! ( o instanceof DatasetRenderingOrder )  )  { return false; }^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equals ( order.toString (  )  )  )  )  {     return false; }^107^^^^^102^118^[Delete]^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( this.equals ( REVERSE )  )  {     return REVERSE; }^107^^^^^102^118^[Delete]^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P3_Replace_Literal]^return true;^108^^^^^102^118^return false;^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !this.name.equals ( REVERSE.toString (  )  )  )  {^112^^^^^102^118^if  ( !this.name.equals ( order.toString (  )  )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^if  ( !this.name .DatasetRenderingOrder ( name )   )  {^112^^^^^102^118^if  ( !this.name.equals ( order.toString (  )  )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^if  ( !this.name.equals ( order.equals (  )  )  )  {^112^^^^^102^118^if  ( !this.name.equals ( order.toString (  )  )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^if  ( !this.name.equals ( REVERSE.equals (  )  )  )  {^112^^^^^102^118^if  ( !this.name.equals ( order.toString (  )  )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P15_Unwrap_Block]^return false;^112^113^114^^^102^118^if  ( !this.name.equals ( order.toString (  )  )  )  { return false; }^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P16_Remove_Block]^^112^113^114^^^102^118^if  ( !this.name.equals ( order.toString (  )  )  )  { return false; }^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( o instanceof DatasetRenderingOrder )  )  {     return false; }^112^^^^^102^118^[Delete]^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P3_Replace_Literal]^return true;^113^^^^^102^118^return false;^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^if  ( !this.name.equals ( order .DatasetRenderingOrder ( name )   )  )  {^112^^^^^102^118^if  ( !this.name.equals ( order.toString (  )  )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equals ( order.toString (  )  )  )  )  {     return false; }^112^^^^^102^118^[Delete]^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P3_Replace_Literal]^return false;^116^^^^^102^118^return true;^[CLASS] DatasetRenderingOrder  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  Object  o  String  name  boolean  long  serialVersionUID  
[P5_Replace_Variable]^if  ( this.equals ( DatasetRenderingOrder.order )  )  {^128^^^^^127^135^if  ( this.equals ( DatasetRenderingOrder.FORWARD )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^if  ( this.toString ( DatasetRenderingOrder.FORWARD )  )  {^128^^^^^127^135^if  ( this.equals ( DatasetRenderingOrder.FORWARD )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^if  ( this .DatasetRenderingOrder ( name )   )  {^128^^^^^127^135^if  ( this.equals ( DatasetRenderingOrder.FORWARD )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P15_Unwrap_Block]^return org.jfree.chart.plot.DatasetRenderingOrder.FORWARD;^128^129^130^^^127^135^if  ( this.equals ( DatasetRenderingOrder.FORWARD )  )  { return DatasetRenderingOrder.FORWARD; }^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P16_Remove_Block]^^128^129^130^^^127^135^if  ( this.equals ( DatasetRenderingOrder.FORWARD )  )  { return DatasetRenderingOrder.FORWARD; }^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P5_Replace_Variable]^else if  ( this.equals ( DatasetRenderingOrder.order )  )  {^131^^^^^127^135^else if  ( this.equals ( DatasetRenderingOrder.REVERSE )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^else if  ( this.toString ( DatasetRenderingOrder.REVERSE )  )  {^131^^^^^127^135^else if  ( this.equals ( DatasetRenderingOrder.REVERSE )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^else if  ( this .DatasetRenderingOrder ( name )   )  {^131^^^^^127^135^else if  ( this.equals ( DatasetRenderingOrder.REVERSE )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^else if  ( this.toString ( DatasetRenderingOrder.order )  )  {^131^^^^^127^135^else if  ( this.equals ( DatasetRenderingOrder.REVERSE )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P15_Unwrap_Block]^return org.jfree.chart.plot.DatasetRenderingOrder.REVERSE;^131^132^133^^^127^135^else if  ( this.equals ( DatasetRenderingOrder.REVERSE )  )  { return DatasetRenderingOrder.REVERSE; }^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P16_Remove_Block]^^131^132^133^^^127^135^else if  ( this.equals ( DatasetRenderingOrder.REVERSE )  )  { return DatasetRenderingOrder.REVERSE; }^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( o instanceof DatasetRenderingOrder )  )  {     return false; }^131^^^^^127^135^[Delete]^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( o instanceof DatasetRenderingOrder )  )  {     return false; }^132^^^^^127^135^[Delete]^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P12_Insert_Condition]^if  ( this.equals ( DatasetRenderingOrder.FORWARD )  )  { return DatasetRenderingOrder.FORWARD; }^129^^^^^127^135^return DatasetRenderingOrder.FORWARD;^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( o instanceof DatasetRenderingOrder )  )  {     return false; }^129^^^^^127^135^[Delete]^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^if  ( this.equals ( DatasetRenderingOrder.order )  )  {^131^^^^^127^135^else if  ( this.equals ( DatasetRenderingOrder.REVERSE )  )  {^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( o instanceof DatasetRenderingOrder )  )  {     return false; }^128^^^^^127^135^[Delete]^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^return this;^134^^^^^127^135^return null;^[CLASS] DatasetRenderingOrder  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] DatasetRenderingOrder  FORWARD  REVERSE  order  String  name  boolean  long  serialVersionUID  
