[BugLab_Argument_Swapping]^long instant = getInstantMillis ( chrono, object ) ;^101^^^^^100^103^long instant = getInstantMillis ( object, chrono ) ;^[CLASS] AbstractConverter  [METHOD] getPartialValues [RETURN_TYPE] int[]   ReadablePartial fieldSource Object object Chronology chrono [VARIABLES] ReadablePartial  fieldSource  boolean  Object  object  Chronology  chrono  long  instant  
[BugLab_Argument_Swapping]^return instant.get ( fieldSource, chrono ) ;^102^^^^^100^103^return chrono.get ( fieldSource, instant ) ;^[CLASS] AbstractConverter  [METHOD] getPartialValues [RETURN_TYPE] int[]   ReadablePartial fieldSource Object object Chronology chrono [VARIABLES] ReadablePartial  fieldSource  boolean  Object  object  Chronology  chrono  long  instant  
[BugLab_Argument_Swapping]^return chrono.get ( instant, fieldSource ) ;^102^^^^^100^103^return chrono.get ( fieldSource, instant ) ;^[CLASS] AbstractConverter  [METHOD] getPartialValues [RETURN_TYPE] int[]   ReadablePartial fieldSource Object object Chronology chrono [VARIABLES] ReadablePartial  fieldSource  boolean  Object  object  Chronology  chrono  long  instant  
[BugLab_Argument_Swapping]^return fieldSource.get ( chrono, instant ) ;^102^^^^^100^103^return chrono.get ( fieldSource, instant ) ;^[CLASS] AbstractConverter  [METHOD] getPartialValues [RETURN_TYPE] int[]   ReadablePartial fieldSource Object object Chronology chrono [VARIABLES] ReadablePartial  fieldSource  boolean  Object  object  Chronology  chrono  long  instant  
[BugLab_Argument_Swapping]^return getPartialValues ( object, fieldSource, chrono ) ;^123^^^^^121^124^return getPartialValues ( fieldSource, object, chrono ) ;^[CLASS] AbstractConverter  [METHOD] getPartialValues [RETURN_TYPE] int[]   ReadablePartial fieldSource Object object Chronology chrono DateTimeFormatter parser [VARIABLES] ReadablePartial  fieldSource  boolean  Object  object  Chronology  chrono  DateTimeFormatter  parser  
[BugLab_Argument_Swapping]^return getPartialValues ( fieldSource, chrono, object ) ;^123^^^^^121^124^return getPartialValues ( fieldSource, object, chrono ) ;^[CLASS] AbstractConverter  [METHOD] getPartialValues [RETURN_TYPE] int[]   ReadablePartial fieldSource Object object Chronology chrono DateTimeFormatter parser [VARIABLES] ReadablePartial  fieldSource  boolean  Object  object  Chronology  chrono  DateTimeFormatter  parser  
[BugLab_Argument_Swapping]^return getPartialValues ( chrono, object, fieldSource ) ;^123^^^^^121^124^return getPartialValues ( fieldSource, object, chrono ) ;^[CLASS] AbstractConverter  [METHOD] getPartialValues [RETURN_TYPE] int[]   ReadablePartial fieldSource Object object Chronology chrono DateTimeFormatter parser [VARIABLES] ReadablePartial  fieldSource  boolean  Object  object  Chronology  chrono  DateTimeFormatter  parser  
[BugLab_Wrong_Literal]^return true;^148^^^^^147^149^return false;^[CLASS] AbstractConverter  [METHOD] isReadableInterval [RETURN_TYPE] boolean   Object object Chronology chrono [VARIABLES] boolean  Object  object  Chronology  chrono  
[BugLab_Wrong_Operator]^return "Converter[" +  &  ( getSupportedType (  )  == null ? "null" : getSupportedType (  ) .getName (  )  )  + "]";^158^^^^^157^159^return "Converter[" +  ( getSupportedType (  )  == null ? "null" : getSupportedType (  ) .getName (  )  )  + "]";^[CLASS] AbstractConverter  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] boolean  
[BugLab_Wrong_Operator]^return "Converter[" +  ==  ( getSupportedType (  )  == null ? "null" : getSupportedType (  ) .getName (  )  )  + "]";^158^^^^^157^159^return "Converter[" +  ( getSupportedType (  )  == null ? "null" : getSupportedType (  ) .getName (  )  )  + "]";^[CLASS] AbstractConverter  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] boolean  
[BugLab_Wrong_Operator]^return "Converter[" +  ( getSupportedType (  )  != null ? "null" : getSupportedType (  ) .getName (  )  )  + "]";^158^^^^^157^159^return "Converter[" +  ( getSupportedType (  )  == null ? "null" : getSupportedType (  ) .getName (  )  )  + "]";^[CLASS] AbstractConverter  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] boolean  
