[buglab_swap_variables]^chrono =  ( interval != null ? chrono : DateTimeUtils.getIntervalChronology ( chrono )  ) ;^65^^^^^63^72^chrono =  ( chrono != null ? chrono : DateTimeUtils.getIntervalChronology ( interval )  ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^int[] values = end.get ( writablePeriod, start, chrono ) ;^68^^^^^63^72^int[] values = chrono.get ( writablePeriod, start, end ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^int[] values = chrono.get ( start, writablePeriod, end ) ;^68^^^^^63^72^int[] values = chrono.get ( writablePeriod, start, end ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^int[] values = chrono.get (  start, end ) ;^68^^^^^63^72^int[] values = chrono.get ( writablePeriod, start, end ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^int[] values = start.get ( writablePeriod, chrono, end ) ;^68^^^^^63^72^int[] values = chrono.get ( writablePeriod, start, end ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^int[] values = chrono.get ( writablePeriod,  end ) ;^68^^^^^63^72^int[] values = chrono.get ( writablePeriod, start, end ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^int[] values = chrono.get ( end, start, writablePeriod ) ;^68^^^^^63^72^int[] values = chrono.get ( writablePeriod, start, end ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^int[] values = chrono.get ( writablePeriod, start ) ;^68^^^^^63^72^int[] values = chrono.get ( writablePeriod, start, end ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^int[] values = chrono.get ( writablePeriod, end, start ) ;^68^^^^^63^72^int[] values = chrono.get ( writablePeriod, start, end ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^for  ( valuesnt i = 0; i < i.length; i++ )  {^69^^^^^63^72^for  ( int i = 0; i < values.length; i++ )  {^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^for  ( values.lengthnt i = 0; i < i; i++ )  {^69^^^^^63^72^for  ( int i = 0; i < values.length; i++ )  {^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^writablePeriod.setValue (  values[i] ) ;^70^^^^^63^72^writablePeriod.setValue ( i, values[i] ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^writablePeriod.setValue ( i[i] ) ;^70^^^^^63^72^writablePeriod.setValue ( i, values[i] ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
[buglab_swap_variables]^writablePeriod.setValue ( values, i[i] ) ;^70^^^^^63^72^writablePeriod.setValue ( i, values[i] ) ;^[CLASS] ReadableIntervalConverter  [METHOD] setInto [RETURN_TYPE] void   ReadWritablePeriod writablePeriod Object object Chronology chrono [VARIABLES] ReadableIntervalConverter  INSTANCE  boolean  ReadWritablePeriod  writablePeriod  ReadableInterval  interval  Object  object  int[]  values  Chronology  chrono  long  end  start  int  i  
