[P14_Delete_Statement]^^40^^^^^39^42^super (  ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] JXPathContextFactoryConfigurationError()   [VARIABLES] Exception  exception  boolean  
[P11_Insert_Donor_Statement]^super ( msg ) ;super (  ) ;^40^^^^^39^42^super (  ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] JXPathContextFactoryConfigurationError()   [VARIABLES] Exception  exception  boolean  
[P8_Replace_Mix]^this.exception = true;^41^^^^^39^42^this.exception = null;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] JXPathContextFactoryConfigurationError()   [VARIABLES] Exception  exception  boolean  
[P11_Insert_Donor_Statement]^this.exception = e;this.exception = null;^41^^^^^39^42^this.exception = null;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] JXPathContextFactoryConfigurationError()   [VARIABLES] Exception  exception  boolean  
[P14_Delete_Statement]^^52^^^^^51^54^super ( msg ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] String)   String msg [VARIABLES] Exception  exception  String  msg  boolean  
[P11_Insert_Donor_Statement]^super (  ) ;super ( msg ) ;^52^^^^^51^54^super ( msg ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] String)   String msg [VARIABLES] Exception  exception  String  msg  boolean  
[P8_Replace_Mix]^this.exception = false;^53^^^^^51^54^this.exception = null;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] String)   String msg [VARIABLES] Exception  exception  String  msg  boolean  
[P11_Insert_Donor_Statement]^this.exception = e;this.exception = null;^53^^^^^51^54^this.exception = null;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] String)   String msg [VARIABLES] Exception  exception  String  msg  boolean  
[P5_Replace_Variable]^super ( exception.toString (  )  ) ;^66^^^^^65^68^super ( e.toString (  )  ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] Exception)   Exception e [VARIABLES] Exception  e  exception  boolean  
[P14_Delete_Statement]^^66^67^^^^65^68^super ( e.toString (  )  ) ; this.exception = e;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] Exception)   Exception e [VARIABLES] Exception  e  exception  boolean  
[P8_Replace_Mix]^this.exception =  exception;^67^^^^^65^68^this.exception = e;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] Exception)   Exception e [VARIABLES] Exception  e  exception  boolean  
[P11_Insert_Donor_Statement]^this.exception = null;this.exception = e;^67^^^^^65^68^this.exception = e;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] Exception)   Exception e [VARIABLES] Exception  e  exception  boolean  
[P14_Delete_Statement]^^80^^^^^79^82^super ( msg ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] String)   Exception e String msg [VARIABLES] Exception  e  exception  String  msg  boolean  
[P11_Insert_Donor_Statement]^super (  ) ;super ( msg ) ;^80^^^^^79^82^super ( msg ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] String)   Exception e String msg [VARIABLES] Exception  e  exception  String  msg  boolean  
[P5_Replace_Variable]^this.exception = exception;^81^^^^^79^82^this.exception = e;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] String)   Exception e String msg [VARIABLES] Exception  e  exception  String  msg  boolean  
[P11_Insert_Donor_Statement]^this.exception = null;this.exception = e;^81^^^^^79^82^this.exception = e;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] <init> [RETURN_TYPE] String)   Exception e String msg [VARIABLES] Exception  e  exception  String  msg  boolean  
[P1_Replace_Type]^char message = super.getMessage  (  ) ;^94^^^^^93^101^String message = super.getMessage  (  ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P8_Replace_Mix]^String message = super .toString (  )  ;^94^^^^^93^101^String message = super.getMessage  (  ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P14_Delete_Statement]^^94^^^^^93^101^String message = super.getMessage  (  ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P11_Insert_Donor_Statement]^return exception.getMessage (  ) ;String message = super.getMessage  (  ) ;^94^^^^^93^101^String message = super.getMessage  (  ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P2_Replace_Operator]^if  ( message == null || exception != null )  {^96^^^^^93^101^if  ( message == null && exception != null )  {^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P2_Replace_Operator]^if  ( message != null && exception != null )  {^96^^^^^93^101^if  ( message == null && exception != null )  {^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P2_Replace_Operator]^if  ( message == null && exception == null )  {^96^^^^^93^101^if  ( message == null && exception != null )  {^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P5_Replace_Variable]^if  ( message == null && e != null )  {^96^^^^^93^101^if  ( message == null && exception != null )  {^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P5_Replace_Variable]^if  ( exception == null && message != null )  {^96^^^^^93^101^if  ( message == null && exception != null )  {^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P6_Replace_Expression]^if  ( message == null ) {^96^^^^^93^101^if  ( message == null && exception != null )  {^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P6_Replace_Expression]^if  (  exception != null )  {^96^^^^^93^101^if  ( message == null && exception != null )  {^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P8_Replace_Mix]^if  ( message == this && exception != this )  {^96^^^^^93^101^if  ( message == null && exception != null )  {^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P15_Unwrap_Block]^return exception.getMessage();^96^97^98^^^93^101^if  ( message == null && exception != null )  { return exception.getMessage (  ) ; }^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P16_Remove_Block]^^96^97^98^^^93^101^if  ( message == null && exception != null )  { return exception.getMessage (  ) ; }^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P5_Replace_Variable]^return e.getMessage (  ) ;^97^^^^^93^101^return exception.getMessage (  ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P7_Replace_Invocation]^return exception.toString (  ) ;^97^^^^^93^101^return exception.getMessage (  ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P14_Delete_Statement]^^97^^^^^93^101^return exception.getMessage (  ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P8_Replace_Mix]^return e.toString (  ) ;^97^^^^^93^101^return exception.getMessage (  ) ;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getMessage [RETURN_TYPE] String   [VARIABLES] Exception  e  exception  String  message  boolean  
[P5_Replace_Variable]^return e;^111^^^^^110^112^return exception;^[CLASS] JXPathContextFactoryConfigurationError  [METHOD] getException [RETURN_TYPE] Exception   [VARIABLES] Exception  e  exception  boolean  
