[ADD]^^38^^^^^37^84^[ADD] JsonArray results = json.getJsonArray ( "results" ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^if  ( results.isEmpty (  )  )  {^40^^^^^37^84^[REPLACE] if  ( !results.isEmpty (  )  )  {^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^for  ( JsonObject component : results.getValuesAs ( JsonObject.class )  )  {^46^^^^^40^81^[REPLACE] for  ( JsonObject component : components.getValuesAs ( JsonObject.class )  )  {^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^typesLoop: for  ( JsonString type : result.getJsonArray ( "types" ) .getValuesAs ( JsonString.class )  )  {^50^^^^^46^78^[REPLACE] typesLoop: for  ( JsonString type : component.getJsonArray ( "types" ) .getValuesAs ( JsonString.class )  )  {^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^switch  ( type .getString ( value )   )  {^52^^^^^46^78^[REPLACE] switch  ( type.getString (  )  )  {^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address .setState ( value )  ;^54^^^^^46^78^[REPLACE] address.setHouse ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setState ( value )  ;^57^^^^^46^78^[REPLACE] address.setStreet ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setStreet ( value ) ;^60^^^^^46^78^[REPLACE] address.setSettlement ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[ADD]^^60^^^^^46^78^[ADD] address.setSettlement ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setStreet ( value ) ;^63^^^^^46^78^[REPLACE] address.setDistrict ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setStreet ( value )  ;^66^^^^^46^78^[REPLACE] address.setState ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setHouse ( value )  ;^69^^^^^46^78^[REPLACE] address.setCountry ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address .setState ( value )  ;^72^^^^^46^78^[REPLACE] address.setPostcode ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^String value = result.getString ( "short_name" ) ;^48^^^^^46^78^[REPLACE] String value = component.getString ( "short_name" ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setState ( value ) ;^54^^^^^46^78^[REPLACE] address.setHouse ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REMOVE]^address.setState ( value )  ;^54^^^^^46^78^[REMOVE] ^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REMOVE]^address.setStreet ( value )  ;^60^^^^^46^78^[REMOVE] ^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[ADD]^^63^^^^^46^78^[ADD] address.setDistrict ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setState ( value ) ;^72^^^^^46^78^[REPLACE] address.setPostcode ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[ADD]^^72^^^^^46^78^[ADD] address.setPostcode ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^JsonObject result =  ( JsonObject )  results .isEmpty (  )  ;^43^^^^^46^78^[REPLACE] JsonObject result =  ( JsonObject )  results.get ( 0 ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^JsonArray components = result.getString ( "address_components" ) ;^44^^^^^46^78^[REPLACE] JsonArray components = result.getJsonArray ( "address_components" ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[ADD]^^48^^^^^46^78^[ADD] String value = component.getString ( "short_name" ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[ADD]^^52^53^54^^^46^78^[ADD] switch  ( type.getString (  )  )  { case "street_number": address.setHouse ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setStreet ( value )  ;^60^^^^^46^78^[REPLACE] address.setSettlement ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[ADD]^^60^61^^^^46^78^[ADD] address.setSettlement ( value ) ; break typesLoop;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address .setStreet ( value )  ;^63^^^^^46^78^[REPLACE] address.setDistrict ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setStreet ( value ) ;^66^^^^^46^78^[REPLACE] address.setState ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[ADD]^^66^67^^^^46^78^[ADD] address.setState ( value ) ; break typesLoop;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setHouse ( value ) ;^69^^^^^46^78^[REPLACE] address.setCountry ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setState ( value )  ;^72^^^^^46^78^[REPLACE] address.setPostcode ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^String value = result.getJsonArray ( "short_name" ) ;^48^^^^^46^78^[REPLACE] String value = component.getString ( "short_name" ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^address.setState ( value ) ;^57^^^^^46^78^[REPLACE] address.setStreet ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[ADD]^^43^44^^^^46^78^[ADD] JsonObject result =  ( JsonObject )  results.get ( 0 ) ; JsonArray components = result.getJsonArray ( "address_components" ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^JsonArray components = json .getString ( value )  ;^44^^^^^46^78^[REPLACE] JsonArray components = result.getJsonArray ( "address_components" ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[ADD]^^50^51^52^53^54^46^78^[ADD] typesLoop: for  ( JsonString type : component.getJsonArray ( "types" ) .getValuesAs ( JsonString.class )  )  {  switch  ( type.getString (  )  )  { case "street_number": address.setHouse ( value ) ;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
[REPLACE]^return this;^83^^^^^37^84^[REPLACE] return null;^[METHOD] parseAddress [TYPE] Address [PARAMETER] JsonObject json [CLASS] GoogleGeocoder   [TYPE]  JsonArray components  results  [TYPE]  boolean false  true  [TYPE]  Address address  [TYPE]  JsonObject component  json  result  [TYPE]  String value  [TYPE]  JsonString type 
