[buglab_swap_variables]^if  ( StringUtils.isEmpty ( set )  || StringUtils.isEmpty ( str )  )  {^97^^^^^96^103^if  ( StringUtils.isEmpty ( str )  || StringUtils.isEmpty ( set )  )  {^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return squeeze ( strs, str ) ;^102^^^^^96^103^return squeeze ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return squeeze (  strs ) ;^102^^^^^96^103^return squeeze ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return squeeze ( str ) ;^102^^^^^96^103^return squeeze ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^if  ( StringUtils.isEmpty ( set )  || ArrayUtils.isEmpty ( str )  )  {^120^^^^^119^140^if  ( StringUtils.isEmpty ( str )  || ArrayUtils.isEmpty ( set )  )  {^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String[] set [VARIABLES] StringBuffer  buffer  boolean  char  ch  lastChar  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^int sz = chrs.length.length;^126^^^^^119^140^int sz = chrs.length;^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String[] set [VARIABLES] StringBuffer  buffer  boolean  char  ch  lastChar  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^int sz = chrs;^126^^^^^119^140^int sz = chrs.length;^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String[] set [VARIABLES] StringBuffer  buffer  boolean  char  ch  lastChar  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^if  ( ch.contains ( chars )  )  {^131^^^^^119^140^if  ( chars.contains ( ch )  )  {^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String[] set [VARIABLES] StringBuffer  buffer  boolean  char  ch  lastChar  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^if  (  ( i == lastChar )  &&  ( ch != 0 )  )  {^132^^^^^119^140^if  (  ( ch == lastChar )  &&  ( i != 0 )  )  {^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String[] set [VARIABLES] StringBuffer  buffer  boolean  char  ch  lastChar  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^if  (  ( lastChar == ch )  &&  ( i != 0 )  )  {^132^^^^^119^140^if  (  ( ch == lastChar )  &&  ( i != 0 )  )  {^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String[] set [VARIABLES] StringBuffer  buffer  boolean  char  ch  lastChar  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^if  (  ( ch == i )  &&  ( lastChar != 0 )  )  {^132^^^^^119^140^if  (  ( ch == lastChar )  &&  ( i != 0 )  )  {^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String[] set [VARIABLES] StringBuffer  buffer  boolean  char  ch  lastChar  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^for  ( sznt i = 0; i < i; i++ )  {^129^^^^^119^140^for  ( int i = 0; i < sz; i++ )  {^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String[] set [VARIABLES] StringBuffer  buffer  boolean  char  ch  lastChar  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^if  ( charsars.contains ( ch )  )  {^131^^^^^119^140^if  ( chars.contains ( ch )  )  {^[CLASS] CharSetUtils  [METHOD] squeeze [RETURN_TYPE] String   String str String[] set [VARIABLES] StringBuffer  buffer  boolean  char  ch  lastChar  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^if  ( StringUtils.isEmpty ( set )  || StringUtils.isEmpty ( str )  )  {^163^^^^^162^169^if  ( StringUtils.isEmpty ( str )  || StringUtils.isEmpty ( set )  )  {^[CLASS] CharSetUtils  [METHOD] count [RETURN_TYPE] int   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return count ( strs, str ) ;^168^^^^^162^169^return count ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] count [RETURN_TYPE] int   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return count (  strs ) ;^168^^^^^162^169^return count ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] count [RETURN_TYPE] int   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return count ( str ) ;^168^^^^^162^169^return count ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] count [RETURN_TYPE] int   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^if  ( StringUtils.isEmpty ( set )  || ArrayUtils.isEmpty ( str )  )  {^186^^^^^185^199^if  ( StringUtils.isEmpty ( str )  || ArrayUtils.isEmpty ( set )  )  {^[CLASS] CharSetUtils  [METHOD] count [RETURN_TYPE] int   String str String[] set [VARIABLES] boolean  CharSet  chars  String  str  String[]  set  int  count  i  sz  char[]  chrs  
[buglab_swap_variables]^int sz = chrs.length.length;^192^^^^^185^199^int sz = chrs.length;^[CLASS] CharSetUtils  [METHOD] count [RETURN_TYPE] int   String str String[] set [VARIABLES] boolean  CharSet  chars  String  str  String[]  set  int  count  i  sz  char[]  chrs  
[buglab_swap_variables]^int sz = chrs;^192^^^^^185^199^int sz = chrs.length;^[CLASS] CharSetUtils  [METHOD] count [RETURN_TYPE] int   String str String[] set [VARIABLES] boolean  CharSet  chars  String  str  String[]  set  int  count  i  sz  char[]  chrs  
[buglab_swap_variables]^if ( chrs.contains ( chars[i] )  )  {^194^^^^^185^199^if ( chars.contains ( chrs[i] )  )  {^[CLASS] CharSetUtils  [METHOD] count [RETURN_TYPE] int   String str String[] set [VARIABLES] boolean  CharSet  chars  String  str  String[]  set  int  count  i  sz  char[]  chrs  
[buglab_swap_variables]^if  ( set.length (  )  == 0 || StringUtils.isEmpty ( str )  )  {^226^^^^^222^232^if  ( str.length (  )  == 0 || StringUtils.isEmpty ( set )  )  {^[CLASS] CharSetUtils  [METHOD] keep [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return keep ( strs, str ) ;^231^^^^^222^232^return keep ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] keep [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return keep (  strs ) ;^231^^^^^222^232^return keep ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] keep [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return keep ( str ) ;^231^^^^^222^232^return keep ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] keep [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^if  ( set.length (  )  == 0 || ArrayUtils.isEmpty ( str )  )  {^254^^^^^250^258^if  ( str.length (  )  == 0 || ArrayUtils.isEmpty ( set )  )  {^[CLASS] CharSetUtils  [METHOD] keep [RETURN_TYPE] String   String str String[] set [VARIABLES] boolean  String  str  String[]  set  
[buglab_swap_variables]^return modify ( set, str, true ) ;^257^^^^^250^258^return modify ( str, set, true ) ;^[CLASS] CharSetUtils  [METHOD] keep [RETURN_TYPE] String   String str String[] set [VARIABLES] boolean  String  str  String[]  set  
[buglab_swap_variables]^return modify (  set, true ) ;^257^^^^^250^258^return modify ( str, set, true ) ;^[CLASS] CharSetUtils  [METHOD] keep [RETURN_TYPE] String   String str String[] set [VARIABLES] boolean  String  str  String[]  set  
[buglab_swap_variables]^return modify ( str,  true ) ;^257^^^^^250^258^return modify ( str, set, true ) ;^[CLASS] CharSetUtils  [METHOD] keep [RETURN_TYPE] String   String str String[] set [VARIABLES] boolean  String  str  String[]  set  
[buglab_swap_variables]^if  ( StringUtils.isEmpty ( set )  || StringUtils.isEmpty ( str )  )  {^281^^^^^280^287^if  ( StringUtils.isEmpty ( str )  || StringUtils.isEmpty ( set )  )  {^[CLASS] CharSetUtils  [METHOD] delete [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return delete ( strs, str ) ;^286^^^^^280^287^return delete ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] delete [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return delete (  strs ) ;^286^^^^^280^287^return delete ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] delete [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^return delete ( str ) ;^286^^^^^280^287^return delete ( str, strs ) ;^[CLASS] CharSetUtils  [METHOD] delete [RETURN_TYPE] String   String str String set [VARIABLES] boolean  String  set  str  String[]  strs  
[buglab_swap_variables]^if  ( StringUtils.isEmpty ( set )  || ArrayUtils.isEmpty ( str )  )  {^305^^^^^304^309^if  ( StringUtils.isEmpty ( str )  || ArrayUtils.isEmpty ( set )  )  {^[CLASS] CharSetUtils  [METHOD] delete [RETURN_TYPE] String   String str String[] set [VARIABLES] boolean  String  str  String[]  set  
[buglab_swap_variables]^return modify ( set, str, false ) ;^308^^^^^304^309^return modify ( str, set, false ) ;^[CLASS] CharSetUtils  [METHOD] delete [RETURN_TYPE] String   String str String[] set [VARIABLES] boolean  String  str  String[]  set  
[buglab_swap_variables]^return modify (  set, false ) ;^308^^^^^304^309^return modify ( str, set, false ) ;^[CLASS] CharSetUtils  [METHOD] delete [RETURN_TYPE] String   String str String[] set [VARIABLES] boolean  String  str  String[]  set  
[buglab_swap_variables]^return modify ( str,  false ) ;^308^^^^^304^309^return modify ( str, set, false ) ;^[CLASS] CharSetUtils  [METHOD] delete [RETURN_TYPE] String   String str String[] set [VARIABLES] boolean  String  str  String[]  set  
[buglab_swap_variables]^int sz = chrs.length.length;^324^^^^^320^331^int sz = chrs.length;^[CLASS] CharSetUtils  [METHOD] modify [RETURN_TYPE] String   String str String[] set boolean expect [VARIABLES] StringBuffer  buffer  boolean  expect  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^int sz = chrs;^324^^^^^320^331^int sz = chrs.length;^[CLASS] CharSetUtils  [METHOD] modify [RETURN_TYPE] String   String str String[] set boolean expect [VARIABLES] StringBuffer  buffer  boolean  expect  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^if ( expect.contains ( chrs[i] )  == chars )  {^326^^^^^320^331^if ( chars.contains ( chrs[i] )  == expect )  {^[CLASS] CharSetUtils  [METHOD] modify [RETURN_TYPE] String   String str String[] set boolean expect [VARIABLES] StringBuffer  buffer  boolean  expect  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^if ( chrs.contains ( chars[i] )  == expect )  {^326^^^^^320^331^if ( chars.contains ( chrs[i] )  == expect )  {^[CLASS] CharSetUtils  [METHOD] modify [RETURN_TYPE] String   String str String[] set boolean expect [VARIABLES] StringBuffer  buffer  boolean  expect  CharSet  chars  String  str  String[]  set  int  i  sz  char[]  chrs  
[buglab_swap_variables]^int sz = chrs.length.length;^374^^^^^367^388^int sz = chrs.length;^[CLASS] CharSetUtils  [METHOD] translate [RETURN_TYPE] String   String str String searchChars String replaceChars [VARIABLES] StringBuffer  buffer  boolean  String  replaceChars  searchChars  str  int  i  idx  sz  withMax  char[]  chrs  withChrs  
[buglab_swap_variables]^int sz = chrs;^374^^^^^367^388^int sz = chrs.length;^[CLASS] CharSetUtils  [METHOD] translate [RETURN_TYPE] String   String str String searchChars String replaceChars [VARIABLES] StringBuffer  buffer  boolean  String  replaceChars  searchChars  str  int  i  idx  sz  withMax  char[]  chrs  withChrs  
[buglab_swap_variables]^if ( i != -1 )  {^378^^^^^367^388^if ( idx != -1 )  {^[CLASS] CharSetUtils  [METHOD] translate [RETURN_TYPE] String   String str String searchChars String replaceChars [VARIABLES] StringBuffer  buffer  boolean  String  replaceChars  searchChars  str  int  i  idx  sz  withMax  char[]  chrs  withChrs  
[buglab_swap_variables]^if ( withMax > idx )  {^379^^^^^367^388^if ( idx > withMax )  {^[CLASS] CharSetUtils  [METHOD] translate [RETURN_TYPE] String   String str String searchChars String replaceChars [VARIABLES] StringBuffer  buffer  boolean  String  replaceChars  searchChars  str  int  i  idx  sz  withMax  char[]  chrs  withChrs  
[buglab_swap_variables]^int idx = chrs.indexOf ( searchChars[i] ) ;^377^^^^^367^388^int idx = searchChars.indexOf ( chrs[i] ) ;^[CLASS] CharSetUtils  [METHOD] translate [RETURN_TYPE] String   String str String searchChars String replaceChars [VARIABLES] StringBuffer  buffer  boolean  String  replaceChars  searchChars  str  int  i  idx  sz  withMax  char[]  chrs  withChrs  
[buglab_swap_variables]^int chrsdx = searchChars.indexOf ( i[i] ) ;^377^^^^^367^388^int idx = searchChars.indexOf ( chrs[i] ) ;^[CLASS] CharSetUtils  [METHOD] translate [RETURN_TYPE] String   String str String searchChars String replaceChars [VARIABLES] StringBuffer  buffer  boolean  String  replaceChars  searchChars  str  int  i  idx  sz  withMax  char[]  chrs  withChrs  
[buglab_swap_variables]^int searchCharsdx = i.indexOf ( chrs[i] ) ;^377^^^^^367^388^int idx = searchChars.indexOf ( chrs[i] ) ;^[CLASS] CharSetUtils  [METHOD] translate [RETURN_TYPE] String   String str String searchChars String replaceChars [VARIABLES] StringBuffer  buffer  boolean  String  replaceChars  searchChars  str  int  i  idx  sz  withMax  char[]  chrs  withChrs  
