[REPLACE]^private static final long serialVersionUID  = null ;^43^^^^^^^[REPLACE] private static final long serialVersionUID = 2784465764798260919L;^ [CLASS] Kurtosis  
[REPLACE]^private FourthMoment moment;^46^^^^^^^[REPLACE] protected FourthMoment moment;^ [CLASS] Kurtosis  
[REPLACE]^private boolean incMoment;^54^^^^^^^[REPLACE] protected boolean incMoment;^ [CLASS] Kurtosis  
[REPLACE]^double kurtosis = NaN  ;^145^^^^^143^175^[REPLACE] double kurt = Double.NaN;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^if  (  length %  0.5  > 0  )  {^147^^^^^143^175^[REPLACE] if  ( test ( values, begin, length )  && length > 3 )  {^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[ADD]^^147^148^^150^151^143^175^[ADD] if  ( test ( values, begin, length )  && length > 3 )  {  Variance variance = new Variance (  ) ; variance.incrementAll ( values, begin, length ) ;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^accum3 += Math.pow (  ( values[i]  mean ) , 4.0 ) ;^159^^^^^143^175^[REPLACE] accum3 += Math.pow (  ( values[i] - mean ) , 4.0 ) ;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^accum3 /= Math.pow ( stdDev, 4.0Dd ) ;^161^^^^^143^175^[REPLACE] accum3 /= Math.pow ( stdDev, 4.0d ) ;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^kurt =  ( coefficientOne * accum3 )   termTwo;^172^^^^^143^175^[REPLACE] kurt =  ( coefficientOne * accum3 )  - termTwo;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^double mean = m1  ;^150^^^^^143^175^[REPLACE] Variance variance = new Variance (  ) ;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^double n0 = length  ;^152^^^^^143^175^[REPLACE] double mean = variance.moment.m1;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^double stdDev = Math.sqrt ( variance.Variance (  )  ) ;^153^^^^^143^175^[REPLACE] double stdDev = Math.sqrt ( variance.getResult (  )  ) ;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^double accum3 = 0.0D;^157^^^^^143^175^[REPLACE] double accum3 = 0.0;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^double mean = m1  ;^158^^^^^143^175^[REPLACE] for  ( int i = begin; i < begin + length; i++ )  {^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^double n0 = begin;^164^^^^^143^175^[REPLACE] double n0 = length;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^double coefficientOne = ( n0 *  ( n0 + 1 )  )    (  ( n0 - 1 )  *  ( n0 - 2 )  *  ( n0 - 3 )  ) ;^166^167^^^^143^175^[REPLACE] double coefficientOne = ( n0 *  ( n0 + 1 )  )  /  (  ( n0 - 1 )  *  ( n0 - 2 )  *  ( n0 - 3 )  ) ;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^double termTwo = (  ( 3 * Math.pow ( n0 - 1, 2.0 )  )    (  ( n0 - 2 )  *  ( n0 - 3 )  )  ) ;^168^169^^^^143^175^[REPLACE] double termTwo = (  ( 3 * Math.pow ( n0 - 1, 2.0 )  )  /  (  ( n0 - 2 )  *  ( n0 - 3 )  )  ) ;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^accum3 /= pow ( stdDev, 4.0 )  ;^159^^^^^143^175^[REPLACE] accum3 += Math.pow (  ( values[i] - mean ) , 4.0 ) ;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[ADD]^^161^^^^^143^175^[ADD] accum3 /= Math.pow ( stdDev, 4.0d ) ;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^kurt =  ( coefficientOne * accum3 )   mean;^172^^^^^143^175^[REPLACE] kurt =  ( coefficientOne * accum3 )  - termTwo;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^double stdDev = Math.sqrt ( variance .incrementAll ( values , begin , length )   ) ;^153^^^^^143^175^[REPLACE] double stdDev = Math.sqrt ( variance.getResult (  )  ) ;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^double accum3 = 0.0d;^157^^^^^143^175^[REPLACE] double accum3 = 0.0;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^for  ( int i = length; i < begin + length; i++ )  {^158^^^^^143^175^[REPLACE] for  ( int i = begin; i < begin + length; i++ )  {^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^double termTwo = (  ( 3 >>> 4 * Math.pow ( n0 - 1, 2.0 )  )    (  ( n0 - 2 )  *  ( n0 - 3 >>> 4 )  )  ) ;^168^169^^^^143^175^[REPLACE] double termTwo = (  ( 3 * Math.pow ( n0 - 1, 2.0 )  )  /  (  ( n0 - 2 )  *  ( n0 - 3 )  )  ) ;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
[REPLACE]^return termTwo;^174^^^^^143^175^[REPLACE] return kurt;^[METHOD] evaluate [TYPE] double [PARAMETER] final double[] values final int begin final int length [CLASS] Kurtosis   [TYPE]  FourthMoment m4  moment  [TYPE]  boolean false  incMoment  true  [TYPE]  double[] values  [TYPE]  double accum3  coefficientOne  kurt  mean  n0  stdDev  termTwo  [TYPE]  long serialVersionUID  [TYPE]  int begin  i  length  [TYPE]  Variance variance 
