[buglab_swap_variables]^final O value1 = obj1.transform ( this.transformer ) ;^81^^^^^80^84^final O value1 = this.transformer.transform ( obj1 ) ;^[CLASS] TransformingComparator  [METHOD] compare [RETURN_TYPE] int   final I obj1 final I obj2 [VARIABLES] I  obj1  obj2  Transformer  transformer  boolean  long  serialVersionUID  Comparator  decorated  O  value1  value2  
[buglab_swap_variables]^final O value2 = obj2.transform ( this.transformer ) ;^82^^^^^80^84^final O value2 = this.transformer.transform ( obj2 ) ;^[CLASS] TransformingComparator  [METHOD] compare [RETURN_TYPE] int   final I obj1 final I obj2 [VARIABLES] I  obj1  obj2  Transformer  transformer  boolean  long  serialVersionUID  Comparator  decorated  O  value1  value2  
[buglab_swap_variables]^return value1.compare ( this.decorated, value2 ) ;^83^^^^^80^84^return this.decorated.compare ( value1, value2 ) ;^[CLASS] TransformingComparator  [METHOD] compare [RETURN_TYPE] int   final I obj1 final I obj2 [VARIABLES] I  obj1  obj2  Transformer  transformer  boolean  long  serialVersionUID  Comparator  decorated  O  value1  value2  
[buglab_swap_variables]^return this.decorated.compare (  value2 ) ;^83^^^^^80^84^return this.decorated.compare ( value1, value2 ) ;^[CLASS] TransformingComparator  [METHOD] compare [RETURN_TYPE] int   final I obj1 final I obj2 [VARIABLES] I  obj1  obj2  Transformer  transformer  boolean  long  serialVersionUID  Comparator  decorated  O  value1  value2  
[buglab_swap_variables]^return value2.compare ( value1, this.decorated ) ;^83^^^^^80^84^return this.decorated.compare ( value1, value2 ) ;^[CLASS] TransformingComparator  [METHOD] compare [RETURN_TYPE] int   final I obj1 final I obj2 [VARIABLES] I  obj1  obj2  Transformer  transformer  boolean  long  serialVersionUID  Comparator  decorated  O  value1  value2  
[buglab_swap_variables]^return this.decorated.compare ( value1 ) ;^83^^^^^80^84^return this.decorated.compare ( value1, value2 ) ;^[CLASS] TransformingComparator  [METHOD] compare [RETURN_TYPE] int   final I obj1 final I obj2 [VARIABLES] I  obj1  obj2  Transformer  transformer  boolean  long  serialVersionUID  Comparator  decorated  O  value1  value2  
[buglab_swap_variables]^return this.decorated.compare ( value2, value1 ) ;^83^^^^^80^84^return this.decorated.compare ( value1, value2 ) ;^[CLASS] TransformingComparator  [METHOD] compare [RETURN_TYPE] int   final I obj1 final I obj2 [VARIABLES] I  obj1  obj2  Transformer  transformer  boolean  long  serialVersionUID  Comparator  decorated  O  value1  value2  
[buglab_swap_variables]^total = decorated*37 +  ( total == null ? 0 : decorated.hashCode (  )  ) ;^96^^^^^94^99^total = total*37 +  ( decorated == null ? 0 : decorated.hashCode (  )  ) ;^[CLASS] TransformingComparator  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] Transformer  transformer  boolean  long  serialVersionUID  int  total  Comparator  decorated  
[buglab_swap_variables]^total = transformer*37 +  ( total == null ? 0 : transformer.hashCode (  )  ) ;^97^^^^^94^99^total = total*37 +  ( transformer == null ? 0 : transformer.hashCode (  )  ) ;^[CLASS] TransformingComparator  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] Transformer  transformer  boolean  long  serialVersionUID  int  total  Comparator  decorated  
[buglab_swap_variables]^return  ( null == decorated ? null == comp.transformer.decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp : transformer.equals ( comp.transformer )  ) ;^123^124^^^^114^127^return  ( null == decorated ? null == comp.decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^return  ( null == transformer ? null == comp.decorated : decorated.equals ( comp.decorated )  )  && ( null == decorated ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^123^124^^^^114^127^return  ( null == decorated ? null == comp.decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^return  ( null == decorated ? null == comp : decorated.equals ( comp.decorated.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^123^124^^^^114^127^return  ( null == decorated ? null == comp.decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^return  ( null == decorated ? null == comp.transformer : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.decorated : transformer.equals ( comp.transformer )  ) ;^123^124^^^^114^127^return  ( null == decorated ? null == comp.decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^return  ( null == comp ? null == decorated.decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^123^124^^^^114^127^return  ( null == decorated ? null == comp.decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^return  ( null == comp.decorated ? null == decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^123^124^^^^114^127^return  ( null == decorated ? null == comp.decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^( null == comp ? null == transformer.transformer : transformer.equals ( comp.transformer )  ) ;^124^^^^^114^127^( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^( null == comp.transformer ? null == transformer : transformer.equals ( comp.transformer )  ) ;^124^^^^^114^127^( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^return  ( null == decorated ? null == transformer : decorated.equals ( comp.decorated )  )  && ( null == comp.decorated ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^123^124^^^^114^127^return  ( null == decorated ? null == comp.decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^return  ( null == decorated ? null == comp.decorated : decorated.equals ( comp.decorated )  )  && ( null == comp.transformer ? null == transformer : transformer.equals ( comp.transformer )  ) ;^123^124^^^^114^127^return  ( null == decorated ? null == comp.decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^return  ( null == decorated ? null == comp.decorated.decorated : decorated.equals ( comp )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^123^124^^^^114^127^return  ( null == decorated ? null == comp.decorated : decorated.equals ( comp.decorated )  )  && ( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^( null == transformer ? null == comp.transformer.transformer : transformer.equals ( comp )  ) ;^124^^^^^114^127^( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
[buglab_swap_variables]^( null == transformer ? null == comp : transformer.equals ( comp.transformer.transformer )  ) ;^124^^^^^114^127^( null == transformer ? null == comp.transformer : transformer.equals ( comp.transformer )  ) ;^[CLASS] TransformingComparator  [METHOD] equals [RETURN_TYPE] boolean   Object object [VARIABLES] Object  object  Transformer  transformer  boolean  TransformingComparator  comp  long  serialVersionUID  Comparator  decorated  
