[P8_Replace_Mix]^this.mock =  null;^17^^^^^16^19^this.mock = mock;^[CLASS] VoidMethodStubbableImpl  [METHOD] <init> [RETURN_TYPE] MockitoStubber)   T mock MockitoStubber mockitoStubber [VARIABLES] T  mock  MockitoStubber  mockitoStubber  boolean  
[P8_Replace_Mix]^this.mockitoStubber =  null;^18^^^^^16^19^this.mockitoStubber = mockitoStubber;^[CLASS] VoidMethodStubbableImpl  [METHOD] <init> [RETURN_TYPE] MockitoStubber)   T mock MockitoStubber mockitoStubber [VARIABLES] T  mock  MockitoStubber  mockitoStubber  boolean  
[P14_Delete_Statement]^^22^23^^^^21^24^mockitoStubber.addAnswerForVoidMethod  (" ")  ; return this;^[CLASS] VoidMethodStubbableImpl  [METHOD] toThrow [RETURN_TYPE] VoidMethodStubbable   Throwable throwable [VARIABLES] Throwable  throwable  boolean  T  mock  MockitoStubber  mockitoStubber  
[P11_Insert_Donor_Statement]^mockitoStubber.addAnswerForVoidMethod ( answer ) ;mockitoStubber.addAnswerForVoidMethod  (" ")  ;^22^^^^^21^24^mockitoStubber.addAnswerForVoidMethod  (" ")  ;^[CLASS] VoidMethodStubbableImpl  [METHOD] toThrow [RETURN_TYPE] VoidMethodStubbable   Throwable throwable [VARIABLES] Throwable  throwable  boolean  T  mock  MockitoStubber  mockitoStubber  
[P8_Replace_Mix]^return null;^23^^^^^21^24^return this;^[CLASS] VoidMethodStubbableImpl  [METHOD] toThrow [RETURN_TYPE] VoidMethodStubbable   Throwable throwable [VARIABLES] Throwable  throwable  boolean  T  mock  MockitoStubber  mockitoStubber  
[P4_Replace_Constructor]^mockitoStubber.addAnswerForVoidMethod ( mockitoStubber.addAnswerForVoidMethod (  new ThrowsException ( throwable )   ) ;^27^^^^^26^29^mockitoStubber.addAnswerForVoidMethod ( new DoesNothing (  )  ) ;^[CLASS] VoidMethodStubbableImpl  [METHOD] toReturn [RETURN_TYPE] VoidMethodStubbable   [VARIABLES] T  mock  MockitoStubber  mockitoStubber  boolean  
[P14_Delete_Statement]^^27^^^^^26^29^mockitoStubber.addAnswerForVoidMethod ( new DoesNothing (  )  ) ;^[CLASS] VoidMethodStubbableImpl  [METHOD] toReturn [RETURN_TYPE] VoidMethodStubbable   [VARIABLES] T  mock  MockitoStubber  mockitoStubber  boolean  
[P11_Insert_Donor_Statement]^mockitoStubber.addAnswerForVoidMethod ( answer ) ;mockitoStubber.addAnswerForVoidMethod ( new DoesNothing (  )  ) ;^27^^^^^26^29^mockitoStubber.addAnswerForVoidMethod ( new DoesNothing (  )  ) ;^[CLASS] VoidMethodStubbableImpl  [METHOD] toReturn [RETURN_TYPE] VoidMethodStubbable   [VARIABLES] T  mock  MockitoStubber  mockitoStubber  boolean  
[P8_Replace_Mix]^return null;^28^^^^^26^29^return this;^[CLASS] VoidMethodStubbableImpl  [METHOD] toReturn [RETURN_TYPE] VoidMethodStubbable   [VARIABLES] T  mock  MockitoStubber  mockitoStubber  boolean  
[P5_Replace_Variable]^mockitoStubber.addAnswerForVoidMethod ( this ) ;^32^^^^^31^34^mockitoStubber.addAnswerForVoidMethod ( answer ) ;^[CLASS] VoidMethodStubbableImpl  [METHOD] toAnswer [RETURN_TYPE] VoidMethodStubbable   Answer<?> answer [VARIABLES] Answer  answer  boolean  T  mock  MockitoStubber  mockitoStubber  
[P14_Delete_Statement]^^32^33^^^^31^34^mockitoStubber.addAnswerForVoidMethod ( answer ) ; return this;^[CLASS] VoidMethodStubbableImpl  [METHOD] toAnswer [RETURN_TYPE] VoidMethodStubbable   Answer<?> answer [VARIABLES] Answer  answer  boolean  T  mock  MockitoStubber  mockitoStubber  
[P8_Replace_Mix]^return null;^33^^^^^31^34^return this;^[CLASS] VoidMethodStubbableImpl  [METHOD] toAnswer [RETURN_TYPE] VoidMethodStubbable   Answer<?> answer [VARIABLES] Answer  answer  boolean  T  mock  MockitoStubber  mockitoStubber  
