[REPLACE]^private static final long serialVersionUID ;^17^^^^^^^[REPLACE] private static final long serialVersionUID = 1L;^ [CLASS] JacksonXmlModule  
[REPLACE]^protected boolean _cfgDefaultUseWrapper ;^30^^^^^^^[REPLACE] protected boolean _cfgDefaultUseWrapper = JacksonXmlAnnotationIntrospector.DEFAULT_USE_WRAPPER;^ [CLASS] JacksonXmlModule  
[REPLACE]^protected  short  _cfgNameForTextElement = FromXmlParser.DEFAULT_UNNAMED_TEXT_PROPERTY;^40^^^^^^^[REPLACE] protected String _cfgNameForTextElement = FromXmlParser.DEFAULT_UNNAMED_TEXT_PROPERTY;^ [CLASS] JacksonXmlModule  
[REPLACE]^super.setupModule ( context ) ;^50^^^^^48^51^[REPLACE] super ( "JackxonXmlModule", PackageVersion.VERSION ) ;^[METHOD] <init> [TYPE] JacksonXmlModule() [PARAMETER] [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID 
[ADD]^^50^^^^^48^51^[ADD] super ( "JackxonXmlModule", PackageVersion.VERSION ) ;^[METHOD] <init> [TYPE] JacksonXmlModule() [PARAMETER] [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID 
[REPLACE]^context.addBeanDeserializerModifier ( new XmlBeanSerializerModifier (  )  ) ;^57^^^^^54^73^[REPLACE] context.addBeanSerializerModifier ( new XmlBeanSerializerModifier (  )  ) ;^[METHOD] setupModule [TYPE] void [PARAMETER] SetupContext context [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID  [TYPE]  SetupContext context  [TYPE]  XmlMapper m 
[REPLACE]^context .addBeanSerializerModifier ( this )  ;^58^^^^^54^73^[REPLACE] context.addBeanDeserializerModifier ( new XmlBeanDeserializerModifier ( _cfgNameForTextElement )  ) ;^[METHOD] setupModule [TYPE] void [PARAMETER] SetupContext context [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID  [TYPE]  SetupContext context  [TYPE]  XmlMapper m 
[ADD]^^58^59^^61^^54^73^[ADD] context.addBeanDeserializerModifier ( new XmlBeanDeserializerModifier ( _cfgNameForTextElement )  ) ;  context.insertAnnotationIntrospector ( _constructIntrospector (  )  ) ;^[METHOD] setupModule [TYPE] void [PARAMETER] SetupContext context [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID  [TYPE]  SetupContext context  [TYPE]  XmlMapper m 
[REPLACE]^context.addBeanDeserializerModifier ( _constructIntrospector (  )  ) ;^61^^^^^54^73^[REPLACE] context.insertAnnotationIntrospector ( _constructIntrospector (  )  ) ;^[METHOD] setupModule [TYPE] void [PARAMETER] SetupContext context [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID  [TYPE]  SetupContext context  [TYPE]  XmlMapper m 
[REPLACE]^super ( "JackxonXmlModule", PackageVersion.VERSION ) ;^61^^^^^54^73^[REPLACE] context.insertAnnotationIntrospector ( _constructIntrospector (  )  ) ;^[METHOD] setupModule [TYPE] void [PARAMETER] SetupContext context [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID  [TYPE]  SetupContext context  [TYPE]  XmlMapper m 
[REPLACE]^if  ( _cfgNameForTextElement  ==  FromXmlParser.DEFAULT_UNNAMED_TEXT_PROPERTY )  {^64^^^^^54^73^[REPLACE] if  ( _cfgNameForTextElement != FromXmlParser.DEFAULT_UNNAMED_TEXT_PROPERTY )  {^[METHOD] setupModule [TYPE] void [PARAMETER] SetupContext context [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID  [TYPE]  SetupContext context  [TYPE]  XmlMapper m 
[REPLACE]^XmlMapper m =  ( XmlMapper )  context .insertAnnotationIntrospector ( null )  ;^65^^^^^54^73^[REPLACE] XmlMapper m =  ( XmlMapper )  context.getOwner (  ) ;^[METHOD] setupModule [TYPE] void [PARAMETER] SetupContext context [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID  [TYPE]  SetupContext context  [TYPE]  XmlMapper m 
[REPLACE]^XmlMapper m =  ( XmlMapper )  context .insertAnnotationIntrospector ( false )  ;^65^^^^^54^73^[REPLACE] XmlMapper m =  ( XmlMapper )  context.getOwner (  ) ;^[METHOD] setupModule [TYPE] void [PARAMETER] SetupContext context [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID  [TYPE]  SetupContext context  [TYPE]  XmlMapper m 
[ADD]^^65^^^^^54^73^[ADD] XmlMapper m =  ( XmlMapper )  context.getOwner (  ) ;^[METHOD] setupModule [TYPE] void [PARAMETER] SetupContext context [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID  [TYPE]  SetupContext context  [TYPE]  XmlMapper m 
[REPLACE]^super .setDefaultUseWrapper ( true )  ;^72^^^^^54^73^[REPLACE] super.setupModule ( context ) ;^[METHOD] setupModule [TYPE] void [PARAMETER] SetupContext context [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID  [TYPE]  SetupContext context  [TYPE]  XmlMapper m 
[REPLACE]^_cfgDefaultUseWrapper =  true;^96^^^^^95^97^[REPLACE] _cfgDefaultUseWrapper = state;^[METHOD] setDefaultUseWrapper [TYPE] void [PARAMETER] boolean state [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  state  true  [TYPE]  String _cfgNameForTextElement  [TYPE]  long serialVersionUID 
[REPLACE]^_cfgNameForTextElement =  null;^113^^^^^112^114^[REPLACE] _cfgNameForTextElement = name;^[METHOD] setXMLTextElementName [TYPE] void [PARAMETER] String name [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  state  true  [TYPE]  String _cfgNameForTextElement  name  [TYPE]  long serialVersionUID 
[ADD]^^113^^^^^112^114^[ADD] _cfgNameForTextElement = name;^[METHOD] setXMLTextElementName [TYPE] void [PARAMETER] String name [CLASS] JacksonXmlModule   [TYPE]  boolean _cfgDefaultUseWrapper  false  state  true  [TYPE]  String _cfgNameForTextElement  name  [TYPE]  long serialVersionUID 
