[buglab_swap_variables]^this ( DEFAULT_SERIES_PARAMETER, DEFAULT_PREFIX, DEFAULT_ITEM_PARAMETER ) ;^91^^^^^90^92^this ( DEFAULT_PREFIX, DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^[CLASS] StandardXYURLGenerator  [METHOD] <init> [RETURN_TYPE] StandardXYURLGenerator()   [VARIABLES] long  serialVersionUID  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  boolean  
[buglab_swap_variables]^this (  DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^91^^^^^90^92^this ( DEFAULT_PREFIX, DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^[CLASS] StandardXYURLGenerator  [METHOD] <init> [RETURN_TYPE] StandardXYURLGenerator()   [VARIABLES] long  serialVersionUID  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  boolean  
[buglab_swap_variables]^this ( DEFAULT_PREFIX,  DEFAULT_ITEM_PARAMETER ) ;^91^^^^^90^92^this ( DEFAULT_PREFIX, DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^[CLASS] StandardXYURLGenerator  [METHOD] <init> [RETURN_TYPE] StandardXYURLGenerator()   [VARIABLES] long  serialVersionUID  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  boolean  
[buglab_swap_variables]^this ( DEFAULT_PREFIX, DEFAULT_ITEM_PARAMETER, DEFAULT_SERIES_PARAMETER ) ;^91^^^^^90^92^this ( DEFAULT_PREFIX, DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^[CLASS] StandardXYURLGenerator  [METHOD] <init> [RETURN_TYPE] StandardXYURLGenerator()   [VARIABLES] long  serialVersionUID  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  boolean  
[buglab_swap_variables]^this ( DEFAULT_PREFIX, DEFAULT_SERIES_PARAMETER ) ;^91^^^^^90^92^this ( DEFAULT_PREFIX, DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^[CLASS] StandardXYURLGenerator  [METHOD] <init> [RETURN_TYPE] StandardXYURLGenerator()   [VARIABLES] long  serialVersionUID  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  boolean  
[buglab_swap_variables]^this ( DEFAULT_ITEM_PARAMETER, DEFAULT_SERIES_PARAMETER, prefix ) ;^102^^^^^101^103^this ( prefix, DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^[CLASS] StandardXYURLGenerator  [METHOD] <init> [RETURN_TYPE] String)   String prefix [VARIABLES] long  serialVersionUID  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  boolean  
[buglab_swap_variables]^this (  DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^102^^^^^101^103^this ( prefix, DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^[CLASS] StandardXYURLGenerator  [METHOD] <init> [RETURN_TYPE] String)   String prefix [VARIABLES] long  serialVersionUID  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  boolean  
[buglab_swap_variables]^this ( DEFAULT_SERIES_PARAMETER, prefix, DEFAULT_ITEM_PARAMETER ) ;^102^^^^^101^103^this ( prefix, DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^[CLASS] StandardXYURLGenerator  [METHOD] <init> [RETURN_TYPE] String)   String prefix [VARIABLES] long  serialVersionUID  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  boolean  
[buglab_swap_variables]^this ( prefix,  DEFAULT_ITEM_PARAMETER ) ;^102^^^^^101^103^this ( prefix, DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^[CLASS] StandardXYURLGenerator  [METHOD] <init> [RETURN_TYPE] String)   String prefix [VARIABLES] long  serialVersionUID  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  boolean  
[buglab_swap_variables]^this ( prefix, DEFAULT_ITEM_PARAMETER, DEFAULT_SERIES_PARAMETER ) ;^102^^^^^101^103^this ( prefix, DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^[CLASS] StandardXYURLGenerator  [METHOD] <init> [RETURN_TYPE] String)   String prefix [VARIABLES] long  serialVersionUID  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  boolean  
[buglab_swap_variables]^this ( prefix, DEFAULT_SERIES_PARAMETER ) ;^102^^^^^101^103^this ( prefix, DEFAULT_SERIES_PARAMETER, DEFAULT_ITEM_PARAMETER ) ;^[CLASS] StandardXYURLGenerator  [METHOD] <init> [RETURN_TYPE] String)   String prefix [VARIABLES] long  serialVersionUID  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  boolean  
[buglab_swap_variables]^url += this.seriesParameterName + "=" + item + "&amp;" + this.itemParameterName + "=" + series;^146^147^^^^142^149^url += this.seriesParameterName + "=" + series + "&amp;" + this.itemParameterName + "=" + item;^[CLASS] StandardXYURLGenerator  [METHOD] generateURL [RETURN_TYPE] String   XYDataset dataset int series int item [VARIABLES] XYDataset  dataset  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  firstParameter  long  serialVersionUID  int  item  series  
[buglab_swap_variables]^url += this.seriesParameterName + "=" + series + "&amp;" + item + "=" + this.itemParameterName;^146^147^^^^142^149^url += this.seriesParameterName + "=" + series + "&amp;" + this.itemParameterName + "=" + item;^[CLASS] StandardXYURLGenerator  [METHOD] generateURL [RETURN_TYPE] String   XYDataset dataset int series int item [VARIABLES] XYDataset  dataset  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  firstParameter  long  serialVersionUID  int  item  series  
[buglab_swap_variables]^url += series + "=" + this.seriesParameterName + "&amp;" + this.itemParameterName + "=" + item;^146^147^^^^142^149^url += this.seriesParameterName + "=" + series + "&amp;" + this.itemParameterName + "=" + item;^[CLASS] StandardXYURLGenerator  [METHOD] generateURL [RETURN_TYPE] String   XYDataset dataset int series int item [VARIABLES] XYDataset  dataset  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  firstParameter  long  serialVersionUID  int  item  series  
[buglab_swap_variables]^url += this.itemParameterName + "=" + series + "&amp;" + this.seriesParameterName + "=" + item;^146^147^^^^142^149^url += this.seriesParameterName + "=" + series + "&amp;" + this.itemParameterName + "=" + item;^[CLASS] StandardXYURLGenerator  [METHOD] generateURL [RETURN_TYPE] String   XYDataset dataset int series int item [VARIABLES] XYDataset  dataset  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  firstParameter  long  serialVersionUID  int  item  series  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( that.prefix.prefix, this.prefix )  )  {^166^^^^^158^178^if  ( !ObjectUtilities.equal ( that.prefix, this.prefix )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( this.prefix, that.prefix )  )  {^166^^^^^158^178^if  ( !ObjectUtilities.equal ( that.prefix, this.prefix )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal (  this.prefix )  )  {^166^^^^^158^178^if  ( !ObjectUtilities.equal ( that.prefix, this.prefix )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( that.prefix )  )  {^166^^^^^158^178^if  ( !ObjectUtilities.equal ( that.prefix, this.prefix )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( this.prefix.prefix, that )  )  {^166^^^^^158^178^if  ( !ObjectUtilities.equal ( that.prefix, this.prefix )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( that, this.prefix )  )  {^166^^^^^158^178^if  ( !ObjectUtilities.equal ( that.prefix, this.prefix )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( that.seriesParameterName.seriesParameterName, this.seriesParameterName )  )  {^169^170^^^^158^178^if  ( !ObjectUtilities.equal ( that.seriesParameterName, this.seriesParameterName )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( this.seriesParameterName, that.seriesParameterName )  )  {^169^170^^^^158^178^if  ( !ObjectUtilities.equal ( that.seriesParameterName, this.seriesParameterName )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal (  this.seriesParameterName )  )  {^169^170^^^^158^178^if  ( !ObjectUtilities.equal ( that.seriesParameterName, this.seriesParameterName )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( that.seriesParameterName )  )  {^169^170^^^^158^178^if  ( !ObjectUtilities.equal ( that.seriesParameterName, this.seriesParameterName )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( that, this.seriesParameterName )  )  {^169^170^^^^158^178^if  ( !ObjectUtilities.equal ( that.seriesParameterName, this.seriesParameterName )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( this.seriesParameterName.seriesParameterName, that )  )  {^169^170^^^^158^178^if  ( !ObjectUtilities.equal ( that.seriesParameterName, this.seriesParameterName )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( this.itemParameterName.itemParameterName, that )  )  {^173^174^^^^158^178^if  ( !ObjectUtilities.equal ( that.itemParameterName, this.itemParameterName )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( this.itemParameterName, that.itemParameterName )  )  {^173^174^^^^158^178^if  ( !ObjectUtilities.equal ( that.itemParameterName, this.itemParameterName )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal (  this.itemParameterName )  )  {^173^174^^^^158^178^if  ( !ObjectUtilities.equal ( that.itemParameterName, this.itemParameterName )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( that.itemParameterName )  )  {^173^174^^^^158^178^if  ( !ObjectUtilities.equal ( that.itemParameterName, this.itemParameterName )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( that, this.itemParameterName )  )  {^173^174^^^^158^178^if  ( !ObjectUtilities.equal ( that.itemParameterName, this.itemParameterName )  )  {^[CLASS] StandardXYURLGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  StandardXYURLGenerator  that  String  DEFAULT_ITEM_PARAMETER  DEFAULT_PREFIX  DEFAULT_SERIES_PARAMETER  itemParameterName  prefix  seriesParameterName  url  boolean  long  serialVersionUID  
