[REPLACE]^private final EnumValues _values;^41^^^^^^^[REPLACE] protected final EnumValues _values;^ [CLASS] EnumSerializer  
[REPLACE]^protected  Boolean _serializeAsIndex;^50^^^^^^^[REPLACE] protected final Boolean _serializeAsIndex;^ [CLASS] EnumSerializer  
[REPLACE]^this ( _values, true ) ;^63^^^^^62^64^[REPLACE] this ( v, null ) ;^[METHOD] <init> [TYPE] EnumValues) [PARAMETER] EnumValues v [CLASS] EnumSerializer   [TYPE]  Boolean _serializeAsIndex  [TYPE]  EnumValues _values  v  [TYPE]  boolean false  true 
[ADD]^^63^^^^^62^64^[ADD] this ( v, null ) ;^[METHOD] <init> [TYPE] EnumValues) [PARAMETER] EnumValues v [CLASS] EnumSerializer   [TYPE]  Boolean _serializeAsIndex  [TYPE]  EnumValues _values  v  [TYPE]  boolean false  true 
[REPLACE]^super ( Enum.class, true ) ;^68^^^^^66^71^[REPLACE] super ( Enum.class, false ) ;^[METHOD] <init> [TYPE] Boolean) [PARAMETER] EnumValues v Boolean serializeAsIndex [CLASS] EnumSerializer   [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v  [TYPE]  boolean false  true 
[REPLACE]^_values =  null;^69^^^^^66^71^[REPLACE] _values = v;^[METHOD] <init> [TYPE] Boolean) [PARAMETER] EnumValues v Boolean serializeAsIndex [CLASS] EnumSerializer   [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v  [TYPE]  boolean false  true 
[REPLACE]^_serializeAsIndex =  null;^70^^^^^66^71^[REPLACE] _serializeAsIndex = serializeAsIndex;^[METHOD] <init> [TYPE] Boolean) [PARAMETER] EnumValues v Boolean serializeAsIndex [CLASS] EnumSerializer   [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v  [TYPE]  boolean false  true 
[REPLACE]^AnnotationIntrospector intr = config.isEnabled (  ) ;^83^^^^^79^88^[REPLACE] AnnotationIntrospector intr = config.getAnnotationIntrospector (  ) ;^[METHOD] construct [TYPE] EnumSerializer [PARAMETER] Enum<?>> enumClass SerializationConfig config BeanDescription beanDesc Value format [CLASS] EnumSerializer   [TYPE]  boolean false  true  [TYPE]  SerializationConfig config  [TYPE]  BeanDescription beanDesc  [TYPE]  Value format  [TYPE]  AnnotationIntrospector intr  [TYPE]  Class enumClass  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^EnumValues v = config.isEnabled ( SerializationFeature.WRITE_ENUMS_USING_TO_STRING ) ? EnumValues.constructFromToString ( enumClass, intr )  : EnumValues.constructFromToString ( enumClass, intr ) ;^84^85^^^^79^88^[REPLACE] EnumValues v = config.isEnabled ( SerializationFeature.WRITE_ENUMS_USING_TO_STRING ) ? EnumValues.constructFromToString ( enumClass, intr )  : EnumValues.constructFromName ( enumClass, intr ) ;^[METHOD] construct [TYPE] EnumSerializer [PARAMETER] Enum<?>> enumClass SerializationConfig config BeanDescription beanDesc Value format [CLASS] EnumSerializer   [TYPE]  boolean false  true  [TYPE]  SerializationConfig config  [TYPE]  BeanDescription beanDesc  [TYPE]  Value format  [TYPE]  AnnotationIntrospector intr  [TYPE]  Class enumClass  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^Boolean serializeAsIndex = _isShapeWrittenUsingIndex ( null, format, false ) ;^86^^^^^79^88^[REPLACE] Boolean serializeAsIndex = _isShapeWrittenUsingIndex ( enumClass, format, true ) ;^[METHOD] construct [TYPE] EnumSerializer [PARAMETER] Enum<?>> enumClass SerializationConfig config BeanDescription beanDesc Value format [CLASS] EnumSerializer   [TYPE]  boolean false  true  [TYPE]  SerializationConfig config  [TYPE]  BeanDescription beanDesc  [TYPE]  Value format  [TYPE]  AnnotationIntrospector intr  [TYPE]  Class enumClass  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^return  new EnumSerializer ( _values, serializeAsIndex )  ;^87^^^^^79^88^[REPLACE] return new EnumSerializer ( v, serializeAsIndex ) ;^[METHOD] construct [TYPE] EnumSerializer [PARAMETER] Enum<?>> enumClass SerializationConfig config BeanDescription beanDesc Value format [CLASS] EnumSerializer   [TYPE]  boolean false  true  [TYPE]  SerializationConfig config  [TYPE]  BeanDescription beanDesc  [TYPE]  Value format  [TYPE]  AnnotationIntrospector intr  [TYPE]  Class enumClass  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^return construct ( enumClass, config, beanDesc, beanDesc.findExpectedFormat ( this )  ) ;^97^^^^^94^98^[REPLACE] return construct ( enumClass, config, beanDesc, beanDesc.findExpectedFormat ( null )  ) ;^[METHOD] construct [TYPE] EnumSerializer [PARAMETER] Enum<?>> enumClass SerializationConfig config BeanDescription beanDesc [CLASS] EnumSerializer   [TYPE]  Class enumClass  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v  [TYPE]  SerializationConfig config  [TYPE]  BeanDescription beanDesc 
[REPLACE]^if  ( property == null )  {^109^^^^^106^119^[REPLACE] if  ( property != null )  {^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[ADD]^^109^110^111^112^^106^119^[ADD] if  ( property != null )  { JsonFormat.Value format = prov.getAnnotationIntrospector (  ) .findFormat (  ( Annotated )  property.getMember (  )  ) ; if  ( format != null )  { Boolean serializeAsIndex = _isShapeWrittenUsingIndex ( property.getType (  ) .getRawClass (  ) , format, false ) ;^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^if  ( format == null )  {^111^^^^^106^119^[REPLACE] if  ( format != null )  {^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[ADD]^^111^112^113^114^115^106^119^[ADD] if  ( format != null )  { Boolean serializeAsIndex = _isShapeWrittenUsingIndex ( property.getType (  ) .getRawClass (  ) , format, false ) ; if  ( serializeAsIndex != _serializeAsIndex )  { return new EnumSerializer ( _values, serializeAsIndex ) ; }^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^if  ( serializeAsIndex  ==  _serializeAsIndex )  {^113^^^^^106^119^[REPLACE] if  ( serializeAsIndex != _serializeAsIndex )  {^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[ADD]^^113^114^115^^^106^119^[ADD] if  ( serializeAsIndex != _serializeAsIndex )  { return new EnumSerializer ( _values, serializeAsIndex ) ; }^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^return  new EnumSerializer ( v, serializeAsIndex )  ;^114^^^^^106^119^[REPLACE] return new EnumSerializer ( _values, serializeAsIndex ) ;^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^Boolean serializeAsIndex = _isShapeWrittenUsingIndex ( property.getType (  ) .getRawClass (  ) , format, true ) ;^112^^^^^106^119^[REPLACE] Boolean serializeAsIndex = _isShapeWrittenUsingIndex ( property.getType (  ) .getRawClass (  ) , format, false ) ;^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^if  ( _serializeAsIndex  ==  _serializeAsIndex )  {^113^^^^^106^119^[REPLACE] if  ( serializeAsIndex != _serializeAsIndex )  {^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^return  new EnumSerializer ( v, _serializeAsIndex )  ;^114^^^^^106^119^[REPLACE] return new EnumSerializer ( _values, serializeAsIndex ) ;^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^JsonFormat.Value format = prov.isEnabled (  ) .findFormat (  ( Annotated )  property.getMember (  )  ) ;^110^^^^^106^119^[REPLACE] JsonFormat.Value format = prov.getAnnotationIntrospector (  ) .findFormat (  ( Annotated )  property.getMember (  )  ) ;^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^if  ( _serializeAsIndex  ==  serializeAsIndex )  {^113^^^^^106^119^[REPLACE] if  ( serializeAsIndex != _serializeAsIndex )  {^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[ADD]^return new EnumSerializer ( _values, serializeAsIndex ) ;^113^114^115^^^106^119^[ADD] if  ( serializeAsIndex != _serializeAsIndex )  { return new EnumSerializer ( _values, serializeAsIndex ) ; }^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^return new EnumSerializer ( v, serializeAsIndex ) ;^114^^^^^106^119^[REPLACE] return new EnumSerializer ( _values, serializeAsIndex ) ;^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[ADD]^^112^113^114^115^^106^119^[ADD] Boolean serializeAsIndex = _isShapeWrittenUsingIndex ( property.getType (  ) .getRawClass (  ) , format, false ) ; if  ( serializeAsIndex != _serializeAsIndex )  { return new EnumSerializer ( _values, serializeAsIndex ) ; }^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^JsonFormat.Value format = prov.getAnnotationIntrospector (  ) .findFormat (  ( Annotated )  property .getType (  )   ) ;^110^^^^^106^119^[REPLACE] JsonFormat.Value format = prov.getAnnotationIntrospector (  ) .findFormat (  ( Annotated )  property.getMember (  )  ) ;^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^return null;^118^^^^^106^119^[REPLACE] return this;^[METHOD] createContextual [TYPE] JsonSerializer [PARAMETER] SerializerProvider prov BeanProperty property [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider prov  [TYPE]  EnumValues _values  v  [TYPE]  BeanProperty property 
[REPLACE]^return _serializeAsIndex.booleanValue (  ) ;^127^^^^^^^[REPLACE] public EnumValues getEnumValues (  )  { return _values; }^[METHOD] getEnumValues [TYPE] EnumValues [PARAMETER] [CLASS] EnumSerializer   [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v  [TYPE]  boolean false  true 
[REPLACE]^if  ( typeHint != null && stringVisitor != null )  {^140^^^^^136^145^[REPLACE] if  ( _serializeAsIndex ( provider )  )  {^[METHOD] serialize [TYPE] void [PARAMETER] Enum<?> en JsonGenerator jgen SerializerProvider provider [CLASS] EnumSerializer   [TYPE]  Enum en  [TYPE]  JsonGenerator jgen  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[ADD]^^140^141^142^143^^136^145^[ADD] if  ( _serializeAsIndex ( provider )  )  { jgen.writeNumber ( en.ordinal (  )  ) ; return; }^[METHOD] serialize [TYPE] void [PARAMETER] Enum<?> en JsonGenerator jgen SerializerProvider provider [CLASS] EnumSerializer   [TYPE]  Enum en  [TYPE]  JsonGenerator jgen  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^return Boolean.TRUE;^142^^^^^136^145^[REPLACE] return;^[METHOD] serialize [TYPE] void [PARAMETER] Enum<?> en JsonGenerator jgen SerializerProvider provider [CLASS] EnumSerializer   [TYPE]  Enum en  [TYPE]  JsonGenerator jgen  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^jgen.writeString ( _values.serializedValueFor ( true )  ) ;^144^^^^^136^145^[REPLACE] jgen.writeString ( _values.serializedValueFor ( en )  ) ;^[METHOD] serialize [TYPE] void [PARAMETER] Enum<?> en JsonGenerator jgen SerializerProvider provider [CLASS] EnumSerializer   [TYPE]  Enum en  [TYPE]  JsonGenerator jgen  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^jgen.writeString ( _values .values (  )   ) ;^144^^^^^136^145^[REPLACE] jgen.writeString ( _values.serializedValueFor ( en )  ) ;^[METHOD] serialize [TYPE] void [PARAMETER] Enum<?> en JsonGenerator jgen SerializerProvider provider [CLASS] EnumSerializer   [TYPE]  Enum en  [TYPE]  JsonGenerator jgen  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[ADD]^^144^^^^^136^145^[ADD] jgen.writeString ( _values.serializedValueFor ( en )  ) ;^[METHOD] serialize [TYPE] void [PARAMETER] Enum<?> en JsonGenerator jgen SerializerProvider provider [CLASS] EnumSerializer   [TYPE]  Enum en  [TYPE]  JsonGenerator jgen  [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^if  ( typeHint != null && stringVisitor != null )  {^151^^^^^148^165^[REPLACE] if  ( _serializeAsIndex ( provider )  )  {^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[ADD]^return createSchemaNode ( "integer", true ) ;^151^152^153^^^148^165^[ADD] if  ( _serializeAsIndex ( provider )  )  { return createSchemaNode ( "integer", true ) ; }^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^return _serializeAsIndex.booleanValue (  ) ;^152^^^^^148^165^[REPLACE] return createSchemaNode ( "integer", true ) ;^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^ArrayNode enumNode = objectNode.putArray ( "enum" ) ;^154^^^^^148^165^[REPLACE] ObjectNode objectNode = createSchemaNode ( "string", true ) ;^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^if  ( typeHint == null )  {^155^^^^^148^165^[REPLACE] if  ( typeHint != null )  {^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[ADD]^JavaType type = provider.constructType ( typeHint ) ;ArrayNode enumNode = objectNode.putArray ( "enum" ) ;^155^156^157^158^^148^165^[ADD] if  ( typeHint != null )  { JavaType type = provider.constructType ( typeHint ) ; if  ( type.isEnumType (  )  )  { ArrayNode enumNode = objectNode.putArray ( "enum" ) ;^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^if  ( typeHint.isEnumType (  )  )  {^157^^^^^148^165^[REPLACE] if  ( type.isEnumType (  )  )  {^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^ObjectNode objectNode = createSchemaNode ( "string", true ) ;^158^^^^^148^165^[REPLACE] ArrayNode enumNode = objectNode.putArray ( "enum" ) ;^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[ADD]^^158^^^^^148^165^[ADD] ArrayNode enumNode = objectNode.putArray ( "enum" ) ;^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^for  ( SerializedString value : _values.values (  )  )  { enumNode.add ( value.getValue (  )  ) ;^159^^^^^148^165^[REPLACE] for  ( SerializedString value : _values.values (  )  )  {^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[ADD]^^159^160^161^^^148^165^[ADD] for  ( SerializedString value : _values.values (  )  )  { enumNode.add ( value.getValue (  )  ) ; }^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^JavaType type = provider .getAnnotationIntrospector (  )  ;^156^^^^^148^165^[REPLACE] JavaType type = provider.constructType ( typeHint ) ;^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^JsonIntegerFormatVisitor v2 = visitor.expectIntegerFormat ( typeHint ) ;^156^^^^^148^165^[REPLACE] JavaType type = provider.constructType ( typeHint ) ;^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[ADD]^^156^^^^^148^165^[ADD] JavaType type = provider.constructType ( typeHint ) ;^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^return Boolean.TRUE;^164^^^^^148^165^[REPLACE] return objectNode;^[METHOD] getSchema [TYPE] JsonNode [PARAMETER] SerializerProvider provider Type typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  Type typeHint  [TYPE]  JavaType type  [TYPE]  boolean false  true  [TYPE]  ObjectNode objectNode  [TYPE]  ArrayNode enumNode  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^if  ( typeHint != null && stringVisitor != null )  {^172^^^^^168^189^[REPLACE] if  ( visitor.getProvider (  ) .isEnabled ( SerializationFeature.WRITE_ENUMS_USING_INDEX )  )  {^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[ADD]^JsonIntegerFormatVisitor v2 = visitor.expectIntegerFormat ( typeHint ) ;v2.numberType ( JsonParser.NumberType.INT ) ;^172^173^174^175^176^168^189^[ADD] if  ( visitor.getProvider (  ) .isEnabled ( SerializationFeature.WRITE_ENUMS_USING_INDEX )  )  { JsonIntegerFormatVisitor v2 = visitor.expectIntegerFormat ( typeHint ) ; if  ( v2 != null )  { v2.numberType ( JsonParser.NumberType.INT ) ; }^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[REPLACE]^if  ( typeHint == this ) {^179^^^^^168^189^[REPLACE] if  ( typeHint != null && stringVisitor != null )  {^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[ADD]^^179^180^181^182^183^168^189^[ADD] if  ( typeHint != null && stringVisitor != null )  { if  ( typeHint.isEnumType (  )  )  { Set<String> enums = new LinkedHashSet<String> (  ) ; for  ( SerializedString value : _values.values (  )  )  { enums.add ( value.getValue (  )  ) ;^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[REPLACE]^if  ( type.isEnumType (  )  )  {^180^^^^^168^189^[REPLACE] if  ( typeHint.isEnumType (  )  )  {^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[REPLACE]^ObjectNode objectNode = createSchemaNode ( "string", true ) ;^181^^^^^168^189^[REPLACE] Set<String> enums = new LinkedHashSet<String> (  ) ;^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[ADD]^^181^^^^^168^189^[ADD] Set<String> enums = new LinkedHashSet<String> (  ) ;^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[REPLACE]^for  ( SerializedString value : _values.values (  )  )  { enumNode.add ( value.getValue (  )  ) ;^182^^^^^168^189^[REPLACE] for  ( SerializedString value : _values.values (  )  )  {^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[REPLACE]^JsonStringFormatVisitor stringVisitor = visitor.expectIntegerFormat ( typeHint ) ;^178^^^^^168^189^[REPLACE] JsonStringFormatVisitor stringVisitor = visitor.expectStringFormat ( typeHint ) ;^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[ADD]^^182^183^184^^^168^189^[ADD] for  ( SerializedString value : _values.values (  )  )  { enums.add ( value.getValue (  )  ) ; }^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[REPLACE]^if  ( v2 == null )  {^174^^^^^168^189^[REPLACE] if  ( v2 != null )  {^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[REPLACE]^JavaType type = provider.constructType ( typeHint ) ;^175^^^^^168^189^[REPLACE] v2.numberType ( JsonParser.NumberType.INT ) ;^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[REPLACE]^JsonIntegerFormatVisitor v2 = visitor .expectStringFormat ( typeHint )  ;^173^^^^^168^189^[REPLACE] JsonIntegerFormatVisitor v2 = visitor.expectIntegerFormat ( typeHint ) ;^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[REPLACE]^if  (  stringVisitor != null )  {^179^^^^^168^189^[REPLACE] if  ( typeHint != null && stringVisitor != null )  {^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[REPLACE]^JsonIntegerFormatVisitor v2 = visitor.expectStringFormat ( typeHint ) ;^173^^^^^168^189^[REPLACE] JsonIntegerFormatVisitor v2 = visitor.expectIntegerFormat ( typeHint ) ;^[METHOD] acceptJsonFormatVisitor [TYPE] void [PARAMETER] JsonFormatVisitorWrapper visitor JavaType typeHint [CLASS] EnumSerializer   [TYPE]  SerializedString value  [TYPE]  JavaType typeHint  [TYPE]  Set enums  [TYPE]  boolean false  true  [TYPE]  JsonFormatVisitorWrapper visitor  [TYPE]  JsonIntegerFormatVisitor v2  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  JsonStringFormatVisitor stringVisitor  [TYPE]  EnumValues _values  v 
[REPLACE]^if  ( _serializeAsIndex == null )  {^199^^^^^197^204^[REPLACE] if  ( _serializeAsIndex != null )  {^[METHOD] _serializeAsIndex [TYPE] boolean [PARAMETER] SerializerProvider provider [CLASS] EnumSerializer   [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^return Boolean.TRUE;^200^^^^^197^204^[REPLACE] return _serializeAsIndex.booleanValue (  ) ;^[METHOD] _serializeAsIndex [TYPE] boolean [PARAMETER] SerializerProvider provider [CLASS] EnumSerializer   [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^return provider .getAnnotationIntrospector (  )  ;^202^^^^^197^204^[REPLACE] return provider.isEnabled ( SerializationFeature.WRITE_ENUMS_USING_INDEX ) ;^[METHOD] _serializeAsIndex [TYPE] boolean [PARAMETER] SerializerProvider provider [CLASS] EnumSerializer   [TYPE]  boolean false  true  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  SerializerProvider provider  [TYPE]  EnumValues _values  v 
[REPLACE]^JsonFormat.Shape shape  =  null ;^212^^^^^209^229^[REPLACE] JsonFormat.Shape shape =  ( format == null )  ? null : format.getShape (  ) ;^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^if  ( shape != false )  {^213^^^^^209^229^[REPLACE] if  ( shape == null )  {^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^return this;^214^^^^^209^229^[REPLACE] return null;^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^return true;^214^^^^^209^229^[REPLACE] return null;^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^if  (  shape == Shape.SCALAR )  {^216^^^^^209^229^[REPLACE] if  ( shape == Shape.ANY || shape == Shape.SCALAR )  {^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^return true;^217^^^^^209^229^[REPLACE] return null;^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^if  ( shape  !=  Shape.STRING )  {^219^^^^^209^229^[REPLACE] if  ( shape == Shape.STRING )  {^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^return Boolean.TRUE;^220^^^^^209^229^[REPLACE] return Boolean.FALSE;^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^if  ( typeHint != null && stringVisitor != null )  {^222^^^^^209^229^[REPLACE] if  ( shape.isNumeric (  )  )  {^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[ADD]^^222^223^224^^^209^229^[ADD] if  ( shape.isNumeric (  )  )  { return Boolean.TRUE; }^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^return Boolean.FALSE;^223^^^^^209^229^[REPLACE] return Boolean.TRUE;^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
[REPLACE]^return ;^225^226^227^228^^209^229^[REPLACE] throw new IllegalArgumentException  (" ") +", not supported as " +  ( fromClass? "class" : "property" ) +" annotation" ) ;^[METHOD] _isShapeWrittenUsingIndex [TYPE] Boolean [PARAMETER] Class<?> enumClass Value format boolean fromClass [CLASS] EnumSerializer   [TYPE]  Value format  [TYPE]  Class enumClass  [TYPE]  boolean false  fromClass  true  [TYPE]  Shape shape  [TYPE]  Boolean _serializeAsIndex  serializeAsIndex  [TYPE]  EnumValues _values  v 
