[REPLACE]^final ToStringSerializer sls = ToStringSerializer.instance  ;^28^^^^^27^58^[REPLACE] HashMap<Class<?>,Object> sers = new HashMap<Class<?>,Object> (  ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^JsonIntegerFormatVisitor v2 = visitor.expectIntegerFormat ( typeHint )  ;^31^^^^^27^58^[REPLACE] final ToStringSerializer sls = ToStringSerializer.instance;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( class, sls )  ;^33^^^^^27^58^[REPLACE] sers.put ( java.net.URL.class, sls ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( class, sls )  ;^34^^^^^27^58^[REPLACE] sers.put ( java.net.URI.class, sls ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( class, sls )  ;^36^^^^^27^58^[REPLACE] sers.put ( Currency.class, sls ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[ADD]^sers.put ( UUID.class, sls ) ;^36^37^^^^27^58^[ADD] sers.put ( Currency.class, sls ) ; sers.put ( UUID.class, sls ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( class, sls )  ;^37^^^^^27^58^[REPLACE] sers.put ( UUID.class, sls ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[ADD]^^37^^^^^27^58^[ADD] sers.put ( UUID.class, sls ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers .entrySet (  )  ;^38^^^^^27^58^[REPLACE] sers.put ( java.util.regex.Pattern.class, sls ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( class, sls )  ;^39^^^^^27^58^[REPLACE] sers.put ( Locale.class, sls ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( class, sls )  ;^42^^^^^27^58^[REPLACE] sers.put ( Locale.class, sls ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( class, class )  ;^45^^^^^27^58^[REPLACE] sers.put ( AtomicReference.class, AtomicReferenceSerializer.class ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers .entrySet (  )  ;^46^^^^^27^58^[REPLACE] sers.put ( AtomicBoolean.class, AtomicBooleanSerializer.class ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( class, class )  ;^47^^^^^27^58^[REPLACE] sers.put ( AtomicInteger.class, AtomicIntegerSerializer.class ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( class, class )  ;^48^^^^^27^58^[REPLACE] sers.put ( AtomicLong.class, AtomicLongSerializer.class ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[ADD]^^48^^^^^27^58^[ADD] sers.put ( AtomicLong.class, AtomicLongSerializer.class ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( TYPE, class )  ;^51^^^^^27^58^[REPLACE] sers.put ( File.class, FileSerializer.class ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( TYPE, class )  ;^52^^^^^27^58^[REPLACE] sers.put ( Class.class, ClassSerializer.class ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^sers.put ( class, class )  ;^55^^^^^27^58^[REPLACE] sers.put ( Void.TYPE, NullSerializer.class ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
[REPLACE]^return this.HashMap (  ) ;^57^^^^^27^58^[REPLACE] return sers.entrySet (  ) ;^[METHOD] all [TYPE] Collection [PARAMETER] [CLASS] StdJdkSerializers AtomicBooleanSerializer AtomicIntegerSerializer AtomicLongSerializer AtomicReferenceSerializer FileSerializer ClassSerializer   [TYPE]  boolean false  true  [TYPE]  HashMap sers  [TYPE]  ToStringSerializer sls 
