[P1_Replace_Type]^private static final char COMMON_PATTERN = "[a-zA-Z][a-zA-Z0-9\\ \\$_\\-]*$";^33^^^^^28^38^private static final String COMMON_PATTERN = "[a-zA-Z][a-zA-Z0-9\\ \\$_\\-]*$";^[CLASS] JsonFieldNameValidator   [VARIABLES] 
[P3_Replace_Literal]^private static final String COMMON_PATTERN = "a-zA-Z][a-zA-Z0-9\";^33^^^^^28^38^private static final String COMMON_PATTERN = "[a-zA-Z][a-zA-Z0-9\\ \\$_\\-]*$";^[CLASS] JsonFieldNameValidator   [VARIABLES] 
[P8_Replace_Mix]^private static final String COMMON_PATTERN ;^33^^^^^28^38^private static final String COMMON_PATTERN = "[a-zA-Z][a-zA-Z0-9\\ \\$_\\-]*$";^[CLASS] JsonFieldNameValidator   [VARIABLES] 
[P2_Replace_Operator]^private static final Pattern JSON_FIELD_NAME_PATTERN = Pattern.compile ( " ( ^"  >  COMMON_PATTERN + " ) | ( ^[\\$_]" + COMMON_PATTERN + " ) " ) ;^35^36^^^^35^36^private static final Pattern JSON_FIELD_NAME_PATTERN = Pattern.compile ( " ( ^" + COMMON_PATTERN + " ) | ( ^[\\$_]" + COMMON_PATTERN + " ) " ) ;^[CLASS] JsonFieldNameValidator   [VARIABLES] 
[P8_Replace_Mix]^private  final Pattern JSON_FIELD_NAME_PATTERN = Pattern.compile ( " ( ^" + COMMON_PATTERN + " ) | ( ^[\\$_]" + COMMON_PATTERN + " ) " ) ;^35^36^^^^35^36^private static final Pattern JSON_FIELD_NAME_PATTERN = Pattern.compile ( " ( ^" + COMMON_PATTERN + " ) | ( ^[\\$_]" + COMMON_PATTERN + " ) " ) ;^[CLASS] JsonFieldNameValidator   [VARIABLES] 
[P5_Replace_Variable]^Preconditions.checkNotNull ( COMMON_PATTERN ) ;^47^^^^^46^55^Preconditions.checkNotNull ( fieldName ) ;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P7_Replace_Invocation]^Preconditions.checkArgument ( fieldName ) ;^47^^^^^46^55^Preconditions.checkNotNull ( fieldName ) ;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P14_Delete_Statement]^^47^^^^^46^55^Preconditions.checkNotNull ( fieldName ) ;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P11_Insert_Donor_Statement]^Preconditions.checkArgument ( !"".equals ( fieldName.trim (  )  )  ) ;Preconditions.checkNotNull ( fieldName ) ;^47^^^^^46^55^Preconditions.checkNotNull ( fieldName ) ;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P5_Replace_Variable]^Preconditions.checkArgument ( !"".equals ( COMMON_PATTERN.trim (  )  )  ) ;^48^^^^^46^55^Preconditions.checkArgument ( !"".equals ( fieldName.trim (  )  )  ) ;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P7_Replace_Invocation]^Preconditions.checkArgument ( !"".equals ( fieldName.equals (  )  )  ) ;^48^^^^^46^55^Preconditions.checkArgument ( !"".equals ( fieldName.trim (  )  )  ) ;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P14_Delete_Statement]^^48^^^^^46^55^Preconditions.checkArgument ( !"".equals ( fieldName.trim (  )  )  ) ;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P11_Insert_Donor_Statement]^Preconditions.checkNotNull ( fieldName ) ;Preconditions.checkArgument ( !"".equals ( fieldName.trim (  )  )  ) ;^48^^^^^46^55^Preconditions.checkArgument ( !"".equals ( fieldName.trim (  )  )  ) ;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P5_Replace_Variable]^Matcher matcher = JSON_FIELD_NAME_PATTERN.matcher ( COMMON_PATTERN ) ;^50^^^^^46^55^Matcher matcher = JSON_FIELD_NAME_PATTERN.matcher ( fieldName ) ;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P5_Replace_Variable]^Matcher matcher = fieldName.matcher ( JSON_FIELD_NAME_PATTERN ) ;^50^^^^^46^55^Matcher matcher = JSON_FIELD_NAME_PATTERN.matcher ( fieldName ) ;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P14_Delete_Statement]^^50^^^^^46^55^Matcher matcher = JSON_FIELD_NAME_PATTERN.matcher ( fieldName ) ;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P15_Unwrap_Block]^throw new java.lang.IllegalArgumentException((fieldName + " is not a valid JSON field name."));^51^52^53^^^46^55^if  ( !matcher.matches (  )  )  { throw new IllegalArgumentException  (" ")  ; }^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P16_Remove_Block]^^51^52^53^^^46^55^if  ( !matcher.matches (  )  )  { throw new IllegalArgumentException  (" ")  ; }^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P13_Insert_Block]^if  ( ! ( matcher.matches (  )  )  )  {     throw new IllegalArgumentException (  ( fieldName + " is not a valid JSON field name." )  ) ; }^52^^^^^46^55^[Delete]^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
[P5_Replace_Variable]^return COMMON_PATTERN;^54^^^^^46^55^return fieldName;^[CLASS] JsonFieldNameValidator  [METHOD] validate [RETURN_TYPE] String   String fieldName [VARIABLES] Pattern  JSON_FIELD_NAME_PATTERN  String  COMMON_PATTERN  fieldName  boolean  Matcher  matcher  
