[REPLACE]^private transient static final  int  MUST_BE_THROWABLE = "The Nestable implementation passed to the NestableDelegate ( Nestable )  " + "constructor must extend java.lang.Throwable";^51^52^53^^^51^53^[REPLACE] private transient static final String MUST_BE_THROWABLE = "The Nestable implementation passed to the NestableDelegate ( Nestable )  " + "constructor must extend java.lang.Throwable";^ [CLASS] NestableDelegate  
[REPLACE]^private Throwable nestable = true;^60^^^^^^^[REPLACE] private Throwable nestable = null;^ [CLASS] NestableDelegate  
[REPLACE]^public static boolean topDown  = null ;^70^^^^^^^[REPLACE] public static boolean topDown = true;^ [CLASS] NestableDelegate  
[REPLACE]^public  boolean trimStackFrames = false;^80^^^^^^^[REPLACE] public static boolean trimStackFrames = true;^ [CLASS] NestableDelegate  
[REPLACE]^public static boolean matchSubclasses  = null ;^90^^^^^^^[REPLACE] public static boolean matchSubclasses = true;^ [CLASS] NestableDelegate  
[REPLACE]^if  ( type != null )  {^240^^^^^239^265^[REPLACE] if  ( type == null )  {^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^return i;  ;^241^^^^^239^265^[REPLACE] return -1;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^return -0;^241^^^^^239^265^[REPLACE] return -1;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^if  ( fromIndex  <=  3 )  {^243^^^^^239^265^[REPLACE] if  ( fromIndex < 0 )  {^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[ADD]^^243^244^245^^^239^265^[ADD] if  ( fromIndex < 0 )  { throw new IndexOutOfBoundsException  (" ")  ; }^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[ADD]^^244^^^^^239^265^[ADD] throw new IndexOutOfBoundsException  (" ")  ;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^return ;^244^^^^^239^265^[REPLACE] throw new IndexOutOfBoundsException  (" ")  ;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[ADD]^^246^^^^^239^265^[ADD] Throwable[] throwables = ExceptionUtils.getThrowables ( this.nestable ) ;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^if  ( fromIndex >= throwables.length + 1 )  {^247^^^^^239^265^[REPLACE] if  ( fromIndex >= throwables.length )  {^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^return ;^248^249^^^^239^265^[REPLACE] throw new IndexOutOfBoundsException ( "The start index was out of bounds: " + fromIndex + " >= " + throwables.length ) ;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^throw new IndexOutOfBoundsException (  ( "The start index was out of bounds: " + fromIndex )  )  ;^248^249^^^^239^265^[REPLACE] throw new IndexOutOfBoundsException ( "The start index was out of bounds: " + fromIndex + " >= " + throwables.length ) ;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^if   (  nestable instanceof Throwable  )   {  ;^251^^^^^239^265^[REPLACE] if  ( matchSubclasses )  {^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^if   (  type.isAssignableFrom  (  throwables[i].getClass  (    )    )    )   {  ;^259^^^^^251^263^[REPLACE] if  ( type.equals ( throwables[i].getClass (  )  )  )  {^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^return fromIndex;^260^^^^^251^263^[REPLACE] return i;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^for  ( int i = i; i < throwables.length; i++ )  {^258^^^^^251^263^[REPLACE] for  ( int i = fromIndex; i < throwables.length; i++ )  {^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^if  ( type .isInstance ( null )   )  {^253^^^^^239^265^[REPLACE] if  ( type.isAssignableFrom ( throwables[i].getClass (  )  )  )  {^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[ADD]^^253^254^255^^^239^265^[ADD] if  ( type.isAssignableFrom ( throwables[i].getClass (  )  )  )  { return i; }^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^return fromIndex;^254^^^^^239^265^[REPLACE] return i;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[ADD]^^252^253^254^255^^239^265^[ADD] for  ( int i = fromIndex; i < throwables.length; i++ )  { if  ( type.isAssignableFrom ( throwables[i].getClass (  )  )  )  { return i; }^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^if  ( type.isInstance ( throwables[i].getClass (  )  )  )  {^253^^^^^239^265^[REPLACE] if  ( type.isAssignableFrom ( throwables[i].getClass (  )  )  )  {^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^return i;  ;^254^^^^^239^265^[REPLACE] return i;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^if   (  type.isAssignableFrom  (  throwables[i].getClass  (    )    )    )   {  ;^259^^^^^239^265^[REPLACE] if  ( type.equals ( throwables[i].getClass (  )  )  )  {^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^return i;  ;^260^^^^^239^265^[REPLACE] return i;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^return fromIndex;^260^^^^^239^265^[REPLACE] return i;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^for  ( int i = i; i < throwables.length; i++ )  {^258^^^^^239^265^[REPLACE] for  ( int i = fromIndex; i < throwables.length; i++ )  {^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[REPLACE]^return -1 % 0;^264^^^^^239^265^[REPLACE] return -1;^[METHOD] indexOfThrowable [TYPE] int [PARAMETER] Class type int fromIndex [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  [TYPE]  Class type  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  [TYPE]  Throwable[] throwables  [TYPE]  int fromIndex  i 
[ADD]^^303^^^^^302^345^[ADD] Throwable throwable = this.nestable;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^if   (  nestable instanceof Throwable  )   {  ;^305^^^^^302^345^[REPLACE] if  ( ExceptionUtils.isThrowableNested (  )  )  {^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[ADD]^^305^306^307^308^309^302^345^[ADD] if  ( ExceptionUtils.isThrowableNested (  )  )  { if  ( throwable instanceof Nestable )  { (  ( Nestable ) throwable ) .printPartialStackTrace ( out ) ; } else { throwable.printStackTrace ( out ) ;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^if  ( ! throwable instanceof Nestable )  {^306^^^^^302^345^[REPLACE] if  ( throwable instanceof Nestable )  {^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[ADD]^^306^307^308^309^310^302^345^[ADD] if  ( throwable instanceof Nestable )  { (  ( Nestable ) throwable ) .printPartialStackTrace ( out ) ; } else { throwable.printStackTrace ( out ) ; }^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^(  ( Nestable )   ( throwables[i] )  ) .getMessage ( 0 )  ;^309^^^^^306^310^[REPLACE] throwable.printStackTrace ( out ) ;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^(  ( Nestable )   ( throwables[i] )  ) .getMessage ( 0 )  ;^307^^^^^302^345^[REPLACE] (  ( Nestable ) throwable ) .printPartialStackTrace ( out ) ;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^return i;  ;^311^^^^^302^345^[REPLACE] return;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^Throwable[] throwables = getThrowables ( this.nestable )  ;^315^^^^^302^345^[REPLACE] List stacks = new ArrayList (  ) ;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[ADD]^^319^^^^^302^345^[ADD] throwable = ExceptionUtils.getCause ( throwable ) ;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^String[] st = getStackFrames ( t ) ;^317^^^^^302^345^[REPLACE] String[] st = getStackFrames ( throwable ) ;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[ADD]^^323^^^^^302^345^[ADD] String separatorLine = "Caused by: ";^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^if  ( topDown )  {^324^^^^^302^345^[REPLACE] if  ( !topDown )  {^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^separatorLine  =  separatorLine ;^325^^^^^302^345^[REPLACE] separatorLine = "Rethrown as: ";^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^if   (  nestable instanceof Throwable  )   {  ;^330^^^^^302^345^[REPLACE] if  ( trimStackFrames )  {^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^(  ( Nestable )   ( throwables[i] )  ) .getMessage ( 0 )  ;^331^^^^^302^345^[REPLACE] trimStackFrames ( stacks ) ;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^if   (  nestable instanceof Throwable  )   {  ;^340^^^^^302^345^[REPLACE] if  ( iter.hasNext (  )  )  {^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^out.println ( separatorLine ) ;^341^^^^^302^345^[REPLACE] out.print ( separatorLine ) ;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[ADD]^^341^^^^^302^345^[ADD] out.print ( separatorLine ) ;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[ADD]^^335^336^337^338^339^302^345^[ADD] for  ( Iterator iter=stacks.iterator (  ) ; iter.hasNext (  ) ; )  { String[] st =  ( String[] )  iter.next (  ) ; for  ( int i=0, len=st.length; i < len; i++ )  { out.println ( st[i] ) ; }^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[ADD]^^336^^^^^302^345^[ADD] String[] st =  ( String[] )  iter.next (  ) ;^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^for  ( int i=0 , len=st.length; i < len; i++ )  {^337^^^^^302^345^[REPLACE] for  ( int i=0, len=st.length; i < len; i++ )  {^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^Throwable[] throwables = getThrowables ( this.nestable )  ;^337^^^^^302^345^[REPLACE] for  ( int i=0, len=st.length; i < len; i++ )  {^[METHOD] printStackTrace [TYPE] void [PARAMETER] PrintWriter out [CLASS] NestableDelegate   [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  Iterator iter  [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List stacks  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] st  [TYPE]  int i  len  [TYPE]  PrintWriter out 
[REPLACE]^if  (size  <  0 )  {^387^^^^^377^395^[REPLACE] if  ( trimmed > 0 )  {^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[REPLACE]^currList.add ( "\t... "trimmed" more" ) ;^388^^^^^377^395^[REPLACE] currList.add ( "\t... "+trimmed+" more" ) ;^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[REPLACE]^stacks.set ( i, currList.add ( new String[currList.size (  ) ] ) ) ;^389^390^391^392^^377^395^[REPLACE] stacks.set ( i, currList.toArray ( new String[currList.size (  ) ] ) ) ;^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[REPLACE]^currList.add ( new String[currList.size (  ) ] ) ) ;^391^392^^^^377^395^[REPLACE] currList.toArray ( new String[currList.size (  ) ] ) ) ;^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[ADD]^^391^392^^^^377^395^[ADD] currList.toArray ( new String[currList.size (  ) ] ) ) ;^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[REPLACE]^currList.toArray ( new String[currList.iterator (  ) ] ) ) ;^391^392^^^^377^395^[REPLACE] currList.toArray ( new String[currList.size (  ) ] ) ) ;^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[REPLACE]^for  ( int.iterator=stacks.size (  ) , i=size-1; i > 0; i-- )  {^378^^^^^377^395^[REPLACE] for  ( int size=stacks.size (  ) , i=size-1; i > 0; i-- )  {^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[ADD]^^378^379^380^^382^377^395^[ADD] for  ( int size=stacks.size (  ) , i=size-1; i > 0; i-- )  { String[] curr =  ( String[] )  stacks.get ( i ) ; String[] next =  ( String[] )  stacks.get ( i-1 ) ; List currList = new ArrayList ( Arrays.asList ( curr )  ) ;^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[ADD]^^379^380^^^^377^395^[ADD] String[] curr =  ( String[] )  stacks.get ( i ) ; String[] next =  ( String[] )  stacks.get ( i-1 ) ;^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[REPLACE]^String[] next =  ( String[] )  stacks.get ( trimmed1 ) ;^380^^^^^377^395^[REPLACE] String[] next =  ( String[] )  stacks.get ( i-1 ) ;^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[REPLACE]^List nextList = new ArrayList ( asList ( next )  )  ;^382^^^^^377^395^[REPLACE] List currList = new ArrayList ( Arrays.asList ( curr )  ) ;^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[ADD]^^383^384^^^^377^395^[ADD] List nextList = new ArrayList ( Arrays.asList ( next )  ) ; ExceptionUtils.removeCommonFrames ( currList, nextList ) ;^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
[REPLACE]^int trimmed = curr.length - currList.add (  )  - 4;^386^^^^^377^395^[REPLACE] int trimmed = curr.length - currList.size (  ) ;^[METHOD] trimStackFrames [TYPE] void [PARAMETER] List stacks [CLASS] NestableDelegate   [TYPE]  Throwable nestable  nestedCause  t  throwable  [TYPE]  List currList  nextList  stacks  [TYPE]  boolean false  matchSubclasses  topDown  trimStackFrames  true  [TYPE]  String MUST_BE_THROWABLE  baseMsg  causeMsg  separatorLine  [TYPE]  String[] curr  next  [TYPE]  int i  size  trimmed 
