[BugLab_Wrong_Literal]^private boolean highFarOut = true;^72^^^^^67^77^private boolean highFarOut = false;^[CLASS] OutlierListCollection   [VARIABLES] 
[BugLab_Wrong_Literal]^private boolean lowFarOut = true;^78^^^^^73^83^private boolean lowFarOut = false;^[CLASS] OutlierListCollection   [VARIABLES] 
[BugLab_Variable_Misuse]^return lowFarOut;^94^^^^^93^95^return this.highFarOut;^[CLASS] OutlierListCollection  [METHOD] isHighFarOut [RETURN_TYPE] boolean   [VARIABLES] List  outlierLists  boolean  highFarOut  lowFarOut  
[BugLab_Variable_Misuse]^this.highFarOut = lowFarOut;^104^^^^^103^105^this.highFarOut = farOut;^[CLASS] OutlierListCollection  [METHOD] setHighFarOut [RETURN_TYPE] void   boolean farOut [VARIABLES] List  outlierLists  boolean  farOut  highFarOut  lowFarOut  
[BugLab_Variable_Misuse]^return highFarOut;^114^^^^^113^115^return this.lowFarOut;^[CLASS] OutlierListCollection  [METHOD] isLowFarOut [RETURN_TYPE] boolean   [VARIABLES] List  outlierLists  boolean  farOut  highFarOut  lowFarOut  
[BugLab_Variable_Misuse]^this.lowFarOut = lowFarOut;^124^^^^^123^125^this.lowFarOut = farOut;^[CLASS] OutlierListCollection  [METHOD] setLowFarOut [RETURN_TYPE] void   boolean farOut [VARIABLES] List  outlierLists  boolean  farOut  highFarOut  lowFarOut  
[BugLab_Variable_Misuse]^if  ( outlierLists.isEmpty (  )  )  {^139^^^^^137^158^if  ( this.outlierLists.isEmpty (  )  )  {^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Argument_Swapping]^if  ( outlier.isOverlapped ( list )  )  {^147^^^^^137^158^if  ( list.isOverlapped ( outlier )  )  {^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Argument_Swapping]^updated = updateOutlierList ( outlier, list ) ;^148^^^^^137^158^updated = updateOutlierList ( list, outlier ) ;^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Variable_Misuse]^updated = outlierLists.add ( new OutlierList ( outlier )  ) ;^153^^^^^137^158^updated = this.outlierLists.add ( new OutlierList ( outlier )  ) ;^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Argument_Swapping]^updated = outlier.add ( new OutlierList ( this.outlierLists )  ) ;^153^^^^^137^158^updated = this.outlierLists.add ( new OutlierList ( outlier )  ) ;^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Variable_Misuse]^for  ( Iterator iterator = outlierLists.iterator (  ) ;^144^^^^^137^158^for  ( Iterator iterator = this.outlierLists.iterator (  ) ;^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Argument_Swapping]^for  ( Iterator this.outlierLists = iterator.iterator (  ) ;^144^^^^^137^158^for  ( Iterator iterator = this.outlierLists.iterator (  ) ;^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Variable_Misuse]^return lowFarOut;^155^^^^^137^158^return updated;^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Wrong_Literal]^boolean updated = true;^143^^^^^137^158^boolean updated = false;^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Argument_Swapping]^return outlier.add ( new OutlierList ( this.outlierLists )  ) ;^140^^^^^137^158^return this.outlierLists.add ( new OutlierList ( outlier )  ) ;^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Variable_Misuse]^return outlierLists.add ( new OutlierList ( outlier )  ) ;^140^^^^^137^158^return this.outlierLists.add ( new OutlierList ( outlier )  ) ;^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Variable_Misuse]^if  ( !lowFarOut )  {^151^^^^^137^158^if  ( !updated )  {^[CLASS] OutlierListCollection  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  outlier  Iterator  iterator  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Variable_Misuse]^return outlierLists.iterator (  ) ;^166^^^^^165^167^return this.outlierLists.iterator (  ) ;^[CLASS] OutlierListCollection  [METHOD] iterator [RETURN_TYPE] Iterator   [VARIABLES] List  outlierLists  boolean  farOut  highFarOut  lowFarOut  updated  
[BugLab_Wrong_Literal]^boolean result = true;^181^^^^^180^186^boolean result = false;^[CLASS] OutlierListCollection  [METHOD] updateOutlierList [RETURN_TYPE] boolean   OutlierList list Outlier outlier [VARIABLES] Outlier  outlier  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  result  updated  
[BugLab_Argument_Swapping]^result = outlier.add ( list ) ;^182^^^^^180^186^result = list.add ( outlier ) ;^[CLASS] OutlierListCollection  [METHOD] updateOutlierList [RETURN_TYPE] boolean   OutlierList list Outlier outlier [VARIABLES] Outlier  outlier  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  result  updated  
[BugLab_Wrong_Literal]^list.setMultiple ( false ) ;^184^^^^^180^186^list.setMultiple ( true ) ;^[CLASS] OutlierListCollection  [METHOD] updateOutlierList [RETURN_TYPE] boolean   OutlierList list Outlier outlier [VARIABLES] Outlier  outlier  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  result  updated  
[BugLab_Variable_Misuse]^return lowFarOut;^185^^^^^180^186^return result;^[CLASS] OutlierListCollection  [METHOD] updateOutlierList [RETURN_TYPE] boolean   OutlierList list Outlier outlier [VARIABLES] Outlier  outlier  OutlierList  list  List  outlierLists  boolean  farOut  highFarOut  lowFarOut  result  updated  
