[BugLab_Wrong_Literal]^private boolean multiple = true;^79^^^^^74^84^private boolean multiple = false;^[CLASS] OutlierList   [VARIABLES] 
[BugLab_Variable_Misuse]^setAveragedOutlier ( averagedOutlier ) ;^88^^^^^86^89^setAveragedOutlier ( outlier ) ;^[CLASS] OutlierList  [METHOD] <init> [RETURN_TYPE] Outlier)   Outlier outlier [VARIABLES] Outlier  averagedOutlier  outlier  List  outliers  boolean  multiple  
[BugLab_Argument_Swapping]^return outlier.add ( this.outliers ) ;^99^^^^^98^100^return this.outliers.add ( outlier ) ;^[CLASS] OutlierList  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  averagedOutlier  outlier  List  outliers  boolean  multiple  
[BugLab_Variable_Misuse]^return this.outliers.add ( averagedOutlier ) ;^99^^^^^98^100^return this.outliers.add ( outlier ) ;^[CLASS] OutlierList  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  averagedOutlier  outlier  List  outliers  boolean  multiple  
[BugLab_Variable_Misuse]^return outliers.add ( outlier ) ;^99^^^^^98^100^return this.outliers.add ( outlier ) ;^[CLASS] OutlierList  [METHOD] add [RETURN_TYPE] boolean   Outlier outlier [VARIABLES] Outlier  averagedOutlier  outlier  List  outliers  boolean  multiple  
[BugLab_Variable_Misuse]^return outliers.size (  ) ;^108^^^^^107^109^return this.outliers.size (  ) ;^[CLASS] OutlierList  [METHOD] getItemCount [RETURN_TYPE] int   [VARIABLES] Outlier  averagedOutlier  outlier  List  outliers  boolean  multiple  
[BugLab_Variable_Misuse]^this.averagedOutlier = outlier;^126^^^^^125^127^this.averagedOutlier = averagedOutlier;^[CLASS] OutlierList  [METHOD] setAveragedOutlier [RETURN_TYPE] void   Outlier averagedOutlier [VARIABLES] Outlier  averagedOutlier  outlier  List  outliers  boolean  multiple  
[BugLab_Variable_Misuse]^if  ( outlier == null )  {^159^^^^^157^166^if  ( other == null )  {^[CLASS] OutlierList  [METHOD] isOverlapped [RETURN_TYPE] boolean   Outlier other [VARIABLES] Outlier  averagedOutlier  other  outlier  List  outliers  boolean  multiple  result  
[BugLab_Wrong_Operator]^if  ( other != null )  {^159^^^^^157^166^if  ( other == null )  {^[CLASS] OutlierList  [METHOD] isOverlapped [RETURN_TYPE] boolean   Outlier other [VARIABLES] Outlier  averagedOutlier  other  outlier  List  outliers  boolean  multiple  result  
[BugLab_Wrong_Literal]^return true;^160^^^^^157^166^return false;^[CLASS] OutlierList  [METHOD] isOverlapped [RETURN_TYPE] boolean   Outlier other [VARIABLES] Outlier  averagedOutlier  other  outlier  List  outliers  boolean  multiple  result  
[BugLab_Variable_Misuse]^boolean result = outlier.overlaps ( getAveragedOutlier (  )  ) ;^163^^^^^157^166^boolean result = other.overlaps ( getAveragedOutlier (  )  ) ;^[CLASS] OutlierList  [METHOD] isOverlapped [RETURN_TYPE] boolean   Outlier other [VARIABLES] Outlier  averagedOutlier  other  outlier  List  outliers  boolean  multiple  result  
[BugLab_Variable_Misuse]^return multiple;^164^^^^^157^166^return result;^[CLASS] OutlierList  [METHOD] isOverlapped [RETURN_TYPE] boolean   Outlier other [VARIABLES] Outlier  averagedOutlier  other  outlier  List  outliers  boolean  multiple  result  
[BugLab_Variable_Misuse]^for  ( Iterator iterator = outliers.iterator (  ) ;^176^^^^^172^185^for  ( Iterator iterator = this.outliers.iterator (  ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Argument_Swapping]^for  ( Iterator this.outliers = iterator.iterator (  ) ;^176^^^^^172^185^for  ( Iterator iterator = this.outliers.iterator (  ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Variable_Misuse]^totalYCoords += outlier.getY (  ) ;^180^^^^^172^185^totalYCoords += o.getY (  ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Variable_Misuse]^totalXCoords += outlier.getX (  ) ;^179^^^^^172^185^totalXCoords += o.getX (  ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Argument_Swapping]^new Point2D.Double ( totalYCoords / size, totalXCoords / size ) ) ;^183^184^^^^172^185^new Point2D.Double ( totalXCoords / size, totalYCoords / size ) ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Argument_Swapping]^new Point2D.Double ( size / totalXCoords, totalYCoords / size ) ) ;^183^184^^^^172^185^new Point2D.Double ( totalXCoords / size, totalYCoords / size ) ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Wrong_Operator]^new Point2D.Double ( totalXCoords * size, totalYCoords / size ) ) ;^183^184^^^^172^185^new Point2D.Double ( totalXCoords / size, totalYCoords / size ) ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Wrong_Operator]^new Point2D.Double ( totalXCoords / size, totalYCoords + size ) ) ;^183^184^^^^172^185^new Point2D.Double ( totalXCoords / size, totalYCoords / size ) ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Variable_Misuse]^getAveragedOutlier (  ) .getPoint (  ) .setLocation ( new Point2D.Double ( totalYCoords / size, totalYCoords / size ) ) ;^182^183^184^^^172^185^getAveragedOutlier (  ) .getPoint (  ) .setLocation ( new Point2D.Double ( totalXCoords / size, totalYCoords / size ) ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Argument_Swapping]^getAveragedOutlier (  ) .getPoint (  ) .setLocation ( new Point2D.Double ( totalYCoords / size, totalXCoords / size ) ) ;^182^183^184^^^172^185^getAveragedOutlier (  ) .getPoint (  ) .setLocation ( new Point2D.Double ( totalXCoords / size, totalYCoords / size ) ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Argument_Swapping]^getAveragedOutlier (  ) .getPoint (  ) .setLocation ( new Point2D.Double ( totalXCoords / totalYCoords, size / size ) ) ;^182^183^184^^^172^185^getAveragedOutlier (  ) .getPoint (  ) .setLocation ( new Point2D.Double ( totalXCoords / size, totalYCoords / size ) ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Wrong_Operator]^getAveragedOutlier (  ) .getPoint (  ) .setLocation ( new Point2D.Double ( totalXCoords + size, totalYCoords / size ) ) ;^182^183^184^^^172^185^getAveragedOutlier (  ) .getPoint (  ) .setLocation ( new Point2D.Double ( totalXCoords / size, totalYCoords / size ) ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
[BugLab_Wrong_Operator]^getAveragedOutlier (  ) .getPoint (  ) .setLocation ( new Point2D.Double ( totalXCoords / size, totalYCoords + size ) ) ;^182^183^184^^^172^185^getAveragedOutlier (  ) .getPoint (  ) .setLocation ( new Point2D.Double ( totalXCoords / size, totalYCoords / size ) ) ;^[CLASS] OutlierList  [METHOD] updateAveragedOutlier [RETURN_TYPE] void   [VARIABLES] Outlier  averagedOutlier  o  other  outlier  Iterator  iterator  List  outliers  boolean  multiple  result  double  totalXCoords  totalYCoords  int  size  
