[BugLab_Argument_Swapping]^stream.println ( formatter.format ( level, error )  ) ;^53^^^^^52^54^stream.println ( error.format ( level, formatter )  ) ;^[CLASS] PrintStreamErrorManager  [METHOD] println [RETURN_TYPE] void   CheckLevel level JSError error [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  CheckLevel  level  JSError  error  
[BugLab_Argument_Swapping]^stream.println ( error.format ( formatter, level )  ) ;^53^^^^^52^54^stream.println ( error.format ( level, formatter )  ) ;^[CLASS] PrintStreamErrorManager  [METHOD] println [RETURN_TYPE] void   CheckLevel level JSError error [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  CheckLevel  level  JSError  error  
[BugLab_Argument_Swapping]^stream.println ( level.format ( error, formatter )  ) ;^53^^^^^52^54^stream.println ( error.format ( level, formatter )  ) ;^[CLASS] PrintStreamErrorManager  [METHOD] println [RETURN_TYPE] void   CheckLevel level JSError error [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  CheckLevel  level  JSError  error  
[BugLab_Wrong_Operator]^if  ( summaryDetailLevel >= 3 && ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^62^63^64^^^61^73^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Operator]^if  ( summaryDetailLevel > 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^62^63^64^^^61^73^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Operator]^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 || getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^62^63^64^^^61^73^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Operator]^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel > 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^62^63^64^^^61^73^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Operator]^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  >= 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^62^63^64^^^61^73^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Operator]^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )   ^  getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^62^63^64^^^61^73^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Operator]^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel > 2 && getTypedPercent (  )  > 0.0 )  )  {^62^63^64^^^61^73^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Operator]^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  >= 0.0 )  )  {^62^63^64^^^61^73^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Literal]^if  ( summaryDetailLevel >= summaryDetailLevel || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^62^63^64^^^61^73^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Literal]^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >=  && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^62^63^64^^^61^73^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Literal]^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 1 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 1.1 )  )  {^62^63^64^^^61^73^if  ( summaryDetailLevel >= 3 || ( summaryDetailLevel >= 1 && getErrorCount (  )  + getWarningCount (  )  > 0 )  || ( summaryDetailLevel >= 2 && getTypedPercent (  )  > 0.0 )  )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Operator]^if  ( getTypedPercent (  )  == 0.0 )  {^65^^^^^61^73^if  ( getTypedPercent (  )  > 0.0 )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
[BugLab_Wrong_Operator]^if  ( getTypedPercent (  )  >= 0.0 )  {^65^^^^^61^73^if  ( getTypedPercent (  )  > 0.0 )  {^[CLASS] PrintStreamErrorManager  [METHOD] printSummary [RETURN_TYPE] void   [VARIABLES] PrintStream  stream  MessageFormatter  formatter  boolean  int  summaryDetailLevel  
