[P1_Replace_Type]^private static final  short  serialVersionUID = 2751952018173406822L;^84^^^^^79^89^private static final long serialVersionUID = 2751952018173406822L;^[CLASS] ChartRenderingInfo   [VARIABLES] 
[P8_Replace_Mix]^private static final long serialVersionUID ;^84^^^^^79^89^private static final long serialVersionUID = 2751952018173406822L;^[CLASS] ChartRenderingInfo   [VARIABLES] 
[P14_Delete_Statement]^^105^^^^^104^106^this ( new StandardEntityCollection (  )  ) ;^[CLASS] ChartRenderingInfo  [METHOD] <init> [RETURN_TYPE] ChartRenderingInfo()   [VARIABLES] Rectangle2D  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P8_Replace_Mix]^this.chartArea ;^117^^^^^116^120^this.chartArea = new Rectangle2D.Double (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] <init> [RETURN_TYPE] EntityCollection)   EntityCollection entities [VARIABLES] Rectangle2D  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P11_Insert_Donor_Statement]^clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ;this.chartArea = new Rectangle2D.Double (  ) ;^117^^^^^116^120^this.chartArea = new Rectangle2D.Double (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] <init> [RETURN_TYPE] EntityCollection)   EntityCollection entities [VARIABLES] Rectangle2D  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P11_Insert_Donor_Statement]^this.chartArea =  ( Rectangle2D )  SerialUtilities.readShape ( stream ) ;this.chartArea = new Rectangle2D.Double (  ) ;^117^^^^^116^120^this.chartArea = new Rectangle2D.Double (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] <init> [RETURN_TYPE] EntityCollection)   EntityCollection entities [VARIABLES] Rectangle2D  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P8_Replace_Mix]^this.plotInfo ;^118^^^^^116^120^this.plotInfo = new PlotRenderingInfo ( this ) ;^[CLASS] ChartRenderingInfo  [METHOD] <init> [RETURN_TYPE] EntityCollection)   EntityCollection entities [VARIABLES] Rectangle2D  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P8_Replace_Mix]^this.entities =  null;^119^^^^^116^120^this.entities = entities;^[CLASS] ChartRenderingInfo  [METHOD] <init> [RETURN_TYPE] EntityCollection)   EntityCollection entities [VARIABLES] Rectangle2D  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P5_Replace_Variable]^return chartArea;^130^^^^^129^131^return this.chartArea;^[CLASS] ChartRenderingInfo  [METHOD] getChartArea [RETURN_TYPE] Rectangle2D   [VARIABLES] Rectangle2D  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P5_Replace_Variable]^this.chartArea.setRect ( chartArea ) ;^141^^^^^140^142^this.chartArea.setRect ( area ) ;^[CLASS] ChartRenderingInfo  [METHOD] setChartArea [RETURN_TYPE] void   Rectangle2D area [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P14_Delete_Statement]^^141^^^^^140^142^this.chartArea.setRect ( area ) ;^[CLASS] ChartRenderingInfo  [METHOD] setChartArea [RETURN_TYPE] void   Rectangle2D area [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P11_Insert_Donor_Statement]^this.chartArea.setRect ( 0.0, 0.0, 0.0, 0.0 ) ;this.chartArea.setRect ( area ) ;^141^^^^^140^142^this.chartArea.setRect ( area ) ;^[CLASS] ChartRenderingInfo  [METHOD] setChartArea [RETURN_TYPE] void   Rectangle2D area [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P5_Replace_Variable]^return entities;^152^^^^^151^153^return this.entities;^[CLASS] ChartRenderingInfo  [METHOD] getEntityCollection [RETURN_TYPE] EntityCollection   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P8_Replace_Mix]^this.entities =  null;^163^^^^^162^164^this.entities = entities;^[CLASS] ChartRenderingInfo  [METHOD] setEntityCollection [RETURN_TYPE] void   EntityCollection entities [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P14_Delete_Statement]^^170^171^^^^169^175^this.chartArea.setRect ( 0.0, 0.0, 0.0, 0.0 ) ; this.plotInfo = new PlotRenderingInfo ( this ) ;^[CLASS] ChartRenderingInfo  [METHOD] clear [RETURN_TYPE] void   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P11_Insert_Donor_Statement]^this.chartArea.setRect ( area ) ;this.chartArea.setRect ( 0.0, 0.0, 0.0, 0.0 ) ;^170^^^^^169^175^this.chartArea.setRect ( 0.0, 0.0, 0.0, 0.0 ) ;^[CLASS] ChartRenderingInfo  [METHOD] clear [RETURN_TYPE] void   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P8_Replace_Mix]^this.plotInfo  = null ;^171^^^^^169^175^this.plotInfo = new PlotRenderingInfo ( this ) ;^[CLASS] ChartRenderingInfo  [METHOD] clear [RETURN_TYPE] void   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P2_Replace_Operator]^if  ( this.entities == null )  {^172^^^^^169^175^if  ( this.entities != null )  {^[CLASS] ChartRenderingInfo  [METHOD] clear [RETURN_TYPE] void   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P5_Replace_Variable]^if  ( entities != null )  {^172^^^^^169^175^if  ( this.entities != null )  {^[CLASS] ChartRenderingInfo  [METHOD] clear [RETURN_TYPE] void   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P8_Replace_Mix]^if  ( entities != false )  {^172^^^^^169^175^if  ( this.entities != null )  {^[CLASS] ChartRenderingInfo  [METHOD] clear [RETURN_TYPE] void   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P9_Replace_Statement]^if  ( this.chartArea != null )  {^172^^^^^169^175^if  ( this.entities != null )  {^[CLASS] ChartRenderingInfo  [METHOD] clear [RETURN_TYPE] void   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P15_Unwrap_Block]^this.entities.clear();^172^173^174^^^169^175^if  ( this.entities != null )  { this.entities.clear (  ) ; }^[CLASS] ChartRenderingInfo  [METHOD] clear [RETURN_TYPE] void   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P16_Remove_Block]^^172^173^174^^^169^175^if  ( this.entities != null )  { this.entities.clear (  ) ; }^[CLASS] ChartRenderingInfo  [METHOD] clear [RETURN_TYPE] void   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P8_Replace_Mix]^this.entities .clear (  )  ;^173^^^^^169^175^this.entities.clear (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clear [RETURN_TYPE] void   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P14_Delete_Statement]^^173^^^^^169^175^this.entities.clear (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clear [RETURN_TYPE] void   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P5_Replace_Variable]^return plotInfo;^183^^^^^182^184^return this.plotInfo;^[CLASS] ChartRenderingInfo  [METHOD] getPlotInfo [RETURN_TYPE] PlotRenderingInfo   [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P2_Replace_Operator]^if  ( obj > this )  {^194^^^^^193^211^if  ( obj == this )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P15_Unwrap_Block]^return true;^194^195^196^^^193^211^if  ( obj == this )  { return true; }^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P16_Remove_Block]^^194^195^196^^^193^211^if  ( obj == this )  { return true; }^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P3_Replace_Literal]^return false;^195^^^^^193^211^return true;^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P2_Replace_Operator]^if  ( ! ( obj  >>  ChartRenderingInfo )  )  {^197^^^^^193^211^if  ( ! ( obj instanceof ChartRenderingInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P15_Unwrap_Block]^return false;^197^198^199^^^193^211^if  ( ! ( obj instanceof ChartRenderingInfo )  )  { return false; }^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P16_Remove_Block]^^197^198^199^^^193^211^if  ( ! ( obj instanceof ChartRenderingInfo )  )  { return false; }^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P3_Replace_Literal]^return true;^198^^^^^193^211^return false;^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P11_Insert_Donor_Statement]^ChartRenderingInfo clone =  ( ChartRenderingInfo )  super.clone (  ) ;ChartRenderingInfo that =  ( ChartRenderingInfo )  obj;^200^^^^^193^211^ChartRenderingInfo that =  ( ChartRenderingInfo )  obj;^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( chartArea, that.chartArea )  )  {^201^^^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.chartArea, chartArea )  )  {^201^^^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.chartArea.chartArea )  )  {^201^^^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal (  that.chartArea )  )  {^201^^^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.chartArea )  )  {^201^^^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( that, this.chartArea.chartArea )  )  {^201^^^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( that.chartArea, this.chartArea )  )  {^201^^^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P9_Replace_Statement]^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^201^^^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P9_Replace_Statement]^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^201^^^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P15_Unwrap_Block]^return false;^201^202^203^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  { return false; }^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P16_Remove_Block]^^201^202^203^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  { return false; }^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equal ( this.plotInfo, that.plotInfo )  )  )  {     return false; }^201^^^^^193^211^[Delete]^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equal ( this.entities, that.entities )  )  )  {     return false; }^201^^^^^193^211^[Delete]^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P3_Replace_Literal]^return true;^202^^^^^193^211^return false;^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea.chartArea )  )  {^201^^^^^193^211^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equal ( this.chartArea, that.chartArea )  )  )  {     return false; }^201^^^^^193^211^[Delete]^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( plotInfo, that.plotInfo )  )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.plotInfo.plotInfo )  )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal (  that.plotInfo )  )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.plotInfo )  )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( that, this.plotInfo.plotInfo )  )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( that.plotInfo, this.plotInfo )  )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P8_Replace_Mix]^if  ( !ObjectUtilities.equal ( this.plotInfo, plotInfo )  )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P9_Replace_Statement]^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P9_Replace_Statement]^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P15_Unwrap_Block]^return false;^204^205^206^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  { return false; }^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P16_Remove_Block]^^204^205^206^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  { return false; }^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equal ( this.chartArea, that.chartArea )  )  )  {     return false; }^204^^^^^193^211^[Delete]^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equal ( this.entities, that.entities )  )  )  {     return false; }^204^^^^^193^211^[Delete]^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P3_Replace_Literal]^return true;^205^^^^^193^211^return false;^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo.plotInfo )  )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.plotInfo, that )  )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P7_Replace_Invocation]^if  ( !ObjectUtilities .equal ( area , area )   )  {^204^^^^^193^211^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equal ( this.plotInfo, that.plotInfo )  )  )  {     return false; }^204^^^^^193^211^[Delete]^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( entities, that.entities )  )  {^207^^^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.entities, entities )  )  {^207^^^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.entities.entities )  )  {^207^^^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal (  that.entities )  )  {^207^^^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.entities )  )  {^207^^^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( that, this.entities.entities )  )  {^207^^^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( that.entities, this.entities )  )  {^207^^^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P9_Replace_Statement]^if  ( !ObjectUtilities.equal ( this.chartArea, that.chartArea )  )  {^207^^^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P9_Replace_Statement]^if  ( !ObjectUtilities.equal ( this.plotInfo, that.plotInfo )  )  {^207^^^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P15_Unwrap_Block]^return false;^207^208^209^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  { return false; }^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P16_Remove_Block]^^207^208^209^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  { return false; }^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equal ( this.plotInfo, that.plotInfo )  )  )  {     return false; }^207^^^^^193^211^[Delete]^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equal ( this.chartArea, that.chartArea )  )  )  {     return false; }^207^^^^^193^211^[Delete]^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P3_Replace_Literal]^return true;^208^^^^^193^211^return false;^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.entities, that.entities.entities )  )  {^207^^^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !ObjectUtilities.equal ( this.entities, that )  )  {^207^^^^^193^211^if  ( !ObjectUtilities.equal ( this.entities, that.entities )  )  {^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equal ( this.entities, that.entities )  )  )  {     return false; }^207^^^^^193^211^[Delete]^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P3_Replace_Literal]^return false;^210^^^^^193^211^return true;^[CLASS] ChartRenderingInfo  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  that  Object  obj  long  serialVersionUID  
[P7_Replace_Invocation]^ChartRenderingInfo clone =  ( ChartRenderingInfo )  super .clone (  )  ;^221^^^^^220^230^ChartRenderingInfo clone =  ( ChartRenderingInfo )  super.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P11_Insert_Donor_Statement]^ChartRenderingInfo that =  ( ChartRenderingInfo )  obj;ChartRenderingInfo clone =  ( ChartRenderingInfo )  super.clone (  ) ;^221^^^^^220^230^ChartRenderingInfo clone =  ( ChartRenderingInfo )  super.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P14_Delete_Statement]^^221^^^^^220^230^ChartRenderingInfo clone =  ( ChartRenderingInfo )  super.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P2_Replace_Operator]^if  ( this.chartArea == null )  {^222^^^^^220^230^if  ( this.chartArea != null )  {^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P5_Replace_Variable]^if  ( chartArea != null )  {^222^^^^^220^230^if  ( this.chartArea != null )  {^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P8_Replace_Mix]^if  ( this.chartArea != true )  {^222^^^^^220^230^if  ( this.chartArea != null )  {^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P9_Replace_Statement]^if  ( this.entities != null )  {^222^^^^^220^230^if  ( this.chartArea != null )  {^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P15_Unwrap_Block]^clone.chartArea = ((java.awt.geom.Rectangle2D) (this.chartArea.clone()));^222^223^224^^^220^230^if  ( this.chartArea != null )  { clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ; }^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P16_Remove_Block]^^222^223^224^^^220^230^if  ( this.chartArea != null )  { clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ; }^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P5_Replace_Variable]^clone.chartArea =  ( Rectangle2D )  chartArea.clone (  ) ;^223^^^^^220^230^clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P7_Replace_Invocation]^clone.chartArea =  ( Rectangle2D )  this.chartArea .clone (  )  ;^223^^^^^220^230^clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P8_Replace_Mix]^clone.chartArea =   ( Rectangle2D )  this.chartArea.null (  ) ;^223^^^^^220^230^clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P11_Insert_Donor_Statement]^this.chartArea =  ( Rectangle2D )  SerialUtilities.readShape ( stream ) ;clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ;^223^^^^^220^230^clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P11_Insert_Donor_Statement]^this.chartArea = new Rectangle2D.Double (  ) ;clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ;^223^^^^^220^230^clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P13_Insert_Block]^if  (  ( this.chartArea )  != null )  {     clone.chartArea =  (  ( Rectangle2D )   ( clone (  )  )  ) ; }^223^^^^^220^230^[Delete]^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P14_Delete_Statement]^^223^^^^^220^230^clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P2_Replace_Operator]^if  ( this.entities  &&  PublicCloneable )  {^225^^^^^220^230^if  ( this.entities instanceof PublicCloneable )  {^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P8_Replace_Mix]^if  ( entities instanceof PublicCloneable )  {^225^^^^^220^230^if  ( this.entities instanceof PublicCloneable )  {^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P15_Unwrap_Block]^org.jfree.chart.util.PublicCloneable pc = ((org.jfree.chart.util.PublicCloneable) (this.entities)); clone.entities = ((org.jfree.chart.entity.EntityCollection) (pc.clone()));^225^226^227^228^^220^230^if  ( this.entities instanceof PublicCloneable )  { PublicCloneable pc =  ( PublicCloneable )  this.entities; clone.entities =  ( EntityCollection )  pc.clone (  ) ; }^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P16_Remove_Block]^^225^226^227^228^^220^230^if  ( this.entities instanceof PublicCloneable )  { PublicCloneable pc =  ( PublicCloneable )  this.entities; clone.entities =  ( EntityCollection )  pc.clone (  ) ; }^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P7_Replace_Invocation]^clone.entities =  ( EntityCollection )  pc .clone (  )  ;^227^^^^^220^230^clone.entities =  ( EntityCollection )  pc.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P8_Replace_Mix]^clone.entities =   ( EntityCollection )  pc.null (  ) ;^227^^^^^220^230^clone.entities =  ( EntityCollection )  pc.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P14_Delete_Statement]^^227^^^^^220^230^clone.entities =  ( EntityCollection )  pc.clone (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] boolean  PublicCloneable  pc  PlotRenderingInfo  plotInfo  EntityCollection  entities  Rectangle2D  area  chartArea  ChartRenderingInfo  clone  long  serialVersionUID  
[P14_Delete_Statement]^^240^241^^^^239^242^stream.defaultWriteObject (  ) ; SerialUtilities.writeShape ( this.chartArea, stream ) ;^[CLASS] ChartRenderingInfo  [METHOD] writeObject [RETURN_TYPE] void   ObjectOutputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  ObjectOutputStream  stream  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P11_Insert_Donor_Statement]^stream.defaultReadObject (  ) ;stream.defaultWriteObject (  ) ;^240^^^^^239^242^stream.defaultWriteObject (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] writeObject [RETURN_TYPE] void   ObjectOutputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  ObjectOutputStream  stream  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P5_Replace_Variable]^SerialUtilities.writeShape ( this.chartArea ) ;^241^^^^^239^242^SerialUtilities.writeShape ( this.chartArea, stream ) ;^[CLASS] ChartRenderingInfo  [METHOD] writeObject [RETURN_TYPE] void   ObjectOutputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  ObjectOutputStream  stream  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P5_Replace_Variable]^SerialUtilities.writeShape (  stream ) ;^241^^^^^239^242^SerialUtilities.writeShape ( this.chartArea, stream ) ;^[CLASS] ChartRenderingInfo  [METHOD] writeObject [RETURN_TYPE] void   ObjectOutputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  ObjectOutputStream  stream  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P5_Replace_Variable]^SerialUtilities.writeShape ( stream, this.chartArea ) ;^241^^^^^239^242^SerialUtilities.writeShape ( this.chartArea, stream ) ;^[CLASS] ChartRenderingInfo  [METHOD] writeObject [RETURN_TYPE] void   ObjectOutputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  ObjectOutputStream  stream  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P7_Replace_Invocation]^SerialUtilities.readShape ( this.chartArea, stream ) ;^241^^^^^239^242^SerialUtilities.writeShape ( this.chartArea, stream ) ;^[CLASS] ChartRenderingInfo  [METHOD] writeObject [RETURN_TYPE] void   ObjectOutputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  ObjectOutputStream  stream  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P8_Replace_Mix]^SerialUtilities.readShape ( chartArea, stream ) ;^241^^^^^239^242^SerialUtilities.writeShape ( this.chartArea, stream ) ;^[CLASS] ChartRenderingInfo  [METHOD] writeObject [RETURN_TYPE] void   ObjectOutputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  ObjectOutputStream  stream  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P14_Delete_Statement]^^241^^^^^239^242^SerialUtilities.writeShape ( this.chartArea, stream ) ;^[CLASS] ChartRenderingInfo  [METHOD] writeObject [RETURN_TYPE] void   ObjectOutputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  ObjectOutputStream  stream  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  
[P14_Delete_Statement]^^254^^^^^252^256^stream.defaultReadObject (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] readObject [RETURN_TYPE] void   ObjectInputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  ObjectInputStream  stream  
[P11_Insert_Donor_Statement]^stream.defaultWriteObject (  ) ;stream.defaultReadObject (  ) ;^254^^^^^252^256^stream.defaultReadObject (  ) ;^[CLASS] ChartRenderingInfo  [METHOD] readObject [RETURN_TYPE] void   ObjectInputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  ObjectInputStream  stream  
[P8_Replace_Mix]^this.chartArea =   ( Rectangle2D )  SerialUtilities.readShape ( null ) ;^255^^^^^252^256^this.chartArea =  ( Rectangle2D )  SerialUtilities.readShape ( stream ) ;^[CLASS] ChartRenderingInfo  [METHOD] readObject [RETURN_TYPE] void   ObjectInputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  ObjectInputStream  stream  
[P11_Insert_Donor_Statement]^clone.chartArea =  ( Rectangle2D )  this.chartArea.clone (  ) ;this.chartArea =  ( Rectangle2D )  SerialUtilities.readShape ( stream ) ;^255^^^^^252^256^this.chartArea =  ( Rectangle2D )  SerialUtilities.readShape ( stream ) ;^[CLASS] ChartRenderingInfo  [METHOD] readObject [RETURN_TYPE] void   ObjectInputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  ObjectInputStream  stream  
[P11_Insert_Donor_Statement]^this.chartArea = new Rectangle2D.Double (  ) ;this.chartArea =  ( Rectangle2D )  SerialUtilities.readShape ( stream ) ;^255^^^^^252^256^this.chartArea =  ( Rectangle2D )  SerialUtilities.readShape ( stream ) ;^[CLASS] ChartRenderingInfo  [METHOD] readObject [RETURN_TYPE] void   ObjectInputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  ObjectInputStream  stream  
[P14_Delete_Statement]^^255^^^^^252^256^this.chartArea =  ( Rectangle2D )  SerialUtilities.readShape ( stream ) ;^[CLASS] ChartRenderingInfo  [METHOD] readObject [RETURN_TYPE] void   ObjectInputStream stream [VARIABLES] Rectangle2D  area  chartArea  boolean  PlotRenderingInfo  plotInfo  EntityCollection  entities  long  serialVersionUID  ObjectInputStream  stream  
