[buglab_swap_variables]^this ( name, member, null ) ;^47^^^^^46^48^this ( member, name, null ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] <init> [RETURN_TYPE] String)   AnnotatedMember member String name [VARIABLES] AnnotationIntrospector  _introspector  AnnotatedMember  _member  member  String  _name  name  boolean  
[buglab_swap_variables]^this (  name, null ) ;^47^^^^^46^48^this ( member, name, null ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] <init> [RETURN_TYPE] String)   AnnotatedMember member String name [VARIABLES] AnnotationIntrospector  _introspector  AnnotatedMember  _member  member  String  _name  name  boolean  
[buglab_swap_variables]^this ( member,  null ) ;^47^^^^^46^48^this ( member, name, null ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] <init> [RETURN_TYPE] String)   AnnotatedMember member String name [VARIABLES] AnnotationIntrospector  _introspector  AnnotatedMember  _member  member  String  _name  name  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition ( config, member.getName (  ) , ( member == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^62^63^^^^60^64^return new SimpleBeanPropertyDefinition ( member, member.getName (  ) , ( config == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] construct [RETURN_TYPE] SimpleBeanPropertyDefinition   MapperConfig<?> config AnnotatedMember member [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  MapperConfig  config  String  _name  name  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition (  member.getName (  ) , ( config == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^62^63^^^^60^64^return new SimpleBeanPropertyDefinition ( member, member.getName (  ) , ( config == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] construct [RETURN_TYPE] SimpleBeanPropertyDefinition   MapperConfig<?> config AnnotatedMember member [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  MapperConfig  config  String  _name  name  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition ( config, name, ( member == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^71^72^^^^69^73^return new SimpleBeanPropertyDefinition ( member, name, ( config == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] construct [RETURN_TYPE] SimpleBeanPropertyDefinition   MapperConfig<?> config AnnotatedMember member String name [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  MapperConfig  config  String  _name  name  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition (  name, ( config == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^71^72^^^^69^73^return new SimpleBeanPropertyDefinition ( member, name, ( config == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] construct [RETURN_TYPE] SimpleBeanPropertyDefinition   MapperConfig<?> config AnnotatedMember member String name [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  MapperConfig  config  String  _name  name  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition ( member, config, ( name == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^71^72^^^^69^73^return new SimpleBeanPropertyDefinition ( member, name, ( config == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] construct [RETURN_TYPE] SimpleBeanPropertyDefinition   MapperConfig<?> config AnnotatedMember member String name [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  MapperConfig  config  String  _name  name  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition ( member,  ( config == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^71^72^^^^69^73^return new SimpleBeanPropertyDefinition ( member, name, ( config == null )  ? null : config.getAnnotationIntrospector (  )  ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] construct [RETURN_TYPE] SimpleBeanPropertyDefinition   MapperConfig<?> config AnnotatedMember member String name [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  MapperConfig  config  String  _name  name  boolean  
[buglab_swap_variables]^if  ( newName.equals ( _name )  )  {^83^^^^^82^87^if  ( _name.equals ( newName )  )  {^[CLASS] SimpleBeanPropertyDefinition  [METHOD] withName [RETURN_TYPE] SimpleBeanPropertyDefinition   String newName [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  String  _name  name  newName  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition ( _member, _introspector, newName ) ;^86^^^^^82^87^return new SimpleBeanPropertyDefinition ( _member, newName, _introspector ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] withName [RETURN_TYPE] SimpleBeanPropertyDefinition   String newName [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  String  _name  name  newName  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition ( _member,  _introspector ) ;^86^^^^^82^87^return new SimpleBeanPropertyDefinition ( _member, newName, _introspector ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] withName [RETURN_TYPE] SimpleBeanPropertyDefinition   String newName [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  String  _name  name  newName  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition ( newName, _member, _introspector ) ;^86^^^^^82^87^return new SimpleBeanPropertyDefinition ( _member, newName, _introspector ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] withName [RETURN_TYPE] SimpleBeanPropertyDefinition   String newName [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  String  _name  name  newName  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition (  newName, _introspector ) ;^86^^^^^82^87^return new SimpleBeanPropertyDefinition ( _member, newName, _introspector ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] withName [RETURN_TYPE] SimpleBeanPropertyDefinition   String newName [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  String  _name  name  newName  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition ( _introspector, newName, _member ) ;^86^^^^^82^87^return new SimpleBeanPropertyDefinition ( _member, newName, _introspector ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] withName [RETURN_TYPE] SimpleBeanPropertyDefinition   String newName [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  String  _name  name  newName  boolean  
[buglab_swap_variables]^return new SimpleBeanPropertyDefinition ( _member, newName ) ;^86^^^^^82^87^return new SimpleBeanPropertyDefinition ( _member, newName, _introspector ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] withName [RETURN_TYPE] SimpleBeanPropertyDefinition   String newName [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  String  _name  name  newName  boolean  
[buglab_swap_variables]^return  ( _member == null )  ? null : _introspector.findWrapperName ( _introspector ) ;^103^^^^^102^104^return  ( _introspector == null )  ? null : _introspector.findWrapperName ( _member ) ;^[CLASS] SimpleBeanPropertyDefinition  [METHOD] getWrapperName [RETURN_TYPE] PropertyName   [VARIABLES] AnnotationIntrospector  _introspector  intr  AnnotatedMember  _member  member  String  _name  name  newName  boolean  
