[BugLab_Wrong_Literal]^public static final int EQUAL_BIT_KEY = -;^50^^^^^45^55^public static final int EQUAL_BIT_KEY = -2;^[CLASS] KeyAnalyzer   [VARIABLES] 
[BugLab_Variable_Misuse]^return bitIndex == NULL_BIT_KEY;^58^^^^^57^59^return bitIndex == OUT_OF_BOUNDS_BIT_KEY;^[CLASS] KeyAnalyzer  [METHOD] isOutOfBoundsIndex [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Argument_Swapping]^return OUT_OF_BOUNDS_BIT_KEY == bitIndex;^58^^^^^57^59^return bitIndex == OUT_OF_BOUNDS_BIT_KEY;^[CLASS] KeyAnalyzer  [METHOD] isOutOfBoundsIndex [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Wrong_Operator]^return bitIndex != OUT_OF_BOUNDS_BIT_KEY;^58^^^^^57^59^return bitIndex == OUT_OF_BOUNDS_BIT_KEY;^[CLASS] KeyAnalyzer  [METHOD] isOutOfBoundsIndex [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Variable_Misuse]^return OUT_OF_BOUNDS_BIT_KEY == EQUAL_BIT_KEY;^65^^^^^64^66^return bitIndex == EQUAL_BIT_KEY;^[CLASS] KeyAnalyzer  [METHOD] isEqualBitKey [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Variable_Misuse]^return bitIndex == OUT_OF_BOUNDS_BIT_KEY;^65^^^^^64^66^return bitIndex == EQUAL_BIT_KEY;^[CLASS] KeyAnalyzer  [METHOD] isEqualBitKey [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Argument_Swapping]^return EQUAL_BIT_KEY == bitIndex;^65^^^^^64^66^return bitIndex == EQUAL_BIT_KEY;^[CLASS] KeyAnalyzer  [METHOD] isEqualBitKey [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Wrong_Operator]^return bitIndex < EQUAL_BIT_KEY;^65^^^^^64^66^return bitIndex == EQUAL_BIT_KEY;^[CLASS] KeyAnalyzer  [METHOD] isEqualBitKey [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Variable_Misuse]^return OUT_OF_BOUNDS_BIT_KEY == NULL_BIT_KEY;^72^^^^^71^73^return bitIndex == NULL_BIT_KEY;^[CLASS] KeyAnalyzer  [METHOD] isNullBitKey [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Variable_Misuse]^return bitIndex == OUT_OF_BOUNDS_BIT_KEY;^72^^^^^71^73^return bitIndex == NULL_BIT_KEY;^[CLASS] KeyAnalyzer  [METHOD] isNullBitKey [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Argument_Swapping]^return NULL_BIT_KEY == bitIndex;^72^^^^^71^73^return bitIndex == NULL_BIT_KEY;^[CLASS] KeyAnalyzer  [METHOD] isNullBitKey [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Wrong_Operator]^return bitIndex != NULL_BIT_KEY;^72^^^^^71^73^return bitIndex == NULL_BIT_KEY;^[CLASS] KeyAnalyzer  [METHOD] isNullBitKey [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Variable_Misuse]^return OUT_OF_BOUNDS_BIT_KEY >= 0;^80^^^^^79^81^return bitIndex >= 0;^[CLASS] KeyAnalyzer  [METHOD] isValidBitIndex [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Wrong_Operator]^return bitIndex > 0;^80^^^^^79^81^return bitIndex >= 0;^[CLASS] KeyAnalyzer  [METHOD] isValidBitIndex [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Wrong_Literal]^return bitIndex >= EQUAL_BIT_KEY;^80^^^^^79^81^return bitIndex >= 0;^[CLASS] KeyAnalyzer  [METHOD] isValidBitIndex [RETURN_TYPE] boolean   final int bitIndex [VARIABLES] long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  boolean  
[BugLab_Wrong_Operator]^if  ( o1 != null )  {^139^^^^^138^146^if  ( o1 == null )  {^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Wrong_Literal]^if  ( o2 == null )  {^139^^^^^138^146^if  ( o1 == null )  {^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Wrong_Literal]^if  ( ootherOffsetInBits == null )  {^139^^^^^138^146^if  ( o1 == null )  {^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Variable_Misuse]^} else if  ( o1 == null )  {^141^^^^^138^146^} else if  ( o2 == null )  {^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Wrong_Operator]^} else if  ( o2 != null )  {^141^^^^^138^146^} else if  ( o2 == null )  {^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Wrong_Literal]^return lengthInBits;^142^^^^^138^146^return 1;^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Variable_Misuse]^return o1 == null ? 0 : -1;^140^^^^^138^146^return o2 == null ? 0 : -1;^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Wrong_Operator]^return o2 != null ? 0 : -1;^140^^^^^138^146^return o2 == null ? 0 : -1;^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Wrong_Literal]^return o2 == null ? OUT_OF_BOUNDS_BIT_KEY : -1;^140^^^^^138^146^return o2 == null ? 0 : -1;^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Wrong_Literal]^return o2 == null ? 0 : -lengthInBits;^140^^^^^138^146^return o2 == null ? 0 : -1;^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Wrong_Literal]^return 2;^142^^^^^138^146^return 1;^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Wrong_Literal]^return o2 == null ? 1 : -1;^140^^^^^138^146^return o2 == null ? 0 : -1;^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Wrong_Literal]^return o2 == null ? 0 : -;^140^^^^^138^146^return o2 == null ? 0 : -1;^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Wrong_Literal]^return offsetInBits;^142^^^^^138^146^return 1;^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
[BugLab_Variable_Misuse]^return  (  ( Comparable<K> )  o1 ) .compareTo ( o1 ) ;^145^^^^^138^146^return  (  ( Comparable<K> )  o1 ) .compareTo ( o2 ) ;^[CLASS] KeyAnalyzer  [METHOD] compare [RETURN_TYPE] int   final K o1 final K o2 [VARIABLES] K  o1  o2  boolean  long  serialVersionUID  int  EQUAL_BIT_KEY  NULL_BIT_KEY  OUT_OF_BOUNDS_BIT_KEY  bitIndex  lengthInBits  offsetInBits  otherLengthInBits  otherOffsetInBits  
