[BugLab_Variable_Misuse]^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, this, WED, THU, FRI, SAT };^37^^^^^32^42^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, TUE, WED, THU, FRI, SAT };^[CLASS] Weekday   [VARIABLES] 
[BugLab_Argument_Swapping]^private static Weekday[]            _weekdays = new Weekday[] { null, TUE, MON, SUN, WED, THU, FRI, SAT };^37^^^^^32^42^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, TUE, WED, THU, FRI, SAT };^[CLASS] Weekday   [VARIABLES] 
[BugLab_Argument_Swapping]^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, WED, TUE, MON, THU, FRI, SAT };^37^^^^^32^42^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, TUE, WED, THU, FRI, SAT };^[CLASS] Weekday   [VARIABLES] 
[BugLab_Argument_Swapping]^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, WED, TUE, THU, FRI, SAT };^37^^^^^32^42^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, TUE, WED, THU, FRI, SAT };^[CLASS] Weekday   [VARIABLES] 
[BugLab_Argument_Swapping]^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, TUE, WED, FRI, THU, SAT };^37^^^^^32^42^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, TUE, WED, THU, FRI, SAT };^[CLASS] Weekday   [VARIABLES] 
[BugLab_Argument_Swapping]^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, FRI, WED, THU, TUE, SAT };^37^^^^^32^42^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, TUE, WED, THU, FRI, SAT };^[CLASS] Weekday   [VARIABLES] 
[BugLab_Argument_Swapping]^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, TUE, WED, THU, SAT, FRI };^37^^^^^32^42^private static Weekday[]            _weekdays = new Weekday[] { null, SUN, MON, TUE, WED, THU, FRI, SAT };^[CLASS] Weekday   [VARIABLES] 
[BugLab_Wrong_Literal]^public static int DAYS_PER_WEEK = 6;^43^^^^^38^48^public static int DAYS_PER_WEEK = 7;^[CLASS] Weekday   [VARIABLES] 
[BugLab_Wrong_Literal]^SUN ( 2, true ) , MON ( 2, false ) , TUE ( 3, false ) , WED ( 4, false ) , THU ( 5, false ) , FRI ( 6, false ) , SAT ( 7, true ) ;^34^^^^^29^39^SUN ( 1, true ) , MON ( 2, false ) , TUE ( 3, false ) , WED ( 4, false ) , THU ( 5, false ) , FRI ( 6, false ) , SAT ( 7, true ) ;^[CLASS] Weekday   [VARIABLES] 
[BugLab_Wrong_Literal]^SUN ( 1, false ) , MON ( 2, false ) , TUE ( 3, false ) , WED ( 4, false ) , THU ( 5, false ) , FRI ( 6, false ) , SAT ( 7, false ) ;^34^^^^^29^39^SUN ( 1, true ) , MON ( 2, false ) , TUE ( 3, false ) , WED ( 4, false ) , THU ( 5, false ) , FRI ( 6, false ) , SAT ( 7, true ) ;^[CLASS] Weekday   [VARIABLES] 
[BugLab_Wrong_Literal]^SUN ( 1, true ) , MON ( 2, false ) , TUE ( 4, false ) , WED ( 4, false ) , THU ( 5, false ) , FRI ( 6, false ) , SAT ( 7, true ) ;^34^^^^^29^39^SUN ( 1, true ) , MON ( 2, false ) , TUE ( 3, false ) , WED ( 4, false ) , THU ( 5, false ) , FRI ( 6, false ) , SAT ( 7, true ) ;^[CLASS] Weekday   [VARIABLES] 
[BugLab_Wrong_Literal]^SUN ( 1, true ) , MON ( 2, false ) , TUE ( 3, false ) , WED ( , false ) , THU ( 5, false ) , FRI ( 6, false ) , SAT ( 7, true ) ;^34^^^^^29^39^SUN ( 1, true ) , MON ( 2, false ) , TUE ( 3, false ) , WED ( 4, false ) , THU ( 5, false ) , FRI ( 6, false ) , SAT ( 7, true ) ;^[CLASS] Weekday   [VARIABLES] 
[BugLab_Wrong_Literal]^SUN ( 1, true ) , MON ( 2, false ) , TUE ( 3, false ) , WED ( 4, false ) , THU ( 6, false ) , FRI ( 6, false ) , SAT ( 7, true ) ;^34^^^^^29^39^SUN ( 1, true ) , MON ( 2, false ) , TUE ( 3, false ) , WED ( 4, false ) , THU ( 5, false ) , FRI ( 6, false ) , SAT ( 7, true ) ;^[CLASS] Weekday   [VARIABLES] 
[BugLab_Wrong_Literal]^SUN ( 1, true ) , MON ( 2, false ) , TUE ( 3, false ) , WED ( 4, false ) , THU ( 5, false ) , FRI ( 6, false ) , SAT ( 4, true ) ;^34^^^^^29^39^SUN ( 1, true ) , MON ( 2, false ) , TUE ( 3, false ) , WED ( 4, false ) , THU ( 5, false ) , FRI ( 6, false ) , SAT ( 7, true ) ;^[CLASS] Weekday   [VARIABLES] 
[BugLab_Variable_Misuse]^_weekday = _weekday;^104^^^^^103^106^_weekday = weekday;^[CLASS] Weekday  [METHOD] <init> [RETURN_TYPE] Weekday(int,boolean)   int weekday boolean isWeekend [VARIABLES] Weekday  FRI  MON  SAT  SUN  THU  TUE  WED  boolean  _isWeekend  isWeekend  Weekday[]  _weekdays  String[]  FULL_NAME  Map  _names  int  DAYS_PER_WEEK  _weekday  weekday  
[BugLab_Variable_Misuse]^_isWeekend = _isWeekend;^105^^^^^103^106^_isWeekend = isWeekend;^[CLASS] Weekday  [METHOD] <init> [RETURN_TYPE] Weekday(int,boolean)   int weekday boolean isWeekend [VARIABLES] Weekday  FRI  MON  SAT  SUN  THU  TUE  WED  boolean  _isWeekend  isWeekend  Weekday[]  _weekdays  String[]  FULL_NAME  Map  _names  int  DAYS_PER_WEEK  _weekday  weekday  
[BugLab_Wrong_Operator]^if  ( str.length (  )  >= 3 )  {^79^^^^^77^89^if  ( str.length (  )  == 3 )  {^[CLASS] Weekday  [METHOD] weekday [RETURN_TYPE] Weekday   String str [VARIABLES] Weekday  FRI  MON  SAT  SUN  THU  TUE  WED  weekday  boolean  _isWeekend  isWeekend  Weekday[]  _weekdays  String[]  FULL_NAME  String  str  Map  _names  int  DAYS_PER_WEEK  _weekday  index  weekday  IllegalArgumentException  iae  
[BugLab_Wrong_Literal]^if  ( str.length (  )  == DAYS_PER_WEEK )  {^79^^^^^77^89^if  ( str.length (  )  == 3 )  {^[CLASS] Weekday  [METHOD] weekday [RETURN_TYPE] Weekday   String str [VARIABLES] Weekday  FRI  MON  SAT  SUN  THU  TUE  WED  weekday  boolean  _isWeekend  isWeekend  Weekday[]  _weekdays  String[]  FULL_NAME  String  str  Map  _names  int  DAYS_PER_WEEK  _weekday  index  weekday  IllegalArgumentException  iae  
[BugLab_Argument_Swapping]^weekday = str.get ( _names.toLowerCase (  )  ) ;^86^^^^^77^89^weekday = _names.get ( str.toLowerCase (  )  ) ;^[CLASS] Weekday  [METHOD] weekday [RETURN_TYPE] Weekday   String str [VARIABLES] Weekday  FRI  MON  SAT  SUN  THU  TUE  WED  weekday  boolean  _isWeekend  isWeekend  Weekday[]  _weekdays  String[]  FULL_NAME  String  str  Map  _names  int  DAYS_PER_WEEK  _weekday  index  weekday  IllegalArgumentException  iae  
[BugLab_Variable_Misuse]^return WED;^88^^^^^77^89^return weekday;^[CLASS] Weekday  [METHOD] weekday [RETURN_TYPE] Weekday   String str [VARIABLES] Weekday  FRI  MON  SAT  SUN  THU  TUE  WED  weekday  boolean  _isWeekend  isWeekend  Weekday[]  _weekdays  String[]  FULL_NAME  String  str  Map  _names  int  DAYS_PER_WEEK  _weekday  index  weekday  IllegalArgumentException  iae  
[BugLab_Variable_Misuse]^return ! isWeekend;^116^^^^^115^117^return ! _isWeekend;^[CLASS] Weekday  [METHOD] isWeekday [RETURN_TYPE] boolean   [VARIABLES] Weekday  FRI  MON  SAT  SUN  THU  TUE  WED  weekday  boolean  _isWeekend  isWeekend  Weekday[]  _weekdays  String[]  FULL_NAME  Map  _names  int  DAYS_PER_WEEK  _weekday  index  weekday  
[BugLab_Variable_Misuse]^return isWeekend;^124^^^^^123^125^return _isWeekend;^[CLASS] Weekday  [METHOD] isWeekend [RETURN_TYPE] boolean   [VARIABLES] Weekday  FRI  MON  SAT  SUN  THU  TUE  WED  weekday  boolean  _isWeekend  isWeekend  Weekday[]  _weekdays  String[]  FULL_NAME  Map  _names  int  DAYS_PER_WEEK  _weekday  index  weekday  
[BugLab_Variable_Misuse]^return weekday;^159^^^^^158^160^return _weekday;^[CLASS] Weekday  [METHOD] getValue [RETURN_TYPE] int   [VARIABLES] Weekday  FRI  MON  SAT  SUN  THU  TUE  WED  weekday  boolean  _isWeekend  isWeekend  Weekday[]  _weekdays  String[]  FULL_NAME  Map  _names  int  DAYS_PER_WEEK  _weekday  index  weekday  
