[buglab_swap_variables]^_property = src._property._property;^37^^^^^34^38^_property = src._property;^[CLASS] ArraySerializerBase  [METHOD] <init> [RETURN_TYPE] ArraySerializerBase)   ArraySerializerBase<?> src [VARIABLES] ArraySerializerBase  src  BeanProperty  _property  property  boolean  
[buglab_swap_variables]^_property = src;^37^^^^^34^38^_property = src._property;^[CLASS] ArraySerializerBase  [METHOD] <init> [RETURN_TYPE] ArraySerializerBase)   ArraySerializerBase<?> src [VARIABLES] ArraySerializerBase  src  BeanProperty  _property  property  boolean  
[buglab_swap_variables]^serializeContents ( jgen, value, provider ) ;^53^^^^^47^59^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serialize [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider [VARIABLES] JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents (  jgen, provider ) ;^53^^^^^47^59^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serialize [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider [VARIABLES] JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents ( value, provider, jgen ) ;^53^^^^^47^59^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serialize [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider [VARIABLES] JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents ( value,  provider ) ;^53^^^^^47^59^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serialize [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider [VARIABLES] JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents ( value, jgen ) ;^53^^^^^47^59^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serialize [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider [VARIABLES] JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents ( provider, jgen, value ) ;^57^^^^^47^59^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serialize [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider [VARIABLES] JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents (  jgen, provider ) ;^57^^^^^47^59^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serialize [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider [VARIABLES] JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents ( jgen, value, provider ) ;^57^^^^^47^59^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serialize [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider [VARIABLES] JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents ( value,  provider ) ;^57^^^^^47^59^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serialize [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider [VARIABLES] JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents ( value, jgen ) ;^57^^^^^47^59^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serialize [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider [VARIABLES] JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^typeSer.writeTypePrefixForArray ( jgen, value ) ;^67^^^^^62^70^typeSer.writeTypePrefixForArray ( value, jgen ) ;^[CLASS] ArraySerializerBase  [METHOD] serializeWithType [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider TypeSerializer typeSer [VARIABLES] TypeSerializer  typeSer  JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^typeSer.writeTypePrefixForArray (  jgen ) ;^67^^^^^62^70^typeSer.writeTypePrefixForArray ( value, jgen ) ;^[CLASS] ArraySerializerBase  [METHOD] serializeWithType [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider TypeSerializer typeSer [VARIABLES] TypeSerializer  typeSer  JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^typeSer.writeTypePrefixForArray ( value ) ;^67^^^^^62^70^typeSer.writeTypePrefixForArray ( value, jgen ) ;^[CLASS] ArraySerializerBase  [METHOD] serializeWithType [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider TypeSerializer typeSer [VARIABLES] TypeSerializer  typeSer  JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents ( provider, jgen, value ) ;^68^^^^^62^70^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serializeWithType [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider TypeSerializer typeSer [VARIABLES] TypeSerializer  typeSer  JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents (  jgen, provider ) ;^68^^^^^62^70^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serializeWithType [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider TypeSerializer typeSer [VARIABLES] TypeSerializer  typeSer  JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents ( value, provider, jgen ) ;^68^^^^^62^70^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serializeWithType [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider TypeSerializer typeSer [VARIABLES] TypeSerializer  typeSer  JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents ( value,  provider ) ;^68^^^^^62^70^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serializeWithType [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider TypeSerializer typeSer [VARIABLES] TypeSerializer  typeSer  JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^serializeContents ( value, jgen ) ;^68^^^^^62^70^serializeContents ( value, jgen, provider ) ;^[CLASS] ArraySerializerBase  [METHOD] serializeWithType [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider TypeSerializer typeSer [VARIABLES] TypeSerializer  typeSer  JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^typeSer.writeTypeSuffixForArray (  jgen ) ;^69^^^^^62^70^typeSer.writeTypeSuffixForArray ( value, jgen ) ;^[CLASS] ArraySerializerBase  [METHOD] serializeWithType [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider TypeSerializer typeSer [VARIABLES] TypeSerializer  typeSer  JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
[buglab_swap_variables]^typeSer.writeTypeSuffixForArray ( value ) ;^69^^^^^62^70^typeSer.writeTypeSuffixForArray ( value, jgen ) ;^[CLASS] ArraySerializerBase  [METHOD] serializeWithType [RETURN_TYPE] void   T value JsonGenerator jgen SerializerProvider provider TypeSerializer typeSer [VARIABLES] TypeSerializer  typeSer  JsonGenerator  jgen  boolean  T  value  SerializerProvider  provider  BeanProperty  _property  property  
