[BugLab_Variable_Misuse]^super ( DEFAULT_ITEM_LABEL_FORMAT, xFormat, yFormat ) ;^110^^^^^107^111^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] NumberFormat)   String formatString NumberFormat xFormat NumberFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  NumberFormat  xFormat  yFormat  
[BugLab_Variable_Misuse]^super ( formatString, xFormat, xFormat ) ;^110^^^^^107^111^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] NumberFormat)   String formatString NumberFormat xFormat NumberFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  NumberFormat  xFormat  yFormat  
[BugLab_Argument_Swapping]^super ( yFormat, xFormat, formatString ) ;^110^^^^^107^111^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] NumberFormat)   String formatString NumberFormat xFormat NumberFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  NumberFormat  xFormat  yFormat  
[BugLab_Argument_Swapping]^super ( formatString, yFormat, xFormat ) ;^110^^^^^107^111^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] NumberFormat)   String formatString NumberFormat xFormat NumberFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  NumberFormat  xFormat  yFormat  
[BugLab_Argument_Swapping]^super ( xFormat, formatString, yFormat ) ;^126^^^^^123^127^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] NumberFormat)   String formatString DateFormat xFormat NumberFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  DateFormat  xFormat  NumberFormat  yFormat  
[BugLab_Argument_Swapping]^super ( formatString, yFormat, xFormat ) ;^126^^^^^123^127^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] NumberFormat)   String formatString DateFormat xFormat NumberFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  DateFormat  xFormat  NumberFormat  yFormat  
[BugLab_Variable_Misuse]^super ( DEFAULT_ITEM_LABEL_FORMAT, xFormat, yFormat ) ;^146^^^^^143^147^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] DateFormat)   String formatString NumberFormat xFormat DateFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  NumberFormat  xFormat  DateFormat  yFormat  
[BugLab_Argument_Swapping]^super ( xFormat, formatString, yFormat ) ;^146^^^^^143^147^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] DateFormat)   String formatString NumberFormat xFormat DateFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  NumberFormat  xFormat  DateFormat  yFormat  
[BugLab_Argument_Swapping]^super ( formatString, yFormat, xFormat ) ;^146^^^^^143^147^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] DateFormat)   String formatString NumberFormat xFormat DateFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  NumberFormat  xFormat  DateFormat  yFormat  
[BugLab_Variable_Misuse]^super ( DEFAULT_ITEM_LABEL_FORMAT, xFormat, yFormat ) ;^162^^^^^159^163^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] DateFormat)   String formatString DateFormat xFormat DateFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  DateFormat  xFormat  yFormat  
[BugLab_Argument_Swapping]^super ( yFormat, xFormat, formatString ) ;^162^^^^^159^163^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] DateFormat)   String formatString DateFormat xFormat DateFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  DateFormat  xFormat  yFormat  
[BugLab_Argument_Swapping]^super ( formatString, yFormat, xFormat ) ;^162^^^^^159^163^super ( formatString, xFormat, yFormat ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] <init> [RETURN_TYPE] DateFormat)   String formatString DateFormat xFormat DateFormat yFormat [VARIABLES] String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  DateFormat  xFormat  yFormat  
[BugLab_Variable_Misuse]^return generateLabelString ( dataset, item, item ) ;^175^^^^^174^176^return generateLabelString ( dataset, series, item ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] generateLabel [RETURN_TYPE] String   XYDataset dataset int series int item [VARIABLES] XYDataset  dataset  String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^return generateLabelString ( item, series, dataset ) ;^175^^^^^174^176^return generateLabelString ( dataset, series, item ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] generateLabel [RETURN_TYPE] String   XYDataset dataset int series int item [VARIABLES] XYDataset  dataset  String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^return generateLabelString ( dataset, item, series ) ;^175^^^^^174^176^return generateLabelString ( dataset, series, item ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] generateLabel [RETURN_TYPE] String   XYDataset dataset int series int item [VARIABLES] XYDataset  dataset  String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^return generateLabelString ( series, dataset, item ) ;^175^^^^^174^176^return generateLabelString ( dataset, series, item ) ;^[CLASS] StandardXYItemLabelGenerator  [METHOD] generateLabel [RETURN_TYPE] String   XYDataset dataset int series int item [VARIABLES] XYDataset  dataset  String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Operator]^if  ( obj <= this )  {^197^^^^^196^204^if  ( obj == this )  {^[CLASS] StandardXYItemLabelGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  
[BugLab_Wrong_Literal]^return false;^198^^^^^196^204^return true;^[CLASS] StandardXYItemLabelGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  
[BugLab_Wrong_Operator]^if  ( ! ( obj  &  StandardXYItemLabelGenerator )  )  {^200^^^^^196^204^if  ( ! ( obj instanceof StandardXYItemLabelGenerator )  )  {^[CLASS] StandardXYItemLabelGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  
[BugLab_Wrong_Literal]^return true;^201^^^^^196^204^return false;^[CLASS] StandardXYItemLabelGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  String  DEFAULT_ITEM_LABEL_FORMAT  formatString  boolean  long  serialVersionUID  
