[BugLab_Wrong_Operator]^if  ( data  >=  YisSymbolic )  {^88^^^^^85^109^if  ( data instanceof YisSymbolic )  {^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^yStr = Double.toString ( round ( x, 2 )  ) ;^93^^^^^85^109^yStr = Double.toString ( round ( y, 2 )  ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Literal]^yStr = Double.toString ( round ( y, item )  ) ;^93^^^^^85^109^yStr = Double.toString ( round ( y, 2 )  ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^double y = data.getYValue ( item, item ) ;^92^^^^^85^109^double y = data.getYValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^double y = data.getYValue ( series, series ) ;^92^^^^^85^109^double y = data.getYValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^double y = series.getYValue ( data, item ) ;^92^^^^^85^109^double y = data.getYValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^double y = data.getYValue ( item, series ) ;^92^^^^^85^109^double y = data.getYValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^double y = item.getYValue ( series, data ) ;^92^^^^^85^109^double y = data.getYValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Literal]^yStr = Double.toString ( round ( y, series )  ) ;^93^^^^^85^109^yStr = Double.toString ( round ( y, 2 )  ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^yStr =  (  ( YisSymbolic )  data ) .getYSymbolicValue ( item, series ) ;^89^^^^^85^109^yStr =  (  ( YisSymbolic )  data ) .getYSymbolicValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^yStr =  (  ( YisSymbolic )  data ) .getYSymbolicValue ( item, item ) ;^89^^^^^85^109^yStr =  (  ( YisSymbolic )  data ) .getYSymbolicValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Literal]^yStr = Double.toString ( round ( y, 1 )  ) ;^93^^^^^85^109^yStr = Double.toString ( round ( y, 2 )  ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Literal]^yStr = Double.toString ( round ( y,  )  ) ;^93^^^^^85^109^yStr = Double.toString ( round ( y, 2 )  ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Operator]^if  ( data  <  XisSymbolic )  {^95^^^^^85^109^if  ( data instanceof XisSymbolic )  {^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Operator]^if  ( data  >  XisSymbolic )  {^95^^^^^85^109^if  ( data instanceof XisSymbolic )  {^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Operator]^else if  ( data  ==  TimeSeriesCollection )  {^98^^^^^85^109^else if  ( data instanceof TimeSeriesCollection )  {^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^xStr = Double.toString ( round ( y, 2 )  ) ;^106^^^^^85^109^xStr = Double.toString ( round ( x, 2 )  ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Literal]^xStr = Double.toString ( round ( x, 3 )  ) ;^106^^^^^85^109^xStr = Double.toString ( round ( x, 2 )  ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^double x = data.getXValue ( item, item ) ;^105^^^^^85^109^double x = data.getXValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^double x = data.getXValue ( series, series ) ;^105^^^^^85^109^double x = data.getXValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^double x = item.getXValue ( series, data ) ;^105^^^^^85^109^double x = data.getXValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^double x = data.getXValue ( item, series ) ;^105^^^^^85^109^double x = data.getXValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Literal]^xStr = Double.toString ( round ( x,  )  ) ;^106^^^^^85^109^xStr = Double.toString ( round ( x, 2 )  ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^RegularTimePeriod p =  (  ( TimeSeriesCollection )  data ) .getSeries ( item ) .getTimePeriod ( item ) ;^99^100^101^^^85^109^RegularTimePeriod p =  (  ( TimeSeriesCollection )  data ) .getSeries ( series ) .getTimePeriod ( item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^RegularTimePeriod p =  (  ( TimeSeriesCollection )  data ) .getSeries ( series ) .getTimePeriod ( series ) ;^99^100^101^^^85^109^RegularTimePeriod p =  (  ( TimeSeriesCollection )  data ) .getSeries ( series ) .getTimePeriod ( item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^RegularTimePeriod p =  (  ( TimeSeriesCollection )  data ) .getSeries ( item ) .getTimePeriod ( series ) ;^99^100^101^^^85^109^RegularTimePeriod p =  (  ( TimeSeriesCollection )  data ) .getSeries ( series ) .getTimePeriod ( item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^=  (  ( TimeSeriesCollection )  data ) .getSeries ( series ) .getTimePeriod ( series ) ;^100^101^^^^85^109^=  (  ( TimeSeriesCollection )  data ) .getSeries ( series ) .getTimePeriod ( item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^=  (  ( TimeSeriesCollection )  data ) .getSeries ( item ) .getTimePeriod ( item ) ;^100^101^^^^85^109^=  (  ( TimeSeriesCollection )  data ) .getSeries ( series ) .getTimePeriod ( item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Literal]^xStr = Double.toString ( round ( x, 1 )  ) ;^106^^^^^85^109^xStr = Double.toString ( round ( x, 2 )  ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^=  (  ( TimeSeriesCollection )  data ) .getSeries ( item ) .getTimePeriod ( series ) ;^100^101^^^^85^109^=  (  ( TimeSeriesCollection )  data ) .getSeries ( series ) .getTimePeriod ( item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^double x = series.getXValue ( data, item ) ;^105^^^^^85^109^double x = data.getXValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^xStr =  (  ( XisSymbolic )  data ) .getXSymbolicValue ( series, series ) ;^96^^^^^85^109^xStr =  (  ( XisSymbolic )  data ) .getXSymbolicValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^xStr =  (  ( XisSymbolic )  data ) .getXSymbolicValue ( item, series ) ;^96^^^^^85^109^xStr =  (  ( XisSymbolic )  data ) .getXSymbolicValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Variable_Misuse]^xStr =  (  ( XisSymbolic )  data ) .getXSymbolicValue ( item, item ) ;^96^^^^^85^109^xStr =  (  ( XisSymbolic )  data ) .getXSymbolicValue ( series, item ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Operator]^else if  ( data  <=  TimeSeriesCollection )  {^98^^^^^85^109^else if  ( data instanceof TimeSeriesCollection )  {^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Literal]^xStr = Double.toString ( round ( x, item )  ) ;^106^^^^^85^109^xStr = Double.toString ( round ( x, 2 )  ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Argument_Swapping]^return "X: " + yStr + ", Y: " + xStr;^108^^^^^85^109^return "X: " + xStr + ", Y: " + yStr;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Operator]^return "X: "  >  xStr  >  ", Y: " + yStr;^108^^^^^85^109^return "X: " + xStr + ", Y: " + yStr;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Operator]^return "X: "  >  xStr + ", Y: " + yStr;^108^^^^^85^109^return "X: " + xStr + ", Y: " + yStr;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] generateToolTip [RETURN_TYPE] String   XYDataset data int series int item [VARIABLES] boolean  double  x  y  XYDataset  data  String  xStr  yStr  RegularTimePeriod  p  long  serialVersionUID  int  item  series  
[BugLab_Wrong_Operator]^if  ( nb < 0 )  {^134^^^^^133^140^if  ( nb <= 0 )  {^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Wrong_Literal]^if  ( nb <= nb )  {^134^^^^^133^140^if  ( nb <= 0 )  {^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Variable_Misuse]^return Math.floor ( tempval + 0.5d ) ;^135^^^^^133^140^return Math.floor ( value + 0.5d ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Wrong_Literal]^double p = Math.pow ( 9, nb ) ;^137^^^^^133^140^double p = Math.pow ( 10, nb ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Variable_Misuse]^double tempval = Math.floor ( p * p + 0.5d ) ;^138^^^^^133^140^double tempval = Math.floor ( value * p + 0.5d ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Variable_Misuse]^double tempval = Math.floor ( value * value + 0.5d ) ;^138^^^^^133^140^double tempval = Math.floor ( value * p + 0.5d ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Argument_Swapping]^double tempval = Math.floor ( p * value + 0.5d ) ;^138^^^^^133^140^double tempval = Math.floor ( value * p + 0.5d ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Wrong_Operator]^double tempval = Math.floor ( value + p + 0.5d ) ;^138^^^^^133^140^double tempval = Math.floor ( value * p + 0.5d ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Variable_Misuse]^double tempval = Math.floor ( tempval * p + 0.5d ) ;^138^^^^^133^140^double tempval = Math.floor ( value * p + 0.5d ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Variable_Misuse]^double tempval = Math.floor ( value * tempval + 0.5d ) ;^138^^^^^133^140^double tempval = Math.floor ( value * p + 0.5d ) ;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Variable_Misuse]^return value / p;^139^^^^^133^140^return tempval / p;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Variable_Misuse]^return tempval / value;^139^^^^^133^140^return tempval / p;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Argument_Swapping]^return p / tempval;^139^^^^^133^140^return tempval / p;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Wrong_Operator]^return tempval - p;^139^^^^^133^140^return tempval / p;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] round [RETURN_TYPE] double   double value int nb [VARIABLES] boolean  long  serialVersionUID  double  p  tempval  value  int  nb  
[BugLab_Wrong_Operator]^if  ( obj < this )  {^161^^^^^160^168^if  ( obj == this )  {^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] long  serialVersionUID  Object  obj  boolean  
[BugLab_Wrong_Literal]^return false;^162^^^^^160^168^return true;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] long  serialVersionUID  Object  obj  boolean  
[BugLab_Wrong_Operator]^if  ( obj  >=  SymbolicXYItemLabelGenerator )  {^164^^^^^160^168^if  ( obj instanceof SymbolicXYItemLabelGenerator )  {^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] long  serialVersionUID  Object  obj  boolean  
[BugLab_Wrong_Literal]^return false;^165^^^^^160^168^return true;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] long  serialVersionUID  Object  obj  boolean  
[BugLab_Wrong_Literal]^return true;^167^^^^^160^168^return false;^[CLASS] SymbolicXYItemLabelGenerator  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] long  serialVersionUID  Object  obj  boolean  
