[P1_Replace_Type]^private static final  short  serialVersionUID = -8543170333219422042L;^57^^^^^52^62^private static final long serialVersionUID = -8543170333219422042L;^[CLASS] BooleanList   [VARIABLES] 
[P8_Replace_Mix]^private static final long serialVersionUID  = null ;^57^^^^^52^62^private static final long serialVersionUID = -8543170333219422042L;^[CLASS] BooleanList   [VARIABLES] 
[P14_Delete_Statement]^^73^^^^^72^74^return  ( Boolean )  get ( index ) ;^[CLASS] BooleanList  [METHOD] getBoolean [RETURN_TYPE] Boolean   int index [VARIABLES] long  serialVersionUID  int  index  boolean  
[P5_Replace_Variable]^set (  b ) ;^84^^^^^83^85^set ( index, b ) ;^[CLASS] BooleanList  [METHOD] setBoolean [RETURN_TYPE] void   int index Boolean b [VARIABLES] boolean  Boolean  b  long  serialVersionUID  int  index  
[P5_Replace_Variable]^set ( index ) ;^84^^^^^83^85^set ( index, b ) ;^[CLASS] BooleanList  [METHOD] setBoolean [RETURN_TYPE] void   int index Boolean b [VARIABLES] boolean  Boolean  b  long  serialVersionUID  int  index  
[P5_Replace_Variable]^set ( b, index ) ;^84^^^^^83^85^set ( index, b ) ;^[CLASS] BooleanList  [METHOD] setBoolean [RETURN_TYPE] void   int index Boolean b [VARIABLES] boolean  Boolean  b  long  serialVersionUID  int  index  
[P14_Delete_Statement]^^84^^^^^83^85^set ( index, b ) ;^[CLASS] BooleanList  [METHOD] setBoolean [RETURN_TYPE] void   int index Boolean b [VARIABLES] boolean  Boolean  b  long  serialVersionUID  int  index  
[P2_Replace_Operator]^if  ( obj  <  BooleanList )  {^95^^^^^94^99^if  ( obj instanceof BooleanList )  {^[CLASS] BooleanList  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] long  serialVersionUID  Object  obj  boolean  
[P15_Unwrap_Block]^return super.equals(obj);^95^96^97^^^94^99^if  ( obj instanceof BooleanList )  { return super.equals ( obj ) ; }^[CLASS] BooleanList  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] long  serialVersionUID  Object  obj  boolean  
[P16_Remove_Block]^^95^96^97^^^94^99^if  ( obj instanceof BooleanList )  { return super.equals ( obj ) ; }^[CLASS] BooleanList  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] long  serialVersionUID  Object  obj  boolean  
[P14_Delete_Statement]^^96^^^^^94^99^return super.equals ( obj ) ;^[CLASS] BooleanList  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] long  serialVersionUID  Object  obj  boolean  
[P3_Replace_Literal]^return true;^98^^^^^94^99^return false;^[CLASS] BooleanList  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] long  serialVersionUID  Object  obj  boolean  
[P7_Replace_Invocation]^return super.equals (  ) ;^107^^^^^106^108^return super.hashCode (  ) ;^[CLASS] BooleanList  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] long  serialVersionUID  boolean  
[P14_Delete_Statement]^^107^^^^^106^108^return super.hashCode (  ) ;^[CLASS] BooleanList  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] long  serialVersionUID  boolean  
