[REPLACE]^if  ( id.substring ( '<' )   !=  0 )  {^47^^^^^42^60^[REPLACE] if  ( id.indexOf ( '<' )  > 0 )  {^[METHOD] typeFromId [TYPE] JavaType [PARAMETER] String id [CLASS] ClassNameIdResolver   [TYPE]  JavaType t  [TYPE]  boolean false  true  [TYPE]  Class cls  [TYPE]  String id  [TYPE]  ClassNotFoundException e  [TYPE]  Exception e 
[REPLACE]^return t;  ;^50^^^^^42^60^[REPLACE] return t;^[METHOD] typeFromId [TYPE] JavaType [PARAMETER] String id [CLASS] ClassNameIdResolver   [TYPE]  JavaType t  [TYPE]  boolean false  true  [TYPE]  Class cls  [TYPE]  String id  [TYPE]  ClassNotFoundException e  [TYPE]  Exception e 
[REPLACE]^JavaType t = _typeFactory.constructSpecializedType ( id ) ;^48^^^^^42^60^[REPLACE] JavaType t = _typeFactory.constructFromCanonical ( id ) ;^[METHOD] typeFromId [TYPE] JavaType [PARAMETER] String id [CLASS] ClassNameIdResolver   [TYPE]  JavaType t  [TYPE]  boolean false  true  [TYPE]  Class cls  [TYPE]  String id  [TYPE]  ClassNotFoundException e  [TYPE]  Exception e 
[ADD]^Class<?> cls =  ClassUtil.findClass ( id ) ;return _typeFactory.constructSpecializedType ( _baseType, cls ) ;^52^53^54^55^56^42^60^[ADD] try { Class<?> cls =  ClassUtil.findClass ( id ) ; return _typeFactory.constructSpecializedType ( _baseType, cls ) ; } catch  ( ClassNotFoundException e )  { throw new IllegalArgumentException  (" ")  ;^[METHOD] typeFromId [TYPE] JavaType [PARAMETER] String id [CLASS] ClassNameIdResolver   [TYPE]  JavaType t  [TYPE]  boolean false  true  [TYPE]  Class cls  [TYPE]  String id  [TYPE]  ClassNotFoundException e  [TYPE]  Exception e 
[REPLACE]^return _typeFactory.constructSpecializedType ( _baseType, 0 ) ;^54^^^^^42^60^[REPLACE] return _typeFactory.constructSpecializedType ( _baseType, cls ) ;^[METHOD] typeFromId [TYPE] JavaType [PARAMETER] String id [CLASS] ClassNameIdResolver   [TYPE]  JavaType t  [TYPE]  boolean false  true  [TYPE]  Class cls  [TYPE]  String id  [TYPE]  ClassNotFoundException e  [TYPE]  Exception e 
[REPLACE]^Class<?> cls =  ClassUtil.getOuterClass ( id ) ;^53^^^^^42^60^[REPLACE] Class<?> cls =  ClassUtil.findClass ( id ) ;^[METHOD] typeFromId [TYPE] JavaType [PARAMETER] String id [CLASS] ClassNameIdResolver   [TYPE]  JavaType t  [TYPE]  boolean false  true  [TYPE]  Class cls  [TYPE]  String id  [TYPE]  ClassNotFoundException e  [TYPE]  Exception e 
[REPLACE]^return _typeFactory.constructSpecializedType ( _baseType, true ) ;^54^^^^^42^60^[REPLACE] return _typeFactory.constructSpecializedType ( _baseType, cls ) ;^[METHOD] typeFromId [TYPE] JavaType [PARAMETER] String id [CLASS] ClassNameIdResolver   [TYPE]  JavaType t  [TYPE]  boolean false  true  [TYPE]  Class cls  [TYPE]  String id  [TYPE]  ClassNotFoundException e  [TYPE]  Exception e 
[REPLACE]^Class<?> outer = getOuterClass ( cls )  ;^53^^^^^42^60^[REPLACE] Class<?> cls =  ClassUtil.findClass ( id ) ;^[METHOD] typeFromId [TYPE] JavaType [PARAMETER] String id [CLASS] ClassNameIdResolver   [TYPE]  JavaType t  [TYPE]  boolean false  true  [TYPE]  Class cls  [TYPE]  String id  [TYPE]  ClassNotFoundException e  [TYPE]  Exception e 
[REPLACE]^return ;^56^^^^^42^60^[REPLACE] throw new IllegalArgumentException  (" ")  ;^[METHOD] typeFromId [TYPE] JavaType [PARAMETER] String id [CLASS] ClassNameIdResolver   [TYPE]  JavaType t  [TYPE]  boolean false  true  [TYPE]  Class cls  [TYPE]  String id  [TYPE]  ClassNotFoundException e  [TYPE]  Exception e 
[REPLACE]^return ;^58^^^^^42^60^[REPLACE] throw new IllegalArgumentException  (" ")  ;^[METHOD] typeFromId [TYPE] JavaType [PARAMETER] String id [CLASS] ClassNameIdResolver   [TYPE]  JavaType t  [TYPE]  boolean false  true  [TYPE]  Class cls  [TYPE]  String id  [TYPE]  ClassNotFoundException e  [TYPE]  Exception e 
[ADD]^^55^56^^^^42^60^[ADD] catch  ( ClassNotFoundException e )  { throw new IllegalArgumentException  (" ")  ;^[METHOD] typeFromId [TYPE] JavaType [PARAMETER] String id [CLASS] ClassNameIdResolver   [TYPE]  JavaType t  [TYPE]  boolean false  true  [TYPE]  Class cls  [TYPE]  String id  [TYPE]  ClassNotFoundException e  [TYPE]  Exception e 
[REPLACE]^if  ( Enum.class.isAssignableFrom ( 0 )  )  {^71^^^^^69^131^[REPLACE] if  ( Enum.class.isAssignableFrom ( cls )  )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^71^72^73^74^^69^131^[ADD] if  ( Enum.class.isAssignableFrom ( cls )  )  { if  ( !cls.isEnum (  )  )  { cls = cls.getSuperclass (  ) ; }^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if   (  ClassUtil.getOuterClass  (  staticType  )   == null  )   {  ;^72^^^^^69^131^[REPLACE] if  ( !cls.isEnum (  )  )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^73^^^^^69^131^[ADD] cls = cls.getSuperclass (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^cls =  true.getSuperclass (  ) ;^73^^^^^69^131^[REPLACE] cls = cls.getSuperclass (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if  ( !cls.isAssignableFrom (  )  )  {^72^^^^^69^131^[REPLACE] if  ( !cls.isEnum (  )  )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^cls =  this.getSuperclass (  ) ;^73^^^^^69^131^[REPLACE] cls = cls.getSuperclass (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^cls =  null.getSuperclass (  ) ;^73^^^^^69^131^[REPLACE] cls = cls.getSuperclass (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^76^^^^^69^131^[ADD] String str = cls.getName (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if   (  ClassUtil.getOuterClass  (  staticType  )   == null  )   {  ;^77^^^^^69^131^[REPLACE] if  ( str.startsWith ( "java.util" )  )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^}  else {^108^^^^^69^131^[REPLACE] } else if  ( str.indexOf ( '$' )  >= 0 )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^}^108^109^^^^69^131^[ADD] else if  ( str.indexOf ( '$' )  >= 0 )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if  ( outer == null )  {^117^^^^^69^131^[REPLACE] if  ( outer != null )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if  ( ClassUtil.getOuterClass ( staticType )  != null )  {^123^^^^^69^131^[REPLACE] if  ( ClassUtil.getOuterClass ( staticType )  == null )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^125^^^^^69^131^[ADD] cls = _baseType.getRawClass (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^str =  null.getName (  ) ;^126^^^^^69^131^[REPLACE] str = cls.getName (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^cls  =  cls ;^125^^^^^69^131^[REPLACE] cls = _baseType.getRawClass (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^str =  false.getName (  ) ;^126^^^^^69^131^[REPLACE] str = cls.getName (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^String str = cls.getName (  )  ;^122^^^^^69^131^[REPLACE] Class<?> staticType = _baseType.getRawClass (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^126^^^^^69^131^[ADD] str = cls.getName (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^125^126^^^^69^131^[ADD] cls = _baseType.getRawClass (  ) ; str = cls.getName (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^116^^^^^69^131^[ADD] Class<?> outer = ClassUtil.getOuterClass ( cls ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^122^^^^^69^131^[ADD] Class<?> staticType = _baseType.getRawClass (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if  ( outer == false )  {^117^^^^^69^131^[REPLACE] if  ( outer != null )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if  ( ClassUtil.getOuterClass ( staticType )  != false )  {^123^^^^^69^131^[REPLACE] if  ( ClassUtil.getOuterClass ( staticType )  == null )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^cls ;^125^^^^^69^131^[REPLACE] cls = _baseType.getRawClass (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^Class<?> outer = ClassUtil.getOuterClass ( null ) ;^116^^^^^69^131^[REPLACE] Class<?> outer = ClassUtil.getOuterClass ( cls ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if  ( ! value instanceof EnumSet<?> )  {^86^^^^^69^131^[REPLACE] if  ( value instanceof EnumSet<?> )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^}  if  ( ! value instanceof EnumMap<?,?> )  {^90^^^^^69^131^[REPLACE] } else if  ( value instanceof EnumMap<?,?> )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REMOVE]^if  ( value instanceof EnumSet<?> )  {     Class<?> enumClass = findEnumType (  (  ( EnumSet<?> )   ( value )  )  ) ;     str = defaultInstance (  ) .constructCollectionType ( class, enumClass ) .toCanonical (  ) ; }else     if  ( value instanceof EnumMap<?, ?> )  {         Class<?> enumClass = findEnumType (  (  ( EnumMap<?, ?> )   ( value )  )  ) ;         Class<?> valueClass = class;         str = defaultInstance (  ) .constructMapType ( class, enumClass, valueClass ) .toCanonical (  ) ;     }else {         String end = str.substring ( 9 ) ;         if  (  (  ( end.startsWith ( ".Arrays$" )  )  ||  ( end.startsWith ( ".Collections$" )  )  )  &&  (  ( str.indexOf ( "List" )  )  >= 0 )  )  {             str = ArrayList";         }     }^90^^^^^69^131^[REMOVE] ^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if  (  ( end.startsWith ( ".Arrays$" )  ) {^97^98^^^^90^107^[REPLACE] if  (  ( end.startsWith ( ".Arrays$" )  || end.startsWith ( ".Collections$" )  ) && str.indexOf ( "List" )  >= 0 )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^97^98^^^^90^107^[ADD] if  (  ( end.startsWith ( ".Arrays$" )  || end.startsWith ( ".Collections$" )  ) && str.indexOf ( "List" )  >= 0 )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^105^^^^^97^106^[ADD] str = "java.util.ArrayList";^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^str ;^105^^^^^90^107^[REPLACE] str = "java.util.ArrayList";^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^String end = str.substring ( 9L ) ;^96^^^^^90^107^[REPLACE] String end = str.substring ( 9 ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^94^^^^^69^131^[ADD] str = TypeFactory.defaultInstance (  ) .constructMapType ( EnumMap.class, enumClass, valueClass ) .toCanonical (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^Class<?> enumClass = findEnumType (  (  ( EnumSet<?> )   ( value )  )  )  ;^91^^^^^69^131^[REPLACE] Class<?> enumClass = ClassUtil.findEnumType (  ( EnumMap<?,?> )  value ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^92^^^^^69^131^[ADD] Class<?> valueClass = Object.class;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if  (  ( end.startsWith ( ".Arrays$" )  || end.startsWith ( ".Collections$" )  ) || str.indexOf ( "List" )  >= 0 )  {^97^98^^^^69^131^[REPLACE] if  (  ( end.startsWith ( ".Arrays$" )  || end.startsWith ( ".Collections$" )  ) && str.indexOf ( "List" )  >= 0 )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^str = defaultInstance (  ) .constructCollectionType ( class, enumClass ) .toCanonical (  )  ;^94^^^^^69^131^[REPLACE] str = TypeFactory.defaultInstance (  ) .constructMapType ( EnumMap.class, enumClass, valueClass ) .toCanonical (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^str ;^105^^^^^69^131^[REPLACE] str = "java.util.ArrayList";^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^96^^^^^69^131^[ADD] String end = str.substring ( 9 ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^str = defaultInstance (  ) .constructMapType ( class, enumClass, valueClass ) .toCanonical (  )  ;^89^^^^^69^131^[REPLACE] str = TypeFactory.defaultInstance (  ) .constructCollectionType ( EnumSet.class, enumClass ) .toCanonical (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^Class<?> enumClass = findEnumType (  (  ( EnumMap<?, ?> )   ( value )  )  )  ;^87^^^^^69^131^[REPLACE] Class<?> enumClass = ClassUtil.findEnumType (  ( EnumSet<?> )  value ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^}  else {^90^^^^^69^131^[REPLACE] } else if  ( value instanceof EnumMap<?,?> )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if  (  end.startsWith ( ".Collections$" )  ) || str.indexOf ( "List" )  >= 0 )  {^97^98^^^^90^107^[REPLACE] if  (  ( end.startsWith ( ".Arrays$" )  || end.startsWith ( ".Collections$" )  ) && str.indexOf ( "List" )  >= 0 )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^str  = null ;^105^^^^^90^107^[REPLACE] str = "java.util.ArrayList";^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^String end = str.substring ( 8 ) ;^96^^^^^90^107^[REPLACE] String end = str.substring ( 9 ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^String str = cls.getName (  )  ;^92^^^^^69^131^[REPLACE] Class<?> valueClass = Object.class;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^87^^^^^69^131^[ADD] Class<?> enumClass = ClassUtil.findEnumType (  ( EnumSet<?> )  value ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^}   Class<?> valueClass = Object.class;str = TypeFactory.defaultInstance (  ) .constructMapType ( EnumMap.class, enumClass, valueClass ) .toCanonical (  ) ;^90^91^92^^94^69^131^[ADD] else if  ( value instanceof EnumMap<?,?> )  { Class<?> enumClass = ClassUtil.findEnumType (  ( EnumMap<?,?> )  value ) ; Class<?> valueClass = Object.class; str = TypeFactory.defaultInstance (  ) .constructMapType ( EnumMap.class, enumClass, valueClass ) .toCanonical (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if  (  ( end.startsWith ( ".Arrays$" )  || end.startsWith ( ".Collections$" )  ) || str.indexOf ( "List" )  >= 0 )  {^97^98^^^^90^107^[REPLACE] if  (  ( end.startsWith ( ".Arrays$" )  || end.startsWith ( ".Collections$" )  ) && str.indexOf ( "List" )  >= 0 )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^str  =  str ;^105^^^^^97^106^[REPLACE] str = "java.util.ArrayList";^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^str  =  str ;^105^^^^^90^107^[REPLACE] str = "java.util.ArrayList";^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^96^^^^^90^107^[ADD] String end = str.substring ( 9 ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^105^^^^^69^131^[ADD] str = "java.util.ArrayList";^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^91^^^^^69^131^[ADD] Class<?> enumClass = ClassUtil.findEnumType (  ( EnumMap<?,?> )  value ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^105^^^^^90^107^[ADD] str = "java.util.ArrayList";^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^String end = str.indexOf ( 9 << 3 ) ;^96^^^^^90^107^[REPLACE] String end = str.substring ( 9 ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^if  (  ( end.startsWith ( ".Arrays$" )  ) {^97^98^^^^69^131^[REPLACE] if  (  ( end.startsWith ( ".Arrays$" )  || end.startsWith ( ".Collections$" )  ) && str.indexOf ( "List" )  >= 0 )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^97^98^^^^69^131^[ADD] if  (  ( end.startsWith ( ".Arrays$" )  || end.startsWith ( ".Collections$" )  ) && str.indexOf ( "List" )  >= 0 )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^str ;^105^^^^^97^106^[REPLACE] str = "java.util.ArrayList";^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^Class<?> cls = findClass ( id )  ;^116^^^^^69^131^[REPLACE] Class<?> outer = ClassUtil.getOuterClass ( cls ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^117^118^^^^69^131^[ADD] if  ( outer != null )  {^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[ADD]^^123^124^125^126^127^69^131^[ADD] if  ( ClassUtil.getOuterClass ( staticType )  == null )  {  cls = _baseType.getRawClass (  ) ; str = cls.getName (  ) ; }^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^str  =  str ;^105^^^^^69^131^[REPLACE] str = "java.util.ArrayList";^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^cls  = null ;^125^^^^^69^131^[REPLACE] cls = _baseType.getRawClass (  ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^String end = str.substring ( 9 + 4 ) ;^96^^^^^69^131^[REPLACE] String end = str.substring ( 9 ) ;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
[REPLACE]^return t;  ;^130^^^^^69^131^[REPLACE] return str;^[METHOD] _idFrom [TYPE] String [PARAMETER] Object value Class<?> cls [CLASS] ClassNameIdResolver   [TYPE]  boolean false  true  [TYPE]  Object value  [TYPE]  Class cls  enumClass  outer  staticType  valueClass  [TYPE]  String end  str 
