[P1_Replace_Type]^public static final  short  JANUARY = 1;^33^^^^^28^38^public static final int JANUARY = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int JANUARY ;^33^^^^^28^38^public static final int JANUARY = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  long  FEBRUARY = 2;^36^^^^^31^41^public static final int FEBRUARY = 2;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int FEBRUARY = -1;^36^^^^^31^41^public static final int FEBRUARY = 2;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int FEBRUARY ;^36^^^^^31^41^public static final int FEBRUARY = 2;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  long  MARCH = 3;^39^^^^^34^44^public static final int MARCH = 3;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int MARCH = -1;^39^^^^^34^44^public static final int MARCH = 3;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int MARCH = 3 >>> 1;^39^^^^^34^44^public static final int MARCH = 3;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  long  APRIL = 4;^42^^^^^37^47^public static final int APRIL = 4;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int APRIL = 2;^42^^^^^37^47^public static final int APRIL = 4;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int APRIL = 1;^42^^^^^37^47^public static final int APRIL = 4;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  MAY = 5;^45^^^^^40^50^public static final int MAY = 5;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int MAY = -1;^45^^^^^40^50^public static final int MAY = 5;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int MAY = 0;^45^^^^^40^50^public static final int MAY = 5;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  JUNE = 6;^48^^^^^43^53^public static final int JUNE = 6;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int JUNE = 2;^48^^^^^43^53^public static final int JUNE = 6;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  JULY = 7;^51^^^^^46^56^public static final int JULY = 7;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int JULY = 13;^51^^^^^46^56^public static final int JULY = 7;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int JULY ;^51^^^^^46^56^public static final int JULY = 7;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  AUGUST = 8;^54^^^^^49^59^public static final int AUGUST = 8;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int AUGUST = 17;^54^^^^^49^59^public static final int AUGUST = 8;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int AUGUST ;^54^^^^^49^59^public static final int AUGUST = 8;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  SEPTEMBER = 9;^57^^^^^52^62^public static final int SEPTEMBER = 9;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int SEPTEMBER = 13;^57^^^^^52^62^public static final int SEPTEMBER = 9;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^private static final int SEPTEMBER = 2;^57^^^^^52^62^public static final int SEPTEMBER = 9;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  OCTOBER = 10;^60^^^^^55^65^public static final int OCTOBER = 10;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int OCTOBER = 11;^60^^^^^55^65^public static final int OCTOBER = 10;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int OCTOBER = 7;^60^^^^^55^65^public static final int OCTOBER = 10;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  long  NOVEMBER = 11;^63^^^^^58^68^public static final int NOVEMBER = 11;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int NOVEMBER = 13;^63^^^^^58^68^public static final int NOVEMBER = 11;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int NOVEMBER = 0;^63^^^^^58^68^public static final int NOVEMBER = 11;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  long  DECEMBER = 12;^66^^^^^61^71^public static final int DECEMBER = 12;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int DECEMBER = 17;^66^^^^^61^71^public static final int DECEMBER = 12;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int DECEMBER ;^66^^^^^61^71^public static final int DECEMBER = 12;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  MONDAY = 1;^70^^^^^65^75^public static final int MONDAY = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int MONDAY = 10;^70^^^^^65^75^public static final int MONDAY = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int MONDAY = 1 / 0;^70^^^^^65^75^public static final int MONDAY = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  TUESDAY = 2;^73^^^^^68^78^public static final int TUESDAY = 2;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int TUESDAY = 2 / 4;^73^^^^^68^78^public static final int TUESDAY = 2;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  WEDNESDAY = 3;^76^^^^^71^81^public static final int WEDNESDAY = 3;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int WEDNESDAY = 9;^76^^^^^71^81^public static final int WEDNESDAY = 3;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int WEDNESDAY ;^76^^^^^71^81^public static final int WEDNESDAY = 3;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  THURSDAY = 4;^79^^^^^74^84^public static final int THURSDAY = 4;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int THURSDAY = -3;^79^^^^^74^84^public static final int THURSDAY = 4;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int THURSDAY ;^79^^^^^74^84^public static final int THURSDAY = 4;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  FRIDAY = 5;^82^^^^^77^87^public static final int FRIDAY = 5;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int FRIDAY = -2;^82^^^^^77^87^public static final int FRIDAY = 5;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int FRIDAY  = null ;^82^^^^^77^87^public static final int FRIDAY = 5;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  SATURDAY = 6;^85^^^^^80^90^public static final int SATURDAY = 6;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int SATURDAY = -1;^85^^^^^80^90^public static final int SATURDAY = 6;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static  int SATURDAY = 8;^85^^^^^80^90^public static final int SATURDAY = 6;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  SUNDAY = 7;^88^^^^^83^93^public static final int SUNDAY = 7;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int SUNDAY = 4;^88^^^^^83^93^public static final int SUNDAY = 7;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static  int SUNDAY = 1;^88^^^^^83^93^public static final int SUNDAY = 7;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  AM = 0;^92^^^^^87^97^public static final int AM = 0;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int AM = -7;^92^^^^^87^97^public static final int AM = 0;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int AM ;^92^^^^^87^97^public static final int AM = 0;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  PM = 1;^95^^^^^90^100^public static final int PM = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int PM = 3;^95^^^^^90^100^public static final int PM = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int PM  = null ;^95^^^^^90^100^public static final int PM = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  BC = 0;^99^^^^^94^104^public static final int BC = 0;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int BC = 5;^99^^^^^94^104^public static final int BC = 0;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int BC = 3;^99^^^^^94^104^public static final int BC = 0;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  BCE = 0;^101^^^^^96^106^public static final int BCE = 0;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int BCE = 3;^101^^^^^96^106^public static final int BCE = 0;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int BCE ;^101^^^^^96^106^public static final int BCE = 0;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  AD = 1;^111^^^^^106^116^public static final int AD = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int AD = 10;^111^^^^^106^116^public static final int AD = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int AD = 3;^111^^^^^106^116^public static final int AD = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  CE = 1;^120^^^^^115^125^public static final int CE = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int CE = 0;^120^^^^^115^125^public static final int CE = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int CE = 2;^120^^^^^115^125^public static final int CE = 1;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  MILLIS_PER_SECOND = 1000;^124^^^^^119^129^public static final int MILLIS_PER_SECOND = 1000;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int MILLIS_PER_SECOND = 1001;^124^^^^^119^129^public static final int MILLIS_PER_SECOND = 1000;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int MILLIS_PER_SECOND = 1000 - 2;^124^^^^^119^129^public static final int MILLIS_PER_SECOND = 1000;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  SECONDS_PER_MINUTE = 60;^127^^^^^122^132^public static final int SECONDS_PER_MINUTE = 60;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int SECONDS_PER_MINUTE = 69;^127^^^^^122^132^public static final int SECONDS_PER_MINUTE = 60;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int SECONDS_PER_MINUTE = 60 << 4;^127^^^^^122^132^public static final int SECONDS_PER_MINUTE = 60;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  MILLIS_PER_MINUTE = MILLIS_PER_SECOND * SECONDS_PER_MINUTE;^129^^^^^124^134^public static final int MILLIS_PER_MINUTE = MILLIS_PER_SECOND * SECONDS_PER_MINUTE;^[CLASS] DateTimeConstants   [VARIABLES] 
[P2_Replace_Operator]^public / static final int MILLIS_PER_MINUTE = MILLIS_PER_SECOND * SECONDS_PER_MINUTE;^129^^^^^124^134^public static final int MILLIS_PER_MINUTE = MILLIS_PER_SECOND * SECONDS_PER_MINUTE;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int MILLIS_PER_MINUTE = SECONDS_PER_MINUTE * MILLIS_PER_SECOND;^129^^^^^124^134^public static final int MILLIS_PER_MINUTE = MILLIS_PER_SECOND * SECONDS_PER_MINUTE;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  MINUTES_PER_HOUR = 60;^132^^^^^127^137^public static final int MINUTES_PER_HOUR = 60;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int MINUTES_PER_HOUR = 4;^132^^^^^127^137^public static final int MINUTES_PER_HOUR = 60;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  long  SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;^134^^^^^129^139^public static final int SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;^[CLASS] DateTimeConstants   [VARIABLES] 
[P2_Replace_Operator]^public + static final int SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;^134^^^^^129^139^public static final int SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int SECONDS_PER_HOUR = 2 * MINUTES_PER_HOUR;^134^^^^^129^139^public static final int SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int SECONDS_PER_HOUR = MINUTES_PER_HOUR * SECONDS_PER_MINUTE;^134^^^^^129^139^public static final int SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public  final  short  SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;^134^^^^^129^139^public static final int SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  long  MILLIS_PER_HOUR = MILLIS_PER_MINUTE * MINUTES_PER_HOUR;^136^^^^^131^141^public static final int MILLIS_PER_HOUR = MILLIS_PER_MINUTE * MINUTES_PER_HOUR;^[CLASS] DateTimeConstants   [VARIABLES] 
[P2_Replace_Operator]^public / static final int MILLIS_PER_HOUR = MILLIS_PER_MINUTE * MINUTES_PER_HOUR;^136^^^^^131^141^public static final int MILLIS_PER_HOUR = MILLIS_PER_MINUTE * MINUTES_PER_HOUR;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int MILLIS_PER_HOUR = MINUTES_PER_HOUR * MILLIS_PER_MINUTE;^136^^^^^131^141^public static final int MILLIS_PER_HOUR = MILLIS_PER_MINUTE * MINUTES_PER_HOUR;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final  short  MILLIS_PER_HOUR = MILLIS_PER_MINUTE * MINUTES_PER_HOUR;^136^^^^^131^141^public static final int MILLIS_PER_HOUR = MILLIS_PER_MINUTE * MINUTES_PER_HOUR;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  HOURS_PER_DAY = 24;^140^^^^^135^145^public static final int HOURS_PER_DAY = 24;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int HOURS_PER_DAY = 26;^140^^^^^135^145^public static final int HOURS_PER_DAY = 24;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int HOURS_PER_DAY = 0;^140^^^^^135^145^public static final int HOURS_PER_DAY = 24;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY;^143^^^^^138^148^public static final int MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY;^[CLASS] DateTimeConstants   [VARIABLES] 
[P2_Replace_Operator]^public - static final int MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY;^143^^^^^138^148^public static final int MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int MINUTES_PER_DAY = HOURS_PER_DAY * MINUTES_PER_HOUR;^143^^^^^138^148^public static final int MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static   long  MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY;^143^^^^^138^148^public static final int MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  long  SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;^146^^^^^141^151^public static final int SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;^[CLASS] DateTimeConstants   [VARIABLES] 
[P2_Replace_Operator]^public + static final int SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;^146^^^^^141^151^public static final int SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int SECONDS_PER_DAY = HOURS_PER_DAY * SECONDS_PER_HOUR;^146^^^^^141^151^public static final int SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final  short  SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;^146^^^^^141^151^public static final int SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  MILLIS_PER_DAY = MILLIS_PER_HOUR * HOURS_PER_DAY;^149^^^^^144^154^public static final int MILLIS_PER_DAY = MILLIS_PER_HOUR * HOURS_PER_DAY;^[CLASS] DateTimeConstants   [VARIABLES] 
[P2_Replace_Operator]^public / static final int MILLIS_PER_DAY = MILLIS_PER_HOUR * HOURS_PER_DAY;^149^^^^^144^154^public static final int MILLIS_PER_DAY = MILLIS_PER_HOUR * HOURS_PER_DAY;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int MILLIS_PER_DAY = HOURS_PER_DAY * MILLIS_PER_HOUR;^149^^^^^144^154^public static final int MILLIS_PER_DAY = MILLIS_PER_HOUR * HOURS_PER_DAY;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  long  DAYS_PER_WEEK = 7;^152^^^^^147^157^public static final int DAYS_PER_WEEK = 7;^[CLASS] DateTimeConstants   [VARIABLES] 
[P3_Replace_Literal]^public static final int DAYS_PER_WEEK = 13;^152^^^^^147^157^public static final int DAYS_PER_WEEK = 7;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int DAYS_PER_WEEK = 5;^152^^^^^147^157^public static final int DAYS_PER_WEEK = 7;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  HOURS_PER_WEEK = HOURS_PER_DAY * DAYS_PER_WEEK;^155^^^^^150^160^public static final int HOURS_PER_WEEK = HOURS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P2_Replace_Operator]^public / static final int HOURS_PER_WEEK = HOURS_PER_DAY * DAYS_PER_WEEK;^155^^^^^150^160^public static final int HOURS_PER_WEEK = HOURS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int HOURS_PER_WEEK = DAYS_PER_WEEK * HOURS_PER_DAY;^155^^^^^150^160^public static final int HOURS_PER_WEEK = HOURS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  long  MINUTES_PER_WEEK = MINUTES_PER_DAY * DAYS_PER_WEEK;^158^^^^^153^163^public static final int MINUTES_PER_WEEK = MINUTES_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P2_Replace_Operator]^public / static final int MINUTES_PER_WEEK = MINUTES_PER_DAY * DAYS_PER_WEEK;^158^^^^^153^163^public static final int MINUTES_PER_WEEK = MINUTES_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int MINUTES_PER_WEEK = DAYS_PER_WEEK * MINUTES_PER_DAY;^158^^^^^153^163^public static final int MINUTES_PER_WEEK = MINUTES_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static   short  MINUTES_PER_WEEK = MINUTES_PER_DAY * DAYS_PER_WEEK;^158^^^^^153^163^public static final int MINUTES_PER_WEEK = MINUTES_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  SECONDS_PER_WEEK = SECONDS_PER_DAY * DAYS_PER_WEEK;^161^^^^^156^166^public static final int SECONDS_PER_WEEK = SECONDS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P2_Replace_Operator]^public / static final int SECONDS_PER_WEEK = SECONDS_PER_DAY * DAYS_PER_WEEK;^161^^^^^156^166^public static final int SECONDS_PER_WEEK = SECONDS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int SECONDS_PER_WEEK = SECONDS_PER_DAY * null;^161^^^^^156^166^public static final int SECONDS_PER_WEEK = SECONDS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int SECONDS_PER_WEEK = DAYS_PER_WEEK * SECONDS_PER_DAY;^161^^^^^156^166^public static final int SECONDS_PER_WEEK = SECONDS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final int SECONDS_PER_WEEK ;^161^^^^^156^166^public static final int SECONDS_PER_WEEK = SECONDS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P1_Replace_Type]^public static final  short  MILLIS_PER_WEEK = MILLIS_PER_DAY * DAYS_PER_WEEK;^164^^^^^159^169^public static final int MILLIS_PER_WEEK = MILLIS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P2_Replace_Operator]^public + static final int MILLIS_PER_WEEK = MILLIS_PER_DAY * DAYS_PER_WEEK;^164^^^^^159^169^public static final int MILLIS_PER_WEEK = MILLIS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P5_Replace_Variable]^public static final int MILLIS_PER_WEEK = DAYS_PER_WEEK * MILLIS_PER_DAY;^164^^^^^159^169^public static final int MILLIS_PER_WEEK = MILLIS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
[P8_Replace_Mix]^public static final  long  MILLIS_PER_WEEK = MILLIS_PER_DAY * DAYS_PER_WEEK;^164^^^^^159^169^public static final int MILLIS_PER_WEEK = MILLIS_PER_DAY * DAYS_PER_WEEK;^[CLASS] DateTimeConstants   [VARIABLES] 
