[P1_Replace_Type]^private static final  short  serialVersionUID = -1774146392916359839L;^54^^^^^49^59^private static final long serialVersionUID = -1774146392916359839L;^[CLASS] AreaRendererEndType   [VARIABLES] 
[P8_Replace_Mix]^private static final long serialVersionUID  = null ;^54^^^^^49^59^private static final long serialVersionUID = -1774146392916359839L;^[CLASS] AreaRendererEndType   [VARIABLES] 
[P3_Replace_Literal]^public static final AreaRendererEndType TAPER = new AreaRendererEndType ( "AreaRendererEndType.T" ) ;^59^60^61^^^59^61^public static final AreaRendererEndType TAPER = new AreaRendererEndType ( "AreaRendererEndType.TAPER" ) ;^[CLASS] AreaRendererEndType   [VARIABLES] 
[P3_Replace_Literal]^public static final AreaRendererEndType TRUNCATE = new AreaRendererEndType ( "reaRendererEndType.TRU" ) ;^66^67^68^^^66^68^public static final AreaRendererEndType TRUNCATE = new AreaRendererEndType ( "AreaRendererEndType.TRUNCATE" ) ;^[CLASS] AreaRendererEndType   [VARIABLES] 
[P3_Replace_Literal]^public static final AreaRendererEndType LEVEL = new AreaRendererEndType ( "eaRenreaRendererEndType.LEVEL" ) ;^73^74^75^^^73^75^public static final AreaRendererEndType LEVEL = new AreaRendererEndType ( "AreaRendererEndType.LEVEL" ) ;^[CLASS] AreaRendererEndType   [VARIABLES] 
[P1_Replace_Type]^private char name;^78^^^^^73^83^private String name;^[CLASS] AreaRendererEndType   [VARIABLES] 
[P8_Replace_Mix]^this.name =  null;^86^^^^^85^87^this.name = name;^[CLASS] AreaRendererEndType  [METHOD] <init> [RETURN_TYPE] String)   String name [VARIABLES] AreaRendererEndType  LEVEL  TAPER  TRUNCATE  String  name  boolean  long  serialVersionUID  
[P5_Replace_Variable]^return name;^95^^^^^94^96^return this.name;^[CLASS] AreaRendererEndType  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] AreaRendererEndType  LEVEL  TAPER  TRUNCATE  String  name  boolean  long  serialVersionUID  
[P2_Replace_Operator]^if  ( this >= o )  {^108^^^^^106^122^if  ( this == o )  {^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P15_Unwrap_Block]^return true;^108^109^110^^^106^122^if  ( this == o )  { return true; }^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P16_Remove_Block]^^108^109^110^^^106^122^if  ( this == o )  { return true; }^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P3_Replace_Literal]^return false;^109^^^^^106^122^return true;^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P2_Replace_Operator]^if  ( ! ( o  <=  AreaRendererEndType )  )  {^111^^^^^106^122^if  ( ! ( o instanceof AreaRendererEndType )  )  {^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P15_Unwrap_Block]^return false;^111^112^113^^^106^122^if  ( ! ( o instanceof AreaRendererEndType )  )  { return false; }^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P16_Remove_Block]^^111^112^113^^^106^122^if  ( ! ( o instanceof AreaRendererEndType )  )  { return false; }^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P3_Replace_Literal]^return true;^112^^^^^106^122^return false;^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P5_Replace_Variable]^if  ( !this.name.equals ( TRUNCATE.toString (  )  )  )  {^116^^^^^106^122^if  ( !this.name.equals ( t.toString (  )  )  )  {^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^if  ( !this.name.equals ( t.equals (  )  )  )  {^116^^^^^106^122^if  ( !this.name.equals ( t.toString (  )  )  )  {^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P15_Unwrap_Block]^return false;^116^117^118^^^106^122^if  ( !this.name.equals ( t.toString (  )  )  )  { return false; }^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P16_Remove_Block]^^116^117^118^^^106^122^if  ( !this.name.equals ( t.toString (  )  )  )  { return false; }^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P3_Replace_Literal]^return true;^117^^^^^106^122^return false;^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( equals ( t.toString (  )  )  )  )  {     return false; }^116^^^^^106^122^[Delete]^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^if  ( !this.name.equals ( t .AreaRendererEndType ( name )   )  )  {^116^^^^^106^122^if  ( !this.name.equals ( t.toString (  )  )  )  {^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^if  ( !this.name.equals ( TRUNCATE.equals (  )  )  )  {^116^^^^^106^122^if  ( !this.name.equals ( t.toString (  )  )  )  {^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P3_Replace_Literal]^return false;^120^^^^^106^122^return true;^[CLASS] AreaRendererEndType  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] Object  o  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P5_Replace_Variable]^if  ( this.equals ( AreaRendererEndType.t )  )  {^133^^^^^131^143^if  ( this.equals ( AreaRendererEndType.LEVEL )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^if  ( this.toString ( AreaRendererEndType.LEVEL )  )  {^133^^^^^131^143^if  ( this.equals ( AreaRendererEndType.LEVEL )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^if  ( this .AreaRendererEndType ( name )   )  {^133^^^^^131^143^if  ( this.equals ( AreaRendererEndType.LEVEL )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P15_Unwrap_Block]^result = org.jfree.chart.renderer.AreaRendererEndType.LEVEL;^133^134^135^^^131^143^if  ( this.equals ( AreaRendererEndType.LEVEL )  )  { result = AreaRendererEndType.LEVEL; }^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P16_Remove_Block]^^133^134^135^^^131^143^if  ( this.equals ( AreaRendererEndType.LEVEL )  )  { result = AreaRendererEndType.LEVEL; }^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( this.equals ( TAPER )  )  {     result = TAPER; }else     if  ( this.equals ( TRUNCATE )  )  {         result = TRUNCATE;     }^133^^^^^131^143^[Delete]^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P5_Replace_Variable]^else if  ( this.equals ( AreaRendererEndType.t )  )  {^136^^^^^131^143^else if  ( this.equals ( AreaRendererEndType.TAPER )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^else if  ( this.toString ( AreaRendererEndType.TAPER )  )  {^136^^^^^131^143^else if  ( this.equals ( AreaRendererEndType.TAPER )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^else if  ( this .AreaRendererEndType ( name )   )  {^136^^^^^131^143^else if  ( this.equals ( AreaRendererEndType.TAPER )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^else {^136^^^^^131^143^else if  ( this.equals ( AreaRendererEndType.TAPER )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P15_Unwrap_Block]^result = org.jfree.chart.renderer.AreaRendererEndType.TAPER;^136^137^138^^^131^143^else if  ( this.equals ( AreaRendererEndType.TAPER )  )  { result = AreaRendererEndType.TAPER; }^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P16_Remove_Block]^^136^137^138^^^131^143^else if  ( this.equals ( AreaRendererEndType.TAPER )  )  { result = AreaRendererEndType.TAPER; }^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( this.equals ( LEVEL )  )  {     result = LEVEL; }else     if  ( this.equals ( TAPER )  )  {         result = TAPER;     }else         if  ( this.equals ( TRUNCATE )  )  {             result = TRUNCATE;         }^136^^^^^131^143^[Delete]^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P5_Replace_Variable]^else if  ( this.equals ( AreaRendererEndType.t )  )  {^139^^^^^131^143^else if  ( this.equals ( AreaRendererEndType.TRUNCATE )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^else if  ( this.toString ( AreaRendererEndType.TRUNCATE )  )  {^139^^^^^131^143^else if  ( this.equals ( AreaRendererEndType.TRUNCATE )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P15_Unwrap_Block]^result = org.jfree.chart.renderer.AreaRendererEndType.TRUNCATE;^139^140^141^^^131^143^else if  ( this.equals ( AreaRendererEndType.TRUNCATE )  )  { result = AreaRendererEndType.TRUNCATE; }^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P16_Remove_Block]^^139^140^141^^^131^143^else if  ( this.equals ( AreaRendererEndType.TRUNCATE )  )  { result = AreaRendererEndType.TRUNCATE; }^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^result ;^140^^^^^131^143^result = AreaRendererEndType.TRUNCATE;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P11_Insert_Donor_Statement]^result = AreaRendererEndType.TAPER;result = AreaRendererEndType.TRUNCATE;^140^^^^^131^143^result = AreaRendererEndType.TRUNCATE;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P11_Insert_Donor_Statement]^result = AreaRendererEndType.LEVEL;result = AreaRendererEndType.TRUNCATE;^140^^^^^131^143^result = AreaRendererEndType.TRUNCATE;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( o instanceof AreaRendererEndType )  )  {     return false; }^140^^^^^131^143^[Delete]^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^result  =  result ;^140^^^^^131^143^result = AreaRendererEndType.TRUNCATE;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^else if  ( this .AreaRendererEndType ( name )   )  {^139^^^^^131^143^else if  ( this.equals ( AreaRendererEndType.TRUNCATE )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( o instanceof AreaRendererEndType )  )  {     return false; }^139^^^^^131^143^[Delete]^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^result  = null ;^137^^^^^131^143^result = AreaRendererEndType.TAPER;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P11_Insert_Donor_Statement]^result = AreaRendererEndType.TRUNCATE;result = AreaRendererEndType.TAPER;^137^^^^^131^143^result = AreaRendererEndType.TAPER;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P11_Insert_Donor_Statement]^result = AreaRendererEndType.LEVEL;result = AreaRendererEndType.TAPER;^137^^^^^131^143^result = AreaRendererEndType.TAPER;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( o instanceof AreaRendererEndType )  )  {     return false; }^137^^^^^131^143^[Delete]^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^if  ( this.toString ( AreaRendererEndType.TRUNCATE )  )  {^139^^^^^131^143^else if  ( this.equals ( AreaRendererEndType.TRUNCATE )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( o instanceof AreaRendererEndType )  )  {     return false; }^136^^^^^131^143^[Delete]^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^result  =  result ;^134^^^^^131^143^result = AreaRendererEndType.LEVEL;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P11_Insert_Donor_Statement]^result = AreaRendererEndType.TRUNCATE;result = AreaRendererEndType.LEVEL;^134^^^^^131^143^result = AreaRendererEndType.LEVEL;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P11_Insert_Donor_Statement]^result = AreaRendererEndType.TAPER;result = AreaRendererEndType.LEVEL;^134^^^^^131^143^result = AreaRendererEndType.LEVEL;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P12_Insert_Condition]^if  ( this.equals ( AreaRendererEndType.LEVEL )  )  { result = AreaRendererEndType.LEVEL; }^134^^^^^131^143^result = AreaRendererEndType.LEVEL;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( o instanceof AreaRendererEndType )  )  {     return false; }^134^^^^^131^143^[Delete]^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^if  ( this.toString ( AreaRendererEndType.TAPER )  )  {^136^^^^^131^143^else if  ( this.equals ( AreaRendererEndType.TAPER )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^if  ( this.equals ( AreaRendererEndType.t )  )  {^139^^^^^131^143^else if  ( this.equals ( AreaRendererEndType.TRUNCATE )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^result  = null ;^140^^^^^131^143^result = AreaRendererEndType.TRUNCATE;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^result ;^137^^^^^131^143^result = AreaRendererEndType.TAPER;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^result  = null ;^134^^^^^131^143^result = AreaRendererEndType.LEVEL;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^result  =  result ;^137^^^^^131^143^result = AreaRendererEndType.TAPER;^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^if  ( this.toString ( AreaRendererEndType.t )  )  {^133^^^^^131^143^if  ( this.equals ( AreaRendererEndType.LEVEL )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P13_Insert_Block]^if  ( ! ( o instanceof AreaRendererEndType )  )  {     return false; }^133^^^^^131^143^[Delete]^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
[P8_Replace_Mix]^else if  ( this.toString ( AreaRendererEndType.t )  )  {^136^^^^^131^143^else if  ( this.equals ( AreaRendererEndType.TAPER )  )  {^[CLASS] AreaRendererEndType  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] Object  result  AreaRendererEndType  LEVEL  TAPER  TRUNCATE  t  String  name  boolean  long  serialVersionUID  
