[P1_Replace_Type]^private int lowerBound;^62^^^^^57^67^private double lowerBound;^[CLASS] GrayPaintScale   [VARIABLES] 
[P8_Replace_Mix]^private float lowerBound;^62^^^^^57^67^private double lowerBound;^[CLASS] GrayPaintScale   [VARIABLES] 
[P1_Replace_Type]^private int upperBound;^65^^^^^60^70^private double upperBound;^[CLASS] GrayPaintScale   [VARIABLES] 
[P14_Delete_Statement]^^71^^^^^70^72^this ( 0.0, 1.0 ) ;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale()   [VARIABLES] double  lowerBound  upperBound  boolean  
[P2_Replace_Operator]^if  ( lowerBound > upperBound )  {^81^^^^^80^87^if  ( lowerBound >= upperBound )  {^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P5_Replace_Variable]^if  ( upperBound >= lowerBound )  {^81^^^^^80^87^if  ( lowerBound >= upperBound )  {^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P9_Replace_Statement]^if  ( this.lowerBound != that.lowerBound )  {^81^^^^^80^87^if  ( lowerBound >= upperBound )  {^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P9_Replace_Statement]^if  ( this.upperBound != that.upperBound )  {^81^^^^^80^87^if  ( lowerBound >= upperBound )  {^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P15_Unwrap_Block]^throw new java.lang.IllegalArgumentException("Requires lowerBound < upperBound.");^81^82^83^84^^80^87^if  ( lowerBound >= upperBound )  { throw new IllegalArgumentException ( "Requires lowerBound < upperBound." ) ; }^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P16_Remove_Block]^^81^82^83^84^^80^87^if  ( lowerBound >= upperBound )  { throw new IllegalArgumentException ( "Requires lowerBound < upperBound." ) ; }^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P3_Replace_Literal]^throw new IllegalArgumentException ( "Requires lowerBound < upperBound.we" ) ;^82^83^^^^80^87^throw new IllegalArgumentException ( "Requires lowerBound < upperBound." ) ;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P13_Insert_Block]^if  ( lowerBound >= upperBound )  {     throw new IllegalArgumentException ( "Requires lowerBound < upperBound." ) ; }^82^^^^^80^87^[Delete]^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P3_Replace_Literal]^throw new IllegalArgumentException ( "s equires lowerBound < upperBound." ) ;^82^83^^^^80^87^throw new IllegalArgumentException ( "Requires lowerBound < upperBound." ) ;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P3_Replace_Literal]^throw new IllegalArgumentException ( "erBound " ) ;^82^83^^^^80^87^throw new IllegalArgumentException ( "Requires lowerBound < upperBound." ) ;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P3_Replace_Literal]^throw new IllegalArgumentException ( "Requires lowerBound < upperBound.owe" ) ;^82^83^^^^80^87^throw new IllegalArgumentException ( "Requires lowerBound < upperBound." ) ;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P8_Replace_Mix]^return ;^82^83^^^^80^87^throw new IllegalArgumentException ( "Requires lowerBound < upperBound." ) ;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P5_Replace_Variable]^this.lowerBound = upperBound;^85^^^^^80^87^this.lowerBound = lowerBound;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P11_Insert_Donor_Statement]^this.upperBound = upperBound;this.lowerBound = lowerBound;^85^^^^^80^87^this.lowerBound = lowerBound;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P12_Insert_Condition]^if  ( this.lowerBound != that.lowerBound )  { this.lowerBound = lowerBound; }^85^^^^^80^87^this.lowerBound = lowerBound;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P12_Insert_Condition]^if  ( lowerBound >= upperBound )  { this.lowerBound = lowerBound; }^85^^^^^80^87^this.lowerBound = lowerBound;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P5_Replace_Variable]^this.upperBound = lowerBound;^86^^^^^80^87^this.upperBound = upperBound;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P11_Insert_Donor_Statement]^this.lowerBound = lowerBound;this.upperBound = upperBound;^86^^^^^80^87^this.upperBound = upperBound;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P12_Insert_Condition]^if  ( lowerBound >= upperBound )  { this.upperBound = upperBound; }^86^^^^^80^87^this.upperBound = upperBound;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P12_Insert_Condition]^if  ( this.upperBound != that.upperBound )  { this.upperBound = upperBound; }^86^^^^^80^87^this.upperBound = upperBound;^[CLASS] GrayPaintScale  [METHOD] <init> [RETURN_TYPE] GrayPaintScale(double,double)   double lowerBound double upperBound [VARIABLES] double  lowerBound  upperBound  boolean  
[P5_Replace_Variable]^return upperBound;^95^^^^^94^96^return this.lowerBound;^[CLASS] GrayPaintScale  [METHOD] getLowerBound [RETURN_TYPE] double   [VARIABLES] double  lowerBound  upperBound  boolean  
[P5_Replace_Variable]^return upperBound;^104^^^^^103^105^return this.upperBound;^[CLASS] GrayPaintScale  [METHOD] getUpperBound [RETURN_TYPE] double   [VARIABLES] double  lowerBound  upperBound  boolean  
[P1_Replace_Type]^float v = Math.max ( value, this.lowerBound ) ;^115^^^^^114^120^double v = Math.max ( value, this.lowerBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^double v = Math.max ( upperBound, this.lowerBound ) ;^115^^^^^114^120^double v = Math.max ( value, this.lowerBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^double v = Math.max ( value, value ) ;^115^^^^^114^120^double v = Math.max ( value, this.lowerBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^double v = Math.max (  this.lowerBound ) ;^115^^^^^114^120^double v = Math.max ( value, this.lowerBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^double v = Math.max ( value ) ;^115^^^^^114^120^double v = Math.max ( value, this.lowerBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^double v = Math.max ( this.lowerBound, value ) ;^115^^^^^114^120^double v = Math.max ( value, this.lowerBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^double v = Math.max ( v, this.lowerBound ) ;^115^^^^^114^120^double v = Math.max ( value, this.lowerBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^double v = Math.max ( value, v ) ;^115^^^^^114^120^double v = Math.max ( value, this.lowerBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P14_Delete_Statement]^^115^116^^^^114^120^double v = Math.max ( value, this.lowerBound ) ; v = Math.min ( v, this.upperBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P11_Insert_Donor_Statement]^v = Math.min ( v, this.upperBound ) ;double v = Math.max ( value, this.lowerBound ) ;^115^^^^^114^120^double v = Math.max ( value, this.lowerBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^v = Math.min ( value, this.upperBound ) ;^116^^^^^114^120^v = Math.min ( v, this.upperBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^v = Math.min ( v, value ) ;^116^^^^^114^120^v = Math.min ( v, this.upperBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^v = Math.min (  this.upperBound ) ;^116^^^^^114^120^v = Math.min ( v, this.upperBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^v = Math.min ( v ) ;^116^^^^^114^120^v = Math.min ( v, this.upperBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^v = Math.min ( this.upperBound, v ) ;^116^^^^^114^120^v = Math.min ( v, this.upperBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P14_Delete_Statement]^^116^^^^^114^120^v = Math.min ( v, this.upperBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P11_Insert_Donor_Statement]^double v = Math.max ( value, this.lowerBound ) ;v = Math.min ( v, this.upperBound ) ;^116^^^^^114^120^v = Math.min ( v, this.upperBound ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P1_Replace_Type]^short  g =  (  short  )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^117^118^^^^114^120^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P2_Replace_Operator]^int / g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^117^118^^^^114^120^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P2_Replace_Operator]^int g =  ( int )   (  ( value - this.lowerBound )  +  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^117^118^^^^114^120^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P2_Replace_Operator]^int g =  ( int )   (  ( value  &&  this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^117^118^^^^114^120^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P2_Replace_Operator]^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound  <<  this.lowerBound )  * 255.0 ) ;^117^118^^^^114^120^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P3_Replace_Literal]^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 51.0 ) ;^117^118^^^^114^120^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^int g =  ( int )   (  ( v - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^117^118^^^^114^120^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^int g =  ( int )   (  ( value - value )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^117^118^^^^114^120^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^int g =  ( int )   (  ( value - this.lowerBound )  /  ( value - this.lowerBound )  * 255.0 ) ;^117^118^^^^114^120^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^int g =  ( int )   (  ( this.lowerBound - value )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^117^118^^^^114^120^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P5_Replace_Variable]^int g =  ( int )   (  ( this.upperBound - this.lowerBound )  /  ( value - this.lowerBound )  * 255.0 ) ;^117^118^^^^114^120^int g =  ( int )   (  ( value - this.lowerBound )  /  ( this.upperBound - this.lowerBound )  * 255.0 ) ;^[CLASS] GrayPaintScale  [METHOD] getPaint [RETURN_TYPE] Paint   double value [VARIABLES] double  lowerBound  upperBound  v  value  int  g  boolean  
[P2_Replace_Operator]^if  ( obj <= this )  {^136^^^^^135^150^if  ( obj == this )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P15_Unwrap_Block]^return true;^136^137^138^^^135^150^if  ( obj == this )  { return true; }^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P16_Remove_Block]^^136^137^138^^^135^150^if  ( obj == this )  { return true; }^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P3_Replace_Literal]^return false;^137^^^^^135^150^return true;^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P2_Replace_Operator]^if  ( ! ( obj  <<  GrayPaintScale )  )  {^139^^^^^135^150^if  ( ! ( obj instanceof GrayPaintScale )  )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P8_Replace_Mix]^if  (  ( obj instanceof GrayPaintScale )  )  {^139^^^^^135^150^if  ( ! ( obj instanceof GrayPaintScale )  )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P15_Unwrap_Block]^return false;^139^140^141^^^135^150^if  ( ! ( obj instanceof GrayPaintScale )  )  { return false; }^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P16_Remove_Block]^^139^140^141^^^135^150^if  ( ! ( obj instanceof GrayPaintScale )  )  { return false; }^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P3_Replace_Literal]^return true;^140^^^^^135^150^return false;^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P2_Replace_Operator]^if  ( this.lowerBound < that.lowerBound )  {^143^^^^^135^150^if  ( this.lowerBound != that.lowerBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P5_Replace_Variable]^if  ( value != that.lowerBound )  {^143^^^^^135^150^if  ( this.lowerBound != that.lowerBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P5_Replace_Variable]^if  ( this.lowerBound != value )  {^143^^^^^135^150^if  ( this.lowerBound != that.lowerBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P5_Replace_Variable]^if  ( this.lowerBound != that.lowerBound.lowerBound )  {^143^^^^^135^150^if  ( this.lowerBound != that.lowerBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P5_Replace_Variable]^if  ( that.lowerBound != this.lowerBound )  {^143^^^^^135^150^if  ( this.lowerBound != that.lowerBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P9_Replace_Statement]^if  ( lowerBound >= upperBound )  {^143^^^^^135^150^if  ( this.lowerBound != that.lowerBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P9_Replace_Statement]^if  ( this.upperBound != that.upperBound )  {^143^^^^^135^150^if  ( this.lowerBound != that.lowerBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P15_Unwrap_Block]^return false;^143^144^145^^^135^150^if  ( this.lowerBound != that.lowerBound )  { return false; }^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P16_Remove_Block]^^143^144^145^^^135^150^if  ( this.lowerBound != that.lowerBound )  { return false; }^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P13_Insert_Block]^if  (  ( this.upperBound )  !=  ( that.upperBound )  )  {     return false; }^143^^^^^135^150^[Delete]^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P3_Replace_Literal]^return true;^144^^^^^135^150^return false;^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P2_Replace_Operator]^if  ( this.upperBound == that.upperBound )  {^146^^^^^135^150^if  ( this.upperBound != that.upperBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P5_Replace_Variable]^if  ( value != that.upperBound )  {^146^^^^^135^150^if  ( this.upperBound != that.upperBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P5_Replace_Variable]^if  ( this.upperBound != v )  {^146^^^^^135^150^if  ( this.upperBound != that.upperBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P5_Replace_Variable]^if  ( this.upperBound != that.upperBound.upperBound )  {^146^^^^^135^150^if  ( this.upperBound != that.upperBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P5_Replace_Variable]^if  ( that.upperBound != this.upperBound )  {^146^^^^^135^150^if  ( this.upperBound != that.upperBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P8_Replace_Mix]^if  ( v != that.upperBound )  {^146^^^^^135^150^if  ( this.upperBound != that.upperBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P9_Replace_Statement]^if  ( this.lowerBound != that.lowerBound )  {^146^^^^^135^150^if  ( this.upperBound != that.upperBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P9_Replace_Statement]^if  ( lowerBound >= upperBound )  {^146^^^^^135^150^if  ( this.upperBound != that.upperBound )  {^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P15_Unwrap_Block]^return false;^146^147^148^^^135^150^if  ( this.upperBound != that.upperBound )  { return false; }^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P16_Remove_Block]^^146^147^148^^^135^150^if  ( this.upperBound != that.upperBound )  { return false; }^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P13_Insert_Block]^if  (  ( this.lowerBound )  !=  ( that.lowerBound )  )  {     return false; }^146^^^^^135^150^[Delete]^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P3_Replace_Literal]^return true;^147^^^^^135^150^return false;^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P3_Replace_Literal]^return false;^149^^^^^135^150^return true;^[CLASS] GrayPaintScale  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Object  obj  boolean  double  lowerBound  upperBound  v  value  GrayPaintScale  that  
[P14_Delete_Statement]^^161^^^^^160^162^return super.clone (  ) ;^[CLASS] GrayPaintScale  [METHOD] clone [RETURN_TYPE] Object   [VARIABLES] double  lowerBound  upperBound  v  value  boolean  
