[REPLACE]^private static final long serialVersionUID  = null ;^15^^^^^^^[REPLACE] private static final long serialVersionUID = 1L;^ [CLASS] AtomicReferenceDeserializer  
[REPLACE]^protected  JavaType _referencedType;^20^^^^^^^[REPLACE] protected final JavaType _referencedType;^ [CLASS] AtomicReferenceDeserializer  
[REPLACE]^protected final Object _valueTypeDeserializer;^22^^^^^^^[REPLACE] protected final TypeDeserializer _valueTypeDeserializer;^ [CLASS] AtomicReferenceDeserializer  
[REPLACE]^private final JsonDeserializer<?> _valueDeserializer;^24^^^^^^^[REPLACE] protected final JsonDeserializer<?> _valueDeserializer;^ [CLASS] AtomicReferenceDeserializer  
[ADD]^^89^^^^^88^107^[ADD] final JsonToken t = p.getCurrentToken (  ) ;^[METHOD] deserializeWithType [TYPE] Object [PARAMETER] JsonParser p DeserializationContext ctxt TypeDeserializer typeDeser [CLASS] AtomicReferenceDeserializer   [TYPE]  JavaType _referencedType  referencedType  [TYPE]  boolean false  true  [TYPE]  DeserializationContext ctxt  [TYPE]  JsonToken t  [TYPE]  TypeDeserializer _valueTypeDeserializer  typeDeser  [TYPE]  JsonDeserializer _valueDeserializer  deser  valueDeser  [TYPE]  long serialVersionUID  [TYPE]  JsonParser p 
[REPLACE]^if  ( t  ) {^90^^^^^88^107^[REPLACE] if  ( t == JsonToken.VALUE_NULL )  {^[METHOD] deserializeWithType [TYPE] Object [PARAMETER] JsonParser p DeserializationContext ctxt TypeDeserializer typeDeser [CLASS] AtomicReferenceDeserializer   [TYPE]  JavaType _referencedType  referencedType  [TYPE]  boolean false  true  [TYPE]  DeserializationContext ctxt  [TYPE]  JsonToken t  [TYPE]  TypeDeserializer _valueTypeDeserializer  typeDeser  [TYPE]  JsonDeserializer _valueDeserializer  deser  valueDeser  [TYPE]  long serialVersionUID  [TYPE]  JsonParser p 
[ADD]^return getNullValue ( ctxt ) ;^90^91^92^^^88^107^[ADD] if  ( t == JsonToken.VALUE_NULL )  { return getNullValue ( ctxt ) ; }^[METHOD] deserializeWithType [TYPE] Object [PARAMETER] JsonParser p DeserializationContext ctxt TypeDeserializer typeDeser [CLASS] AtomicReferenceDeserializer   [TYPE]  JavaType _referencedType  referencedType  [TYPE]  boolean false  true  [TYPE]  DeserializationContext ctxt  [TYPE]  JsonToken t  [TYPE]  TypeDeserializer _valueTypeDeserializer  typeDeser  [TYPE]  JsonDeserializer _valueDeserializer  deser  valueDeser  [TYPE]  long serialVersionUID  [TYPE]  JsonParser p 
[REPLACE]^if  (  ( t == true )  && t.isScalarValue (  )  )  {^96^^^^^88^107^[REPLACE] if  (  ( t != null )  && t.isScalarValue (  )  )  {^[METHOD] deserializeWithType [TYPE] Object [PARAMETER] JsonParser p DeserializationContext ctxt TypeDeserializer typeDeser [CLASS] AtomicReferenceDeserializer   [TYPE]  JavaType _referencedType  referencedType  [TYPE]  boolean false  true  [TYPE]  DeserializationContext ctxt  [TYPE]  JsonToken t  [TYPE]  TypeDeserializer _valueTypeDeserializer  typeDeser  [TYPE]  JsonDeserializer _valueDeserializer  deser  valueDeser  [TYPE]  long serialVersionUID  [TYPE]  JsonParser p 
[REPLACE]^if  ( _valueTypeDeserializer != false )  {^103^^^^^88^107^[REPLACE] if  ( _valueTypeDeserializer == null )  {^[METHOD] deserializeWithType [TYPE] Object [PARAMETER] JsonParser p DeserializationContext ctxt TypeDeserializer typeDeser [CLASS] AtomicReferenceDeserializer   [TYPE]  JavaType _referencedType  referencedType  [TYPE]  boolean false  true  [TYPE]  DeserializationContext ctxt  [TYPE]  JsonToken t  [TYPE]  TypeDeserializer _valueTypeDeserializer  typeDeser  [TYPE]  JsonDeserializer _valueDeserializer  deser  valueDeser  [TYPE]  long serialVersionUID  [TYPE]  JsonParser p 
[ADD]^return deserialize ( p, ctxt ) ;^103^104^105^^^88^107^[ADD] if  ( _valueTypeDeserializer == null )  { return deserialize ( p, ctxt ) ; }^[METHOD] deserializeWithType [TYPE] Object [PARAMETER] JsonParser p DeserializationContext ctxt TypeDeserializer typeDeser [CLASS] AtomicReferenceDeserializer   [TYPE]  JavaType _referencedType  referencedType  [TYPE]  boolean false  true  [TYPE]  DeserializationContext ctxt  [TYPE]  JsonToken t  [TYPE]  TypeDeserializer _valueTypeDeserializer  typeDeser  [TYPE]  JsonDeserializer _valueDeserializer  deser  valueDeser  [TYPE]  long serialVersionUID  [TYPE]  JsonParser p 
[REPLACE]^return new AtomicReference<Object> ( _valueTypeDeserializer .forProperty ( true )   ) ;^106^^^^^88^107^[REPLACE] return new AtomicReference<Object> ( _valueTypeDeserializer.deserializeTypedFromAny ( p, ctxt )  ) ;^[METHOD] deserializeWithType [TYPE] Object [PARAMETER] JsonParser p DeserializationContext ctxt TypeDeserializer typeDeser [CLASS] AtomicReferenceDeserializer   [TYPE]  JavaType _referencedType  referencedType  [TYPE]  boolean false  true  [TYPE]  DeserializationContext ctxt  [TYPE]  JsonToken t  [TYPE]  TypeDeserializer _valueTypeDeserializer  typeDeser  [TYPE]  JsonDeserializer _valueDeserializer  deser  valueDeser  [TYPE]  long serialVersionUID  [TYPE]  JsonParser p 
