[P3_Replace_Literal]^public static final Years ZERO = new Years ( 8 ) ;^44^^^^^39^49^public static final Years ZERO = new Years ( 0 ) ;^[CLASS] Years   [VARIABLES] 
[P4_Replace_Constructor]^public static final Years ZERO = public static final new Years ( years )  ;^44^^^^^39^49^public static final Years ZERO = new Years ( 0 ) ;^[CLASS] Years   [VARIABLES] 
[P8_Replace_Mix]^public static final Years ZERO = new Years ( 2 ) ;^44^^^^^39^49^public static final Years ZERO = new Years ( 0 ) ;^[CLASS] Years   [VARIABLES] 
[P3_Replace_Literal]^public static final Years ONE = new Years ( -5 ) ;^46^^^^^41^51^public static final Years ONE = new Years ( 1 ) ;^[CLASS] Years   [VARIABLES] 
[P4_Replace_Constructor]^public static final Years ONE = public static final new Years ( years )  ;^46^^^^^41^51^public static final Years ONE = new Years ( 1 ) ;^[CLASS] Years   [VARIABLES] 
[P8_Replace_Mix]^public static final Years ONE = new Years ( 2 ) ;^46^^^^^41^51^public static final Years ONE = new Years ( 1 ) ;^[CLASS] Years   [VARIABLES] 
[P3_Replace_Literal]^public static final Years TWO = new Years ( -3 ) ;^48^^^^^43^53^public static final Years TWO = new Years ( 2 ) ;^[CLASS] Years   [VARIABLES] 
[P4_Replace_Constructor]^public static final Years TWO = public static final new Years ( years )  ;^48^^^^^43^53^public static final Years TWO = new Years ( 2 ) ;^[CLASS] Years   [VARIABLES] 
[P8_Replace_Mix]^public static final Years TWO = new Years ( 2 / 4 ) ;^48^^^^^43^53^public static final Years TWO = new Years ( 2 ) ;^[CLASS] Years   [VARIABLES] 
[P3_Replace_Literal]^public static final Years THREE = new Years ( null ) ;^50^^^^^45^55^public static final Years THREE = new Years ( 3 ) ;^[CLASS] Years   [VARIABLES] 
[P4_Replace_Constructor]^public static final Years THREE = public static final new Years ( years )  ;^50^^^^^45^55^public static final Years THREE = new Years ( 3 ) ;^[CLASS] Years   [VARIABLES] 
[P8_Replace_Mix]^public static final Years THREE = new Years ( 2 ) ;^50^^^^^45^55^public static final Years THREE = new Years ( 3 ) ;^[CLASS] Years   [VARIABLES] 
[P8_Replace_Mix]^private static final Years MAX_VALUE = new Years ( Integer.MAX_VALUE ) ;^52^^^^^47^57^public static final Years MAX_VALUE = new Years ( Integer.MAX_VALUE ) ;^[CLASS] Years   [VARIABLES] 
[P8_Replace_Mix]^public static  Years MIN_VALUE = new Years ( Integer.MIN_VALUE ) ;^54^^^^^49^59^public static final Years MIN_VALUE = new Years ( Integer.MIN_VALUE ) ;^[CLASS] Years   [VARIABLES] 
[P1_Replace_Type]^private static final  int  serialVersionUID = 87525275727380868L;^59^^^^^54^64^private static final long serialVersionUID = 87525275727380868L;^[CLASS] Years   [VARIABLES] 
[P8_Replace_Mix]^private static final long serialVersionUID = 87525275727380868;^59^^^^^54^64^private static final long serialVersionUID = 87525275727380868L;^[CLASS] Years   [VARIABLES] 
[P14_Delete_Statement]^^174^^^^^173^175^super ( years ) ;^[CLASS] Years  [METHOD] <init> [RETURN_TYPE] Years(int)   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P5_Replace_Variable]^return THREE;^73^^^^^70^87^return ZERO;^[CLASS] Years  [METHOD] years [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P8_Replace_Mix]^return TWO;^73^^^^^70^87^return ZERO;^[CLASS] Years  [METHOD] years [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P5_Replace_Variable]^return ZERO;^75^^^^^70^87^return ONE;^[CLASS] Years  [METHOD] years [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P5_Replace_Variable]^return ZERO;^77^^^^^70^87^return TWO;^[CLASS] Years  [METHOD] years [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P5_Replace_Variable]^return ZERO;^79^^^^^70^87^return THREE;^[CLASS] Years  [METHOD] years [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P5_Replace_Variable]^return ZERO;^81^^^^^70^87^return MAX_VALUE;^[CLASS] Years  [METHOD] years [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P5_Replace_Variable]^return ZERO;^83^^^^^70^87^return MIN_VALUE;^[CLASS] Years  [METHOD] years [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P1_Replace_Type]^short  amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^101^^^^^100^103^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  amount  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between ( end, end, DurationFieldType.years (  )  ) ;^101^^^^^100^103^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  amount  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between (  end, DurationFieldType.years (  )  ) ;^101^^^^^100^103^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  amount  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between ( start,  DurationFieldType.years (  )  ) ;^101^^^^^100^103^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  amount  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between ( end, start, DurationFieldType.years (  )  ) ;^101^^^^^100^103^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  amount  
[P11_Insert_Donor_Statement]^int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType.years (  )  ) ;int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^101^^^^^100^103^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  amount  
[P11_Insert_Donor_Statement]^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^101^^^^^100^103^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  amount  
[P14_Delete_Statement]^^101^^^^^100^103^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  amount  
[P7_Replace_Invocation]^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType .years ( amount )   ) ;^101^^^^^100^103^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  amount  
[P7_Replace_Invocation]^return Years.Years ( amount ) ;^102^^^^^100^103^return Years.years ( amount ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  amount  
[P14_Delete_Statement]^^102^^^^^100^103^return Years.years ( amount ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  amount  
[P2_Replace_Operator]^if  ( start instanceof LocalDate || end instanceof LocalDate )    {^118^^^^^117^126^if  ( start instanceof LocalDate && end instanceof LocalDate )    {^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P2_Replace_Operator]^if  ( start  ==  LocalDate && end instanceof LocalDate )    {^118^^^^^117^126^if  ( start instanceof LocalDate && end instanceof LocalDate )    {^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P2_Replace_Operator]^if  ( start instanceof LocalDate && end  &  LocalDate )    {^118^^^^^117^126^if  ( start instanceof LocalDate && end instanceof LocalDate )    {^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^if  ( end instanceof LocalDate && end instanceof LocalDate )    {^118^^^^^117^126^if  ( start instanceof LocalDate && end instanceof LocalDate )    {^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^if  ( start instanceof LocalDate && start instanceof LocalDate )    {^118^^^^^117^126^if  ( start instanceof LocalDate && end instanceof LocalDate )    {^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^if  ( end instanceof LocalDate && start instanceof LocalDate )    {^118^^^^^117^126^if  ( start instanceof LocalDate && end instanceof LocalDate )    {^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P6_Replace_Expression]^if  ( start instanceof LocalDate ) {^118^^^^^117^126^if  ( start instanceof LocalDate && end instanceof LocalDate )    {^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P6_Replace_Expression]^if  (  end instanceof LocalDate )    {^118^^^^^117^126^if  ( start instanceof LocalDate && end instanceof LocalDate )    {^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P15_Unwrap_Block]^org.joda.time.Chronology chrono = org.joda.time.DateTimeUtils.getChronology(start.getChronology()); int years = chrono.years().getDifference(((org.joda.time.LocalDate) (end)).getLocalMillis(), ((org.joda.time.LocalDate) (start)).getLocalMillis()); return org.joda.time.Years.years(years);^118^119^120^121^122^117^126^if  ( start instanceof LocalDate && end instanceof LocalDate )    { Chronology chrono = DateTimeUtils.getChronology ( start.getChronology (  )  ) ; int years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ; return Years.years ( years ) ; }^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P16_Remove_Block]^^118^119^120^121^122^117^126^if  ( start instanceof LocalDate && end instanceof LocalDate )    { Chronology chrono = DateTimeUtils.getChronology ( start.getChronology (  )  ) ; int years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ; return Years.years ( years ) ; }^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^return Years.years ( amount ) ;^122^^^^^117^126^return Years.years ( years ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P7_Replace_Invocation]^return Years.Years ( years ) ;^122^^^^^117^126^return Years.years ( years ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P7_Replace_Invocation]^return Years .Years ( amount )  ;^122^^^^^117^126^return Years.years ( years ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P1_Replace_Type]^long  years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^120^121^^^^117^126^int years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P7_Replace_Invocation]^int years = chrono.years (  )  .getValue (  )  .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^120^121^^^^117^126^int years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^Chronology chrono = DateTimeUtils.getChronology ( end.getChronology (  )  ) ;^119^^^^^117^126^Chronology chrono = DateTimeUtils.getChronology ( start.getChronology (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P14_Delete_Statement]^^119^^^^^117^126^Chronology chrono = DateTimeUtils.getChronology ( start.getChronology (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P7_Replace_Invocation]^int years = chrono .Years ( amount )  .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^120^121^^^^117^126^int years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P14_Delete_Statement]^^120^121^122^123^^117^126^int years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ; return Years.years ( years ) ; }^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P7_Replace_Invocation]^(  ( LocalDate )  end )  .getValue (  )  ,  (  ( LocalDate )  start )^121^^^^^117^126^(  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P14_Delete_Statement]^^121^^^^^117^126^(  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P11_Insert_Donor_Statement]^int years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;(  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^121^^^^^117^126^(  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P14_Delete_Statement]^^121^122^^^^117^126^(  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ; return Years.years ( years ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P14_Delete_Statement]^^122^^^^^117^126^return Years.years ( years ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P1_Replace_Type]^short  years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^120^121^^^^117^126^int years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P7_Replace_Invocation]^int years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end )  .getValue (  )  ,  (  ( LocalDate )  start )^120^121^^^^117^126^int years = chrono.years (  ) .getDifference ( (  ( LocalDate )  end ) .getLocalMillis (  ) ,  (  ( LocalDate )  start ) .getLocalMillis (  )  ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P1_Replace_Type]^short  amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^124^^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between ( end, end, ZERO ) ;^124^^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between ( start, start, ZERO ) ;^124^^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between ( start, end, TWO ) ;^124^^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between (  end, ZERO ) ;^124^^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between ( start,  ZERO ) ;^124^^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between ( start, end ) ;^124^^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between ( end, start, ZERO ) ;^124^^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between ( ZERO, end, start ) ;^124^^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P11_Insert_Donor_Statement]^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^124^^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^int amount = BaseSingleFieldPeriod.between ( start, ZERO, end ) ;^124^^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P14_Delete_Statement]^^124^125^^^^117^126^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ; return Years.years ( amount ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P5_Replace_Variable]^return Years.years ( years ) ;^125^^^^^117^126^return Years.years ( amount ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P7_Replace_Invocation]^return Years.Years ( amount ) ;^125^^^^^117^126^return Years.years ( amount ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P7_Replace_Invocation]^return Years .Years ( years )  ;^125^^^^^117^126^return Years.years ( amount ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P14_Delete_Statement]^^125^^^^^117^126^return Years.years ( amount ) ;^[CLASS] Years  [METHOD] yearsBetween [RETURN_TYPE] Years   ReadablePartial start ReadablePartial end [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  ReadablePartial  end  start  Chronology  chrono  boolean  long  serialVersionUID  int  amount  years  
[P2_Replace_Operator]^if  ( interval != null )    {^138^^^^^137^143^if  ( interval == null )    {^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P8_Replace_Mix]^if  ( interval == false )    {^138^^^^^137^143^if  ( interval == null )    {^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P9_Replace_Statement]^if  ( years == null )  {^138^^^^^137^143^if  ( interval == null )    {^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P9_Replace_Statement]^if  ( other == null )  {^138^^^^^137^143^if  ( interval == null )    {^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P15_Unwrap_Block]^return org.joda.time.Years.ZERO;^138^139^140^^^137^143^if  ( interval == null )    { return Years.ZERO; }^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P16_Remove_Block]^^138^139^140^^^137^143^if  ( interval == null )    { return Years.ZERO; }^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P13_Insert_Block]^if  ( years == null )  {     return this; }^138^^^^^137^143^[Delete]^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  > 0; }^138^^^^^137^143^[Delete]^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  < 0; }^138^^^^^137^143^[Delete]^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P1_Replace_Type]^long  amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType.years (  )  ) ;^141^^^^^137^143^int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P7_Replace_Invocation]^int amount = BaseSingleFieldPeriod .between ( this , this , THREE )  , DurationFieldType.years (  )  ) ;^141^^^^^137^143^int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P7_Replace_Invocation]^int amount = BaseSingleFieldPeriod.between ( interval .getEnd (  )  , interval.getEnd (  ) , DurationFieldType.years (  )  ) ;^141^^^^^137^143^int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P8_Replace_Mix]^int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval .getStart (  )  , DurationFieldType.years (  )  ) ;^141^^^^^137^143^int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P11_Insert_Donor_Statement]^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.years (  )  ) ;int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType.years (  )  ) ;^141^^^^^137^143^int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P8_Replace_Mix]^int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType .years ( amount )   ) ;^141^^^^^137^143^int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P14_Delete_Statement]^^141^142^^^^137^143^int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType.years (  )  ) ; return Years.years ( amount ) ;^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P14_Delete_Statement]^^141^^^^^137^143^int amount = BaseSingleFieldPeriod.between ( interval.getStart (  ) , interval.getEnd (  ) , DurationFieldType.years (  )  ) ;^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P7_Replace_Invocation]^return Years.Years ( amount ) ;^142^^^^^137^143^return Years.years ( amount ) ;^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P14_Delete_Statement]^^142^^^^^137^143^return Years.years ( amount ) ;^[CLASS] Years  [METHOD] yearsIn [RETURN_TYPE] Years   ReadableInterval interval [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  ReadableInterval  interval  int  amount  
[P14_Delete_Statement]^^157^^^^^156^163^throw ExceptionUtils.unsupportedInGwt (  ) ;^[CLASS] Years  [METHOD] parseYears [RETURN_TYPE] Years   String periodStr [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  String  periodStr  boolean  long  serialVersionUID  
[P7_Replace_Invocation]^return Years.years ( getLocalMillis (  )  ) ;^183^^^^^182^184^return Years.years ( getValue (  )  ) ;^[CLASS] Years  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  
[P14_Delete_Statement]^^183^^^^^182^184^return Years.years ( getValue (  )  ) ;^[CLASS] Years  [METHOD] readResolve [RETURN_TYPE] Object   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  
[P14_Delete_Statement]^^193^^^^^192^194^return DurationFieldType.years (  ) ;^[CLASS] Years  [METHOD] getFieldType [RETURN_TYPE] DurationFieldType   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  
[P14_Delete_Statement]^^202^^^^^201^203^return PeriodType.years (  ) ;^[CLASS] Years  [METHOD] getPeriodType [RETURN_TYPE] PeriodType   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  
[P7_Replace_Invocation]^return getLocalMillis (  ) ;^212^^^^^211^213^return getValue (  ) ;^[CLASS] Years  [METHOD] getYears [RETURN_TYPE] int   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  
[P14_Delete_Statement]^^212^^^^^211^213^return getValue (  ) ;^[CLASS] Years  [METHOD] getYears [RETURN_TYPE] int   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  
[P2_Replace_Operator]^if  ( years != 0 )  {^226^^^^^225^230^if  ( years == 0 )  {^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P3_Replace_Literal]^if  ( years == years )  {^226^^^^^225^230^if  ( years == 0 )  {^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P8_Replace_Mix]^if  ( years == 0 + 0 )  {^226^^^^^225^230^if  ( years == 0 )  {^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P9_Replace_Statement]^if  ( divisor == 1 )  {^226^^^^^225^230^if  ( years == 0 )  {^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P9_Replace_Statement]^if  ( years == null )  {^226^^^^^225^230^if  ( years == 0 )  {^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P15_Unwrap_Block]^return this;^226^227^228^^^225^230^if  ( years == 0 )  { return this; }^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P16_Remove_Block]^^226^227^228^^^225^230^if  ( years == 0 )  { return this; }^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P13_Insert_Block]^if  ( years == null )  {     return this; }^226^^^^^225^230^[Delete]^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  > 0; }^226^^^^^225^230^[Delete]^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  < 0; }^226^^^^^225^230^[Delete]^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P13_Insert_Block]^if  ( divisor == 1 )  {     return this; }^226^^^^^225^230^[Delete]^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P8_Replace_Mix]^return null;^227^^^^^225^230^return this;^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P7_Replace_Invocation]^return Years.Years ( FieldUtils.safeAdd ( getValue (  ) , years )  ) ;^229^^^^^225^230^return Years.years ( FieldUtils.safeAdd ( getValue (  ) , years )  ) ;^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P7_Replace_Invocation]^return Years.years ( FieldUtils.safeNegate ( getValue (  ) , years )  ) ;^229^^^^^225^230^return Years.years ( FieldUtils.safeAdd ( getValue (  ) , years )  ) ;^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P7_Replace_Invocation]^return Years.years ( FieldUtils .safeNegate ( years )   ) ;^229^^^^^225^230^return Years.years ( FieldUtils.safeAdd ( getValue (  ) , years )  ) ;^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P7_Replace_Invocation]^return Years.years ( FieldUtils.safeAdd ( getLocalMillis (  ) , years )  ) ;^229^^^^^225^230^return Years.years ( FieldUtils.safeAdd ( getValue (  ) , years )  ) ;^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P14_Delete_Statement]^^229^^^^^225^230^return Years.years ( FieldUtils.safeAdd ( getValue (  ) , years )  ) ;^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  boolean  long  serialVersionUID  int  years  
[P2_Replace_Operator]^if  ( years != null )  {^242^^^^^241^246^if  ( years == null )  {^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P5_Replace_Variable]^if  ( THREE == null )  {^242^^^^^241^246^if  ( years == null )  {^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P8_Replace_Mix]^if  ( ZERO == false )  {^242^^^^^241^246^if  ( years == null )  {^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P9_Replace_Statement]^if  ( years == 0 )  {^242^^^^^241^246^if  ( years == null )  {^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P9_Replace_Statement]^if  ( other == null )  {^242^^^^^241^246^if  ( years == null )  {^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P9_Replace_Statement]^if  ( interval == null )    {^242^^^^^241^246^if  ( years == null )  {^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P15_Unwrap_Block]^return this;^242^243^244^^^241^246^if  ( years == null )  { return this; }^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P16_Remove_Block]^^242^243^244^^^241^246^if  ( years == null )  { return this; }^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P13_Insert_Block]^if  ( interval == null )  {     return ZERO; }^242^^^^^241^246^[Delete]^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P13_Insert_Block]^if  ( years == 0 )  {     return this; }^242^^^^^241^246^[Delete]^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  > 0; }^242^^^^^241^246^[Delete]^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  < 0; }^242^^^^^241^246^[Delete]^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P13_Insert_Block]^if  ( divisor == 1 )  {     return this; }^242^^^^^241^246^[Delete]^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P8_Replace_Mix]^return null;^243^^^^^241^246^return this;^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P5_Replace_Variable]^return plus ( THREE.getValue (  )  ) ;^245^^^^^241^246^return plus ( years.getValue (  )  ) ;^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P7_Replace_Invocation]^return minus ( years.getValue (  )  ) ;^245^^^^^241^246^return plus ( years.getValue (  )  ) ;^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P5_Replace_Variable]^return plus ( ZERO.getValue (  )  ) ;^245^^^^^241^246^return plus ( years.getValue (  )  ) ;^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P14_Delete_Statement]^^245^^^^^241^246^return plus ( years.getValue (  )  ) ;^[CLASS] Years  [METHOD] plus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P7_Replace_Invocation]^return minus ( FieldUtils.safeNegate ( years )  ) ;^259^^^^^258^260^return plus ( FieldUtils.safeNegate ( years )  ) ;^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  years  
[P7_Replace_Invocation]^return plus ( FieldUtils.safeAdd ( years )  ) ;^259^^^^^258^260^return plus ( FieldUtils.safeNegate ( years )  ) ;^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  years  
[P14_Delete_Statement]^^259^^^^^258^260^return plus ( FieldUtils.safeNegate ( years )  ) ;^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   int years [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  years  
[P2_Replace_Operator]^if  ( years != null )  {^272^^^^^271^276^if  ( years == null )  {^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P5_Replace_Variable]^if  ( ZERO == null )  {^272^^^^^271^276^if  ( years == null )  {^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P8_Replace_Mix]^if  ( years == this )  {^272^^^^^271^276^if  ( years == null )  {^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P9_Replace_Statement]^if  ( years == 0 )  {^272^^^^^271^276^if  ( years == null )  {^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P9_Replace_Statement]^if  ( other == null )  {^272^^^^^271^276^if  ( years == null )  {^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P9_Replace_Statement]^if  ( interval == null )    {^272^^^^^271^276^if  ( years == null )  {^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P15_Unwrap_Block]^return this;^272^273^274^^^271^276^if  ( years == null )  { return this; }^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P16_Remove_Block]^^272^273^274^^^271^276^if  ( years == null )  { return this; }^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P13_Insert_Block]^if  ( interval == null )  {     return ZERO; }^272^^^^^271^276^[Delete]^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P13_Insert_Block]^if  ( years == 0 )  {     return this; }^272^^^^^271^276^[Delete]^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  > 0; }^272^^^^^271^276^[Delete]^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  < 0; }^272^^^^^271^276^[Delete]^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P13_Insert_Block]^if  ( divisor == 1 )  {     return this; }^272^^^^^271^276^[Delete]^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P8_Replace_Mix]^return null;^273^^^^^271^276^return this;^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P5_Replace_Variable]^return minus ( ZERO.getValue (  )  ) ;^275^^^^^271^276^return minus ( years.getValue (  )  ) ;^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P7_Replace_Invocation]^return plus ( years.getValue (  )  ) ;^275^^^^^271^276^return minus ( years.getValue (  )  ) ;^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P7_Replace_Invocation]^return minus ( years .getLocalMillis (  )   ) ;^275^^^^^271^276^return minus ( years.getValue (  )  ) ;^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P14_Delete_Statement]^^275^^^^^271^276^return minus ( years.getValue (  )  ) ;^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P5_Replace_Variable]^return minus ( THREE.getValue (  )  ) ;^275^^^^^271^276^return minus ( years.getValue (  )  ) ;^[CLASS] Years  [METHOD] minus [RETURN_TYPE] Years   Years years [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P7_Replace_Invocation]^return Years.Years ( FieldUtils.safeMultiply ( getValue (  ) , scalar )  ) ;^289^^^^^288^290^return Years.years ( FieldUtils.safeMultiply ( getValue (  ) , scalar )  ) ;^[CLASS] Years  [METHOD] multipliedBy [RETURN_TYPE] Years   int scalar [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  scalar  
[P7_Replace_Invocation]^return Years .Years ( scalar )   ) ;^289^^^^^288^290^return Years.years ( FieldUtils.safeMultiply ( getValue (  ) , scalar )  ) ;^[CLASS] Years  [METHOD] multipliedBy [RETURN_TYPE] Years   int scalar [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  scalar  
[P7_Replace_Invocation]^return Years.years ( FieldUtils.safeAdd ( getValue (  ) , scalar )  ) ;^289^^^^^288^290^return Years.years ( FieldUtils.safeMultiply ( getValue (  ) , scalar )  ) ;^[CLASS] Years  [METHOD] multipliedBy [RETURN_TYPE] Years   int scalar [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  scalar  
[P7_Replace_Invocation]^return Years.years ( FieldUtils.safeMultiply ( getLocalMillis (  ) , scalar )  ) ;^289^^^^^288^290^return Years.years ( FieldUtils.safeMultiply ( getValue (  ) , scalar )  ) ;^[CLASS] Years  [METHOD] multipliedBy [RETURN_TYPE] Years   int scalar [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  scalar  
[P7_Replace_Invocation]^return Years.years ( FieldUtils .safeAdd ( scalar )   ) ;^289^^^^^288^290^return Years.years ( FieldUtils.safeMultiply ( getValue (  ) , scalar )  ) ;^[CLASS] Years  [METHOD] multipliedBy [RETURN_TYPE] Years   int scalar [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  scalar  
[P14_Delete_Statement]^^289^^^^^288^290^return Years.years ( FieldUtils.safeMultiply ( getValue (  ) , scalar )  ) ;^[CLASS] Years  [METHOD] multipliedBy [RETURN_TYPE] Years   int scalar [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  scalar  
[P2_Replace_Operator]^if  ( divisor != 1 )  {^303^^^^^302^307^if  ( divisor == 1 )  {^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P3_Replace_Literal]^if  ( divisor == divisor )  {^303^^^^^302^307^if  ( divisor == 1 )  {^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P8_Replace_Mix]^if  ( divisor == 1L )  {^303^^^^^302^307^if  ( divisor == 1 )  {^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P9_Replace_Statement]^if  ( years == 0 )  {^303^^^^^302^307^if  ( divisor == 1 )  {^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P15_Unwrap_Block]^return this;^303^304^305^^^302^307^if  ( divisor == 1 )  { return this; }^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P16_Remove_Block]^^303^304^305^^^302^307^if  ( divisor == 1 )  { return this; }^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P13_Insert_Block]^if  ( years == 0 )  {     return this; }^303^^^^^302^307^[Delete]^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P13_Insert_Block]^if  ( years == null )  {     return this; }^303^^^^^302^307^[Delete]^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  > 0; }^303^^^^^302^307^[Delete]^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  < 0; }^303^^^^^302^307^[Delete]^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P8_Replace_Mix]^return null;^304^^^^^302^307^return this;^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P2_Replace_Operator]^return Years.years ( getValue (  )  + divisor ) ;^306^^^^^302^307^return Years.years ( getValue (  )  / divisor ) ;^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P7_Replace_Invocation]^return Years.Years ( getValue (  )  / divisor ) ;^306^^^^^302^307^return Years.years ( getValue (  )  / divisor ) ;^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P7_Replace_Invocation]^return Years .Years ( divisor )  ;^306^^^^^302^307^return Years.years ( getValue (  )  / divisor ) ;^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P7_Replace_Invocation]^return Years.years ( getLocalMillis (  )  / divisor ) ;^306^^^^^302^307^return Years.years ( getValue (  )  / divisor ) ;^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P8_Replace_Mix]^return Years.Years ( getValue (  )  - divisor ) ;^306^^^^^302^307^return Years.years ( getValue (  )  / divisor ) ;^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P14_Delete_Statement]^^306^^^^^302^307^return Years.years ( getValue (  )  / divisor ) ;^[CLASS] Years  [METHOD] dividedBy [RETURN_TYPE] Years   int divisor [VARIABLES] Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  long  serialVersionUID  int  divisor  
[P7_Replace_Invocation]^return Years.years ( FieldUtils.safeNegate ( getLocalMillis (  )  )  ) ;^317^^^^^316^318^return Years.years ( FieldUtils.safeNegate ( getValue (  )  )  ) ;^[CLASS] Years  [METHOD] negated [RETURN_TYPE] Years   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P14_Delete_Statement]^^317^^^^^316^318^return Years.years ( FieldUtils.safeNegate ( getValue (  )  )  ) ;^[CLASS] Years  [METHOD] negated [RETURN_TYPE] Years   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  years  boolean  
[P2_Replace_Operator]^if  ( other != null )  {^328^^^^^327^332^if  ( other == null )  {^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P6_Replace_Expression]^if  ( getValue() > 0 )  {^328^^^^^327^332^if  ( other == null )  {^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P8_Replace_Mix]^if  ( other == this )  {^328^^^^^327^332^if  ( other == null )  {^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P9_Replace_Statement]^if  ( years == null )  {^328^^^^^327^332^if  ( other == null )  {^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P9_Replace_Statement]^if  ( interval == null )    {^328^^^^^327^332^if  ( other == null )  {^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P15_Unwrap_Block]^return (getValue()) > 0;^328^329^330^^^327^332^if  ( other == null )  { return getValue (  )  > 0; }^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P16_Remove_Block]^^328^329^330^^^327^332^if  ( other == null )  { return getValue (  )  > 0; }^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P13_Insert_Block]^if  ( interval == null )  {     return ZERO; }^328^^^^^327^332^[Delete]^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P13_Insert_Block]^if  ( years == 0 )  {     return this; }^328^^^^^327^332^[Delete]^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P13_Insert_Block]^if  ( years == null )  {     return this; }^328^^^^^327^332^[Delete]^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  < 0; }^328^^^^^327^332^[Delete]^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P13_Insert_Block]^if  ( divisor == 1 )  {     return this; }^328^^^^^327^332^[Delete]^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P2_Replace_Operator]^return getValue (  )  >= 0;^329^^^^^327^332^return getValue (  )  > 0;^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P3_Replace_Literal]^return getValue (  )  > -9;^329^^^^^327^332^return getValue (  )  > 0;^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P7_Replace_Invocation]^return getLocalMillis (  )  > 0;^329^^^^^327^332^return getValue (  )  > 0;^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P14_Delete_Statement]^^329^^^^^327^332^return getValue (  )  > 0;^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P2_Replace_Operator]^return getValue (  )  < 0;^329^^^^^327^332^return getValue (  )  > 0;^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P3_Replace_Literal]^return getValue (  )  > -2;^329^^^^^327^332^return getValue (  )  > 0;^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P2_Replace_Operator]^return getValue (  )  >= other.getValue (  ) ;^331^^^^^327^332^return getValue (  )  > other.getValue (  ) ;^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P5_Replace_Variable]^return getValue (  )  > years.getValue (  ) ;^331^^^^^327^332^return getValue (  )  > other.getValue (  ) ;^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P7_Replace_Invocation]^return getValue (  )  > other.getLocalMillis (  ) ;^331^^^^^327^332^return getValue (  )  > other.getValue (  ) ;^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P14_Delete_Statement]^^331^^^^^327^332^return getValue (  )  > other.getValue (  ) ;^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P8_Replace_Mix]^return getValue (  )  > TWO.getValue (  ) ;^331^^^^^327^332^return getValue (  )  > other.getValue (  ) ;^[CLASS] Years  [METHOD] isGreaterThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P2_Replace_Operator]^if  ( other != null )  {^341^^^^^340^345^if  ( other == null )  {^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P5_Replace_Variable]^if  ( years == null )  {^341^^^^^340^345^if  ( other == null )  {^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P6_Replace_Expression]^if  ( getValue() < 0 )  {^341^^^^^340^345^if  ( other == null )  {^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P8_Replace_Mix]^if  ( other == false )  {^341^^^^^340^345^if  ( other == null )  {^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P9_Replace_Statement]^if  ( interval == null )    {^341^^^^^340^345^if  ( other == null )  {^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P15_Unwrap_Block]^return (getValue()) < 0;^341^342^343^^^340^345^if  ( other == null )  { return getValue (  )  < 0; }^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P16_Remove_Block]^^341^342^343^^^340^345^if  ( other == null )  { return getValue (  )  < 0; }^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P13_Insert_Block]^if  ( interval == null )  {     return ZERO; }^341^^^^^340^345^[Delete]^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P13_Insert_Block]^if  ( years == 0 )  {     return this; }^341^^^^^340^345^[Delete]^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P13_Insert_Block]^if  ( years == null )  {     return this; }^341^^^^^340^345^[Delete]^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P13_Insert_Block]^if  ( other == null )  {     return  ( getValue (  )  )  > 0; }^341^^^^^340^345^[Delete]^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P13_Insert_Block]^if  ( divisor == 1 )  {     return this; }^341^^^^^340^345^[Delete]^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P2_Replace_Operator]^return getValue (  )  > 0;^342^^^^^340^345^return getValue (  )  < 0;^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P3_Replace_Literal]^return getValue (  )  < 6;^342^^^^^340^345^return getValue (  )  < 0;^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P7_Replace_Invocation]^return getLocalMillis (  )  < 0;^342^^^^^340^345^return getValue (  )  < 0;^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P8_Replace_Mix]^return getLocalMillis (  )   ;^342^^^^^340^345^return getValue (  )  < 0;^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P14_Delete_Statement]^^342^^^^^340^345^return getValue (  )  < 0;^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P2_Replace_Operator]^return getValue (  )  == 0;^342^^^^^340^345^return getValue (  )  < 0;^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P3_Replace_Literal]^return getValue (  )  < ;^342^^^^^340^345^return getValue (  )  < 0;^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P2_Replace_Operator]^return getValue (  )  <= other.getValue (  ) ;^344^^^^^340^345^return getValue (  )  < other.getValue (  ) ;^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P5_Replace_Variable]^return getValue (  )  < years.getValue (  ) ;^344^^^^^340^345^return getValue (  )  < other.getValue (  ) ;^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P7_Replace_Invocation]^return getValue (  )  < other.getLocalMillis (  ) ;^344^^^^^340^345^return getValue (  )  < other.getValue (  ) ;^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P14_Delete_Statement]^^344^^^^^340^345^return getValue (  )  < other.getValue (  ) ;^[CLASS] Years  [METHOD] isLessThan [RETURN_TYPE] boolean   Years other [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P2_Replace_Operator]^return "P" + String.valueOf ( getValue (  !=  )  )  + "Y";^356^^^^^355^357^return "P" + String.valueOf ( getValue (  )  )  + "Y";^[CLASS] Years  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P2_Replace_Operator]^return "P" + String.valueOf ( getValue (  ^  )  )  + "Y";^356^^^^^355^357^return "P" + String.valueOf ( getValue (  )  )  + "Y";^[CLASS] Years  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P3_Replace_Literal]^return "P" + String.valueOf ( getValue (  )  )  + "";^356^^^^^355^357^return "P" + String.valueOf ( getValue (  )  )  + "Y";^[CLASS] Years  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P7_Replace_Invocation]^return "P" + String.valueOf ( getLocalMillis (  )  )  + "Y";^356^^^^^355^357^return "P" + String.valueOf ( getValue (  )  )  + "Y";^[CLASS] Years  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P8_Replace_Mix]^return false ;^356^^^^^355^357^return "P" + String.valueOf ( getValue (  )  )  + "Y";^[CLASS] Years  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
[P14_Delete_Statement]^^356^^^^^355^357^return "P" + String.valueOf ( getValue (  )  )  + "Y";^[CLASS] Years  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] long  serialVersionUID  Years  MAX_VALUE  MIN_VALUE  ONE  THREE  TWO  ZERO  other  years  boolean  
