[buglab_swap_variables]^super ( new Expression[] { arg2, arg1 } ) ;^39^^^^^38^40^super ( new Expression[] { arg1, arg2 } ) ;^[CLASS] CoreOperationCompare  [METHOD] <init> [RETURN_TYPE] Expression)   Expression arg1 Expression arg2 [VARIABLES] boolean  Expression  arg1  arg2  
[buglab_swap_variables]^super ( new Expression[] {  arg2 } ) ;^39^^^^^38^40^super ( new Expression[] { arg1, arg2 } ) ;^[CLASS] CoreOperationCompare  [METHOD] <init> [RETURN_TYPE] Expression)   Expression arg1 Expression arg2 [VARIABLES] boolean  Expression  arg1  arg2  
[buglab_swap_variables]^super ( new Expression[] { arg1 } ) ;^39^^^^^38^40^super ( new Expression[] { arg1, arg2 } ) ;^[CLASS] CoreOperationCompare  [METHOD] <init> [RETURN_TYPE] Expression)   Expression arg1 Expression arg2 [VARIABLES] boolean  Expression  arg1  arg2  
[buglab_swap_variables]^Object l = context.compute ( left ) ;^50^^^^^35^65^Object l = left.compute ( context ) ;^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   EvalContext context Expression left Expression right [VARIABLES] boolean  Expression  left  right  EvalContext  context  Object  l  r  
[buglab_swap_variables]^Object r = context.compute ( right ) ;^51^^^^^36^66^Object r = right.compute ( context ) ;^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   EvalContext context Expression left Expression right [VARIABLES] boolean  Expression  left  right  EvalContext  context  Object  l  r  
[buglab_swap_variables]^if  (  ( r instanceof Iterator )  && ! ( l instanceof Iterator )  )  {^73^^^^^58^88^if  (  ( l instanceof Iterator )  && ! ( r instanceof Iterator )  )  {^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   EvalContext context Expression left Expression right [VARIABLES] boolean  Expression  left  right  EvalContext  context  Object  l  r  
[buglab_swap_variables]^else if  ( r instanceof Iterator && l instanceof Iterator )  {^79^^^^^64^94^else if  ( l instanceof Iterator && r instanceof Iterator )  {^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   EvalContext context Expression left Expression right [VARIABLES] boolean  Expression  left  right  EvalContext  context  Object  l  r  
[buglab_swap_variables]^return contains (  ( Iterator )  r ) ;^77^^^^^62^92^return contains (  ( Iterator )  r, l ) ;^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   EvalContext context Expression left Expression right [VARIABLES] boolean  Expression  left  right  EvalContext  context  Object  l  r  
[buglab_swap_variables]^return contains (  ( Iterator )  l ) ;^74^^^^^59^89^return contains (  ( Iterator )  l, r ) ;^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   EvalContext context Expression left Expression right [VARIABLES] boolean  Expression  left  right  EvalContext  context  Object  l  r  
[buglab_swap_variables]^return equal ( r, l ) ;^83^^^^^68^98^return equal ( l, r ) ;^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   EvalContext context Expression left Expression right [VARIABLES] boolean  Expression  left  right  EvalContext  context  Object  l  r  
[buglab_swap_variables]^return equal (  r ) ;^83^^^^^68^98^return equal ( l, r ) ;^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   EvalContext context Expression left Expression right [VARIABLES] boolean  Expression  left  right  EvalContext  context  Object  l  r  
[buglab_swap_variables]^return equal ( l ) ;^83^^^^^68^98^return equal ( l, r ) ;^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   EvalContext context Expression left Expression right [VARIABLES] boolean  Expression  left  right  EvalContext  context  Object  l  r  
[buglab_swap_variables]^if  ( equal ( value, element )  )  {^89^^^^^86^94^if  ( equal ( element, value )  )  {^[CLASS] CoreOperationCompare  [METHOD] contains [RETURN_TYPE] boolean   Iterator it Object value [VARIABLES] boolean  Iterator  it  Object  element  value  
[buglab_swap_variables]^if  ( equal (  value )  )  {^89^^^^^86^94^if  ( equal ( element, value )  )  {^[CLASS] CoreOperationCompare  [METHOD] contains [RETURN_TYPE] boolean   Iterator it Object value [VARIABLES] boolean  Iterator  it  Object  element  value  
[buglab_swap_variables]^if  ( equal ( element )  )  {^89^^^^^86^94^if  ( equal ( element, value )  )  {^[CLASS] CoreOperationCompare  [METHOD] contains [RETURN_TYPE] boolean   Iterator it Object value [VARIABLES] boolean  Iterator  it  Object  element  value  
[buglab_swap_variables]^if  ( contains ( rit.iterator (  ) , left.next (  )  )  )  {^102^^^^^96^107^if  ( contains ( left.iterator (  ) , rit.next (  )  )  )  {^[CLASS] CoreOperationCompare  [METHOD] findMatch [RETURN_TYPE] boolean   Iterator lit Iterator rit [VARIABLES] boolean  Iterator  lit  rit  HashSet  left  
[buglab_swap_variables]^if  ( contains ( left.iterator (  ) .next (  )  )  )  {^102^^^^^96^107^if  ( contains ( left.iterator (  ) , rit.next (  )  )  )  {^[CLASS] CoreOperationCompare  [METHOD] findMatch [RETURN_TYPE] boolean   Iterator lit Iterator rit [VARIABLES] boolean  Iterator  lit  rit  HashSet  left  
[buglab_swap_variables]^if  ( r instanceof Pointer && l instanceof Pointer )  {^110^^^^^95^125^if  ( l instanceof Pointer && r instanceof Pointer )  {^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   Object l Object r [VARIABLES] boolean  Object  l  r  
[buglab_swap_variables]^if  ( r.equals ( l )  )  {^111^^^^^96^126^if  ( l.equals ( r )  )  {^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   Object l Object r [VARIABLES] boolean  Object  l  r  
[buglab_swap_variables]^if  ( r == l )  {^124^^^^^109^139^if  ( l == r )  {^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   Object l Object r [VARIABLES] boolean  Object  l  r  
[buglab_swap_variables]^if  ( r instanceof Boolean || l instanceof Boolean )  {^129^^^^^114^144^if  ( l instanceof Boolean || r instanceof Boolean )  {^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   Object l Object r [VARIABLES] boolean  Object  l  r  
[buglab_swap_variables]^else if  ( r instanceof Number || l instanceof Number )  {^132^^^^^117^147^else if  ( l instanceof Number || r instanceof Number )  {^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   Object l Object r [VARIABLES] boolean  Object  l  r  
[buglab_swap_variables]^else if  ( r instanceof String || l instanceof String )  {^135^^^^^120^150^else if  ( l instanceof String || r instanceof String )  {^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   Object l Object r [VARIABLES] boolean  Object  l  r  
[buglab_swap_variables]^return  ( InfoSetUtil.stringValue ( r ) .equals ( InfoSetUtil.stringValue ( l )  )  ) ;^136^137^^^^121^151^return  ( InfoSetUtil.stringValue ( l ) .equals ( InfoSetUtil.stringValue ( r )  )  ) ;^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   Object l Object r [VARIABLES] boolean  Object  l  r  
[buglab_swap_variables]^return  ( InfoSetUtil.doubleValue ( r )  == InfoSetUtil.doubleValue ( l )  ) ;^133^^^^^118^148^return  ( InfoSetUtil.doubleValue ( l )  == InfoSetUtil.doubleValue ( r )  ) ;^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   Object l Object r [VARIABLES] boolean  Object  l  r  
[buglab_swap_variables]^return  ( InfoSetUtil.booleanValue ( r )  == InfoSetUtil.booleanValue ( l )  ) ;^130^^^^^115^145^return  ( InfoSetUtil.booleanValue ( l )  == InfoSetUtil.booleanValue ( r )  ) ;^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   Object l Object r [VARIABLES] boolean  Object  l  r  
[buglab_swap_variables]^return r.equals ( l ) ;^142^^^^^127^157^return l.equals ( r ) ;^[CLASS] CoreOperationCompare  [METHOD] equal [RETURN_TYPE] boolean   Object l Object r [VARIABLES] boolean  Object  l  r  
