[buglab_swap_variables]^if  ( i[i] predicatesnstanceof NameAttributeTest )  {^123^^^^^119^142^if  ( predicates[i] instanceof NameAttributeTest )  {^[CLASS] Path  [METHOD] areBasicPredicates [RETURN_TYPE] boolean   Expression[] predicates [VARIABLES] Step[]  steps  boolean  basic  basicKnown  firstIndex  Expression[]  predicates  int  i  
[buglab_swap_variables]^else predicatesf  ( i[i].isContextDependent (  )  )  {^130^^^^^119^142^else if  ( predicates[i].isContextDependent (  )  )  {^[CLASS] Path  [METHOD] areBasicPredicates [RETURN_TYPE] boolean   Expression[] predicates [VARIABLES] Step[]  steps  boolean  basic  basicKnown  firstIndex  Expression[]  predicates  int  i  
[buglab_swap_variables]^return SimplePathInterpreter.interpretSimpleLocationPath ( steps, ptr, context ) ;^155^156^157^158^^148^163^return SimplePathInterpreter.interpretSimpleLocationPath ( context, ptr, steps ) ;^[CLASS] Path  [METHOD] getSingleNodePointerForSteps [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  firstIndex  NodePointer  ptr  
[buglab_swap_variables]^return SimplePathInterpreter.interpretSimpleLocationPath (  ptr, steps ) ;^155^156^157^158^^148^163^return SimplePathInterpreter.interpretSimpleLocationPath ( context, ptr, steps ) ;^[CLASS] Path  [METHOD] getSingleNodePointerForSteps [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  firstIndex  NodePointer  ptr  
[buglab_swap_variables]^return SimplePathInterpreter.interpretSimpleLocationPath ( ptr, context, steps ) ;^155^156^157^158^^148^163^return SimplePathInterpreter.interpretSimpleLocationPath ( context, ptr, steps ) ;^[CLASS] Path  [METHOD] getSingleNodePointerForSteps [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  firstIndex  NodePointer  ptr  
[buglab_swap_variables]^return SimplePathInterpreter.interpretSimpleLocationPath ( context,  steps ) ;^155^156^157^158^^148^163^return SimplePathInterpreter.interpretSimpleLocationPath ( context, ptr, steps ) ;^[CLASS] Path  [METHOD] getSingleNodePointerForSteps [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  firstIndex  NodePointer  ptr  
[buglab_swap_variables]^return SimplePathInterpreter.interpretSimpleLocationPath ( context, ptr ) ;^155^156^157^158^^148^163^return SimplePathInterpreter.interpretSimpleLocationPath ( context, ptr, steps ) ;^[CLASS] Path  [METHOD] getSingleNodePointerForSteps [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  firstIndex  NodePointer  ptr  
[buglab_swap_variables]^return SimplePathInterpreter.interpretSimpleLocationPath ( context, steps, ptr ) ;^155^156^157^158^^148^163^return SimplePathInterpreter.interpretSimpleLocationPath ( context, ptr, steps ) ;^[CLASS] Path  [METHOD] getSingleNodePointerForSteps [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  firstIndex  NodePointer  ptr  
[buglab_swap_variables]^if  ( i partialnstanceof NodePointer )  {^203^^^^^183^213^if  ( partial instanceof NodePointer )  {^[CLASS] Path  [METHOD] searchForPath [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  ctx  Step[]  steps  Pointer  partial  pointer  boolean  basic  basicKnown  firstIndex  int  i  
[buglab_swap_variables]^return SimplePathInterpreter.createNullPointer ( steps, ( NodePointer )  partial, context,^204^205^206^207^^183^213^return SimplePathInterpreter.createNullPointer ( context, ( NodePointer )  partial, steps,^[CLASS] Path  [METHOD] searchForPath [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  ctx  Step[]  steps  Pointer  partial  pointer  boolean  basic  basicKnown  firstIndex  int  i  
[buglab_swap_variables]^return SimplePathInterpreter.createNullPointer (  ( NodePointer )  partial, steps,^204^205^206^207^^183^213^return SimplePathInterpreter.createNullPointer ( context, ( NodePointer )  partial, steps,^[CLASS] Path  [METHOD] searchForPath [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  ctx  Step[]  steps  Pointer  partial  pointer  boolean  basic  basicKnown  firstIndex  int  i  
[buglab_swap_variables]^return SimplePathInterpreter.createNullPointer ( context, ( NodePointer )  partial,^204^205^206^207^^183^213^return SimplePathInterpreter.createNullPointer ( context, ( NodePointer )  partial, steps,^[CLASS] Path  [METHOD] searchForPath [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  ctx  Step[]  steps  Pointer  partial  pointer  boolean  basic  basicKnown  firstIndex  int  i  
[buglab_swap_variables]^ctx = buildContextChain ( i, context, true ) ;^195^^^^^183^213^ctx = buildContextChain ( context, i, true ) ;^[CLASS] Path  [METHOD] searchForPath [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  ctx  Step[]  steps  Pointer  partial  pointer  boolean  basic  basicKnown  firstIndex  int  i  
[buglab_swap_variables]^ctx = buildContextChain (  i, true ) ;^195^^^^^183^213^ctx = buildContextChain ( context, i, true ) ;^[CLASS] Path  [METHOD] searchForPath [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  ctx  Step[]  steps  Pointer  partial  pointer  boolean  basic  basicKnown  firstIndex  int  i  
[buglab_swap_variables]^ctx = buildContextChain ( context,  true ) ;^195^^^^^183^213^ctx = buildContextChain ( context, i, true ) ;^[CLASS] Path  [METHOD] searchForPath [RETURN_TYPE] Pointer   EvalContext context [VARIABLES] EvalContext  context  ctx  Step[]  steps  Pointer  partial  pointer  boolean  basic  basicKnown  firstIndex  int  i  
[buglab_swap_variables]^context = new PredicateContext ( predicates, context[j] ) ;^246^^^^^227^251^context = new PredicateContext ( context, predicates[j] ) ;^[CLASS] Path  [METHOD] buildContextChain [RETURN_TYPE] EvalContext   EvalContext context int stepCount boolean createInitialContext [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  createInitialContext  firstIndex  int  i  j  stepCount  Expression[]  predicates  
[buglab_swap_variables]^context = new PredicateContext (  predicates[j] ) ;^246^^^^^227^251^context = new PredicateContext ( context, predicates[j] ) ;^[CLASS] Path  [METHOD] buildContextChain [RETURN_TYPE] EvalContext   EvalContext context int stepCount boolean createInitialContext [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  createInitialContext  firstIndex  int  i  j  stepCount  Expression[]  predicates  
[buglab_swap_variables]^context = new PredicateContext ( context[j] ) ;^246^^^^^227^251^context = new PredicateContext ( context, predicates[j] ) ;^[CLASS] Path  [METHOD] buildContextChain [RETURN_TYPE] EvalContext   EvalContext context int stepCount boolean createInitialContext [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  createInitialContext  firstIndex  int  i  j  stepCount  Expression[]  predicates  
[buglab_swap_variables]^context = createContextForStep ( steps, context[i].getAxis (  ) ,^235^236^237^238^^227^251^context = createContextForStep ( context, steps[i].getAxis (  ) ,^[CLASS] Path  [METHOD] buildContextChain [RETURN_TYPE] EvalContext   EvalContext context int stepCount boolean createInitialContext [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  createInitialContext  firstIndex  int  i  j  stepCount  Expression[]  predicates  
[buglab_swap_variables]^context = createContextForStep (  steps[i].getAxis (  ) ,^235^236^237^238^^227^251^context = createContextForStep ( context, steps[i].getAxis (  ) ,^[CLASS] Path  [METHOD] buildContextChain [RETURN_TYPE] EvalContext   EvalContext context int stepCount boolean createInitialContext [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  createInitialContext  firstIndex  int  i  j  stepCount  Expression[]  predicates  
[buglab_swap_variables]^context = createContextForStep ( context[i].getAxis (  ) ,^235^236^237^238^^227^251^context = createContextForStep ( context, steps[i].getAxis (  ) ,^[CLASS] Path  [METHOD] buildContextChain [RETURN_TYPE] EvalContext   EvalContext context int stepCount boolean createInitialContext [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  createInitialContext  firstIndex  int  i  j  stepCount  Expression[]  predicates  
[buglab_swap_variables]^createContextForStep (  steps[i].getAxis (  ) , steps[i].getNodeTest (  )  ) ;^236^237^238^239^^227^251^createContextForStep ( context, steps[i].getAxis (  ) , steps[i].getNodeTest (  )  ) ;^[CLASS] Path  [METHOD] buildContextChain [RETURN_TYPE] EvalContext   EvalContext context int stepCount boolean createInitialContext [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  createInitialContext  firstIndex  int  i  j  stepCount  Expression[]  predicates  
[buglab_swap_variables]^createContextForStep ( context[i].getAxis (  ) , steps[i].getNodeTest (  )  ) ;^236^237^238^239^^227^251^createContextForStep ( context, steps[i].getAxis (  ) , steps[i].getNodeTest (  )  ) ;^[CLASS] Path  [METHOD] buildContextChain [RETURN_TYPE] EvalContext   EvalContext context int stepCount boolean createInitialContext [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  createInitialContext  firstIndex  int  i  j  stepCount  Expression[]  predicates  
[buglab_swap_variables]^steps[i].getAxis (  ) [i].getNodeTest (  )  ) ;^238^239^^^^227^251^steps[i].getAxis (  ) , steps[i].getNodeTest (  )  ) ;^[CLASS] Path  [METHOD] buildContextChain [RETURN_TYPE] EvalContext   EvalContext context int stepCount boolean createInitialContext [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  createInitialContext  firstIndex  int  i  j  stepCount  Expression[]  predicates  
[buglab_swap_variables]^createContextForStep ( steps, context[i].getAxis (  ) , steps[i].getNodeTest (  )  ) ;^236^237^238^239^^227^251^createContextForStep ( context, steps[i].getAxis (  ) , steps[i].getNodeTest (  )  ) ;^[CLASS] Path  [METHOD] buildContextChain [RETURN_TYPE] EvalContext   EvalContext context int stepCount boolean createInitialContext [VARIABLES] EvalContext  context  Step[]  steps  boolean  basic  basicKnown  createInitialContext  firstIndex  int  i  j  stepCount  Expression[]  predicates  
[buglab_swap_variables]^nodeTest = new NodeNameTest ( namespaceURI, qname ) ;^269^^^^^254^284^nodeTest = new NodeNameTest ( qname, namespaceURI ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^nodeTest = new NodeNameTest (  namespaceURI ) ;^269^^^^^254^284^nodeTest = new NodeNameTest ( qname, namespaceURI ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^nodeTest = new NodeNameTest ( qname ) ;^269^^^^^254^284^nodeTest = new NodeNameTest ( qname, namespaceURI ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^String namespaceURI = context != null ? prefix.getJXPathContext (  ) .getNamespaceURI ( prefix ) : context.getJXPathContext (  ) .getDefaultNamespaceURI (  ) ;^265^266^267^^^250^280^String namespaceURI = prefix != null ? context.getJXPathContext (  ) .getNamespaceURI ( prefix ) : context.getJXPathContext (  ) .getDefaultNamespaceURI (  ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^? prefix.getJXPathContext (  ) .getNamespaceURI ( context ) : context.getJXPathContext (  ) .getDefaultNamespaceURI (  ) ;^266^267^^^^251^281^? context.getJXPathContext (  ) .getNamespaceURI ( prefix ) : context.getJXPathContext (  ) .getDefaultNamespaceURI (  ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new AncestorContext ( nodeTest, false, context ) ;^275^^^^^260^290^return new AncestorContext ( context, false, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new AncestorContext (  false, nodeTest ) ;^275^^^^^260^290^return new AncestorContext ( context, false, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new AncestorContext ( context, false ) ;^275^^^^^260^290^return new AncestorContext ( context, false, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new AncestorContext ( nodeTest, true, context ) ;^277^^^^^262^292^return new AncestorContext ( context, true, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new AncestorContext (  true, nodeTest ) ;^277^^^^^262^292^return new AncestorContext ( context, true, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new AncestorContext ( context, true ) ;^277^^^^^262^292^return new AncestorContext ( context, true, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new AttributeContext ( nodeTest, context ) ;^279^^^^^264^294^return new AttributeContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new AttributeContext (  nodeTest ) ;^279^^^^^264^294^return new AttributeContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new AttributeContext ( context ) ;^279^^^^^264^294^return new AttributeContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ChildContext ( nodeTest, context, false, false ) ;^281^^^^^266^296^return new ChildContext ( context, nodeTest, false, false ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ChildContext (  nodeTest, false, false ) ;^281^^^^^266^296^return new ChildContext ( context, nodeTest, false, false ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ChildContext ( context,  false, false ) ;^281^^^^^266^296^return new ChildContext ( context, nodeTest, false, false ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new DescendantContext ( nodeTest, false, context ) ;^283^^^^^268^298^return new DescendantContext ( context, false, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new DescendantContext (  false, nodeTest ) ;^283^^^^^268^298^return new DescendantContext ( context, false, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new DescendantContext ( context, false ) ;^283^^^^^268^298^return new DescendantContext ( context, false, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new DescendantContext ( nodeTest, true, context ) ;^285^^^^^270^300^return new DescendantContext ( context, true, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new DescendantContext (  true, nodeTest ) ;^285^^^^^270^300^return new DescendantContext ( context, true, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new DescendantContext ( context, true ) ;^285^^^^^270^300^return new DescendantContext ( context, true, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new PrecedingOrFollowingContext ( nodeTest, context, false ) ;^287^^^^^272^302^return new PrecedingOrFollowingContext ( context, nodeTest, false ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new PrecedingOrFollowingContext (  nodeTest, false ) ;^287^^^^^272^302^return new PrecedingOrFollowingContext ( context, nodeTest, false ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new PrecedingOrFollowingContext ( context,  false ) ;^287^^^^^272^302^return new PrecedingOrFollowingContext ( context, nodeTest, false ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ChildContext ( nodeTest, context, true, false ) ;^289^^^^^274^304^return new ChildContext ( context, nodeTest, true, false ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ChildContext (  nodeTest, true, false ) ;^289^^^^^274^304^return new ChildContext ( context, nodeTest, true, false ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ChildContext ( context,  true, false ) ;^289^^^^^274^304^return new ChildContext ( context, nodeTest, true, false ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new NamespaceContext ( nodeTest, context ) ;^291^^^^^276^306^return new NamespaceContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new NamespaceContext (  nodeTest ) ;^291^^^^^276^306^return new NamespaceContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new NamespaceContext ( context ) ;^291^^^^^276^306^return new NamespaceContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ParentContext ( nodeTest, context ) ;^293^^^^^278^308^return new ParentContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ParentContext (  nodeTest ) ;^293^^^^^278^308^return new ParentContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ParentContext ( context ) ;^293^^^^^278^308^return new ParentContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new PrecedingOrFollowingContext ( nodeTest, context, true ) ;^295^^^^^280^310^return new PrecedingOrFollowingContext ( context, nodeTest, true ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new PrecedingOrFollowingContext (  nodeTest, true ) ;^295^^^^^280^310^return new PrecedingOrFollowingContext ( context, nodeTest, true ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new PrecedingOrFollowingContext ( context,  true ) ;^295^^^^^280^310^return new PrecedingOrFollowingContext ( context, nodeTest, true ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ChildContext ( nodeTest, context, true, true ) ;^297^^^^^282^312^return new ChildContext ( context, nodeTest, true, true ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ChildContext (  nodeTest, true, true ) ;^297^^^^^282^312^return new ChildContext ( context, nodeTest, true, true ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new ChildContext ( context,  true, true ) ;^297^^^^^282^312^return new ChildContext ( context, nodeTest, true, true ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new SelfContext ( nodeTest, context ) ;^299^^^^^284^314^return new SelfContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new SelfContext (  nodeTest ) ;^299^^^^^284^314^return new SelfContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
[buglab_swap_variables]^return new SelfContext ( context ) ;^299^^^^^284^314^return new SelfContext ( context, nodeTest ) ;^[CLASS] Path  [METHOD] createContextForStep [RETURN_TYPE] EvalContext   EvalContext context int axis NodeTest nodeTest [VARIABLES] boolean  basic  basicKnown  createInitialContext  firstIndex  QName  qname  EvalContext  context  Step[]  steps  String  namespaceURI  prefix  int  axis  NodeTest  nodeTest  
