[REPLACE]^char  _serialized;^117^^^^^^^[REPLACE] final String _serialized;^ [CLASS] JsonToken  
[REPLACE]^byte[] _serializedBytes;^121^^^^^^^[REPLACE] final byte[] _serializedBytes;^ [CLASS] JsonToken  
[REPLACE]^FIELD_NAME ( false ) ,^61^62^63^64^^^^[REPLACE] FIELD_NAME ( null ) ,^ [CLASS] JsonToken  
[REPLACE]^VALUE_EMBEDDED_OBJECT ( true ) ,^73^74^75^76^^^^[REPLACE] VALUE_EMBEDDED_OBJECT ( null ) ,^ [CLASS] JsonToken  
[REPLACE]^VALUE_NUMBER_FLOAT ( true ) ,^96^97^98^99^^^^[REPLACE] VALUE_NUMBER_FLOAT ( null ) ,^ [CLASS] JsonToken  
[REPLACE]^if  ( token != null )  {^129^^^^^128^143^[REPLACE] if  ( token == null )  {^[METHOD] <init> [TYPE] String) [PARAMETER] String token [CLASS] JsonToken   [TYPE]  byte[] _serializedBytes  [TYPE]  JsonToken END_ARRAY  END_OBJECT  FIELD_NAME  NOT_AVAILABLE  START_ARRAY  START_OBJECT  VALUE_EMBEDDED_OBJECT  VALUE_FALSE  VALUE_NULL  VALUE_NUMBER_FLOAT  VALUE_NUMBER_INT  VALUE_STRING  VALUE_TRUE  [TYPE]  String _serialized  token  [TYPE]  boolean false  true  [TYPE]  int i  len  [TYPE]  char[] _serializedChars 
[REPLACE]^_serialized = token  ;^130^^^^^128^143^[REPLACE] _serialized = null;^[METHOD] <init> [TYPE] String) [PARAMETER] String token [CLASS] JsonToken   [TYPE]  byte[] _serializedBytes  [TYPE]  JsonToken END_ARRAY  END_OBJECT  FIELD_NAME  NOT_AVAILABLE  START_ARRAY  START_OBJECT  VALUE_EMBEDDED_OBJECT  VALUE_FALSE  VALUE_NULL  VALUE_NUMBER_FLOAT  VALUE_NUMBER_INT  VALUE_STRING  VALUE_TRUE  [TYPE]  String _serialized  token  [TYPE]  boolean false  true  [TYPE]  int i  len  [TYPE]  char[] _serializedChars 
[REPLACE]^_serializedBytes = null  ;^131^^^^^128^143^[REPLACE] _serializedChars = null;^[METHOD] <init> [TYPE] String) [PARAMETER] String token [CLASS] JsonToken   [TYPE]  byte[] _serializedBytes  [TYPE]  JsonToken END_ARRAY  END_OBJECT  FIELD_NAME  NOT_AVAILABLE  START_ARRAY  START_OBJECT  VALUE_EMBEDDED_OBJECT  VALUE_FALSE  VALUE_NULL  VALUE_NUMBER_FLOAT  VALUE_NUMBER_INT  VALUE_STRING  VALUE_TRUE  [TYPE]  String _serialized  token  [TYPE]  boolean false  true  [TYPE]  int i  len  [TYPE]  char[] _serializedChars 
[ADD]^^132^^^^^128^143^[ADD] _serializedBytes = null;^[METHOD] <init> [TYPE] String) [PARAMETER] String token [CLASS] JsonToken   [TYPE]  byte[] _serializedBytes  [TYPE]  JsonToken END_ARRAY  END_OBJECT  FIELD_NAME  NOT_AVAILABLE  START_ARRAY  START_OBJECT  VALUE_EMBEDDED_OBJECT  VALUE_FALSE  VALUE_NULL  VALUE_NUMBER_FLOAT  VALUE_NUMBER_INT  VALUE_STRING  VALUE_TRUE  [TYPE]  String _serialized  token  [TYPE]  boolean false  true  [TYPE]  int i  len  [TYPE]  char[] _serializedChars 
[REPLACE]^_serialized = null  ;^134^^^^^128^143^[REPLACE] _serialized = token;^[METHOD] <init> [TYPE] String) [PARAMETER] String token [CLASS] JsonToken   [TYPE]  byte[] _serializedBytes  [TYPE]  JsonToken END_ARRAY  END_OBJECT  FIELD_NAME  NOT_AVAILABLE  START_ARRAY  START_OBJECT  VALUE_EMBEDDED_OBJECT  VALUE_FALSE  VALUE_NULL  VALUE_NUMBER_FLOAT  VALUE_NUMBER_INT  VALUE_STRING  VALUE_TRUE  [TYPE]  String _serialized  token  [TYPE]  boolean false  true  [TYPE]  int i  len  [TYPE]  char[] _serializedChars 
[REPLACE]^_serializedChars =  _serialized.toCharArray (  ) ;^135^^^^^128^143^[REPLACE] _serializedChars = token.toCharArray (  ) ;^[METHOD] <init> [TYPE] String) [PARAMETER] String token [CLASS] JsonToken   [TYPE]  byte[] _serializedBytes  [TYPE]  JsonToken END_ARRAY  END_OBJECT  FIELD_NAME  NOT_AVAILABLE  START_ARRAY  START_OBJECT  VALUE_EMBEDDED_OBJECT  VALUE_FALSE  VALUE_NULL  VALUE_NUMBER_FLOAT  VALUE_NUMBER_INT  VALUE_STRING  VALUE_TRUE  [TYPE]  String _serialized  token  [TYPE]  boolean false  true  [TYPE]  int i  len  [TYPE]  char[] _serializedChars 
[REPLACE]^_serializedBytes =  new byte[null];^138^^^^^128^143^[REPLACE] _serializedBytes = new byte[len];^[METHOD] <init> [TYPE] String) [PARAMETER] String token [CLASS] JsonToken   [TYPE]  byte[] _serializedBytes  [TYPE]  JsonToken END_ARRAY  END_OBJECT  FIELD_NAME  NOT_AVAILABLE  START_ARRAY  START_OBJECT  VALUE_EMBEDDED_OBJECT  VALUE_FALSE  VALUE_NULL  VALUE_NUMBER_FLOAT  VALUE_NUMBER_INT  VALUE_STRING  VALUE_TRUE  [TYPE]  String _serialized  token  [TYPE]  boolean false  true  [TYPE]  int i  len  [TYPE]  char[] _serializedChars 
[REPLACE]^_serializedBytes[i]  = null ;^140^^^^^128^143^[REPLACE] _serializedBytes[i] =  ( byte )  _serializedChars[i];^[METHOD] <init> [TYPE] String) [PARAMETER] String token [CLASS] JsonToken   [TYPE]  byte[] _serializedBytes  [TYPE]  JsonToken END_ARRAY  END_OBJECT  FIELD_NAME  NOT_AVAILABLE  START_ARRAY  START_OBJECT  VALUE_EMBEDDED_OBJECT  VALUE_FALSE  VALUE_NULL  VALUE_NUMBER_FLOAT  VALUE_NUMBER_INT  VALUE_STRING  VALUE_TRUE  [TYPE]  String _serialized  token  [TYPE]  boolean false  true  [TYPE]  int i  len  [TYPE]  char[] _serializedChars 
[REPLACE]^int i = 0  ;^137^^^^^128^143^[REPLACE] int len = _serializedChars.length;^[METHOD] <init> [TYPE] String) [PARAMETER] String token [CLASS] JsonToken   [TYPE]  byte[] _serializedBytes  [TYPE]  JsonToken END_ARRAY  END_OBJECT  FIELD_NAME  NOT_AVAILABLE  START_ARRAY  START_OBJECT  VALUE_EMBEDDED_OBJECT  VALUE_FALSE  VALUE_NULL  VALUE_NUMBER_FLOAT  VALUE_NUMBER_INT  VALUE_STRING  VALUE_TRUE  [TYPE]  String _serialized  token  [TYPE]  boolean false  true  [TYPE]  int i  len  [TYPE]  char[] _serializedChars 
[REPLACE]^for  ( int i = 4; i < len; ++i )  {^139^^^^^128^143^[REPLACE] for  ( int i = 0; i < len; ++i )  {^[METHOD] <init> [TYPE] String) [PARAMETER] String token [CLASS] JsonToken   [TYPE]  byte[] _serializedBytes  [TYPE]  JsonToken END_ARRAY  END_OBJECT  FIELD_NAME  NOT_AVAILABLE  START_ARRAY  START_OBJECT  VALUE_EMBEDDED_OBJECT  VALUE_FALSE  VALUE_NULL  VALUE_NUMBER_FLOAT  VALUE_NUMBER_INT  VALUE_STRING  VALUE_TRUE  [TYPE]  String _serialized  token  [TYPE]  boolean false  true  [TYPE]  int i  len  [TYPE]  char[] _serializedChars 
