[BugLab_Argument_Swapping]^printList ( text, pw ) ;^138^^^^^137^139^printList ( pw, text ) ;^[CLASS] AbstractVisitor  [METHOD] print [RETURN_TYPE] void   PrintWriter pw [VARIABLES] StringBuffer  buf  List  text  String[]  OPCODES  TYPES  boolean  PrintWriter  pw  
[BugLab_Wrong_Operator]^if  ( c != '\n' )  {^151^^^^^147^174^if  ( c == '\n' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^if  ( c < '\n' )  {^151^^^^^147^174^if  ( c == '\n' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c <= '\r' )  {^153^^^^^147^174^} else if  ( c == '\r' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c != '\r' )  {^153^^^^^147^174^} else if  ( c == '\r' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c <= '\\' )  {^155^^^^^147^174^} else if  ( c == '\\' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c != '"' )  {^157^^^^^147^174^} else if  ( c == '"' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c < 0x20 && c > 0x7f )  {^159^^^^^147^174^} else if  ( c < 0x20 || c > 0x7f )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c <= 0x20 || c > 0x7f )  {^159^^^^^147^174^} else if  ( c < 0x20 || c > 0x7f )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c < 0x20 || c >= 0x7f )  {^159^^^^^147^174^} else if  ( c < 0x20 || c > 0x7f )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^if  ( c <= 0x10 )  {^161^^^^^147^174^if  ( c < 0x10 )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c <= 0x100 )  {^163^^^^^147^174^} else if  ( c < 0x100 )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c > 0x100 )  {^163^^^^^147^174^} else if  ( c < 0x100 )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c == 0x1000 )  {^165^^^^^147^174^} else if  ( c < 0x1000 )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c <= 0x1000 )  {^165^^^^^147^174^} else if  ( c < 0x1000 )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c > 0x1000 )  {^165^^^^^147^174^} else if  ( c < 0x1000 )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Literal]^buf.append ( Integer.toString ( c, 15 )  ) ;^168^^^^^147^174^buf.append ( Integer.toString ( c, 16 )  ) ;^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Literal]^buf.append ( Integer.toString ( c, 17 )  ) ;^168^^^^^147^174^buf.append ( Integer.toString ( c, 16 )  ) ;^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^if  ( c > 0x10 )  {^161^^^^^147^174^if  ( c < 0x10 )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Literal]^buf.append ( Integer.toString ( c,  )  ) ;^168^^^^^147^174^buf.append ( Integer.toString ( c, 16 )  ) ;^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Literal]^buf.append ( Integer.toString ( c, i )  ) ;^168^^^^^147^174^buf.append ( Integer.toString ( c, 16 )  ) ;^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c > 0x20 || c > 0x7f )  {^159^^^^^147^174^} else if  ( c < 0x20 || c > 0x7f )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c == 0x100 )  {^163^^^^^147^174^} else if  ( c < 0x100 )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^if  ( c == 0x10 )  {^161^^^^^147^174^if  ( c < 0x10 )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c < 0x20 || c == 0x7f )  {^159^^^^^147^174^} else if  ( c < 0x20 || c > 0x7f )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c >= '\\' )  {^155^^^^^147^174^} else if  ( c == '\\' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c != '\\' )  {^155^^^^^147^174^} else if  ( c == '\\' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c >= '"' )  {^157^^^^^147^174^} else if  ( c == '"' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c <= '"' )  {^157^^^^^147^174^} else if  ( c == '"' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c == 0x20 || c > 0x7f )  {^159^^^^^147^174^} else if  ( c < 0x20 || c > 0x7f )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c < '\r' )  {^153^^^^^147^174^} else if  ( c == '\r' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c > '\\' )  {^155^^^^^147^174^} else if  ( c == '\\' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c < 0x20 || c < 0x7f )  {^159^^^^^147^174^} else if  ( c < 0x20 || c > 0x7f )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c < '\\' )  {^155^^^^^147^174^} else if  ( c == '\\' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^for  ( int i = 0; i > s.length (  ) ; ++i )  {^149^^^^^147^174^for  ( int i = 0; i < s.length (  ) ; ++i )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^for  ( int i = 0; i <= s.length (  ) ; ++i )  {^149^^^^^147^174^for  ( int i = 0; i < s.length (  ) ; ++i )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Literal]^for  ( int i = i; i < s.length (  ) ; ++i )  {^149^^^^^147^174^for  ( int i = 0; i < s.length (  ) ; ++i )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^} else if  ( c >= '\r' )  {^153^^^^^147^174^} else if  ( c == '\r' )  {^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Argument_Swapping]^char c = i.charAt ( s ) ;^150^^^^^147^174^char c = s.charAt ( i ) ;^[CLASS] AbstractVisitor  [METHOD] appendString [RETURN_TYPE] void   StringBuffer buf String s [VARIABLES] StringBuffer  buf  boolean  char  c  List  text  String[]  OPCODES  TYPES  String  s  int  i  
[BugLab_Wrong_Operator]^if  ( o  >=  List )  {^186^^^^^183^192^if  ( o instanceof List )  {^[CLASS] AbstractVisitor  [METHOD] printList [RETURN_TYPE] void   PrintWriter pw List l [VARIABLES] StringBuffer  buf  boolean  List  l  text  Object  o  String[]  OPCODES  TYPES  int  i  PrintWriter  pw  
[BugLab_Variable_Misuse]^for  ( int i = 0; i < text.size (  ) ; ++i )  {^184^^^^^183^192^for  ( int i = 0; i < l.size (  ) ; ++i )  {^[CLASS] AbstractVisitor  [METHOD] printList [RETURN_TYPE] void   PrintWriter pw List l [VARIABLES] StringBuffer  buf  boolean  List  l  text  Object  o  String[]  OPCODES  TYPES  int  i  PrintWriter  pw  
[BugLab_Wrong_Operator]^for  ( int i = 0; i <= l.size (  ) ; ++i )  {^184^^^^^183^192^for  ( int i = 0; i < l.size (  ) ; ++i )  {^[CLASS] AbstractVisitor  [METHOD] printList [RETURN_TYPE] void   PrintWriter pw List l [VARIABLES] StringBuffer  buf  boolean  List  l  text  Object  o  String[]  OPCODES  TYPES  int  i  PrintWriter  pw  
[BugLab_Wrong_Operator]^if  ( o  ^  List )  {^186^^^^^183^192^if  ( o instanceof List )  {^[CLASS] AbstractVisitor  [METHOD] printList [RETURN_TYPE] void   PrintWriter pw List l [VARIABLES] StringBuffer  buf  boolean  List  l  text  Object  o  String[]  OPCODES  TYPES  int  i  PrintWriter  pw  
[BugLab_Variable_Misuse]^Object o = text.get ( i ) ;^185^^^^^183^192^Object o = l.get ( i ) ;^[CLASS] AbstractVisitor  [METHOD] printList [RETURN_TYPE] void   PrintWriter pw List l [VARIABLES] StringBuffer  buf  boolean  List  l  text  Object  o  String[]  OPCODES  TYPES  int  i  PrintWriter  pw  
[BugLab_Argument_Swapping]^Object o = i.get ( l ) ;^185^^^^^183^192^Object o = l.get ( i ) ;^[CLASS] AbstractVisitor  [METHOD] printList [RETURN_TYPE] void   PrintWriter pw List l [VARIABLES] StringBuffer  buf  boolean  List  l  text  Object  o  String[]  OPCODES  TYPES  int  i  PrintWriter  pw  
[BugLab_Wrong_Literal]^for  ( int i = i; i < l.size (  ) ; ++i )  {^184^^^^^183^192^for  ( int i = 0; i < l.size (  ) ; ++i )  {^[CLASS] AbstractVisitor  [METHOD] printList [RETURN_TYPE] void   PrintWriter pw List l [VARIABLES] StringBuffer  buf  boolean  List  l  text  Object  o  String[]  OPCODES  TYPES  int  i  PrintWriter  pw  
[BugLab_Wrong_Literal]^return new Attribute[-1];^200^^^^^199^201^return new Attribute[0];^[CLASS] AbstractVisitor  [METHOD] getDefaultAttributes [RETURN_TYPE] Attribute[]   [VARIABLES] StringBuffer  buf  List  l  text  String[]  OPCODES  TYPES  boolean  
