[REPLACE]^private float lowerBound;^70^^^^^^^[REPLACE] private double lowerBound;^ [CLASS] StandardDialRange  
[REPLACE]^private float increment;^78^^^^^^^[REPLACE] private double increment;^ [CLASS] StandardDialRange  
[REPLACE]^this ( 1.0d, 101.0d, Color.white ) ;^102^^^^^101^103^[REPLACE] this ( 0.0, 100.0, Color.white ) ;^[METHOD] <init> [TYPE] StandardDialRange() [PARAMETER] [CLASS] StandardDialRange   [TYPE]  double increment  innerRadius  lowerBound  outerRadius  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[ADD]^^102^^^^^101^103^[ADD] this ( 0.0, 100.0, Color.white ) ;^[METHOD] <init> [TYPE] StandardDialRange() [PARAMETER] [CLASS] StandardDialRange   [TYPE]  double increment  innerRadius  lowerBound  outerRadius  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^if  ( paint != null )  {^113^^^^^112^119^[REPLACE] if  ( paint == null )  {^[METHOD] <init> [TYPE] Paint) [PARAMETER] double lower double upper Paint paint [CLASS] StandardDialRange   [TYPE]  double increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^return ;^114^^^^^112^119^[REPLACE] throw new IllegalArgumentException  (" ")  ;^[METHOD] <init> [TYPE] Paint) [PARAMETER] double lower double upper Paint paint [CLASS] StandardDialRange   [TYPE]  double increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^this.upperBound = bound; ;^116^^^^^112^119^[REPLACE] this.lowerBound = lower;^[METHOD] <init> [TYPE] Paint) [PARAMETER] double lower double upper Paint paint [CLASS] StandardDialRange   [TYPE]  double increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^this.upperBound = bound; ;^117^^^^^112^119^[REPLACE] this.upperBound = upper;^[METHOD] <init> [TYPE] Paint) [PARAMETER] double lower double upper Paint paint [CLASS] StandardDialRange   [TYPE]  double increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^this.paint =  null;^118^^^^^112^119^[REPLACE] this.paint = paint;^[METHOD] <init> [TYPE] Paint) [PARAMETER] double lower double upper Paint paint [CLASS] StandardDialRange   [TYPE]  double increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^return this.upperBound;^129^^^^^128^130^[REPLACE] return this.lowerBound;^[METHOD] getLowerBound [TYPE] double [PARAMETER] [CLASS] StandardDialRange   [TYPE]  double increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^this.upperBound = bound; ;^141^^^^^139^143^[REPLACE] this.lowerBound = bound;^[METHOD] setLowerBound [TYPE] void [PARAMETER] double bound [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^return this.lowerBound;^153^^^^^152^154^[REPLACE] return this.upperBound;^[METHOD] getUpperBound [TYPE] double [PARAMETER] [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^this.lowerBound = lower; ;^165^^^^^163^167^[REPLACE] this.upperBound = bound;^[METHOD] setUpperBound [TYPE] void [PARAMETER] double bound [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^return this.outerRadius;^177^^^^^176^178^[REPLACE] return this.increment;^[METHOD] getIncrement [TYPE] double [PARAMETER] [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^this.increment =  upperBound;^189^^^^^187^191^[REPLACE] this.increment = increment;^[METHOD] setIncrement [TYPE] void [PARAMETER] double increment [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[ADD]^^190^191^^^^187^191^[ADD] notifyListeners ( new DialLayerChangeEvent ( this )  ) ; }^[METHOD] setIncrement [TYPE] void [PARAMETER] double increment [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^return this.outerRadius;^201^^^^^200^202^[REPLACE] return this.paint;^[METHOD] getPaint [TYPE] Paint [PARAMETER] [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^if  ( paint != null )  {^212^^^^^211^217^[REPLACE] if  ( paint == null )  {^[METHOD] setPaint [TYPE] void [PARAMETER] Paint paint [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[ADD]^^212^213^214^^^211^217^[ADD] if  ( paint == null )  { throw new IllegalArgumentException  (" ")  ; }^[METHOD] setPaint [TYPE] void [PARAMETER] Paint paint [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^return ;^213^^^^^211^217^[REPLACE] throw new IllegalArgumentException  (" ")  ;^[METHOD] setPaint [TYPE] void [PARAMETER] Paint paint [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^this.paint =  null;^215^^^^^211^217^[REPLACE] this.paint = paint;^[METHOD] setPaint [TYPE] void [PARAMETER] Paint paint [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^return this.outerRadius;^227^^^^^226^228^[REPLACE] return this.innerRadius;^[METHOD] getInnerRadius [TYPE] double [PARAMETER] [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^this.outerRadius = radius; ;^238^^^^^237^240^[REPLACE] this.innerRadius = radius;^[METHOD] setInnerRadius [TYPE] void [PARAMETER] double radius [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^return this.innerRadius;^250^^^^^249^251^[REPLACE] return this.outerRadius;^[METHOD] getOuterRadius [TYPE] double [PARAMETER] [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^this.innerRadius = radius; ;^261^^^^^260^263^[REPLACE] this.outerRadius = radius;^[METHOD] setOuterRadius [TYPE] void [PARAMETER] double radius [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[ADD]^^261^262^^^^260^263^[ADD] this.outerRadius = radius; notifyListeners ( new DialLayerChangeEvent ( this )  ) ;^[METHOD] setOuterRadius [TYPE] void [PARAMETER] double radius [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[ADD]^^262^263^^^^260^263^[ADD] notifyListeners ( new DialLayerChangeEvent ( this )  ) ; }^[METHOD] setOuterRadius [TYPE] void [PARAMETER] double radius [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^return false;^272^^^^^271^273^[REPLACE] return true;^[METHOD] isClippedToWindow [TYPE] boolean [PARAMETER] [CLASS] StandardDialRange   [TYPE]  double bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^Rectangle2D arcRectInner = DialPlot .getScaleForDataset ( this )  ;^286^287^^^^283^305^[REPLACE] Rectangle2D arcRectInner = DialPlot.rectangleByRadius ( frame, this.innerRadius, this.innerRadius ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[REPLACE]^Rectangle2D arcRectOuter = DialPlot.rectangleByRadius ( arcRectOuter, this.outerRadius, this.outerRadius ) ;^288^289^^^^283^305^[REPLACE] Rectangle2D arcRectOuter = DialPlot.rectangleByRadius ( frame, this.outerRadius, this.outerRadius ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[REPLACE]^DialScale scale = plot.getScaleForDataset ( 0L ) ;^292^^^^^283^305^[REPLACE] DialScale scale = plot.getScaleForDataset ( 0 ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[REPLACE]^double angleMax = scale.valueToAngle ( this.upperBound ) ;^293^^^^^283^305^[REPLACE] double angleMin = scale.valueToAngle ( this.lowerBound ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[REPLACE]^double angleMin = scale.valueToAngle ( this.lowerBound ) ;^294^^^^^283^305^[REPLACE] double angleMax = scale.valueToAngle ( this.upperBound ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[ADD]^^294^^^^^283^305^[ADD] double angleMax = scale.valueToAngle ( this.upperBound ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[REPLACE]^Arc2D arcInner = new Arc2D.Double ( arcRectInner, upper, upper - angleMin, Arc2D.OPEN ) ;^296^297^^^^283^305^[REPLACE] Arc2D arcInner = new Arc2D.Double ( arcRectInner, angleMin, angleMax - angleMin, Arc2D.OPEN ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[REPLACE]^Arc2D arcOuter = new Arc2D.Double ( arcRectOuter, angleMax, angleMin  ==  angleMax, Arc2D.OPEN ) ;^298^299^^^^283^305^[REPLACE] Arc2D arcOuter = new Arc2D.Double ( arcRectOuter, angleMax, angleMin - angleMax, Arc2D.OPEN ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[ADD]^^298^299^^^^283^305^[ADD] Arc2D arcOuter = new Arc2D.Double ( arcRectOuter, angleMax, angleMin - angleMax, Arc2D.OPEN ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[REPLACE]^g2 .setIncrement ( radius )  ;^301^^^^^283^305^[REPLACE] g2.setPaint ( this.paint ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[ADD]^g2.setStroke ( new BasicStroke ( 2.0f )  ) ;^301^302^^^^283^305^[ADD] g2.setPaint ( this.paint ) ; g2.setStroke ( new BasicStroke ( 2.0f )  ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[REPLACE]^g2.setPaint ( new BasicStroke ( 2.0f )  ) ;^302^^^^^283^305^[REPLACE] g2.setStroke ( new BasicStroke ( 2.0f )  ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[REPLACE]^g2.draw ( arcOuter ) ;^303^^^^^283^305^[REPLACE] g2.draw ( arcInner ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[REPLACE]^g2.setStroke ( arcOuter ) ;^304^^^^^283^305^[REPLACE] g2.draw ( arcOuter ) ;^[METHOD] draw [TYPE] void [PARAMETER] Graphics2D g2 DialPlot plot Rectangle2D frame Rectangle2D view [CLASS] StandardDialRange   [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Rectangle2D arcRectInner  arcRectOuter  frame  view  [TYPE]  DialScale scale  [TYPE]  Paint paint  [TYPE]  DialPlot plot  [TYPE]  Arc2D arcInner  arcOuter  [TYPE]  Graphics2D g2 
[REPLACE]^if  ( obj  ||  this )  {^315^^^^^314^341^[REPLACE] if  ( obj == this )  {^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^return false;^316^^^^^314^341^[REPLACE] return true;^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^if  ( ! ! ( obj instanceof StandardDialRange )  )  {^318^^^^^314^341^[REPLACE] if  ( ! ( obj instanceof StandardDialRange )  )  {^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^return true;^319^^^^^314^341^[REPLACE] return false;^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^Rectangle2D arcRectInner = DialPlot.rectangleByRadius ( frame, this.innerRadius, this.innerRadius ) ;^321^^^^^314^341^[REPLACE] StandardDialRange that =  ( StandardDialRange )  obj;^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[ADD]^^321^^^^^314^341^[ADD] StandardDialRange that =  ( StandardDialRange )  obj;^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^if  (upperBound  ==  that.lowerBound )  {^322^^^^^314^341^[REPLACE] if  ( this.lowerBound != that.lowerBound )  {^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^return true;^323^^^^^314^341^[REPLACE] return false;^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^if  ( this.upperBound  ==  that.upperBound )  {^325^^^^^314^341^[REPLACE] if  ( this.upperBound != that.upperBound )  {^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^return true;^326^^^^^314^341^[REPLACE] return false;^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^if  ( this.increment  ==  that.increment )  {^328^^^^^314^341^[REPLACE] if  ( this.increment != that.increment )  {^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^return true;^329^^^^^314^341^[REPLACE] return false;^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^if  ( !  this.paint, that.paint    )  {^331^^^^^314^341^[REPLACE] if  ( !PaintUtilities.equal ( this.paint, that.paint )  )  {^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^return true;^332^^^^^314^341^[REPLACE] return false;^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^if  (lower  ==  that.innerRadius )  {^334^^^^^314^341^[REPLACE] if  ( this.innerRadius != that.innerRadius )  {^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^return true;^335^^^^^314^341^[REPLACE] return false;^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^if  ( this.outerRadius  ==  that.outerRadius )  {^337^^^^^314^341^[REPLACE] if  ( this.outerRadius != that.outerRadius )  {^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[ADD]^^337^338^339^^^314^341^[ADD] if  ( this.outerRadius != that.outerRadius )  { return false; }^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^return true;^338^^^^^314^341^[REPLACE] return false;^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^return false;^340^^^^^314^341^[REPLACE] return true;^[METHOD] equals [TYPE] boolean [PARAMETER] Object obj [CLASS] StandardDialRange   [TYPE]  Object obj  [TYPE]  Paint paint  [TYPE]  StandardDialRange that  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^int result = 193 >>> 1;^349^^^^^348^362^[REPLACE] int result = 193;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^long temp =   this.increment   ;^350^^^^^348^362^[REPLACE] long temp = Double.doubleToLongBits ( this.increment ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^result = 2 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^351^^^^^348^362^[REPLACE] result = 37 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[ADD]^^351^^^^^348^362^[ADD] result = 37 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^temp = Double.doubleToLongBits ( this.outerRadius ) ; ;^352^^^^^348^362^[REPLACE] temp = Double.doubleToLongBits ( this.lowerBound ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[ADD]^^352^^^^^348^362^[ADD] temp = Double.doubleToLongBits ( this.lowerBound ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^result = 37L * result  !=   ( int )   ( temp ^  ( temp >>> 32 )  ) ;^353^^^^^348^362^[REPLACE] result = 37 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^temp = Double.doubleToLongBits ( this.lowerBound ) ; ;^354^^^^^348^362^[REPLACE] temp = Double.doubleToLongBits ( this.upperBound ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[ADD]^result = 37 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^354^355^^^^348^362^[ADD] temp = Double.doubleToLongBits ( this.upperBound ) ; result = 37 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^result = 4 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^355^^^^^348^362^[REPLACE] result = 37 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[ADD]^^355^^^^^348^362^[ADD] result = 37 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^temp = Double.doubleToLongBits ( this.lowerBound ) ; ;^356^^^^^348^362^[REPLACE] temp = Double.doubleToLongBits ( this.innerRadius ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^result = 2 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^357^^^^^348^362^[REPLACE] result = 37 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^temp = Double.doubleToLongBits ( this.lowerBound ) ; ;^358^^^^^348^362^[REPLACE] temp = Double.doubleToLongBits ( this.outerRadius ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^result = 37 * result  <   ( int )   ( temp ^  ( temp >>> 32 )  ) ;^359^^^^^348^362^[REPLACE] result = 37 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[ADD]^^359^360^^^^348^362^[ADD] result = 37 * result +  ( int )   ( temp ^  ( temp >>> 32 )  ) ; result = 37 * result + HashUtilities.hashCodeForPaint ( this.paint ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^result = 18 * result + HashUtilities.hashCodeForPaint ( this.paint ) ;^360^^^^^348^362^[REPLACE] result = 37 * result + HashUtilities.hashCodeForPaint ( this.paint ) ;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[ADD]^return result;^360^361^^^^348^362^[ADD] result = 37 * result + HashUtilities.hashCodeForPaint ( this.paint ) ; return result;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^return this.outerRadius;^361^^^^^348^362^[REPLACE] return result;^[METHOD] hashCode [TYPE] int [PARAMETER] [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  int result  [TYPE]  long temp 
[REPLACE]^return super .clone (  )  ;^373^^^^^372^374^[REPLACE] return super.clone (  ) ;^[METHOD] clone [TYPE] Object [PARAMETER] [CLASS] StandardDialRange   [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  Paint paint  [TYPE]  boolean false  true 
[REPLACE]^stream.defaultReadObject (  ) ;^384^^^^^383^386^[REPLACE] stream.defaultWriteObject (  ) ;^[METHOD] writeObject [TYPE] void [PARAMETER] ObjectOutputStream stream [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  ObjectOutputStream stream  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[ADD]^^384^385^^^^383^386^[ADD] stream.defaultWriteObject (  ) ; SerialUtilities.writePaint ( this.paint, stream ) ;^[METHOD] writeObject [TYPE] void [PARAMETER] ObjectOutputStream stream [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  ObjectOutputStream stream  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^SerialUtilities .readPaint ( null )  ;^385^^^^^383^386^[REPLACE] SerialUtilities.writePaint ( this.paint, stream ) ;^[METHOD] writeObject [TYPE] void [PARAMETER] ObjectOutputStream stream [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  ObjectOutputStream stream  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound 
[REPLACE]^stream.defaultWriteObject (  ) ;^398^^^^^396^400^[REPLACE] stream.defaultReadObject (  ) ;^[METHOD] readObject [TYPE] void [PARAMETER] ObjectInputStream stream [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  ObjectInputStream stream 
[ADD]^^398^399^^^^396^400^[ADD] stream.defaultReadObject (  ) ; this.paint = SerialUtilities.readPaint ( stream ) ;^[METHOD] readObject [TYPE] void [PARAMETER] ObjectInputStream stream [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  ObjectInputStream stream 
[REPLACE]^this.paint =  SerialUtilities.readPaint ( null ) ;^399^^^^^396^400^[REPLACE] this.paint = SerialUtilities.readPaint ( stream ) ;^[METHOD] readObject [TYPE] void [PARAMETER] ObjectInputStream stream [CLASS] StandardDialRange   [TYPE]  Paint paint  [TYPE]  boolean false  true  [TYPE]  double angleMax  angleMin  bound  increment  innerRadius  lower  lowerBound  outerRadius  radius  upper  upperBound  [TYPE]  ObjectInputStream stream 
