[P14_Delete_Statement]^^32^^^^^31^34^super (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext()   [VARIABLES] Number  value  boolean  
[P14_Delete_Statement]^^140^^^^^139^142^super (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue()   [VARIABLES] Number  value  boolean  
[P5_Replace_Variable]^value = value;^145^^^^^144^146^value = n;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] Number)   Number n [VARIABLES] Number  n  value  boolean  
[P8_Replace_Mix]^value =  null;^145^^^^^144^146^value = n;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] Number)   Number n [VARIABLES] Number  n  value  boolean  
[P4_Replace_Constructor]^value = value =  new Long ( l )  ;^149^^^^^148^150^value = new Double ( d ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(double)   double d [VARIABLES] Number  n  value  double  d  boolean  
[P8_Replace_Mix]^value =  new Double ( null ) ;^149^^^^^148^150^value = new Double ( d ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(double)   double d [VARIABLES] Number  n  value  double  d  boolean  
[P11_Insert_Donor_Statement]^value = new Integer ( i ) ;value = new Double ( d ) ;^149^^^^^148^150^value = new Double ( d ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(double)   double d [VARIABLES] Number  n  value  double  d  boolean  
[P11_Insert_Donor_Statement]^value = new Float ( f ) ;value = new Double ( d ) ;^149^^^^^148^150^value = new Double ( d ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(double)   double d [VARIABLES] Number  n  value  double  d  boolean  
[P11_Insert_Donor_Statement]^value = new Long ( l ) ;value = new Double ( d ) ;^149^^^^^148^150^value = new Double ( d ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(double)   double d [VARIABLES] Number  n  value  double  d  boolean  
[P4_Replace_Constructor]^value = value =  new Long ( l )  ;^153^^^^^152^154^value = new Float ( f ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(float)   float f [VARIABLES] Number  n  value  float  f  boolean  
[P8_Replace_Mix]^value =   new Long ( l )  ;^153^^^^^152^154^value = new Float ( f ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(float)   float f [VARIABLES] Number  n  value  float  f  boolean  
[P11_Insert_Donor_Statement]^value = new Integer ( i ) ;value = new Float ( f ) ;^153^^^^^152^154^value = new Float ( f ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(float)   float f [VARIABLES] Number  n  value  float  f  boolean  
[P11_Insert_Donor_Statement]^value = new Double ( d ) ;value = new Float ( f ) ;^153^^^^^152^154^value = new Float ( f ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(float)   float f [VARIABLES] Number  n  value  float  f  boolean  
[P11_Insert_Donor_Statement]^value = new Long ( l ) ;value = new Float ( f ) ;^153^^^^^152^154^value = new Float ( f ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(float)   float f [VARIABLES] Number  n  value  float  f  boolean  
[P4_Replace_Constructor]^value = value =  new Double ( d )  ;^157^^^^^156^158^value = new Integer ( i ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(int)   int i [VARIABLES] Number  n  value  int  i  boolean  
[P8_Replace_Mix]^value =   new Double ( d )  ;^157^^^^^156^158^value = new Integer ( i ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(int)   int i [VARIABLES] Number  n  value  int  i  boolean  
[P11_Insert_Donor_Statement]^value = new Double ( d ) ;value = new Integer ( i ) ;^157^^^^^156^158^value = new Integer ( i ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(int)   int i [VARIABLES] Number  n  value  int  i  boolean  
[P11_Insert_Donor_Statement]^value = new Float ( f ) ;value = new Integer ( i ) ;^157^^^^^156^158^value = new Integer ( i ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(int)   int i [VARIABLES] Number  n  value  int  i  boolean  
[P11_Insert_Donor_Statement]^value = new Long ( l ) ;value = new Integer ( i ) ;^157^^^^^156^158^value = new Integer ( i ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(int)   int i [VARIABLES] Number  n  value  int  i  boolean  
[P4_Replace_Constructor]^value = value =  new Float ( f )  ;^161^^^^^160^162^value = new Long ( l ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(long)   long l [VARIABLES] Number  n  value  long  l  boolean  
[P8_Replace_Mix]^value =  new Long ( null ) ;^161^^^^^160^162^value = new Long ( l ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(long)   long l [VARIABLES] Number  n  value  long  l  boolean  
[P11_Insert_Donor_Statement]^value = new Integer ( i ) ;value = new Long ( l ) ;^161^^^^^160^162^value = new Long ( l ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(long)   long l [VARIABLES] Number  n  value  long  l  boolean  
[P11_Insert_Donor_Statement]^value = new Double ( d ) ;value = new Long ( l ) ;^161^^^^^160^162^value = new Long ( l ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(long)   long l [VARIABLES] Number  n  value  long  l  boolean  
[P11_Insert_Donor_Statement]^value = new Float ( f ) ;value = new Long ( l ) ;^161^^^^^160^162^value = new Long ( l ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(long)   long l [VARIABLES] Number  n  value  long  l  boolean  
[P7_Replace_Invocation]^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .DefaultValue (  ) ;^41^^^^^39^42^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .doubleValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] doubleValue [RETURN_TYPE] double   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P14_Delete_Statement]^^41^^^^^39^42^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .doubleValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] doubleValue [RETURN_TYPE] double   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P7_Replace_Invocation]^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .DefaultValue (  ) ;^49^^^^^47^50^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .floatValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] floatValue [RETURN_TYPE] float   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P7_Replace_Invocation]^return  (  ( DefaultValue ) argument.evaluate ( this )  )  .longValue ( argument )  ;^49^^^^^47^50^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .floatValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] floatValue [RETURN_TYPE] float   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P14_Delete_Statement]^^49^^^^^47^50^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .floatValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] floatValue [RETURN_TYPE] float   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P7_Replace_Invocation]^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .DefaultValue (  ) ;^57^^^^^55^58^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .intValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] intValue [RETURN_TYPE] int   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P7_Replace_Invocation]^return  (  ( DefaultValue ) argument.evaluate ( this )  )  .longValue ( argument )  ;^57^^^^^55^58^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .intValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] intValue [RETURN_TYPE] int   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P14_Delete_Statement]^^57^^^^^55^58^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .intValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] intValue [RETURN_TYPE] int   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P7_Replace_Invocation]^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .DefaultValue (  ) ;^65^^^^^63^66^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .longValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] longValue [RETURN_TYPE] long   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P7_Replace_Invocation]^return  (  ( DefaultValue ) argument.evaluate ( this )  )  .floatValue ( argument )  ;^65^^^^^63^66^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .longValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] longValue [RETURN_TYPE] long   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P14_Delete_Statement]^^65^^^^^63^66^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .longValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] longValue [RETURN_TYPE] long   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P7_Replace_Invocation]^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .DefaultValue (  ) ;^73^^^^^71^74^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .shortValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] shortValue [RETURN_TYPE] short   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P8_Replace_Mix]^return  (  ( DefaultValue ) argument.evaluate ( this )  )  .floatValue ( argument )  ;^73^^^^^71^74^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .shortValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] shortValue [RETURN_TYPE] short   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P14_Delete_Statement]^^73^^^^^71^74^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .shortValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] shortValue [RETURN_TYPE] short   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P7_Replace_Invocation]^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .DefaultValue (  ) ;^81^^^^^79^82^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .byteValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] byteValue [RETURN_TYPE] byte   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P7_Replace_Invocation]^return  (  ( DefaultValue ) argument.evaluate ( this )  )  .intValue ( argument )  ;^81^^^^^79^82^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .byteValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] byteValue [RETURN_TYPE] byte   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P14_Delete_Statement]^^81^^^^^79^82^return  (  ( DefaultValue ) argument.evaluate ( this )  ) .byteValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] byteValue [RETURN_TYPE] byte   Evaluation argument [VARIABLES] Number  n  value  Evaluation  argument  boolean  
[P4_Replace_Constructor]^return return  new DefaultValue ( f )  ;^89^^^^^87^90^return new DefaultValue ( d ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   double d [VARIABLES] Number  n  value  double  d  boolean  
[P8_Replace_Mix]^return  new DefaultValue ( f )  ;^89^^^^^87^90^return new DefaultValue ( d ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   double d [VARIABLES] Number  n  value  double  d  boolean  
[P4_Replace_Constructor]^return return  new DefaultValue ( d )  ;^97^^^^^95^98^return new DefaultValue ( f ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   float f [VARIABLES] Number  n  value  float  f  boolean  
[P8_Replace_Mix]^return  new DefaultValue ( d )  ;^97^^^^^95^98^return new DefaultValue ( f ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   float f [VARIABLES] Number  n  value  float  f  boolean  
[P4_Replace_Constructor]^return return  new DefaultValue ( d )  ;^105^^^^^103^106^return new DefaultValue ( i ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   int i [VARIABLES] Number  n  value  int  i  boolean  
[P8_Replace_Mix]^return  new DefaultValue ( d )  ;^105^^^^^103^106^return new DefaultValue ( i ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   int i [VARIABLES] Number  n  value  int  i  boolean  
[P4_Replace_Constructor]^return return  new DefaultValue ( d )  ;^113^^^^^111^114^return new DefaultValue ( l ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   long l [VARIABLES] Number  n  value  long  l  boolean  
[P8_Replace_Mix]^return  new DefaultValue ( d )  ;^113^^^^^111^114^return new DefaultValue ( l ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   long l [VARIABLES] Number  n  value  long  l  boolean  
[P4_Replace_Constructor]^return return  new DefaultValue ( d )  ;^121^^^^^119^122^return new DefaultValue ( s ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   short s [VARIABLES] Number  n  value  short  s  boolean  
[P8_Replace_Mix]^return  new DefaultValue ( d )  ;^121^^^^^119^122^return new DefaultValue ( s ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   short s [VARIABLES] Number  n  value  short  s  boolean  
[P4_Replace_Constructor]^return return  new DefaultValue ( d )  ;^129^^^^^127^130^return new DefaultValue ( b ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   byte b [VARIABLES] Number  n  value  byte  b  boolean  
[P8_Replace_Mix]^return  new DefaultValue ( d )  ;^129^^^^^127^130^return new DefaultValue ( b ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   byte b [VARIABLES] Number  n  value  byte  b  boolean  
[P8_Replace_Mix]^return null;^169^^^^^167^170^return this;^[CLASS] DefaultContext DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   EvaluationContext context [VARIABLES] Number  n  value  EvaluationContext  context  boolean  
[P5_Replace_Variable]^return n.intValue (  ) ;^177^^^^^175^178^return value.intValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] intValue [RETURN_TYPE] int   [VARIABLES] Number  n  value  boolean  
[P7_Replace_Invocation]^return value.longValue (  ) ;^177^^^^^175^178^return value.intValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] intValue [RETURN_TYPE] int   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^177^^^^^175^178^return value.intValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] intValue [RETURN_TYPE] int   [VARIABLES] Number  n  value  boolean  
[P5_Replace_Variable]^return n.longValue (  ) ;^185^^^^^183^186^return value.longValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] longValue [RETURN_TYPE] long   [VARIABLES] Number  n  value  boolean  
[P7_Replace_Invocation]^return value.floatValue (  ) ;^185^^^^^183^186^return value.longValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] longValue [RETURN_TYPE] long   [VARIABLES] Number  n  value  boolean  
[P8_Replace_Mix]^return n.floatValue (  ) ;^185^^^^^183^186^return value.longValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] longValue [RETURN_TYPE] long   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^185^^^^^183^186^return value.longValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] longValue [RETURN_TYPE] long   [VARIABLES] Number  n  value  boolean  
[P5_Replace_Variable]^return n.floatValue (  ) ;^193^^^^^191^194^return value.floatValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] floatValue [RETURN_TYPE] float   [VARIABLES] Number  n  value  boolean  
[P7_Replace_Invocation]^return value.longValue (  ) ;^193^^^^^191^194^return value.floatValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] floatValue [RETURN_TYPE] float   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^193^^^^^191^194^return value.floatValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] floatValue [RETURN_TYPE] float   [VARIABLES] Number  n  value  boolean  
[P5_Replace_Variable]^return n.doubleValue (  ) ;^201^^^^^199^202^return value.doubleValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] doubleValue [RETURN_TYPE] double   [VARIABLES] Number  n  value  boolean  
[P7_Replace_Invocation]^return value.longValue (  ) ;^201^^^^^199^202^return value.doubleValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] doubleValue [RETURN_TYPE] double   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^201^^^^^199^202^return value.doubleValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] doubleValue [RETURN_TYPE] double   [VARIABLES] Number  n  value  boolean  
[P5_Replace_Variable]^return n.byteValue (  ) ;^209^^^^^207^210^return value.byteValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] byteValue [RETURN_TYPE] byte   [VARIABLES] Number  n  value  boolean  
[P7_Replace_Invocation]^return value.intValue (  ) ;^209^^^^^207^210^return value.byteValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] byteValue [RETURN_TYPE] byte   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^209^^^^^207^210^return value.byteValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] byteValue [RETURN_TYPE] byte   [VARIABLES] Number  n  value  boolean  
[P5_Replace_Variable]^return n.shortValue (  ) ;^217^^^^^215^218^return value.shortValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] shortValue [RETURN_TYPE] short   [VARIABLES] Number  n  value  boolean  
[P7_Replace_Invocation]^return value.floatValue (  ) ;^217^^^^^215^218^return value.shortValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] shortValue [RETURN_TYPE] short   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^217^^^^^215^218^return value.shortValue (  ) ;^[CLASS] DefaultContext DefaultValue  [METHOD] shortValue [RETURN_TYPE] short   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^140^^^^^139^142^super (  ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue()   [VARIABLES] Number  value  boolean  
[P8_Replace_Mix]^value =  null;^145^^^^^144^146^value = n;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] Number)   Number n [VARIABLES] Number  n  value  boolean  
[P4_Replace_Constructor]^value = value =  new Long ( l )  ;^149^^^^^148^150^value = new Double ( d ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(double)   double d [VARIABLES] Number  n  value  double  d  boolean  
[P8_Replace_Mix]^value =  new Double ( null ) ;^149^^^^^148^150^value = new Double ( d ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(double)   double d [VARIABLES] Number  n  value  double  d  boolean  
[P11_Insert_Donor_Statement]^value = new Integer ( i ) ;value = new Double ( d ) ;^149^^^^^148^150^value = new Double ( d ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(double)   double d [VARIABLES] Number  n  value  double  d  boolean  
[P11_Insert_Donor_Statement]^value = new Float ( f ) ;value = new Double ( d ) ;^149^^^^^148^150^value = new Double ( d ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(double)   double d [VARIABLES] Number  n  value  double  d  boolean  
[P11_Insert_Donor_Statement]^value = new Long ( l ) ;value = new Double ( d ) ;^149^^^^^148^150^value = new Double ( d ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(double)   double d [VARIABLES] Number  n  value  double  d  boolean  
[P4_Replace_Constructor]^value = value =  new Long ( l )  ;^153^^^^^152^154^value = new Float ( f ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(float)   float f [VARIABLES] Number  n  value  float  f  boolean  
[P8_Replace_Mix]^value =  new Float ( null ) ;^153^^^^^152^154^value = new Float ( f ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(float)   float f [VARIABLES] Number  n  value  float  f  boolean  
[P11_Insert_Donor_Statement]^value = new Integer ( i ) ;value = new Float ( f ) ;^153^^^^^152^154^value = new Float ( f ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(float)   float f [VARIABLES] Number  n  value  float  f  boolean  
[P11_Insert_Donor_Statement]^value = new Double ( d ) ;value = new Float ( f ) ;^153^^^^^152^154^value = new Float ( f ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(float)   float f [VARIABLES] Number  n  value  float  f  boolean  
[P11_Insert_Donor_Statement]^value = new Long ( l ) ;value = new Float ( f ) ;^153^^^^^152^154^value = new Float ( f ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(float)   float f [VARIABLES] Number  n  value  float  f  boolean  
[P4_Replace_Constructor]^value = value =  new Double ( d )  ;^157^^^^^156^158^value = new Integer ( i ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(int)   int i [VARIABLES] Number  n  value  int  i  boolean  
[P8_Replace_Mix]^value =  new Integer ( null ) ;^157^^^^^156^158^value = new Integer ( i ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(int)   int i [VARIABLES] Number  n  value  int  i  boolean  
[P11_Insert_Donor_Statement]^value = new Double ( d ) ;value = new Integer ( i ) ;^157^^^^^156^158^value = new Integer ( i ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(int)   int i [VARIABLES] Number  n  value  int  i  boolean  
[P11_Insert_Donor_Statement]^value = new Float ( f ) ;value = new Integer ( i ) ;^157^^^^^156^158^value = new Integer ( i ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(int)   int i [VARIABLES] Number  n  value  int  i  boolean  
[P11_Insert_Donor_Statement]^value = new Long ( l ) ;value = new Integer ( i ) ;^157^^^^^156^158^value = new Integer ( i ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(int)   int i [VARIABLES] Number  n  value  int  i  boolean  
[P4_Replace_Constructor]^value = value =  new Float ( f )  ;^161^^^^^160^162^value = new Long ( l ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(long)   long l [VARIABLES] Number  n  value  long  l  boolean  
[P8_Replace_Mix]^value =  new Long ( null ) ;^161^^^^^160^162^value = new Long ( l ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(long)   long l [VARIABLES] Number  n  value  long  l  boolean  
[P11_Insert_Donor_Statement]^value = new Integer ( i ) ;value = new Long ( l ) ;^161^^^^^160^162^value = new Long ( l ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(long)   long l [VARIABLES] Number  n  value  long  l  boolean  
[P11_Insert_Donor_Statement]^value = new Double ( d ) ;value = new Long ( l ) ;^161^^^^^160^162^value = new Long ( l ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(long)   long l [VARIABLES] Number  n  value  long  l  boolean  
[P11_Insert_Donor_Statement]^value = new Float ( f ) ;value = new Long ( l ) ;^161^^^^^160^162^value = new Long ( l ) ;^[CLASS] DefaultValue  [METHOD] <init> [RETURN_TYPE] DefaultContext$DefaultValue(long)   long l [VARIABLES] Number  n  value  long  l  boolean  
[P8_Replace_Mix]^return null;^169^^^^^167^170^return this;^[CLASS] DefaultValue  [METHOD] evaluate [RETURN_TYPE] Evaluation   EvaluationContext context [VARIABLES] Number  n  value  EvaluationContext  context  boolean  
[P7_Replace_Invocation]^return value.longValue (  ) ;^177^^^^^175^178^return value.intValue (  ) ;^[CLASS] DefaultValue  [METHOD] intValue [RETURN_TYPE] int   [VARIABLES] Number  n  value  boolean  
[P5_Replace_Variable]^return n.intValue (  ) ;^177^^^^^175^178^return value.intValue (  ) ;^[CLASS] DefaultValue  [METHOD] intValue [RETURN_TYPE] int   [VARIABLES] Number  n  value  boolean  
[P8_Replace_Mix]^return n.longValue (  ) ;^177^^^^^175^178^return value.intValue (  ) ;^[CLASS] DefaultValue  [METHOD] intValue [RETURN_TYPE] int   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^177^^^^^175^178^return value.intValue (  ) ;^[CLASS] DefaultValue  [METHOD] intValue [RETURN_TYPE] int   [VARIABLES] Number  n  value  boolean  
[P5_Replace_Variable]^return n.longValue (  ) ;^185^^^^^183^186^return value.longValue (  ) ;^[CLASS] DefaultValue  [METHOD] longValue [RETURN_TYPE] long   [VARIABLES] Number  n  value  boolean  
[P7_Replace_Invocation]^return value.floatValue (  ) ;^185^^^^^183^186^return value.longValue (  ) ;^[CLASS] DefaultValue  [METHOD] longValue [RETURN_TYPE] long   [VARIABLES] Number  n  value  boolean  
[P8_Replace_Mix]^return n.floatValue (  ) ;^185^^^^^183^186^return value.longValue (  ) ;^[CLASS] DefaultValue  [METHOD] longValue [RETURN_TYPE] long   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^185^^^^^183^186^return value.longValue (  ) ;^[CLASS] DefaultValue  [METHOD] longValue [RETURN_TYPE] long   [VARIABLES] Number  n  value  boolean  
[P5_Replace_Variable]^return n.floatValue (  ) ;^193^^^^^191^194^return value.floatValue (  ) ;^[CLASS] DefaultValue  [METHOD] floatValue [RETURN_TYPE] float   [VARIABLES] Number  n  value  boolean  
[P7_Replace_Invocation]^return value.longValue (  ) ;^193^^^^^191^194^return value.floatValue (  ) ;^[CLASS] DefaultValue  [METHOD] floatValue [RETURN_TYPE] float   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^193^^^^^191^194^return value.floatValue (  ) ;^[CLASS] DefaultValue  [METHOD] floatValue [RETURN_TYPE] float   [VARIABLES] Number  n  value  boolean  
[P5_Replace_Variable]^return n.doubleValue (  ) ;^201^^^^^199^202^return value.doubleValue (  ) ;^[CLASS] DefaultValue  [METHOD] doubleValue [RETURN_TYPE] double   [VARIABLES] Number  n  value  boolean  
[P7_Replace_Invocation]^return value.longValue (  ) ;^201^^^^^199^202^return value.doubleValue (  ) ;^[CLASS] DefaultValue  [METHOD] doubleValue [RETURN_TYPE] double   [VARIABLES] Number  n  value  boolean  
[P8_Replace_Mix]^return n.longValue (  ) ;^201^^^^^199^202^return value.doubleValue (  ) ;^[CLASS] DefaultValue  [METHOD] doubleValue [RETURN_TYPE] double   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^201^^^^^199^202^return value.doubleValue (  ) ;^[CLASS] DefaultValue  [METHOD] doubleValue [RETURN_TYPE] double   [VARIABLES] Number  n  value  boolean  
[P5_Replace_Variable]^return n.byteValue (  ) ;^209^^^^^207^210^return value.byteValue (  ) ;^[CLASS] DefaultValue  [METHOD] byteValue [RETURN_TYPE] byte   [VARIABLES] Number  n  value  boolean  
[P7_Replace_Invocation]^return value.intValue (  ) ;^209^^^^^207^210^return value.byteValue (  ) ;^[CLASS] DefaultValue  [METHOD] byteValue [RETURN_TYPE] byte   [VARIABLES] Number  n  value  boolean  
[P8_Replace_Mix]^return n.intValue (  ) ;^209^^^^^207^210^return value.byteValue (  ) ;^[CLASS] DefaultValue  [METHOD] byteValue [RETURN_TYPE] byte   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^209^^^^^207^210^return value.byteValue (  ) ;^[CLASS] DefaultValue  [METHOD] byteValue [RETURN_TYPE] byte   [VARIABLES] Number  n  value  boolean  
[P5_Replace_Variable]^return n.shortValue (  ) ;^217^^^^^215^218^return value.shortValue (  ) ;^[CLASS] DefaultValue  [METHOD] shortValue [RETURN_TYPE] short   [VARIABLES] Number  n  value  boolean  
[P7_Replace_Invocation]^return value.floatValue (  ) ;^217^^^^^215^218^return value.shortValue (  ) ;^[CLASS] DefaultValue  [METHOD] shortValue [RETURN_TYPE] short   [VARIABLES] Number  n  value  boolean  
[P8_Replace_Mix]^return n.floatValue (  ) ;^217^^^^^215^218^return value.shortValue (  ) ;^[CLASS] DefaultValue  [METHOD] shortValue [RETURN_TYPE] short   [VARIABLES] Number  n  value  boolean  
[P14_Delete_Statement]^^217^^^^^215^218^return value.shortValue (  ) ;^[CLASS] DefaultValue  [METHOD] shortValue [RETURN_TYPE] short   [VARIABLES] Number  n  value  boolean  
