[REPLACE]^private static final  short  serialVersionUID = 2606474895443431607L;^34^^^^^^^[REPLACE] private static final long serialVersionUID = 2606474895443431607L;^ [CLASS] NewtonSolver  
[REPLACE]^super ( f, 100, 1.0E-6 )  ;^79^^^^^77^100^[REPLACE] clearResult (  ) ;^[METHOD] solve [TYPE] double [PARAMETER] double min double max double startValue [CLASS] NewtonSolver   [TYPE]  UnivariateRealFunction derivative  [TYPE]  boolean false  true  [TYPE]  long serialVersionUID  [TYPE]  double max  min  startValue  x0  x1  [TYPE]  int i 
[ADD]^^79^^^^^77^100^[ADD] clearResult (  ) ;^[METHOD] solve [TYPE] double [PARAMETER] double min double max double startValue [CLASS] NewtonSolver   [TYPE]  UnivariateRealFunction derivative  [TYPE]  boolean false  true  [TYPE]  long serialVersionUID  [TYPE]  double max  min  startValue  x0  x1  [TYPE]  int i 
[REPLACE]^verifySequence ( min, max, max ) ;^80^^^^^77^100^[REPLACE] verifySequence ( min, startValue, max ) ;^[METHOD] solve [TYPE] double [PARAMETER] double min double max double startValue [CLASS] NewtonSolver   [TYPE]  UnivariateRealFunction derivative  [TYPE]  boolean false  true  [TYPE]  long serialVersionUID  [TYPE]  double max  min  startValue  x0  x1  [TYPE]  int i 
[REPLACE]^double x0 = max;^82^^^^^77^100^[REPLACE] double x0 = startValue;^[METHOD] solve [TYPE] double [PARAMETER] double min double max double startValue [CLASS] NewtonSolver   [TYPE]  UnivariateRealFunction derivative  [TYPE]  boolean false  true  [TYPE]  long serialVersionUID  [TYPE]  double max  min  startValue  x0  x1  [TYPE]  int i 
[ADD]^^83^^^^^77^100^[ADD] double x1;^[METHOD] solve [TYPE] double [PARAMETER] double min double max double startValue [CLASS] NewtonSolver   [TYPE]  UnivariateRealFunction derivative  [TYPE]  boolean false  true  [TYPE]  long serialVersionUID  [TYPE]  double max  min  startValue  x0  x1  [TYPE]  int i 
[REPLACE]^int i = 1;^85^^^^^77^100^[REPLACE] int i = 0;^[METHOD] solve [TYPE] double [PARAMETER] double min double max double startValue [CLASS] NewtonSolver   [TYPE]  UnivariateRealFunction derivative  [TYPE]  boolean false  true  [TYPE]  long serialVersionUID  [TYPE]  double max  min  startValue  x0  x1  [TYPE]  int i 
[REPLACE]^if  ( Math.abs ( x1 - x0 )   > x1 )  {^88^^^^^77^100^[REPLACE] if  ( Math.abs ( x1 - x0 )  <= absoluteAccuracy )  {^[METHOD] solve [TYPE] double [PARAMETER] double min double max double startValue [CLASS] NewtonSolver   [TYPE]  UnivariateRealFunction derivative  [TYPE]  boolean false  true  [TYPE]  long serialVersionUID  [TYPE]  double max  min  startValue  x0  x1  [TYPE]  int i 
[REPLACE]^return x0;^91^^^^^77^100^[REPLACE] return x1;^[METHOD] solve [TYPE] double [PARAMETER] double min double max double startValue [CLASS] NewtonSolver   [TYPE]  UnivariateRealFunction derivative  [TYPE]  boolean false  true  [TYPE]  long serialVersionUID  [TYPE]  double max  min  startValue  x0  x1  [TYPE]  int i 
[REPLACE]^x1 = x0   ( f.value ( x0 )  / derivative.value ( x0 )  ) ;^87^^^^^77^100^[REPLACE] x1 = x0 -  ( f.value ( x0 )  / derivative.value ( x0 )  ) ;^[METHOD] solve [TYPE] double [PARAMETER] double min double max double startValue [CLASS] NewtonSolver   [TYPE]  UnivariateRealFunction derivative  [TYPE]  boolean false  true  [TYPE]  long serialVersionUID  [TYPE]  double max  min  startValue  x0  x1  [TYPE]  int i 
[ADD]^^94^95^^^^77^100^[ADD] x0 = x1; ++i;^[METHOD] solve [TYPE] double [PARAMETER] double min double max double startValue [CLASS] NewtonSolver   [TYPE]  UnivariateRealFunction derivative  [TYPE]  boolean false  true  [TYPE]  long serialVersionUID  [TYPE]  double max  min  startValue  x0  x1  [TYPE]  int i 
[REPLACE]^return ;^98^99^^^^77^100^[REPLACE] throw new ConvergenceException ( "Maximum number of iterations exceeded " + i ) ;^[METHOD] solve [TYPE] double [PARAMETER] double min double max double startValue [CLASS] NewtonSolver   [TYPE]  UnivariateRealFunction derivative  [TYPE]  boolean false  true  [TYPE]  long serialVersionUID  [TYPE]  double max  min  startValue  x0  x1  [TYPE]  int i 
