[P14_Delete_Statement]^^21^^^^^20^28^Validate.notNull ( data ) ;^[CLASS] TokenQueue  [METHOD] <init> [RETURN_TYPE] String)   String data [VARIABLES] char  c  String  data  boolean  LinkedList  queue  char[]  chars  
[P8_Replace_Mix]^queue  =  queue ;^23^^^^^20^28^queue = new LinkedList<Character> (  ) ;^[CLASS] TokenQueue  [METHOD] <init> [RETURN_TYPE] String)   String data [VARIABLES] char  c  String  data  boolean  LinkedList  queue  char[]  chars  
[P1_Replace_Type]^queue = new  LinkedHashSet <Character> (  ) ;^23^^^^^20^28^queue = new LinkedList<Character> (  ) ;^[CLASS] TokenQueue  [METHOD] <init> [RETURN_TYPE] String)   String data [VARIABLES] char  c  String  data  boolean  LinkedList  queue  char[]  chars  
[P11_Insert_Donor_Statement]^char[] chars = seq.toCharArray (  ) ;char[] chars = data.toCharArray (  ) ;^24^^^^^20^28^char[] chars = data.toCharArray (  ) ;^[CLASS] TokenQueue  [METHOD] <init> [RETURN_TYPE] String)   String data [VARIABLES] char  c  String  data  boolean  LinkedList  queue  char[]  chars  
[P11_Insert_Donor_Statement]^char[] seqChars = seq.toCharArray (  ) ;char[] chars = data.toCharArray (  ) ;^24^^^^^20^28^char[] chars = data.toCharArray (  ) ;^[CLASS] TokenQueue  [METHOD] <init> [RETURN_TYPE] String)   String data [VARIABLES] char  c  String  data  boolean  LinkedList  queue  char[]  chars  
[P14_Delete_Statement]^^24^^^^^20^28^char[] chars = data.toCharArray (  ) ;^[CLASS] TokenQueue  [METHOD] <init> [RETURN_TYPE] String)   String data [VARIABLES] char  c  String  data  boolean  LinkedList  queue  char[]  chars  
[P1_Replace_Type]^for  ( int c : chars )  {^25^^^^^20^28^for  ( char c : chars )  {^[CLASS] TokenQueue  [METHOD] <init> [RETURN_TYPE] String)   String data [VARIABLES] char  c  String  data  boolean  LinkedList  queue  char[]  chars  
[P7_Replace_Invocation]^queue.addFirst ( c ) ;^26^^^^^20^28^queue.add ( c ) ;^[CLASS] TokenQueue  [METHOD] <init> [RETURN_TYPE] String)   String data [VARIABLES] char  c  String  data  boolean  LinkedList  queue  char[]  chars  
[P14_Delete_Statement]^^26^^^^^20^28^queue.add ( c ) ;^[CLASS] TokenQueue  [METHOD] <init> [RETURN_TYPE] String)   String data [VARIABLES] char  c  String  data  boolean  LinkedList  queue  char[]  chars  
[P11_Insert_Donor_Statement]^queue.addFirst ( c ) ;queue.add ( c ) ;^26^^^^^20^28^queue.add ( c ) ;^[CLASS] TokenQueue  [METHOD] <init> [RETURN_TYPE] String)   String data [VARIABLES] char  c  String  data  boolean  LinkedList  queue  char[]  chars  
[P11_Insert_Donor_Statement]^c = queue.peek (  ) ;queue.add ( c ) ;^26^^^^^20^28^queue.add ( c ) ;^[CLASS] TokenQueue  [METHOD] <init> [RETURN_TYPE] String)   String data [VARIABLES] char  c  String  data  boolean  LinkedList  queue  char[]  chars  
[P7_Replace_Invocation]^return queue.toString (  ) ;^35^^^^^34^36^return queue.isEmpty (  ) ;^[CLASS] TokenQueue  [METHOD] isEmpty [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P14_Delete_Statement]^^35^^^^^34^36^return queue.isEmpty (  ) ;^[CLASS] TokenQueue  [METHOD] isEmpty [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P7_Replace_Invocation]^return queue.size (  ) ;^43^^^^^42^44^return queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] peek [RETURN_TYPE] Character   [VARIABLES] LinkedList  queue  boolean  
[P7_Replace_Invocation]^return queue .removeFirst (  )  ;^43^^^^^42^44^return queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] peek [RETURN_TYPE] Character   [VARIABLES] LinkedList  queue  boolean  
[P14_Delete_Statement]^^43^^^^^42^44^return queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] peek [RETURN_TYPE] Character   [VARIABLES] LinkedList  queue  boolean  
[P7_Replace_Invocation]^queue.add ( c ) ;^51^^^^^50^52^queue.addFirst ( c ) ;^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   Character c [VARIABLES] Character  c  LinkedList  queue  boolean  
[P7_Replace_Invocation]^queue .removeFirst (  )  ;^51^^^^^50^52^queue.addFirst ( c ) ;^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   Character c [VARIABLES] Character  c  LinkedList  queue  boolean  
[P14_Delete_Statement]^^51^^^^^50^52^queue.addFirst ( c ) ;^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   Character c [VARIABLES] Character  c  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^queue.add ( c ) ;queue.addFirst ( c ) ;^51^^^^^50^52^queue.addFirst ( c ) ;^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   Character c [VARIABLES] Character  c  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^return queue.removeFirst (  ) ;queue.addFirst ( c ) ;^51^^^^^50^52^queue.addFirst ( c ) ;^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   Character c [VARIABLES] Character  c  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^char[] chars = data.toCharArray (  ) ;char[] chars = seq.toCharArray (  ) ;^59^^^^^58^63^char[] chars = seq.toCharArray (  ) ;^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P11_Insert_Donor_Statement]^char[] seqChars = seq.toCharArray (  ) ;char[] chars = seq.toCharArray (  ) ;^59^^^^^58^63^char[] chars = seq.toCharArray (  ) ;^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P14_Delete_Statement]^^59^^^^^58^63^char[] chars = seq.toCharArray (  ) ;^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P1_Replace_Type]^for  (  long  i = chars.length - 1; i >= 0; i-- )  {^60^^^^^58^63^for  ( int i = chars.length - 1; i >= 0; i-- )  {^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P2_Replace_Operator]^for  ( int i = chars.length  |  1; i >= 0; i-- )  {^60^^^^^58^63^for  ( int i = chars.length - 1; i >= 0; i-- )  {^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P2_Replace_Operator]^for  ( int i = chars.length - 1; i > 0; i-- )  {^60^^^^^58^63^for  ( int i = chars.length - 1; i >= 0; i-- )  {^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P3_Replace_Literal]^for  ( int i = chars.length - i; i >= 0; i-- )  {^60^^^^^58^63^for  ( int i = chars.length - 1; i >= 0; i-- )  {^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P3_Replace_Literal]^for  ( int i = chars.length - 1; i >= i; i-- )  {^60^^^^^58^63^for  ( int i = chars.length - 1; i >= 0; i-- )  {^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P5_Replace_Variable]^for  ( int i = chars.length.length - 1; i >= 0; i-- )  {^60^^^^^58^63^for  ( int i = chars.length - 1; i >= 0; i-- )  {^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P5_Replace_Variable]^for  ( chars.lengthnt i = i - 1; i >= 0; i-- )  {^60^^^^^58^63^for  ( int i = chars.length - 1; i >= 0; i-- )  {^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P14_Delete_Statement]^^61^^^^^58^63^addFirst ( chars[i] ) ;^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P1_Replace_Type]^for  (  short  i = chars.length - 1; i >= 0; i-- )  {^60^^^^^58^63^for  ( int i = chars.length - 1; i >= 0; i-- )  {^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P2_Replace_Operator]^for  ( int i = chars.length  >>  1; i >= 0; i-- )  {^60^^^^^58^63^for  ( int i = chars.length - 1; i >= 0; i-- )  {^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P5_Replace_Variable]^for  ( int i = chars - 1; i >= 0; i-- )  {^60^^^^^58^63^for  ( int i = chars.length - 1; i >= 0; i-- )  {^[CLASS] TokenQueue  [METHOD] addFirst [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  char[]  chars  
[P1_Replace_Type]^short  len = seq.length (  ) ;^71^^^^^70^83^int len = seq.length (  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^int len = seq.length() + 7 ;^71^^^^^70^83^int len = seq.length (  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^int len = seq.length() + 2 ;^71^^^^^70^83^int len = seq.length (  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P14_Delete_Statement]^^71^^^^^70^83^int len = seq.length (  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P2_Replace_Operator]^if  ( len >= queue.size (  )  ) return false;^72^73^^^^70^83^if  ( len > queue.size (  )  ) return false;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^if  ( len > queue.size (  )  ) return true;^72^73^^^^70^83^if  ( len > queue.size (  )  ) return false;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^if  ( len > queue.size() + 3  ) return false;^72^73^^^^70^83^if  ( len > queue.size (  )  ) return false;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P5_Replace_Variable]^if  ( i > queue.size (  )  ) return false;^72^73^^^^70^83^if  ( len > queue.size (  )  ) return false;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P5_Replace_Variable]^if  ( queue > len.size (  )  ) return false;^72^73^^^^70^83^if  ( len > queue.size (  )  ) return false;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P7_Replace_Invocation]^if  ( len > queue.peek (  )  ) return false;^72^73^^^^70^83^if  ( len > queue.size (  )  ) return false;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P7_Replace_Invocation]^if  ( len > queue .LinkedList (  )   ) return false;^72^73^^^^70^83^if  ( len > queue.size (  )  ) return false;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^return true;^73^^^^^70^83^return false;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^if  ( len > queue.size() + 6  ) return false;^72^73^^^^70^83^if  ( len > queue.size (  )  ) return false;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^List<Character> chars = queue.subList ( , len ) ;^74^^^^^70^83^List<Character> chars = queue.subList ( 0, len ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P5_Replace_Variable]^List<Character> chars = queue.subList ( 0, i ) ;^74^^^^^70^83^List<Character> chars = queue.subList ( 0, len ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P5_Replace_Variable]^List<Character> chars = this.subList ( 0, len ) ;^74^^^^^70^83^List<Character> chars = queue.subList ( 0, len ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P5_Replace_Variable]^List<Character> chars = queue.subList ( 0 ) ;^74^^^^^70^83^List<Character> chars = queue.subList ( 0, len ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P5_Replace_Variable]^List<Character> chars = len.subList ( 0, queue ) ;^74^^^^^70^83^List<Character> chars = queue.subList ( 0, len ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P11_Insert_Donor_Statement]^Character c = queue.peek (  ) ;List<Character> chars = queue.subList ( 0, len ) ;^74^^^^^70^83^List<Character> chars = queue.subList ( 0, len ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^List<Character> chars = queue.subList ( 4, len ) ;^74^^^^^70^83^List<Character> chars = queue.subList ( 0, len ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P14_Delete_Statement]^^74^^^^^70^83^List<Character> chars = queue.subList ( 0, len ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P11_Insert_Donor_Statement]^char[] chars = data.toCharArray (  ) ;char[] seqChars = seq.toCharArray (  ) ;^75^^^^^70^83^char[] seqChars = seq.toCharArray (  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P11_Insert_Donor_Statement]^char[] chars = seq.toCharArray (  ) ;char[] seqChars = seq.toCharArray (  ) ;^75^^^^^70^83^char[] seqChars = seq.toCharArray (  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P14_Delete_Statement]^^75^^^^^70^83^char[] seqChars = seq.toCharArray (  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^if  ( !found.equals ( check )  ) return true;^79^80^^^^70^83^if  ( !found.equals ( check )  ) return false;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P15_Unwrap_Block]^return false;^79^80^81^^^70^83^if  ( !found.equals ( check )  ) return false; }^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P16_Remove_Block]^^79^80^81^^^70^83^if  ( !found.equals ( check )  ) return false; }^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^return true;^80^^^^^70^83^return false;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P1_Replace_Type]^for  (  short  i = 0; i < len; i++ )  {^76^^^^^70^83^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P2_Replace_Operator]^for  ( int i = 0; i == len; i++ )  {^76^^^^^70^83^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^for  ( int i = -2; i < len; i++ )  {^76^^^^^70^83^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P5_Replace_Variable]^for  ( lennt i = 0; i < len; i++ )  {^76^^^^^70^83^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P5_Replace_Variable]^for  ( lennt i = 0; i < i; i++ )  {^76^^^^^70^83^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P5_Replace_Variable]^Character found = Character.toLowerCase ( chars.get ( len )  ) ;^77^^^^^70^83^Character found = Character.toLowerCase ( chars.get ( i )  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P5_Replace_Variable]^Character found = Character.toLowerCase ( i.get ( chars )  ) ;^77^^^^^70^83^Character found = Character.toLowerCase ( chars.get ( i )  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P7_Replace_Invocation]^Character found = Character .isWhitespace ( this )  ;^77^^^^^70^83^Character found = Character.toLowerCase ( chars.get ( i )  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P11_Insert_Donor_Statement]^Character found = Character.toLowerCase ( chars.get ( i )  ) ;Character check = Character.toLowerCase ( seqChars[i] ) ;^78^^^^^70^83^Character check = Character.toLowerCase ( seqChars[i] ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P14_Delete_Statement]^^77^78^^^^70^83^Character found = Character.toLowerCase ( chars.get ( i )  ) ; Character check = Character.toLowerCase ( seqChars[i] ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P11_Insert_Donor_Statement]^Character check = Character.toLowerCase ( seqChars[i] ) ;Character found = Character.toLowerCase ( chars.get ( i )  ) ;^77^^^^^70^83^Character found = Character.toLowerCase ( chars.get ( i )  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P8_Replace_Mix]^Character found = Character.toLowerCase ( 4.get ( i )  ) ;^77^^^^^70^83^Character found = Character.toLowerCase ( chars.get ( i )  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P7_Replace_Invocation]^Character check = Character .isWhitespace ( 3 )  ;^78^^^^^70^83^Character check = Character.toLowerCase ( seqChars[i] ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P14_Delete_Statement]^^78^^^^^70^83^Character check = Character.toLowerCase ( seqChars[i] ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P1_Replace_Type]^for  (  long  i = 0; i < len; i++ )  {^76^^^^^70^83^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P14_Delete_Statement]^^77^^^^^70^83^Character found = Character.toLowerCase ( chars.get ( i )  ) ;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^return false;^82^^^^^70^83^return true;^[CLASS] TokenQueue  [METHOD] matches [RETURN_TYPE] boolean   String seq [VARIABLES] boolean  Character  check  found  List  chars  String  seq  LinkedList  queue  int  i  len  char[]  seqChars  
[P3_Replace_Literal]^if  ( matches ( s )  ) return false;^92^93^^^^90^96^if  ( matches ( s )  ) return true;^[CLASS] TokenQueue  [METHOD] matchesAny [RETURN_TYPE] boolean    seq [VARIABLES] String[]  seq  String  s  boolean  LinkedList  queue  
[P7_Replace_Invocation]^if  ( matchesAny ( s )  ) return true;^92^93^^^^90^96^if  ( matches ( s )  ) return true;^[CLASS] TokenQueue  [METHOD] matchesAny [RETURN_TYPE] boolean    seq [VARIABLES] String[]  seq  String  s  boolean  LinkedList  queue  
[P15_Unwrap_Block]^return true;^92^93^94^^^90^96^if  ( matches ( s )  ) return true; }^[CLASS] TokenQueue  [METHOD] matchesAny [RETURN_TYPE] boolean    seq [VARIABLES] String[]  seq  String  s  boolean  LinkedList  queue  
[P16_Remove_Block]^^92^93^94^^^90^96^if  ( matches ( s )  ) return true; }^[CLASS] TokenQueue  [METHOD] matchesAny [RETURN_TYPE] boolean    seq [VARIABLES] String[]  seq  String  s  boolean  LinkedList  queue  
[P3_Replace_Literal]^return false;^93^^^^^90^96^return true;^[CLASS] TokenQueue  [METHOD] matchesAny [RETURN_TYPE] boolean    seq [VARIABLES] String[]  seq  String  s  boolean  LinkedList  queue  
[P1_Replace_Type]^for  ( char s : seq )  {^91^^^^^90^96^for  ( String s : seq )  {^[CLASS] TokenQueue  [METHOD] matchesAny [RETURN_TYPE] boolean    seq [VARIABLES] String[]  seq  String  s  boolean  LinkedList  queue  
[P3_Replace_Literal]^return true;^95^^^^^90^96^return false;^[CLASS] TokenQueue  [METHOD] matchesAny [RETURN_TYPE] boolean    seq [VARIABLES] String[]  seq  String  s  boolean  LinkedList  queue  
[P7_Replace_Invocation]^if  ( matchesAny ( seq )  )  {^105^^^^^104^111^if  ( matches ( seq )  )  {^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P15_Unwrap_Block]^consume(seq); return true;^105^106^107^108^109^104^111^if  ( matches ( seq )  )  { consume ( seq ) ; return true; } else { return false; }^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P16_Remove_Block]^^105^106^107^108^109^104^111^if  ( matches ( seq )  )  { consume ( seq ) ; return true; } else { return false; }^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P3_Replace_Literal]^return true;^109^^^^^104^111^return false;^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P3_Replace_Literal]^return false;^107^^^^^104^111^return true;^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P7_Replace_Invocation]^consumeTo ( seq ) ;^106^^^^^104^111^consume ( seq ) ;^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P14_Delete_Statement]^^106^107^^^^104^111^consume ( seq ) ; return true;^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P11_Insert_Donor_Statement]^String data = consumeTo ( seq ) ;consume ( seq ) ;^106^^^^^104^111^consume ( seq ) ;^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P11_Insert_Donor_Statement]^return consumeToAny ( seq ) ;consume ( seq ) ;^106^^^^^104^111^consume ( seq ) ;^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P11_Insert_Donor_Statement]^consume (  ) ;consume ( seq ) ;^106^^^^^104^111^consume ( seq ) ;^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P11_Insert_Donor_Statement]^matchChomp ( seq ) ;consume ( seq ) ;^106^^^^^104^111^consume ( seq ) ;^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P14_Delete_Statement]^^106^^^^^104^111^consume ( seq ) ;^[CLASS] TokenQueue  [METHOD] matchChomp [RETURN_TYPE] boolean   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P2_Replace_Operator]^return !queue.isEmpty (  )  || Character.isWhitespace ( queue.peek (  )  ) ;^118^^^^^117^119^return !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  ) ;^[CLASS] TokenQueue  [METHOD] matchesWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P7_Replace_Invocation]^return !queue.toString (  )  && Character.isWhitespace ( queue.peek (  )  ) ;^118^^^^^117^119^return !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  ) ;^[CLASS] TokenQueue  [METHOD] matchesWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P7_Replace_Invocation]^return !queue.isEmpty (  )  && Character.isWhitespace ( queue.size (  )  ) ;^118^^^^^117^119^return !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  ) ;^[CLASS] TokenQueue  [METHOD] matchesWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P7_Replace_Invocation]^return !queue.isEmpty (  )  && Character.isWhitespace ( queue .removeFirst (  )   ) ;^118^^^^^117^119^return !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  ) ;^[CLASS] TokenQueue  [METHOD] matchesWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P8_Replace_Mix]^return   Character.isWhitespace ( queue.peek (  )  ) ;^118^^^^^117^119^return !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  ) ;^[CLASS] TokenQueue  [METHOD] matchesWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P14_Delete_Statement]^^118^^^^^117^119^return !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  ) ;^[CLASS] TokenQueue  [METHOD] matchesWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P2_Replace_Operator]^return !queue.isEmpty (  )  || Character.isLetterOrDigit ( queue.peek (  )  ) ;^126^^^^^125^127^return !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  ) ;^[CLASS] TokenQueue  [METHOD] matchesWord [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P7_Replace_Invocation]^return !queue.toString (  )  && Character.isLetterOrDigit ( queue.peek (  )  ) ;^126^^^^^125^127^return !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  ) ;^[CLASS] TokenQueue  [METHOD] matchesWord [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P7_Replace_Invocation]^return !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.size (  )  ) ;^126^^^^^125^127^return !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  ) ;^[CLASS] TokenQueue  [METHOD] matchesWord [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P7_Replace_Invocation]^return !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue .removeFirst (  )   ) ;^126^^^^^125^127^return !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  ) ;^[CLASS] TokenQueue  [METHOD] matchesWord [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P14_Delete_Statement]^^126^^^^^125^127^return !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  ) ;^[CLASS] TokenQueue  [METHOD] matchesWord [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  
[P7_Replace_Invocation]^return queue.LinkedList (  ) ;^134^^^^^133^135^return queue.removeFirst (  ) ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] Character   [VARIABLES] LinkedList  queue  boolean  
[P14_Delete_Statement]^^134^^^^^133^135^return queue.removeFirst (  ) ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] Character   [VARIABLES] LinkedList  queue  boolean  
[P4_Replace_Constructor]^if  ( !matches ( seq )  ) throw if  ( !matches ( seq )  ) throw  new IllegalStateException ( "Queue not long enough to consume sequence" )   ;^145^146^^^^144^153^if  ( !matches ( seq )  ) throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P7_Replace_Invocation]^if  ( !matchesAny ( seq )  ) throw new IllegalStateException  (" ")  ;^145^146^^^^144^153^if  ( !matches ( seq )  ) throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P4_Replace_Constructor]^throw throw  new IllegalStateException ( "Queue not long enough to consume sequence" )   ;^146^^^^^144^153^throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P1_Replace_Type]^long  len = seq.length (  ) ;^147^^^^^144^153^int len = seq.length (  ) ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P3_Replace_Literal]^int len = seq.length() - 7 ;^147^^^^^144^153^int len = seq.length (  ) ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P3_Replace_Literal]^int len = seq.length() - 9 ;^147^^^^^144^153^int len = seq.length (  ) ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P14_Delete_Statement]^^147^^^^^144^153^int len = seq.length (  ) ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P2_Replace_Operator]^if  ( len == queue.size (  )  ) throw new IllegalStateException  (" ")  ;^148^149^^^^144^153^if  ( len > queue.size (  )  ) throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P3_Replace_Literal]^if  ( len > queue.size() + 6  ) throw new IllegalStateException  (" ")  ;^148^149^^^^144^153^if  ( len > queue.size (  )  ) throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P4_Replace_Constructor]^if  ( len > queue.size (  )  ) throw if  ( len > queue.size (  )  ) throw  new IllegalStateException ( "Queue did not match expected sequence" )   ;^148^149^^^^144^153^if  ( len > queue.size (  )  ) throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P5_Replace_Variable]^if  ( i > queue.size (  )  ) throw new IllegalStateException  (" ")  ;^148^149^^^^144^153^if  ( len > queue.size (  )  ) throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P5_Replace_Variable]^if  ( queue > len.size (  )  ) throw new IllegalStateException  (" ")  ;^148^149^^^^144^153^if  ( len > queue.size (  )  ) throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P7_Replace_Invocation]^if  ( len > queue.peek (  )  ) throw new IllegalStateException  (" ")  ;^148^149^^^^144^153^if  ( len > queue.size (  )  ) throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P15_Unwrap_Block]^throw new java.lang.IllegalStateException("Queue not long enough to consume sequence");^148^149^150^151^152^144^153^if  ( len > queue.size (  )  ) throw new IllegalStateException  (" ")  ; for  ( int i = 0; i < len; i++ )  { consume (  ) ; }^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P16_Remove_Block]^^148^149^150^151^152^144^153^if  ( len > queue.size (  )  ) throw new IllegalStateException  (" ")  ; for  ( int i = 0; i < len; i++ )  { consume (  ) ; }^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P4_Replace_Constructor]^throw throw  new IllegalStateException ( "Queue did not match expected sequence" )   ;^149^^^^^144^153^throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P8_Replace_Mix]^return true;^149^^^^^144^153^throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P3_Replace_Literal]^if  ( len > queue.size() + 3  ) throw new IllegalStateException  (" ")  ;^148^149^^^^144^153^if  ( len > queue.size (  )  ) throw new IllegalStateException  (" ")  ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P1_Replace_Type]^for  (  short  i = 0; i < len; i++ )  {^150^^^^^144^153^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P2_Replace_Operator]^for  ( int i = 0; i <= len; i++ )  {^150^^^^^144^153^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P3_Replace_Literal]^for  ( int i = 5; i < len; i++ )  {^150^^^^^144^153^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P5_Replace_Variable]^for  ( lennt i = 0; i < len; i++ )  {^150^^^^^144^153^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P5_Replace_Variable]^for  ( lennt i = 0; i < i; i++ )  {^150^^^^^144^153^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P14_Delete_Statement]^^151^^^^^144^153^consume (  ) ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P11_Insert_Donor_Statement]^consume ( seq ) ;consume (  ) ;^151^^^^^144^153^consume (  ) ;^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P3_Replace_Literal]^for  ( int i = i; i < len; i++ )  {^150^^^^^144^153^for  ( int i = 0; i < len; i++ )  {^[CLASS] TokenQueue  [METHOD] consume [RETURN_TYPE] void   String seq [VARIABLES] String  seq  boolean  LinkedList  queue  int  i  len  
[P7_Replace_Invocation]^return consumeTo ( seq ) ;^161^^^^^160^162^return consumeToAny ( seq ) ;^[CLASS] TokenQueue  [METHOD] consumeTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P14_Delete_Statement]^^161^^^^^160^162^return consumeToAny ( seq ) ;^[CLASS] TokenQueue  [METHOD] consumeTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  seq  boolean  
[P11_Insert_Donor_Statement]^StringBuilder wordAccum = new StringBuilder (  ) ;StringBuilder accum = new StringBuilder (  ) ;^170^^^^^169^175^StringBuilder accum = new StringBuilder (  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P2_Replace_Operator]^while  ( !queue.isEmpty (  )  || !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^171^172^^^^169^175^while  ( !queue.isEmpty (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P5_Replace_Variable]^while  ( !queue.isEmpty (  )  && !matchesAny ( accum )  ) seq.append ( consume (  )  ) ;^171^172^^^^169^175^while  ( !queue.isEmpty (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P7_Replace_Invocation]^while  ( !queue.toString (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^171^172^^^^169^175^while  ( !queue.isEmpty (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P7_Replace_Invocation]^while  ( !queue.isEmpty (  )  && !matches ( seq )  ) accum.append ( consume (  )  ) ;^171^172^^^^169^175^while  ( !queue.isEmpty (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P7_Replace_Invocation]^accum .StringBuilder (  )  ;^172^^^^^169^175^accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P14_Delete_Statement]^^172^^^^^169^175^accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P11_Insert_Donor_Statement]^wordAccum.append ( queue.removeFirst (  )  ) ;accum.append ( consume (  )  ) ;^172^^^^^169^175^accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P11_Insert_Donor_Statement]^accum.append ( queue.removeFirst (  )  ) ;accum.append ( consume (  )  ) ;^172^^^^^169^175^accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P14_Delete_Statement]^^171^172^^^^169^175^while  ( !queue.isEmpty (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P11_Insert_Donor_Statement]^while  ( !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  )  )  { consume (  ) ;while  ( !queue.isEmpty (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^171^172^^^^169^175^while  ( !queue.isEmpty (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P11_Insert_Donor_Statement]^while  ( !queue.isEmpty (  )  )  { accum.append ( consume (  )  ) ;while  ( !queue.isEmpty (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^171^172^^^^169^175^while  ( !queue.isEmpty (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P11_Insert_Donor_Statement]^while  ( !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  )  )  { wordAccum.append ( queue.removeFirst (  )  ) ;while  ( !queue.isEmpty (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^171^172^^^^169^175^while  ( !queue.isEmpty (  )  && !matchesAny ( seq )  ) accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P7_Replace_Invocation]^return accum.append (  ) ;^174^^^^^169^175^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P8_Replace_Mix]^return accum .StringBuilder (  )  ;^174^^^^^169^175^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P14_Delete_Statement]^^174^^^^^169^175^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeToAny [RETURN_TYPE] String    seq [VARIABLES] String[]  seq  boolean  StringBuilder  accum  LinkedList  queue  
[P1_Replace_Type]^char data = consumeTo ( seq ) ;^186^^^^^185^189^String data = consumeTo ( seq ) ;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P7_Replace_Invocation]^String data = consume ( seq ) ;^186^^^^^185^189^String data = consumeTo ( seq ) ;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P5_Replace_Variable]^String data = consumeTo ( data ) ;^186^^^^^185^189^String data = consumeTo ( seq ) ;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P8_Replace_Mix]^String data = consume ( data ) ;^186^^^^^185^189^String data = consumeTo ( seq ) ;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P14_Delete_Statement]^^186^^^^^185^189^String data = consumeTo ( seq ) ;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P11_Insert_Donor_Statement]^return consumeToAny ( seq ) ;String data = consumeTo ( seq ) ;^186^^^^^185^189^String data = consumeTo ( seq ) ;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P11_Insert_Donor_Statement]^consume ( seq ) ;String data = consumeTo ( seq ) ;^186^^^^^185^189^String data = consumeTo ( seq ) ;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P5_Replace_Variable]^matchChomp ( data ) ;^187^^^^^185^189^matchChomp ( seq ) ;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P7_Replace_Invocation]^matches ( seq ) ;^187^^^^^185^189^matchChomp ( seq ) ;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P14_Delete_Statement]^^187^^^^^185^189^matchChomp ( seq ) ;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P11_Insert_Donor_Statement]^consume ( seq ) ;matchChomp ( seq ) ;^187^^^^^185^189^matchChomp ( seq ) ;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P5_Replace_Variable]^return seq;^188^^^^^185^189^return data;^[CLASS] TokenQueue  [METHOD] chompTo [RETURN_TYPE] String   String seq [VARIABLES] LinkedList  queue  String  data  seq  boolean  
[P3_Replace_Literal]^boolean seen = true;^195^^^^^194^201^boolean seen = false;^[CLASS] TokenQueue  [METHOD] consumeWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  seen  
[P2_Replace_Operator]^while  ( !queue.isEmpty (  )  || Character.isWhitespace ( queue.peek (  )  )  )  {^196^^^^^194^201^while  ( !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  seen  
[P5_Replace_Variable]^while  ( !queue.isEmpty (  )  && Character.isWhitespace ( 1.peek (  )  )  )  {^196^^^^^194^201^while  ( !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  seen  
[P7_Replace_Invocation]^while  ( !queue.toString (  )  && Character.isWhitespace ( queue.peek (  )  )  )  {^196^^^^^194^201^while  ( !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  seen  
[P7_Replace_Invocation]^while  ( !queue.isEmpty (  )  && Character.isWhitespace ( queue.size (  )  )  )  {^196^^^^^194^201^while  ( !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  seen  
[P3_Replace_Literal]^seen = false;^198^^^^^194^201^seen = true;^[CLASS] TokenQueue  [METHOD] consumeWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  seen  
[P14_Delete_Statement]^^197^^^^^194^201^consume (  ) ;^[CLASS] TokenQueue  [METHOD] consumeWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  seen  
[P11_Insert_Donor_Statement]^consume ( seq ) ;consume (  ) ;^197^^^^^194^201^consume (  ) ;^[CLASS] TokenQueue  [METHOD] consumeWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  seen  
[P14_Delete_Statement]^^196^197^^^^194^201^while  ( !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  )  )  { consume (  ) ;^[CLASS] TokenQueue  [METHOD] consumeWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  seen  
[P8_Replace_Mix]^while  ( !queue.isEmpty (  )  && Character.isWhitespace ( queue .removeFirst (  )   )  )  {^196^^^^^194^201^while  ( !queue.isEmpty (  )  && Character.isWhitespace ( queue.peek (  )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  seen  
[P14_Delete_Statement]^^197^198^^^^194^201^consume (  ) ; seen = true;^[CLASS] TokenQueue  [METHOD] consumeWhitespace [RETURN_TYPE] boolean   [VARIABLES] LinkedList  queue  boolean  seen  
[P11_Insert_Donor_Statement]^StringBuilder accum = new StringBuilder (  ) ;StringBuilder wordAccum = new StringBuilder (  ) ;^208^^^^^207^213^StringBuilder wordAccum = new StringBuilder (  ) ;^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P2_Replace_Operator]^while  ( !queue.isEmpty (  )  || Character.isLetterOrDigit ( queue.peek (  )  )  )  {^209^^^^^207^213^while  ( !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^while  ( !queue.toString (  )  && Character.isLetterOrDigit ( queue.peek (  )  )  )  {^209^^^^^207^213^while  ( !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^while  ( !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.size (  )  )  )  {^209^^^^^207^213^while  ( !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^wordAccum.append ( queue.LinkedList (  )  ) ;^210^^^^^207^213^wordAccum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P14_Delete_Statement]^^210^^^^^207^213^wordAccum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^accum.append ( queue.removeFirst (  )  ) ;wordAccum.append ( queue.removeFirst (  )  ) ;^210^^^^^207^213^wordAccum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^accum.append ( consume (  )  ) ;wordAccum.append ( queue.removeFirst (  )  ) ;^210^^^^^207^213^wordAccum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^return queue.removeFirst (  ) ;wordAccum.append ( queue.removeFirst (  )  ) ;^210^^^^^207^213^wordAccum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P14_Delete_Statement]^^209^210^^^^207^213^while  ( !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  )  )  { wordAccum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^while  ( !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue .removeFirst (  )   )  )  {^209^^^^^207^213^while  ( !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P8_Replace_Mix]^while  ( !queue.isEmpty (  )  && Character .isWhitespace ( 2 )   )  {^209^^^^^207^213^while  ( !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P5_Replace_Variable]^while  ( !queue.isEmpty (  )  && Character.isLetterOrDigit ( 0.peek (  )  )  )  {^209^^^^^207^213^while  ( !queue.isEmpty (  )  && Character.isLetterOrDigit ( queue.peek (  )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^return wordAccum.append (  ) ;^212^^^^^207^213^return wordAccum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^return wordAccum .StringBuilder (  )  ;^212^^^^^207^213^return wordAccum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P14_Delete_Statement]^^212^^^^^207^213^return wordAccum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeWord [RETURN_TYPE] String   [VARIABLES] StringBuilder  wordAccum  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^StringBuilder wordAccum = new StringBuilder (  ) ;StringBuilder accum = new StringBuilder (  ) ;^221^^^^^220^228^StringBuilder accum = new StringBuilder (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P7_Replace_Invocation]^Character c = queue.size (  ) ;^222^^^^^220^228^Character c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^List<Character> chars = queue.subList ( 0, len ) ;Character c = queue.peek (  ) ;^222^^^^^220^228^Character c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P14_Delete_Statement]^^222^^^^^220^228^Character c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^c = queue.peek (  ) ;Character c = queue.peek (  ) ;^222^^^^^220^228^Character c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^return queue.peek (  ) ;Character c = queue.peek (  ) ;^222^^^^^220^228^Character c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P2_Replace_Operator]^while  ( !queue.isEmpty (  )  ||  ( Character.isLetterOrDigit ( c )  || c.equals ( '-' )  || c.equals ( '_' )  )  )  {^223^^^^^220^228^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( c )  || c.equals ( '-' )  || c.equals ( '_' )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P2_Replace_Operator]^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( c )  && c.equals ( '-' )  || c.equals ( '_' )  )  )  {^223^^^^^220^228^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( c )  || c.equals ( '-' )  || c.equals ( '_' )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P7_Replace_Invocation]^while  ( !queue.toString (  )  &&  ( Character.isLetterOrDigit ( c )  || c.equals ( '-' )  || c.equals ( '_' )  )  )  {^223^^^^^220^228^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( c )  || c.equals ( '-' )  || c.equals ( '_' )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P7_Replace_Invocation]^while  ( !queue.isEmpty (  )  &&  ( Character.isWhitespace ( c )  || c.equals ( '-' )  || c.equals ( '_' )  )  )  {^223^^^^^220^228^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( c )  || c.equals ( '-' )  || c.equals ( '_' )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P7_Replace_Invocation]^c = queue.size (  ) ;^225^^^^^220^228^c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P8_Replace_Mix]^c  = null ;^225^^^^^220^228^c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P7_Replace_Invocation]^accum.append ( queue.LinkedList (  )  ) ;^224^^^^^220^228^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P14_Delete_Statement]^^224^^^^^220^228^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^wordAccum.append ( queue.removeFirst (  )  ) ;accum.append ( queue.removeFirst (  )  ) ;^224^^^^^220^228^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^accum.append ( consume (  )  ) ;accum.append ( queue.removeFirst (  )  ) ;^224^^^^^220^228^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^return queue.removeFirst (  ) ;accum.append ( queue.removeFirst (  )  ) ;^224^^^^^220^228^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P14_Delete_Statement]^^224^225^^^^220^228^accum.append ( queue.removeFirst (  )  ) ; c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P7_Replace_Invocation]^c = queue .removeFirst (  )  ;^225^^^^^220^228^c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P14_Delete_Statement]^^225^^^^^220^228^c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^return queue.isEmpty (  ) ;c = queue.peek (  ) ;^225^^^^^220^228^c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^queue.add ( c ) ;c = queue.peek (  ) ;^225^^^^^220^228^c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^Character c = queue.peek (  ) ;c = queue.peek (  ) ;^225^^^^^220^228^c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^return queue.peek (  ) ;c = queue.peek (  ) ;^225^^^^^220^228^c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^return queue.removeFirst (  ) ;c = queue.peek (  ) ;^225^^^^^220^228^c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P5_Replace_Variable]^c = 2.peek (  ) ;^225^^^^^220^228^c = queue.peek (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P14_Delete_Statement]^^223^224^^^^220^228^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( c )  || c.equals ( '-' )  || c.equals ( '_' )  )  )  { accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P7_Replace_Invocation]^accum .StringBuilder (  )  ;^224^^^^^220^228^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P7_Replace_Invocation]^accum.append ( queue .addFirst ( 2 )   ) ;^224^^^^^220^228^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P8_Replace_Mix]^accum.append ( 3.LinkedList (  )  ) ;^224^^^^^220^228^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P7_Replace_Invocation]^return accum.append (  ) ;^227^^^^^220^228^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P7_Replace_Invocation]^return accum .StringBuilder (  )  ;^227^^^^^220^228^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P14_Delete_Statement]^^227^^^^^220^228^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeCssIdentifier [RETURN_TYPE] String   [VARIABLES] boolean  StringBuilder  accum  Character  c  LinkedList  queue  
[P11_Insert_Donor_Statement]^StringBuilder wordAccum = new StringBuilder (  ) ;StringBuilder accum = new StringBuilder (  ) ;^235^^^^^234^240^StringBuilder accum = new StringBuilder (  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P2_Replace_Operator]^while  ( !queue.isEmpty (  )  ||  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^236^^^^^234^240^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P2_Replace_Operator]^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  && matchesAny ( "-", "_", ":" )  )  )  {^236^^^^^234^240^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P3_Replace_Literal]^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "", "_", ":" )  )  )  {^236^^^^^234^240^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P3_Replace_Literal]^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "", ":" )  )  )  {^236^^^^^234^240^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P3_Replace_Literal]^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", "" )  )  )  {^236^^^^^234^240^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^while  ( !queue.toString (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^236^^^^^234^240^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.size (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^236^^^^^234^240^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^accum .StringBuilder (  )  ;^237^^^^^234^240^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^accum.append ( queue.LinkedList (  )  ) ;^237^^^^^234^240^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P14_Delete_Statement]^^237^^^^^234^240^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^wordAccum.append ( queue.removeFirst (  )  ) ;accum.append ( queue.removeFirst (  )  ) ;^237^^^^^234^240^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^accum.append ( consume (  )  ) ;accum.append ( queue.removeFirst (  )  ) ;^237^^^^^234^240^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^return queue.removeFirst (  ) ;accum.append ( queue.removeFirst (  )  ) ;^237^^^^^234^240^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P14_Delete_Statement]^^236^237^^^^234^240^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  { accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P5_Replace_Variable]^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( null.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^236^^^^^234^240^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue .removeFirst (  )   )  || matchesAny ( "-", "_", ":" )  )  )  {^236^^^^^234^240^while  ( !queue.isEmpty (  )  &&  ( Character.isLetterOrDigit ( queue.peek (  )  )  || matchesAny ( "-", "_", ":" )  )  )  {^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P8_Replace_Mix]^accum.append ( null.LinkedList (  )  ) ;^237^^^^^234^240^accum.append ( queue.removeFirst (  )  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^return accum.append (  ) ;^239^^^^^234^240^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^return accum .StringBuilder (  )  ;^239^^^^^234^240^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P14_Delete_Statement]^^239^^^^^234^240^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] consumeAttributeKey [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^StringBuilder wordAccum = new StringBuilder (  ) ;StringBuilder accum = new StringBuilder (  ) ;^247^^^^^246^252^StringBuilder accum = new StringBuilder (  ) ;^[CLASS] TokenQueue  [METHOD] remainder [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^while  ( !queue.toString (  )  )  {^248^^^^^246^252^while  ( !queue.isEmpty (  )  )  {^[CLASS] TokenQueue  [METHOD] remainder [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^accum .StringBuilder (  )  ;^249^^^^^246^252^accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] remainder [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P14_Delete_Statement]^^249^^^^^246^252^accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] remainder [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^wordAccum.append ( queue.removeFirst (  )  ) ;accum.append ( consume (  )  ) ;^249^^^^^246^252^accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] remainder [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P11_Insert_Donor_Statement]^accum.append ( queue.removeFirst (  )  ) ;accum.append ( consume (  )  ) ;^249^^^^^246^252^accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] remainder [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P14_Delete_Statement]^^248^249^^^^246^252^while  ( !queue.isEmpty (  )  )  { accum.append ( consume (  )  ) ;^[CLASS] TokenQueue  [METHOD] remainder [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^return accum.append (  ) ;^251^^^^^246^252^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] remainder [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^return accum .StringBuilder (  )  ;^251^^^^^246^252^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] remainder [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P14_Delete_Statement]^^251^^^^^246^252^return accum.toString (  ) ;^[CLASS] TokenQueue  [METHOD] remainder [RETURN_TYPE] String   [VARIABLES] StringBuilder  accum  LinkedList  queue  boolean  
[P7_Replace_Invocation]^return queue.isEmpty (  ) ;^255^^^^^254^256^return queue.toString (  ) ;^[CLASS] TokenQueue  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] LinkedList  queue  boolean  
[P8_Replace_Mix]^return queue .StringBuilder (  )  ;^255^^^^^254^256^return queue.toString (  ) ;^[CLASS] TokenQueue  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] LinkedList  queue  boolean  
[P14_Delete_Statement]^^255^^^^^254^256^return queue.toString (  ) ;^[CLASS] TokenQueue  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] LinkedList  queue  boolean  
