[REPLACE]^private  short  filterLimit;^30^^^^^^^[REPLACE] private long filterLimit;^ [CLASS] FilterHandler  
[REPLACE]^StringBuilder message = new StringBuilder (  )  ;^151^^^^^149^190^[REPLACE] StringBuilder filterType = new StringBuilder (  ) ;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^filterType.append ( "Static " )  ;^154^^^^^149^190^[REPLACE] filterType.append ( "Invalid " ) ;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^if  ( filterZero ( position  )  ||  (  ( filterType.length (  )  )  > 0 )  &&  ( ! ( filterLimit ( position )  )  )  )  )  {^156^^^^^149^190^[REPLACE] if  ( filterZero ( position )  )  {^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[ADD]^filterType.append ( "Zero " ) ;^156^157^158^^^149^190^[ADD] if  ( filterZero ( position )  )  { filterType.append ( "Zero " ) ; }^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^filterType.append ( "Future " )  ;^157^^^^^149^190^[REPLACE] filterType.append ( "Zero " ) ;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^filterType.append ( "Approximate " )  ;^160^^^^^149^190^[REPLACE] filterType.append ( "Duplicate " ) ;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[ADD]^^160^^^^^149^190^[ADD] filterType.append ( "Duplicate " ) ;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^if  (  (  ( filterType.length (  )  )  > 0 )  &&  ( ! ( filterLimit ( position )  )  )  || ( filterFuture ( position )  )  {^162^^^^^149^190^[REPLACE] if  ( filterFuture ( position )  )  {^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^filterType .StringBuilder (  )  ;^163^^^^^149^190^[REPLACE] filterType.append ( "Future " ) ;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^if  (  (  ( filterType.length (  )  )  > 0 )  &&  ( ! ( filterLimit ( position )  )  )  && ( filterApproximate ( position )  )  {^165^^^^^149^190^[REPLACE] if  ( filterApproximate ( position )  )  {^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^filterType.append ( "Duplicate " )  ;^166^^^^^149^190^[REPLACE] filterType.append ( "Approximate " ) ;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^if  ( filterStatic ( position  )  &&  (  ( filterType.length (  )  )  > 0 )  &&  ( ! ( filterLimit ( position )  )  )  )  )  {^168^^^^^149^190^[REPLACE] if  ( filterStatic ( position )  )  {^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^filterType.append ( "Distance " )  ;^169^^^^^149^190^[REPLACE] filterType.append ( "Static " ) ;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^if  ( filterDistance ( position  )  ||  (  ( filterType.length (  )  )  > 0 )  &&  ( ! ( filterLimit ( position )  )  )  )  )  {^171^^^^^149^190^[REPLACE] if  ( filterDistance ( position )  )  {^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[ADD]^^171^172^173^^^149^190^[ADD] if  ( filterDistance ( position )  )  { filterType.append ( "Distance " ) ; }^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^filterType.append ( "Static " )  ;^172^^^^^149^190^[REPLACE] filterType.append ( "Distance " ) ;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REMOVE]^filterType.append ( "Static " )  ;^172^^^^^149^190^[REMOVE] ^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^if  ( filterType.size (  )  > 0 && !filterLimit ( position )  )  {^175^^^^^149^190^[REPLACE] if  ( filterType.length (  )  > 0 && !filterLimit ( position )  )  {^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^return false;^186^^^^^149^190^[REPLACE] return true;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^StringBuilder filterType = new StringBuilder (  )  ;^177^^^^^149^190^[REPLACE] StringBuilder message = new StringBuilder (  ) ;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
[REPLACE]^return true;^189^^^^^149^190^[REPLACE] return false;^[METHOD] filter [TYPE] boolean [PARAMETER] Position position [CLASS] FilterHandler   [TYPE]  boolean false  filterApproximate  filterDuplicate  filterInvalid  filterStatic  filterZero  true  [TYPE]  StringBuilder filterType  message  [TYPE]  Position position  [TYPE]  int filterDistance  [TYPE]  long deviceId  filterFuture  filterLimit 
