[BugLab_Argument_Swapping]^return key.containsKey ( map ) ;^62^^^^^61^63^return map.containsKey ( key ) ;^[CLASS] TransformerMap  [METHOD] containsClass [RETURN_TYPE] boolean   Class key [VARIABLES] Class  key  boolean  Map  map  long  serialVersionUID  NumberTransformer  defaultTransformer  
[BugLab_Variable_Misuse]^return map.containsValue ( defaultTransformer ) ;^71^^^^^70^72^return map.containsValue ( value ) ;^[CLASS] TransformerMap  [METHOD] containsTransformer [RETURN_TYPE] boolean   NumberTransformer value [VARIABLES] boolean  Map  map  long  serialVersionUID  NumberTransformer  defaultTransformer  value  
[BugLab_Argument_Swapping]^return value.containsValue ( map ) ;^71^^^^^70^72^return map.containsValue ( value ) ;^[CLASS] TransformerMap  [METHOD] containsTransformer [RETURN_TYPE] boolean   NumberTransformer value [VARIABLES] boolean  Map  map  long  serialVersionUID  NumberTransformer  defaultTransformer  value  
[BugLab_Argument_Swapping]^return  ( NumberTransformer )  key.get ( map ) ;^81^^^^^80^82^return  ( NumberTransformer )  map.get ( key ) ;^[CLASS] TransformerMap  [METHOD] getTransformer [RETURN_TYPE] NumberTransformer   Class key [VARIABLES] Class  key  boolean  Map  map  long  serialVersionUID  NumberTransformer  defaultTransformer  value  
[BugLab_Variable_Misuse]^return map.put ( key, value ) ;^93^^^^^92^94^return map.put ( key, transformer ) ;^[CLASS] TransformerMap  [METHOD] putTransformer [RETURN_TYPE] Object   Class key NumberTransformer transformer [VARIABLES] Class  key  boolean  Map  map  long  serialVersionUID  NumberTransformer  defaultTransformer  transformer  value  
[BugLab_Argument_Swapping]^return key.put ( map, transformer ) ;^93^^^^^92^94^return map.put ( key, transformer ) ;^[CLASS] TransformerMap  [METHOD] putTransformer [RETURN_TYPE] Object   Class key NumberTransformer transformer [VARIABLES] Class  key  boolean  Map  map  long  serialVersionUID  NumberTransformer  defaultTransformer  transformer  value  
[BugLab_Argument_Swapping]^return transformer.put ( key, map ) ;^93^^^^^92^94^return map.put ( key, transformer ) ;^[CLASS] TransformerMap  [METHOD] putTransformer [RETURN_TYPE] Object   Class key NumberTransformer transformer [VARIABLES] Class  key  boolean  Map  map  long  serialVersionUID  NumberTransformer  defaultTransformer  transformer  value  
[BugLab_Argument_Swapping]^return map.put ( transformer, key ) ;^93^^^^^92^94^return map.put ( key, transformer ) ;^[CLASS] TransformerMap  [METHOD] putTransformer [RETURN_TYPE] Object   Class key NumberTransformer transformer [VARIABLES] Class  key  boolean  Map  map  long  serialVersionUID  NumberTransformer  defaultTransformer  transformer  value  
[BugLab_Argument_Swapping]^return key.remove ( map ) ;^103^^^^^102^104^return map.remove ( key ) ;^[CLASS] TransformerMap  [METHOD] removeTransformer [RETURN_TYPE] Object   Class key [VARIABLES] Class  key  boolean  Map  map  long  serialVersionUID  NumberTransformer  defaultTransformer  transformer  value  
[BugLab_Wrong_Operator]^if  ( o instanceof Number && o instanceof String )  {^139^^^^^136^149^if  ( o instanceof Number || o instanceof String )  {^[CLASS] TransformerMap  [METHOD] transform [RETURN_TYPE] double   Object o [VARIABLES] Object  o  boolean  Map  map  long  serialVersionUID  double  value  NumberTransformer  defaultTransformer  trans  transformer  value  
[BugLab_Wrong_Operator]^if  ( o  &  Number || o instanceof String )  {^139^^^^^136^149^if  ( o instanceof Number || o instanceof String )  {^[CLASS] TransformerMap  [METHOD] transform [RETURN_TYPE] double   Object o [VARIABLES] Object  o  boolean  Map  map  long  serialVersionUID  double  value  NumberTransformer  defaultTransformer  trans  transformer  value  
[BugLab_Wrong_Operator]^if  ( o instanceof Number || o  |  String )  {^139^^^^^136^149^if  ( o instanceof Number || o instanceof String )  {^[CLASS] TransformerMap  [METHOD] transform [RETURN_TYPE] double   Object o [VARIABLES] Object  o  boolean  Map  map  long  serialVersionUID  double  value  NumberTransformer  defaultTransformer  trans  transformer  value  
[BugLab_Variable_Misuse]^if  ( value != null )  {^143^^^^^136^149^if  ( trans != null )  {^[CLASS] TransformerMap  [METHOD] transform [RETURN_TYPE] double   Object o [VARIABLES] Object  o  boolean  Map  map  long  serialVersionUID  double  value  NumberTransformer  defaultTransformer  trans  transformer  value  
[BugLab_Wrong_Operator]^if  ( trans == null )  {^143^^^^^136^149^if  ( trans != null )  {^[CLASS] TransformerMap  [METHOD] transform [RETURN_TYPE] double   Object o [VARIABLES] Object  o  boolean  Map  map  long  serialVersionUID  double  value  NumberTransformer  defaultTransformer  trans  transformer  value  
[BugLab_Variable_Misuse]^value = value.transform ( o ) ;^144^^^^^136^149^value = trans.transform ( o ) ;^[CLASS] TransformerMap  [METHOD] transform [RETURN_TYPE] double   Object o [VARIABLES] Object  o  boolean  Map  map  long  serialVersionUID  double  value  NumberTransformer  defaultTransformer  trans  transformer  value  
[BugLab_Argument_Swapping]^value = o.transform ( trans ) ;^144^^^^^136^149^value = trans.transform ( o ) ;^[CLASS] TransformerMap  [METHOD] transform [RETURN_TYPE] double   Object o [VARIABLES] Object  o  boolean  Map  map  long  serialVersionUID  double  value  NumberTransformer  defaultTransformer  trans  transformer  value  
[BugLab_Variable_Misuse]^value = value.transform ( o ) ;^140^^^^^136^149^value = defaultTransformer.transform ( o ) ;^[CLASS] TransformerMap  [METHOD] transform [RETURN_TYPE] double   Object o [VARIABLES] Object  o  boolean  Map  map  long  serialVersionUID  double  value  NumberTransformer  defaultTransformer  trans  transformer  value  
[BugLab_Argument_Swapping]^value = o.transform ( defaultTransformer ) ;^140^^^^^136^149^value = defaultTransformer.transform ( o ) ;^[CLASS] TransformerMap  [METHOD] transform [RETURN_TYPE] double   Object o [VARIABLES] Object  o  boolean  Map  map  long  serialVersionUID  double  value  NumberTransformer  defaultTransformer  trans  transformer  value  
