[REPLACE]^private  RequestSpec spec;^46^^^^^^^[REPLACE] private final RequestSpec spec;^ [CLASS] RequestReceiver  
[REPLACE]^HeaderMapSpec paramsSpec = this.spec.getBodySpec (  ) ;^69^^^^^68^85^[REPLACE] HeaderMapSpec paramsSpec = this.spec.getHeadersSpec (  ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[ADD]^^70^^^^^68^85^[ADD] HeaderMap.Builder paramsBuilder = new HeaderMap.Builder ( paramsSpec ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^if  ( header != true || header.equals ( "" )  )  {^75^^^^^68^85^[REPLACE] if  ( header == null || header.equals ( "" )  )  {^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^header =  null.getParameter ( name ) ;^77^^^^^68^85^[REPLACE] header = request.getParameter ( name ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^if  ( header == this && !header.equals ( "" )  )  {^79^^^^^68^85^[REPLACE] if  ( header != null && !header.equals ( "" )  )  {^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[ADD]^Object value = gson.fromJson ( header, type ) ;paramsBuilder.put ( name, value ) ;^79^80^81^82^^68^85^[ADD] if  ( header != null && !header.equals ( "" )  )  { Object value = gson.fromJson ( header, type ) ; paramsBuilder.put ( name, value ) ; }^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^Builder paramsBuilder = new Builder ( paramsSpec )  ;^80^^^^^68^85^[REPLACE] Object value = gson.fromJson ( header, type ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[ADD]^^71^72^73^74^^68^85^[ADD] for  ( Map.Entry<String, Type> param : paramsSpec.entrySet (  )  )  { String name = param.getKey (  ) ; Type type = param.getValue (  ) ; String header = request.getHeader ( name ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^if  ( header != false ) {^75^^^^^68^85^[REPLACE] if  ( header == null || header.equals ( "" )  )  {^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^if  ( header == null && !header.equals ( "" )  )  {^79^^^^^68^85^[REPLACE] if  ( header != null && !header.equals ( "" )  )  {^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[ADD]^^79^80^81^82^^68^85^[ADD] if  ( header != null && !header.equals ( "" )  )  { Object value = gson.fromJson ( header, type ) ; paramsBuilder.put ( name, value ) ; }^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^String name = null.getKey (  ) ;^72^^^^^68^85^[REPLACE] String name = param.getKey (  ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[ADD]^^73^74^^^^68^85^[ADD] Type type = param.getValue (  ) ; String header = request.getHeader ( name ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^String header = request.getHeader ( header ) ;^74^^^^^68^85^[REPLACE] String header = request.getHeader ( name ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^Builder paramsBuilder = new Builder ( paramsSpec )  ;^71^^^^^68^85^[REPLACE] for  ( Map.Entry<String, Type> param : paramsSpec.entrySet (  )  )  {^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^String name = this.getKey (  ) ;^72^^^^^68^85^[REPLACE] String name = param.getKey (  ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^Type type = param .getKey (  )  ;^73^^^^^68^85^[REPLACE] Type type = param.getValue (  ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^Object value = gson.fromJson ( name, type ) ;^80^^^^^68^85^[REPLACE] Object value = gson.fromJson ( header, type ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
[REPLACE]^return paramsBuilder.build  (    )  ;  ;^84^^^^^68^85^[REPLACE] return paramsBuilder.build (  ) ;^[METHOD] buildRequestParams [TYPE] HeaderMap [PARAMETER] HttpServletRequest request [CLASS] RequestReceiver   [TYPE]  HttpServletRequest request  [TYPE]  Entry param  [TYPE]  Type type  [TYPE]  boolean false  true  [TYPE]  Builder paramsBuilder  [TYPE]  Gson gson  [TYPE]  Object value  [TYPE]  String header  name  [TYPE]  RequestSpec spec  [TYPE]  HeaderMapSpec paramsSpec 
