[BugLab_Variable_Misuse]^int size = findSize ( 0.size (  )  ) ;^19^^^^^17^29^int size = findSize ( serializers.size (  )  ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] <init> [RETURN_TYPE] Map)   Object>> serializers [VARIABLES] Entry  entry  boolean  Bucket[]  _buckets  buckets  Bucket  next  TypeKey  key  JsonSerializer  value  Map  serializers  int  _size  hashMask  index  size  
[BugLab_Variable_Misuse]^_size = index;^20^^^^^17^29^_size = size;^[CLASS] JsonSerializerMap Bucket  [METHOD] <init> [RETURN_TYPE] Map)   Object>> serializers [VARIABLES] Entry  entry  boolean  Bucket[]  _buckets  buckets  Bucket  next  TypeKey  key  JsonSerializer  value  Map  serializers  int  _size  hashMask  index  size  
[BugLab_Variable_Misuse]^int hashMask =  ( index-1 ) ;^21^^^^^17^29^int hashMask =  ( size-1 ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] <init> [RETURN_TYPE] Map)   Object>> serializers [VARIABLES] Entry  entry  boolean  Bucket[]  _buckets  buckets  Bucket  next  TypeKey  key  JsonSerializer  value  Map  serializers  int  _size  hashMask  index  size  
[BugLab_Wrong_Literal]^int hashMask =  ( size-index ) ;^21^^^^^17^29^int hashMask =  ( size-1 ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] <init> [RETURN_TYPE] Map)   Object>> serializers [VARIABLES] Entry  entry  boolean  Bucket[]  _buckets  buckets  Bucket  next  TypeKey  key  JsonSerializer  value  Map  serializers  int  _size  hashMask  index  size  
[BugLab_Variable_Misuse]^buckets[index] = new Bucket ( _buckets[index], key, entry.getValue (  )  ) ;^26^^^^^17^29^buckets[index] = new Bucket ( buckets[index], key, entry.getValue (  )  ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] <init> [RETURN_TYPE] Map)   Object>> serializers [VARIABLES] Entry  entry  boolean  Bucket[]  _buckets  buckets  Bucket  next  TypeKey  key  JsonSerializer  value  Map  serializers  int  _size  hashMask  index  size  
[BugLab_Argument_Swapping]^buckets[index] = new Bucket ( key[index], buckets, entry.getValue (  )  ) ;^26^^^^^17^29^buckets[index] = new Bucket ( buckets[index], key, entry.getValue (  )  ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] <init> [RETURN_TYPE] Map)   Object>> serializers [VARIABLES] Entry  entry  boolean  Bucket[]  _buckets  buckets  Bucket  next  TypeKey  key  JsonSerializer  value  Map  serializers  int  _size  hashMask  index  size  
[BugLab_Argument_Swapping]^buckets[index] = new Bucket ( buckets[index], entry, key.getValue (  )  ) ;^26^^^^^17^29^buckets[index] = new Bucket ( buckets[index], key, entry.getValue (  )  ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] <init> [RETURN_TYPE] Map)   Object>> serializers [VARIABLES] Entry  entry  boolean  Bucket[]  _buckets  buckets  Bucket  next  TypeKey  key  JsonSerializer  value  Map  serializers  int  _size  hashMask  index  size  
[BugLab_Variable_Misuse]^int index = key.hashCode (  )  & size;^25^^^^^17^29^int index = key.hashCode (  )  & hashMask;^[CLASS] JsonSerializerMap Bucket  [METHOD] <init> [RETURN_TYPE] Map)   Object>> serializers [VARIABLES] Entry  entry  boolean  Bucket[]  _buckets  buckets  Bucket  next  TypeKey  key  JsonSerializer  value  Map  serializers  int  _size  hashMask  index  size  
[BugLab_Argument_Swapping]^int index = hashMask.hashCode (  )  & key;^25^^^^^17^29^int index = key.hashCode (  )  & hashMask;^[CLASS] JsonSerializerMap Bucket  [METHOD] <init> [RETURN_TYPE] Map)   Object>> serializers [VARIABLES] Entry  entry  boolean  Bucket[]  _buckets  buckets  Bucket  next  TypeKey  key  JsonSerializer  value  Map  serializers  int  _size  hashMask  index  size  
[BugLab_Wrong_Operator]^int index = key.hashCode (  )   ||  hashMask;^25^^^^^17^29^int index = key.hashCode (  )  & hashMask;^[CLASS] JsonSerializerMap Bucket  [METHOD] <init> [RETURN_TYPE] Map)   Object>> serializers [VARIABLES] Entry  entry  boolean  Bucket[]  _buckets  buckets  Bucket  next  TypeKey  key  JsonSerializer  value  Map  serializers  int  _size  hashMask  index  size  
[BugLab_Variable_Misuse]^_buckets = _buckets;^28^^^^^17^29^_buckets = buckets;^[CLASS] JsonSerializerMap Bucket  [METHOD] <init> [RETURN_TYPE] Map)   Object>> serializers [VARIABLES] Entry  entry  boolean  Bucket[]  _buckets  buckets  Bucket  next  TypeKey  key  JsonSerializer  value  Map  serializers  int  _size  hashMask  index  size  
[BugLab_Wrong_Operator]^int needed =  ( size > 64 )  ?  ( size + size )  :  ( size +  ( size >> 2 )  ) ;^34^^^^^31^40^int needed =  ( size <= 64 )  ?  ( size + size )  :  ( size +  ( size >> 2 )  ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Wrong_Operator]^int needed =  ( size <= 64 )  ?  ( size  >  size )  :  ( size +  ( size >> 2 )  ) ;^34^^^^^31^40^int needed =  ( size <= 64 )  ?  ( size + size )  :  ( size +  ( size >> 2 )  ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Wrong_Operator]^int needed =  &  ( size <= 64 )  ?  ( size + size )  :  ( size +  ( size >> 2 )  ) ;^34^^^^^31^40^int needed =  ( size <= 64 )  ?  ( size + size )  :  ( size +  ( size >> 2 )  ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Wrong_Operator]^int needed =  ( size <= 64 )  ?  ( size + size )  :  ( size +  ( size  <  2 )  ) ;^34^^^^^31^40^int needed =  ( size <= 64 )  ?  ( size + size )  :  ( size +  ( size >> 2 )  ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Wrong_Literal]^int needed =  ( size <= 63 )  ?  ( size + size )  :  ( size +  ( size >> 2 )  ) ;^34^^^^^31^40^int needed =  ( size <= 64 )  ?  ( size + size )  :  ( size +  ( size >> 2 )  ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Wrong_Literal]^int result = _size;^35^^^^^31^40^int result = 8;^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^while  ( size < needed )  {^36^^^^^31^40^while  ( result < needed )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^while  ( result < size )  {^36^^^^^31^40^while  ( result < needed )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^while  ( needed < result )  {^36^^^^^31^40^while  ( result < needed )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Wrong_Operator]^while  ( result <= needed )  {^36^^^^^31^40^while  ( result < needed )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^result += needed;^37^^^^^31^40^result += result;^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^return size;^39^^^^^31^40^return result;^[CLASS] JsonSerializerMap Bucket  [METHOD] findSize [RETURN_TYPE] int   int size [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^public int size (  )  { return result; }^48^^^^^43^53^public int size (  )  { return _size; }^[CLASS] JsonSerializerMap Bucket  [METHOD] size [RETURN_TYPE] int   [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^int index = key.hashCode (  )  &  ( size-1 ) ;^52^^^^^50^70^int index = key.hashCode (  )  &  ( _buckets.length-1 ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^int index = key.hashCode (  )  &  ( buckets.length-1 ) ;^52^^^^^50^70^int index = key.hashCode (  )  &  ( _buckets.length-1 ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^int index = _buckets.hashCode (  )  &  ( key.length-1 ) ;^52^^^^^50^70^int index = key.hashCode (  )  &  ( _buckets.length-1 ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^int index = _buckets.length.hashCode (  )  &  ( key-1 ) ;^52^^^^^50^70^int index = key.hashCode (  )  &  ( _buckets.length-1 ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^int index = key.hashCode (  )  &  ( _buckets.length.length-1 ) ;^52^^^^^50^70^int index = key.hashCode (  )  &  ( _buckets.length-1 ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Wrong_Operator]^int index = key.hashCode (  )   >>   ( _buckets.length-1 ) ;^52^^^^^50^70^int index = key.hashCode (  )  &  ( _buckets.length-1 ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Wrong_Literal]^int index = key.hashCode (  )  &  ( _buckets.length-index ) ;^52^^^^^50^70^int index = key.hashCode (  )  &  ( _buckets.length-1 ) ;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^Bucket bucket = buckets[index];^53^^^^^50^70^Bucket bucket = _buckets[index];^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^if  ( next == null )  {^58^^^^^50^70^if  ( bucket == null )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Wrong_Operator]^if  ( bucket != null )  {^58^^^^^50^70^if  ( bucket == null )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^if  ( bucket.equals ( key.key )  )  {^61^^^^^50^70^if  ( key.equals ( bucket.key )  )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^if  ( key.equals ( bucket.key.key )  )  {^61^^^^^50^70^if  ( key.equals ( bucket.key )  )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^if  ( key.equals ( bucket )  )  {^61^^^^^50^70^if  ( key.equals ( bucket.key )  )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^return next.value;^62^^^^^50^70^return bucket.value;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^return bucket.value.value;^62^^^^^50^70^return bucket.value;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^return bucket;^62^^^^^50^70^return bucket.value;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^if  ( key.equals ( next.key )  )  {^61^^^^^50^70^if  ( key.equals ( bucket.key )  )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^if  ( bucket.key.equals ( key )  )  {^61^^^^^50^70^if  ( key.equals ( bucket.key )  )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^while  (  ( next = bucket.next )  != null )  {^64^^^^^50^70^while  (  ( bucket = bucket.next )  != null )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^while  (  ( bucket = next )  != null )  {^64^^^^^50^70^while  (  ( bucket = bucket.next )  != null )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^while  (  ( bucket.next = bucket )  != null )  {^64^^^^^50^70^while  (  ( bucket = bucket.next )  != null )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Wrong_Operator]^while  (  ( bucket = bucket.next )  == null )  {^64^^^^^50^70^while  (  ( bucket = bucket.next )  != null )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^if  ( key.equals ( next.key )  )  {^65^^^^^50^70^if  ( key.equals ( bucket.key )  )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^if  ( bucket.key.equals ( key )  )  {^65^^^^^50^70^if  ( key.equals ( bucket.key )  )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^if  ( key.equals ( bucket.key.key )  )  {^65^^^^^50^70^if  ( key.equals ( bucket.key )  )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^return next.value;^66^^^^^50^70^return bucket.value;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^return bucket.value.value;^66^^^^^50^70^return bucket.value;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^return bucket;^66^^^^^50^70^return bucket.value;^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Argument_Swapping]^if  ( bucket.equals ( key.key )  )  {^65^^^^^50^70^if  ( key.equals ( bucket.key )  )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
[BugLab_Variable_Misuse]^if  ( key.equals ( key )  )  {^65^^^^^50^70^if  ( key.equals ( bucket.key )  )  {^[CLASS] JsonSerializerMap Bucket  [METHOD] find [RETURN_TYPE] JsonSerializer   TypeKey key [VARIABLES] TypeKey  key  JsonSerializer  value  boolean  Bucket[]  _buckets  buckets  Bucket  bucket  next  int  _size  hashMask  index  needed  result  size  
