[REPLACE]^private  Type[] types;^26^^^^^^^[REPLACE] private final Type[] types;^ [CLASS] AddPropertyTransformer  
[REPLACE]^int.keySet = props.size (  ) ;^29^^^^^28^35^[REPLACE] int size = props.size (  ) ;^[METHOD] <init> [TYPE] Map) [PARAMETER] Map props [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true  [TYPE]  Map props  [TYPE]  int i  size 
[REPLACE]^names =   ( String[] ) null.keySet (  ) .toArray ( new String[size] ) ;^30^^^^^28^35^[REPLACE] names =  ( String[] ) props.keySet (  ) .toArray ( new String[size] ) ;^[METHOD] <init> [TYPE] Map) [PARAMETER] Map props [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true  [TYPE]  Map props  [TYPE]  int i  size 
[ADD]^^30^^^^^28^35^[ADD] names =  ( String[] ) props.keySet (  ) .toArray ( new String[size] ) ;^[METHOD] <init> [TYPE] Map) [PARAMETER] Map props [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true  [TYPE]  Map props  [TYPE]  int i  size 
[REPLACE]^types =  new Type[i];^31^^^^^28^35^[REPLACE] types = new Type[size];^[METHOD] <init> [TYPE] Map) [PARAMETER] Map props [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true  [TYPE]  Map props  [TYPE]  int i  size 
[ADD]^^31^^^^^28^35^[ADD] types = new Type[size];^[METHOD] <init> [TYPE] Map) [PARAMETER] Map props [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true  [TYPE]  Map props  [TYPE]  int i  size 
[REPLACE]^for (int i = 0; i  <=  size; i++) {^32^^^^^28^35^[REPLACE] for  ( int i = 0; i < size; i++ )  {^[METHOD] <init> [TYPE] Map) [PARAMETER] Map props [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true  [TYPE]  Map props  [TYPE]  int i  size 
[REPLACE]^types[i]  =  types[i] ;^33^^^^^28^35^[REPLACE] types[i] =  ( Type ) props.get ( names[i] ) ;^[METHOD] <init> [TYPE] Map) [PARAMETER] Map props [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true  [TYPE]  Map props  [TYPE]  int i  size 
[REPLACE]^types[i] ;^33^^^^^28^35^[REPLACE] types[i] =  ( Type ) props.get ( names[i] ) ;^[METHOD] <init> [TYPE] Map) [PARAMETER] Map props [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true  [TYPE]  Map props  [TYPE]  int i  size 
[REPLACE]^for  ( int i = 0 ; i < size; i++ )  {^32^^^^^28^35^[REPLACE] for  ( int i = 0; i < size; i++ )  {^[METHOD] <init> [TYPE] Map) [PARAMETER] Map props [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true  [TYPE]  Map props  [TYPE]  int i  size 
[REPLACE]^this.names =  null;^38^^^^^37^40^[REPLACE] this.names = names;^[METHOD] <init> [TYPE] Type[]) [PARAMETER] String[] names Type[] types [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true 
[REPLACE]^this.types =  null;^39^^^^^37^40^[REPLACE] this.types = types;^[METHOD] <init> [TYPE] Type[]) [PARAMETER] String[] names Type[] types [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true 
[ADD]^^39^^^^^37^40^[ADD] this.types = types;^[METHOD] <init> [TYPE] Type[]) [PARAMETER] String[] names Type[] types [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true 
[REPLACE]^if  ( !  getAccess (  )   )  {^43^^^^^42^47^[REPLACE] if  ( !TypeUtils.isAbstract ( getAccess (  )  )  )  {^[METHOD] end_class [TYPE] void [PARAMETER] [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true 
[REPLACE]^if  ( !TypeUtils.isAbstract ( getAccess (  )  )  )  { EmitUtils.add_properties ( this, names, types ) ;^44^^^^^42^47^[REPLACE] EmitUtils.add_properties ( this, names, types ) ;^[METHOD] end_class [TYPE] void [PARAMETER] [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true 
[REPLACE]^super.getAccess (  ) ;^46^^^^^42^47^[REPLACE] super.end_class (  ) ;^[METHOD] end_class [TYPE] void [PARAMETER] [CLASS] AddPropertyTransformer   [TYPE]  Type[] types  [TYPE]  String[] names  [TYPE]  boolean false  true 
