[P1_Replace_Type]^private final  short  numThreads;^34^^^^^29^39^private final int numThreads;^[CLASS] RemoveConstantExpressionsParallel 1 1   [VARIABLES] 
[P8_Replace_Mix]^private final  long  numThreads;^34^^^^^29^39^private final int numThreads;^[CLASS] RemoveConstantExpressionsParallel 1 1   [VARIABLES] 
[P8_Replace_Mix]^this.compiler =  null;^37^^^^^36^39^this.compiler = compiler;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] <init> [RETURN_TYPE] AbstractCompiler,int)   AbstractCompiler compiler int numThreads [VARIABLES] AbstractCompiler  compiler  int  numThreads  boolean  
[P8_Replace_Mix]^this.numThreads =  null;^38^^^^^36^39^this.numThreads = numThreads;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] <init> [RETURN_TYPE] AbstractCompiler,int)   AbstractCompiler compiler int numThreads [VARIABLES] AbstractCompiler  compiler  int  numThreads  boolean  
[P7_Replace_Invocation]^this ( compiler, Runtime.getRuntime (  ) .getRuntime (  )  ) ;^42^^^^^41^43^this ( compiler, Runtime.getRuntime (  ) .availableProcessors (  )  ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] <init> [RETURN_TYPE] AbstractCompiler)   AbstractCompiler compiler [VARIABLES] AbstractCompiler  compiler  int  numThreads  boolean  
[P7_Replace_Invocation]^this ( compiler, Runtime.availableProcessors (  ) .availableProcessors (  )  ) ;^42^^^^^41^43^this ( compiler, Runtime.getRuntime (  ) .availableProcessors (  )  ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] <init> [RETURN_TYPE] AbstractCompiler)   AbstractCompiler compiler [VARIABLES] AbstractCompiler  compiler  int  numThreads  boolean  
[P14_Delete_Statement]^^42^^^^^41^43^this ( compiler, Runtime.getRuntime (  ) .availableProcessors (  )  ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] <init> [RETURN_TYPE] AbstractCompiler)   AbstractCompiler compiler [VARIABLES] AbstractCompiler  compiler  int  numThreads  boolean  
[P8_Replace_Mix]^AstParallelizer splitter = AstParallelizer .createNewFileLevelAstParallelizer ( subtree ) ;^48^49^^^^46^70^AstParallelizer splitter = AstParallelizer .createNewFileLevelAstParallelizer ( root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P14_Delete_Statement]^^48^49^^^^46^70^AstParallelizer splitter = AstParallelizer .createNewFileLevelAstParallelizer ( root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P8_Replace_Mix]^return cb .RemoveConstantRValuesCallback (  )  ;^61^^^^^46^70^return cb.getResult (  ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, root, cb ) ;^60^^^^^46^70^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^NodeTraversal.traverse ( null,  cb ) ;^60^^^^^46^70^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, subtree ) ;^60^^^^^46^70^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, cb, subtree ) ;^60^^^^^46^70^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P14_Delete_Statement]^^60^^^^^46^70^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P14_Delete_Statement]^^61^^^^^46^70^return cb.getResult (  ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P4_Replace_Constructor]^( new ParallelCompilerPass ( compiler,  supplier, numThreads )  ) .process ( externs, root ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P4_Replace_Constructor]^( new ParallelCompilerPass ( compiler, splitter,  numThreads )  ) .process ( externs, root ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass (  splitter, supplier, numThreads )  ) .process ( externs, root ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass ( compiler, splitter, supplier )  ) .process ( externs, root ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass ( splitter, compiler, supplier, numThreads )  ) .process ( externs, root ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass ( compiler, splitter, numThreads, supplier )  ) .process ( externs, root ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass ( numThreads, splitter, supplier, compiler )  ) .process ( externs, root ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P4_Replace_Constructor]^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process (  root ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P4_Replace_Constructor]^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( subtree, root ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, subtree ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass ( compiler, externs, supplier, numThreads )  ) .process ( splitter, root ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass ( compiler, splitter, externs, numThreads )  ) .process ( supplier, root ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( root, externs ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass ( compiler, root, supplier, numThreads )  ) .process ( externs, splitter ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^( new ParallelCompilerPass ( root, splitter, supplier, numThreads )  ) .process ( externs, compiler ) ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P7_Replace_Invocation]^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  )  .RemoveConstantExpressionsParallel ( compiler , numThreads )  ;^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P14_Delete_Statement]^^68^69^^^^46^70^( new ParallelCompilerPass ( compiler, splitter, supplier, numThreads )  ) .process ( externs, root ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] process [RETURN_TYPE] void   Node externs Node root [VARIABLES] AbstractCompiler  compiler  boolean  AstParallelizer  splitter  Node  externs  root  subtree  RemoveConstantRValuesCallback  cb  Supplier  supplier  int  numThreads  
[P5_Replace_Variable]^NodeTraversal.traverse ( null,  cb ) ;^60^^^^^54^64^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, subtree ) ;^60^^^^^54^64^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, cb, subtree ) ;^60^^^^^54^64^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P14_Delete_Statement]^^60^^^^^54^64^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P8_Replace_Mix]^return cb .RemoveConstantRValuesCallback (  )  ;^61^^^^^54^64^return cb.getResult (  ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P14_Delete_Statement]^^61^^^^^54^64^return cb.getResult (  ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P5_Replace_Variable]^NodeTraversal.traverse ( null,  cb ) ;^60^^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, subtree ) ;^60^^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, cb, subtree ) ;^60^^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P14_Delete_Statement]^^60^61^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ; return cb.getResult (  ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P7_Replace_Invocation]^return cb .RemoveConstantRValuesCallback (  )  ;^61^^^^^57^62^return cb.getResult (  ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P14_Delete_Statement]^^61^^^^^57^62^return cb.getResult (  ) ;^[CLASS] RemoveConstantExpressionsParallel 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] RemoveConstantRValuesCallback  cb  AbstractCompiler  compiler  boolean  int  numThreads  Node  subtree  
[P7_Replace_Invocation]^return cb .RemoveConstantRValuesCallback (  )  ;^61^^^^^54^64^return cb.getResult (  ) ;^[CLASS] 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P5_Replace_Variable]^NodeTraversal.traverse ( null,  cb ) ;^60^^^^^54^64^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, subtree ) ;^60^^^^^54^64^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, cb, subtree ) ;^60^^^^^54^64^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P14_Delete_Statement]^^60^^^^^54^64^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P14_Delete_Statement]^^61^^^^^54^64^return cb.getResult (  ) ;^[CLASS] 1 1  [METHOD] get [RETURN_TYPE] Task   [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P5_Replace_Variable]^NodeTraversal.traverse ( null,  cb ) ;^60^^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, subtree ) ;^60^^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, cb, subtree ) ;^60^^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P14_Delete_Statement]^^60^^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P7_Replace_Invocation]^return cb .RemoveConstantRValuesCallback (  )  ;^61^^^^^57^62^return cb.getResult (  ) ;^[CLASS] 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P14_Delete_Statement]^^61^^^^^57^62^return cb.getResult (  ) ;^[CLASS] 1 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P5_Replace_Variable]^NodeTraversal.traverse ( null,  cb ) ;^60^^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, subtree ) ;^60^^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P5_Replace_Variable]^NodeTraversal.traverse ( null, cb, subtree ) ;^60^^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P14_Delete_Statement]^^60^^^^^57^62^NodeTraversal.traverse ( null, subtree, cb ) ;^[CLASS] 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P7_Replace_Invocation]^return cb .RemoveConstantRValuesCallback (  )  ;^61^^^^^57^62^return cb.getResult (  ) ;^[CLASS] 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
[P14_Delete_Statement]^^61^^^^^57^62^return cb.getResult (  ) ;^[CLASS] 1  [METHOD] processSubtree [RETURN_TYPE] Result   Node subtree [VARIABLES] boolean  Node  subtree  RemoveConstantRValuesCallback  cb  
