[P1_Replace_Type]^private static final  short  serialVersionUID = 5278818408044349346L;^34^^^^^29^39^private static final long serialVersionUID = 5278818408044349346L;^[CLASS] PredicateTransformer   [VARIABLES] 
[P8_Replace_Mix]^private static final  short  serialVersionUID = 5278818408044349346;^34^^^^^29^39^private static final long serialVersionUID = 5278818408044349346L;^[CLASS] PredicateTransformer   [VARIABLES] 
[P8_Replace_Mix]^private  Predicate<? super T> iPredicate;^37^^^^^32^42^private final Predicate<? super T> iPredicate;^[CLASS] PredicateTransformer   [VARIABLES] 
[P14_Delete_Statement]^^61^62^^^^60^63^super (  ) ; iPredicate = predicate;^[CLASS] PredicateTransformer  [METHOD] <init> [RETURN_TYPE] Predicate)   Predicate<? super T> predicate [VARIABLES] long  serialVersionUID  Predicate  iPredicate  predicate  boolean  
[P8_Replace_Mix]^iPredicate =  null;^62^^^^^60^63^iPredicate = predicate;^[CLASS] PredicateTransformer  [METHOD] <init> [RETURN_TYPE] Predicate)   Predicate<? super T> predicate [VARIABLES] long  serialVersionUID  Predicate  iPredicate  predicate  boolean  
[P2_Replace_Operator]^if  ( predicate != null )  {^48^^^^^47^52^if  ( predicate == null )  {^[CLASS] PredicateTransformer  [METHOD] predicateTransformer [RETURN_TYPE] <T>   Predicate<? super T> predicate [VARIABLES] long  serialVersionUID  Predicate  iPredicate  predicate  boolean  
[P8_Replace_Mix]^if  ( predicate == this )  {^48^^^^^47^52^if  ( predicate == null )  {^[CLASS] PredicateTransformer  [METHOD] predicateTransformer [RETURN_TYPE] <T>   Predicate<? super T> predicate [VARIABLES] long  serialVersionUID  Predicate  iPredicate  predicate  boolean  
[P15_Unwrap_Block]^throw new java.lang.IllegalArgumentException("Predicate must not be null");^48^49^50^^^47^52^if  ( predicate == null )  { throw new IllegalArgumentException  (" ")  ; }^[CLASS] PredicateTransformer  [METHOD] predicateTransformer [RETURN_TYPE] <T>   Predicate<? super T> predicate [VARIABLES] long  serialVersionUID  Predicate  iPredicate  predicate  boolean  
[P16_Remove_Block]^^48^49^50^^^47^52^if  ( predicate == null )  { throw new IllegalArgumentException  (" ")  ; }^[CLASS] PredicateTransformer  [METHOD] predicateTransformer [RETURN_TYPE] <T>   Predicate<? super T> predicate [VARIABLES] long  serialVersionUID  Predicate  iPredicate  predicate  boolean  
[P13_Insert_Block]^if  ( predicate == null )  {     throw new IllegalArgumentException ( "Predicate must not be null" ) ; }^49^^^^^47^52^[Delete]^[CLASS] PredicateTransformer  [METHOD] predicateTransformer [RETURN_TYPE] <T>   Predicate<? super T> predicate [VARIABLES] long  serialVersionUID  Predicate  iPredicate  predicate  boolean  
[P5_Replace_Variable]^return Boolean.valueOf ( input.evaluate ( iPredicate )  ) ;^72^^^^^71^73^return Boolean.valueOf ( iPredicate.evaluate ( input )  ) ;^[CLASS] PredicateTransformer  [METHOD] transform [RETURN_TYPE] Boolean   final T input [VARIABLES] boolean  T  input  long  serialVersionUID  Predicate  iPredicate  predicate  
[P14_Delete_Statement]^^72^^^^^71^73^return Boolean.valueOf ( iPredicate.evaluate ( input )  ) ;^[CLASS] PredicateTransformer  [METHOD] transform [RETURN_TYPE] Boolean   final T input [VARIABLES] boolean  T  input  long  serialVersionUID  Predicate  iPredicate  predicate  
