[REPLACE]^private final List<AnnotationSpec> annotations;^35^^^^^^^[REPLACE] public final List<AnnotationSpec> annotations;^ [CLASS] ParameterSpec Builder  
[REPLACE]^public  Set<Modifier> modifiers;^36^^^^^^^[REPLACE] public final Set<Modifier> modifiers;^ [CLASS] ParameterSpec Builder  
[REPLACE]^public final Object type;^37^^^^^^^[REPLACE] public final TypeName type;^ [CLASS] ParameterSpec Builder  
[REPLACE]^private  TypeName type;^122^^^^^^^[REPLACE] private final TypeName type;^ [CLASS] ParameterSpec Builder  
[REPLACE]^private final  int  name;^123^^^^^^^[REPLACE] private final String name;^ [CLASS] ParameterSpec Builder  
[REPLACE]^private final List<AnnotationSpec> annotations  = null ;^125^^^^^^^[REPLACE] private final List<AnnotationSpec> annotations = new ArrayList<> (  ) ;^ [CLASS] ParameterSpec Builder  
[REPLACE]^private final List<Object modifiers = new ArrayList<> (  ) ;^126^^^^^^^[REPLACE] private final List<Modifier> modifiers = new ArrayList<> (  ) ;^ [CLASS] ParameterSpec Builder  
[REPLACE]^private final  char  name;^123^^^^^^^[REPLACE] private final String name;^[METHOD] build [TYPE] ParameterSpec [PARAMETER] [CLASS] Builder   [TYPE]  TypeName type  [TYPE]  List annotations  modifiers  result  [TYPE]  Set modifiers  [TYPE]  String name  [TYPE]  boolean false  true 
[REPLACE]^private final List<AnnotationSpec> annotations  = null ;^125^^^^^^^[REPLACE] private final List<AnnotationSpec> annotations = new ArrayList<> (  ) ;^[METHOD] build [TYPE] ParameterSpec [PARAMETER] [CLASS] Builder   [TYPE]  TypeName type  [TYPE]  List annotations  modifiers  result  [TYPE]  Set modifiers  [TYPE]  String name  [TYPE]  boolean false  true 
[REPLACE]^private final List<Object modifiers = new ArrayList<> (  ) ;^126^^^^^^^[REPLACE] private final List<Modifier> modifiers = new ArrayList<> (  ) ;^[METHOD] build [TYPE] ParameterSpec [PARAMETER] [CLASS] Builder   [TYPE]  TypeName type  [TYPE]  List annotations  modifiers  result  [TYPE]  Set modifiers  [TYPE]  String name  [TYPE]  boolean false  true 
