[P8_Replace_Mix]^private JSDocInfo docInfo ;^85^^^^^80^90^private JSDocInfo docInfo = null;^[CLASS] ObjectType   [VARIABLES] 
[P3_Replace_Literal]^private boolean unknown = false;^86^^^^^81^91^private boolean unknown = true;^[CLASS] ObjectType   [VARIABLES] 
[P14_Delete_Statement]^^89^^^^^88^90^super ( registry ) ;^[CLASS] ObjectType  [METHOD] <init> [RETURN_TYPE] JSTypeRegistry)   JSTypeRegistry registry [VARIABLES] JSDocInfo  docInfo  JSTypeRegistry  registry  boolean  unknown  visited  
[P8_Replace_Mix]^return true;^97^^^^^96^98^return null;^[CLASS] ObjectType  [METHOD] getParameterType [RETURN_TYPE] JSType   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P8_Replace_Mix]^return false;^105^^^^^104^106^return null;^[CLASS] ObjectType  [METHOD] getIndexType [RETURN_TYPE] JSType   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P2_Replace_Operator]^if  ( docInfo == null )  {^112^^^^^111^119^if  ( docInfo != null )  {^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P6_Replace_Expression]^if  ( getImplicitPrototype() != null )  {^112^^^^^111^119^if  ( docInfo != null )  {^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P8_Replace_Mix]^if  ( docInfo != true )  {^112^^^^^111^119^if  ( docInfo != null )  {^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P9_Replace_Statement]^if  ( result != null )  {^112^^^^^111^119^if  ( docInfo != null )  {^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P13_Insert_Block]^if  (  ( getImplicitPrototype (  )  )  != null )  {     return getImplicitPrototype (  ) .getJSDocInfo (  ) ; }else {     return super.getJSDocInfo (  ) ; }^112^^^^^111^119^[Delete]^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P2_Replace_Operator]^} else if  ( getImplicitPrototype (  )  == null )  {^114^^^^^111^119^} else if  ( getImplicitPrototype (  )  != null )  {^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P6_Replace_Expression]^} else {^114^^^^^111^119^} else if  ( getImplicitPrototype (  )  != null )  {^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P7_Replace_Invocation]^} else if  ( getJSDocInfo (  )  != null )  {^114^^^^^111^119^} else if  ( getImplicitPrototype (  )  != null )  {^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P15_Unwrap_Block]^return getImplicitPrototype().getJSDocInfo();^114^115^116^117^118^111^119^} else if  ( getImplicitPrototype (  )  != null )  { return getImplicitPrototype (  ) .getJSDocInfo (  ) ; } else { return super.getJSDocInfo (  ) ; }^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P16_Remove_Block]^^114^115^116^117^118^111^119^} else if  ( getImplicitPrototype (  )  != null )  { return getImplicitPrototype (  ) .getJSDocInfo (  ) ; } else { return super.getJSDocInfo (  ) ; }^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P13_Insert_Block]^if  (  ( docInfo )  != null )  {     return docInfo; }else     if  (  ( getImplicitPrototype (  )  )  != null )  {         return getImplicitPrototype (  ) .getJSDocInfo (  ) ;     }else {         return super.getJSDocInfo (  ) ;     }^114^^^^^111^119^[Delete]^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P7_Replace_Invocation]^return super.getNativeType (  ) ;^117^^^^^111^119^return super.getJSDocInfo (  ) ;^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P7_Replace_Invocation]^return super .setJSDocInfo ( docInfo )  ;^117^^^^^111^119^return super.getJSDocInfo (  ) ;^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P14_Delete_Statement]^^117^^^^^111^119^return super.getJSDocInfo (  ) ;^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P7_Replace_Invocation]^return getImplicitPrototype (  ) .isUnknownType (  ) ;^115^^^^^111^119^return getImplicitPrototype (  ) .getJSDocInfo (  ) ;^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P7_Replace_Invocation]^return getJSDocInfo (  ) .getJSDocInfo (  ) ;^115^^^^^111^119^return getImplicitPrototype (  ) .getJSDocInfo (  ) ;^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P14_Delete_Statement]^^115^^^^^111^119^return getImplicitPrototype (  ) .getJSDocInfo (  ) ;^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P7_Replace_Invocation]^return getImplicitPrototype (  )  .setJSDocInfo ( docInfo )  ;^115^^^^^111^119^return getImplicitPrototype (  ) .getJSDocInfo (  ) ;^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P8_Replace_Mix]^}  if  ( getImplicitPrototype (  )  != false )  {^114^^^^^111^119^} else if  ( getImplicitPrototype (  )  != null )  {^[CLASS] ObjectType  [METHOD] getJSDocInfo [RETURN_TYPE] JSDocInfo   [VARIABLES] JSDocInfo  docInfo  boolean  unknown  visited  
[P5_Replace_Variable]^docInfo = docInfo;^126^^^^^125^127^docInfo = info;^[CLASS] ObjectType  [METHOD] setJSDocInfo [RETURN_TYPE] void   JSDocInfo info [VARIABLES] JSDocInfo  docInfo  info  boolean  unknown  visited  
[P8_Replace_Mix]^docInfo =  null;^126^^^^^125^127^docInfo = info;^[CLASS] ObjectType  [METHOD] setJSDocInfo [RETURN_TYPE] void   JSDocInfo info [VARIABLES] JSDocInfo  docInfo  info  boolean  unknown  visited  
[P3_Replace_Literal]^this.visited = false;^141^^^^^139^159^this.visited = true;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^p.visited = true;this.visited = true;^141^^^^^139^159^this.visited = true;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^p.visited = false;this.visited = true;^141^^^^^139^159^this.visited = true;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P7_Replace_Invocation]^ObjectType p = getJSDocInfo (  ) ;^142^^^^^139^159^ObjectType p = getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^ObjectType implicitProto = getImplicitPrototype (  ) ;ObjectType p = getImplicitPrototype (  ) ;^142^^^^^139^159^ObjectType p = getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P14_Delete_Statement]^^142^^^^^139^159^ObjectType p = getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^p = p.getImplicitPrototype (  ) ;ObjectType p = getImplicitPrototype (  ) ;^142^^^^^139^159^ObjectType p = getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P2_Replace_Operator]^while  ( p == null )  {^143^^^^^139^159^while  ( p != null )  {^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P5_Replace_Variable]^if  ( visited )  {^144^^^^^139^159^if  ( p.visited )  {^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P5_Replace_Variable]^if  ( p.visited.visited )  {^144^^^^^139^159^if  ( p.visited )  {^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P5_Replace_Variable]^if  ( p )  {^144^^^^^139^159^if  ( p.visited )  {^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P15_Unwrap_Block]^return true;^144^145^146^147^148^139^159^if  ( p.visited )  { return true; } else { p.visited = true; }^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P16_Remove_Block]^^144^145^146^147^148^139^159^if  ( p.visited )  { return true; } else { p.visited = true; }^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P3_Replace_Literal]^p.visited = false;^147^^^^^139^159^p.visited = true;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^this.visited = true;p.visited = true;^147^^^^^139^159^p.visited = true;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^p.visited = false;p.visited = true;^147^^^^^139^159^p.visited = true;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P3_Replace_Literal]^return false;^145^^^^^139^159^return true;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P7_Replace_Invocation]^p = p.getPropertyType (  ) ;^149^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P8_Replace_Mix]^p =  null.getImnulllicitPrototynulle (  ) ;^149^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^unknown = implicitProto.isUnknownType (  ) ;p = p.getImplicitPrototype (  ) ;^149^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P7_Replace_Invocation]^p = p .isImplicitPrototype ( p )  ;^149^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P14_Delete_Statement]^^149^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^return getImplicitPrototype (  ) .getJSDocInfo (  ) ;p = p.getImplicitPrototype (  ) ;^149^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^ObjectType implicitProto = getImplicitPrototype (  ) ;p = p.getImplicitPrototype (  ) ;^149^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^ObjectType p = getImplicitPrototype (  ) ;p = p.getImplicitPrototype (  ) ;^149^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P8_Replace_Mix]^p ;^153^^^^^139^159^p = this;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P3_Replace_Literal]^p.visited = true;^155^^^^^139^159^p.visited = false;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^this.visited = true;p.visited = false;^155^^^^^139^159^p.visited = false;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^p.visited = true;p.visited = false;^155^^^^^139^159^p.visited = false;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P7_Replace_Invocation]^p = p.getPropertyType (  ) ;^156^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P8_Replace_Mix]^p =  null.getImnulllicitPrototynulle (  ) ;^156^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^unknown = implicitProto.isUnknownType (  ) ;p = p.getImplicitPrototype (  ) ;^156^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P14_Delete_Statement]^^156^157^^^^139^159^p = p.getImplicitPrototype (  ) ; } while  ( p != null ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^return getImplicitPrototype (  ) .getJSDocInfo (  ) ;p = p.getImplicitPrototype (  ) ;^156^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^ObjectType implicitProto = getImplicitPrototype (  ) ;p = p.getImplicitPrototype (  ) ;^156^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P11_Insert_Donor_Statement]^ObjectType p = getImplicitPrototype (  ) ;p = p.getImplicitPrototype (  ) ;^156^^^^^139^159^p = p.getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P3_Replace_Literal]^return true;^158^^^^^139^159^return false;^[CLASS] ObjectType  [METHOD] detectImplicitPrototypeCycle [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  p  boolean  unknown  visited  
[P3_Replace_Literal]^return true;^175^^^^^174^176^return false;^[CLASS] ObjectType  [METHOD] hasReferenceName [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  boolean  unknown  visited  
[P7_Replace_Invocation]^TernaryValue result = super .getLeastSupertype ( that )  ;^181^^^^^179^192^TernaryValue result = super.testForEquality ( that ) ;^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P14_Delete_Statement]^^181^^^^^179^192^TernaryValue result = super.testForEquality ( that ) ;^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P2_Replace_Operator]^if  ( result == null )  {^182^^^^^179^192^if  ( result != null )  {^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P8_Replace_Mix]^if  ( result != true )  {^182^^^^^179^192^if  ( result != null )  {^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P9_Replace_Statement]^if  ( docInfo != null )  {^182^^^^^179^192^if  ( result != null )  {^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P15_Unwrap_Block]^return result;^182^183^184^^^179^192^if  ( result != null )  { return result; }^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P16_Remove_Block]^^182^183^184^^^179^192^if  ( result != null )  { return result; }^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P7_Replace_Invocation]^if  ( that.getLeastSupertype ( getNativeType ( JSTypeNative.OBJECT_NUMBER_STRING_BOOLEAN )  )  )  {^186^187^^^^179^192^if  ( that.isSubtype ( getNativeType ( JSTypeNative.OBJECT_NUMBER_STRING_BOOLEAN )  )  )  {^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P7_Replace_Invocation]^if  ( that.isSubtype ( getJSDocInfo ( JSTypeNative.OBJECT_NUMBER_STRING_BOOLEAN )  )  )  {^186^187^^^^179^192^if  ( that.isSubtype ( getNativeType ( JSTypeNative.OBJECT_NUMBER_STRING_BOOLEAN )  )  )  {^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P15_Unwrap_Block]^return com.google.javascript.rhino.jstype.TernaryValue.UNKNOWN;^186^187^188^189^190^179^192^if  ( that.isSubtype ( getNativeType ( JSTypeNative.OBJECT_NUMBER_STRING_BOOLEAN )  )  )  { return UNKNOWN; } else { return FALSE; }^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P16_Remove_Block]^^186^187^188^189^190^179^192^if  ( that.isSubtype ( getNativeType ( JSTypeNative.OBJECT_NUMBER_STRING_BOOLEAN )  )  )  { return UNKNOWN; } else { return FALSE; }^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return 4;^190^^^^^179^192^return FALSE;^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P7_Replace_Invocation]^getJSDocInfo ( JSTypeNative.OBJECT_NUMBER_STRING_BOOLEAN )  )  )  {^187^^^^^179^192^getNativeType ( JSTypeNative.OBJECT_NUMBER_STRING_BOOLEAN )  )  )  {^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P14_Delete_Statement]^^187^188^^^^179^192^getNativeType ( JSTypeNative.OBJECT_NUMBER_STRING_BOOLEAN )  )  )  { return UNKNOWN;^[CLASS] ObjectType  [METHOD] testForEquality [RETURN_TYPE] TernaryValue   JSType that [VARIABLES] boolean  unknown  visited  JSType  that  TernaryValue  result  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^registry.registerPropertyOnType (  this ) ;^219^^^^^215^222^registry.registerPropertyOnType ( propertyName, this ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P14_Delete_Statement]^^219^^^^^215^222^registry.registerPropertyOnType ( propertyName, this ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P11_Insert_Donor_Statement]^getPropertyType ( propertyName )  : null;registry.registerPropertyOnType ( propertyName, this ) ;^219^^^^^215^222^registry.registerPropertyOnType ( propertyName, this ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P11_Insert_Donor_Statement]^return hasProperty ( propertyName ) ;registry.registerPropertyOnType ( propertyName, this ) ;^219^^^^^215^222^registry.registerPropertyOnType ( propertyName, this ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P3_Replace_Literal]^return defineProperty ( propertyName, type, true, inExterns ) ;^221^^^^^215^222^return defineProperty ( propertyName, type, false, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( propertyName, type, false, visited ) ;^221^^^^^215^222^return defineProperty ( propertyName, type, false, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty (  type, false, inExterns ) ;^221^^^^^215^222^return defineProperty ( propertyName, type, false, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( propertyName,  false, inExterns ) ;^221^^^^^215^222^return defineProperty ( propertyName, type, false, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( propertyName, type, false ) ;^221^^^^^215^222^return defineProperty ( propertyName, type, false, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( inExterns, type, false, propertyName ) ;^221^^^^^215^222^return defineProperty ( propertyName, type, false, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( type, propertyName, false, inExterns ) ;^221^^^^^215^222^return defineProperty ( propertyName, type, false, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( propertyName, inExterns, false, type ) ;^221^^^^^215^222^return defineProperty ( propertyName, type, false, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P14_Delete_Statement]^^221^^^^^215^222^return defineProperty ( propertyName, type, false, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineDeclaredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^registry.registerPropertyOnType (  this ) ;^237^^^^^233^246^registry.registerPropertyOnType ( propertyName, this ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P14_Delete_Statement]^^237^^^^^233^246^registry.registerPropertyOnType ( propertyName, this ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P11_Insert_Donor_Statement]^getPropertyType ( propertyName )  : null;registry.registerPropertyOnType ( propertyName, this ) ;^237^^^^^233^246^registry.registerPropertyOnType ( propertyName, this ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P11_Insert_Donor_Statement]^return hasProperty ( propertyName ) ;registry.registerPropertyOnType ( propertyName, this ) ;^237^^^^^233^246^registry.registerPropertyOnType ( propertyName, this ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P7_Replace_Invocation]^if  ( hasOwnProperty ( propertyName )  )  {^239^^^^^233^246^if  ( hasProperty ( propertyName )  )  {^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P15_Unwrap_Block]^com.google.javascript.rhino.jstype.JSType originalType = getPropertyType(propertyName); type = (originalType == null) ? type : originalType.getLeastSupertype(type);^239^240^241^242^243^233^246^if  ( hasProperty ( propertyName )  )  { JSType originalType = getPropertyType ( propertyName ) ; type = originalType == null ? type : originalType.getLeastSupertype ( type ) ; }^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P16_Remove_Block]^^239^240^241^242^243^233^246^if  ( hasProperty ( propertyName )  )  { JSType originalType = getPropertyType ( propertyName ) ; type = originalType == null ? type : originalType.getLeastSupertype ( type ) ; }^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P2_Replace_Operator]^type = originalType != null ? type : originalType.getLeastSupertype ( type ) ;^241^242^^^^233^246^type = originalType == null ? type : originalType.getLeastSupertype ( type ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^type = type == null ? originalType : originalType.getLeastSupertype ( type ) ;^241^242^^^^233^246^type = originalType == null ? type : originalType.getLeastSupertype ( type ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P6_Replace_Expression]^type = originalType ( originalType.getLeastSupertype ( type ) ;^241^242^^^^233^246^type = originalType == null ? type : originalType.getLeastSupertype ( type ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P8_Replace_Mix]^type = originalType == true ? type : originalType.getLeastSupertype ( type ) ;^241^242^^^^233^246^type = originalType == null ? type : originalType.getLeastSupertype ( type ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P7_Replace_Invocation]^JSType originalType = findPropertyType ( propertyName ) ;^240^^^^^233^246^JSType originalType = getPropertyType ( propertyName ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P14_Delete_Statement]^^240^^^^^233^246^JSType originalType = getPropertyType ( propertyName ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P8_Replace_Mix]^originalType .isSubtype (  )  ;^242^^^^^233^246^originalType.getLeastSupertype ( type ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P14_Delete_Statement]^^242^^^^^233^246^originalType.getLeastSupertype ( type ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P7_Replace_Invocation]^type = originalType == null ? type : originalType .isSubtype (  )  ;^241^242^^^^233^246^type = originalType == null ? type : originalType.getLeastSupertype ( type ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P3_Replace_Literal]^return defineProperty ( propertyName, type, false, inExterns ) ;^245^^^^^233^246^return defineProperty ( propertyName, type, true, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( propertyName, originalType, true, inExterns ) ;^245^^^^^233^246^return defineProperty ( propertyName, type, true, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( propertyName, type, true, visited ) ;^245^^^^^233^246^return defineProperty ( propertyName, type, true, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty (  type, true, inExterns ) ;^245^^^^^233^246^return defineProperty ( propertyName, type, true, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( propertyName,  true, inExterns ) ;^245^^^^^233^246^return defineProperty ( propertyName, type, true, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( propertyName, type, true ) ;^245^^^^^233^246^return defineProperty ( propertyName, type, true, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( type, propertyName, true, inExterns ) ;^245^^^^^233^246^return defineProperty ( propertyName, type, true, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( propertyName, inExterns, true, type ) ;^245^^^^^233^246^return defineProperty ( propertyName, type, true, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P5_Replace_Variable]^return defineProperty ( inExterns, type, true, propertyName ) ;^245^^^^^233^246^return defineProperty ( propertyName, type, true, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P14_Delete_Statement]^^245^^^^^233^246^return defineProperty ( propertyName, type, true, inExterns ) ;^[CLASS] ObjectType  [METHOD] defineInferredProperty [RETURN_TYPE] boolean   String propertyName JSType type boolean inExterns [VARIABLES] boolean  inExterns  unknown  visited  String  propertyName  JSType  originalType  type  JSDocInfo  docInfo  info  
[P8_Replace_Mix]^return this;^271^^^^^270^272^return null;^[CLASS] ObjectType  [METHOD] getOwnPropertyJSDocInfo [RETURN_TYPE] JSDocInfo   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P7_Replace_Invocation]^return hasOwnProperty ( propertyName )  ? getPropertyType ( propertyName )  : null;^291^292^^^^290^293^return hasProperty ( propertyName )  ? getPropertyType ( propertyName )  : null;^[CLASS] ObjectType  [METHOD] findPropertyType [RETURN_TYPE] JSType   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P7_Replace_Invocation]^return hasProperty ( propertyName )  ? findPropertyType ( propertyName )  : null;^291^292^^^^290^293^return hasProperty ( propertyName )  ? getPropertyType ( propertyName )  : null;^[CLASS] ObjectType  [METHOD] findPropertyType [RETURN_TYPE] JSType   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P14_Delete_Statement]^^291^292^^^^290^293^return hasProperty ( propertyName )  ? getPropertyType ( propertyName )  : null;^[CLASS] ObjectType  [METHOD] findPropertyType [RETURN_TYPE] JSType   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P7_Replace_Invocation]^findPropertyType ( propertyName )  : null;^292^^^^^290^293^getPropertyType ( propertyName )  : null;^[CLASS] ObjectType  [METHOD] findPropertyType [RETURN_TYPE] JSType   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P14_Delete_Statement]^^292^^^^^290^293^getPropertyType ( propertyName )  : null;^[CLASS] ObjectType  [METHOD] findPropertyType [RETURN_TYPE] JSType   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P11_Insert_Donor_Statement]^return hasProperty ( propertyName )  ? getPropertyType ( propertyName )  : null;getPropertyType ( propertyName )  : null;^292^^^^^290^293^getPropertyType ( propertyName )  : null;^[CLASS] ObjectType  [METHOD] findPropertyType [RETURN_TYPE] JSType   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P11_Insert_Donor_Statement]^registry.registerPropertyOnType ( propertyName, this ) ;getPropertyType ( propertyName )  : null;^292^^^^^290^293^getPropertyType ( propertyName )  : null;^[CLASS] ObjectType  [METHOD] findPropertyType [RETURN_TYPE] JSType   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P11_Insert_Donor_Statement]^return hasProperty ( propertyName ) ;getPropertyType ( propertyName )  : null;^292^^^^^290^293^getPropertyType ( propertyName )  : null;^[CLASS] ObjectType  [METHOD] findPropertyType [RETURN_TYPE] JSType   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P12_Insert_Condition]^if  ( hasProperty ( propertyName )  )  { getPropertyType ( propertyName )  : null; }^292^^^^^290^293^getPropertyType ( propertyName )  : null;^[CLASS] ObjectType  [METHOD] findPropertyType [RETURN_TYPE] JSType   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P7_Replace_Invocation]^return hasOwnProperty ( propertyName ) ;^316^^^^^315^317^return hasProperty ( propertyName ) ;^[CLASS] ObjectType  [METHOD] hasOwnProperty [RETURN_TYPE] boolean   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P12_Insert_Condition]^if  ( hasProperty ( propertyName )  )  { return hasProperty ( propertyName ) ; }^316^^^^^315^317^return hasProperty ( propertyName ) ;^[CLASS] ObjectType  [METHOD] hasOwnProperty [RETURN_TYPE] boolean   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P14_Delete_Statement]^^316^^^^^315^317^return hasProperty ( propertyName ) ;^[CLASS] ObjectType  [METHOD] hasOwnProperty [RETURN_TYPE] boolean   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P2_Replace_Operator]^return hasOwnProperty ( name )  || isPropertyTypeDeclared ( name ) ;^338^^^^^337^339^return hasOwnProperty ( name )  && isPropertyTypeDeclared ( name ) ;^[CLASS] ObjectType  [METHOD] hasOwnDeclaredProperty [RETURN_TYPE] boolean   String name [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  name  
[P7_Replace_Invocation]^return hasProperty ( name )  && isPropertyTypeDeclared ( name ) ;^338^^^^^337^339^return hasOwnProperty ( name )  && isPropertyTypeDeclared ( name ) ;^[CLASS] ObjectType  [METHOD] hasOwnDeclaredProperty [RETURN_TYPE] boolean   String name [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  name  
[P7_Replace_Invocation]^return hasOwnProperty ( name )  && getPropertyType ( name ) ;^338^^^^^337^339^return hasOwnProperty ( name )  && isPropertyTypeDeclared ( name ) ;^[CLASS] ObjectType  [METHOD] hasOwnDeclaredProperty [RETURN_TYPE] boolean   String name [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  name  
[P8_Replace_Mix]^return   getPropertyType ( name ) ;^338^^^^^337^339^return hasOwnProperty ( name )  && isPropertyTypeDeclared ( name ) ;^[CLASS] ObjectType  [METHOD] hasOwnDeclaredProperty [RETURN_TYPE] boolean   String name [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  name  
[P14_Delete_Statement]^^338^^^^^337^339^return hasOwnProperty ( name )  && isPropertyTypeDeclared ( name ) ;^[CLASS] ObjectType  [METHOD] hasOwnDeclaredProperty [RETURN_TYPE] boolean   String name [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  name  
[P3_Replace_Literal]^return true;^343^^^^^342^344^return false;^[CLASS] ObjectType  [METHOD] isPropertyInExterns [RETURN_TYPE] boolean   String propertyName [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  String  propertyName  
[P14_Delete_Statement]^^356^357^^^^355^359^Set<String> props = Sets.newHashSet (  ) ; collectPropertyNames ( props ) ;^[CLASS] ObjectType  [METHOD] getPropertyNames [RETURN_TYPE] Set   [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  Set  props  
[P7_Replace_Invocation]^getPropertyType ( props ) ;^357^^^^^355^359^collectPropertyNames ( props ) ;^[CLASS] ObjectType  [METHOD] getPropertyNames [RETURN_TYPE] Set   [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  Set  props  
[P8_Replace_Mix]^collectPropertyNames ( null ) ;^357^^^^^355^359^collectPropertyNames ( props ) ;^[CLASS] ObjectType  [METHOD] getPropertyNames [RETURN_TYPE] Set   [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  Set  props  
[P14_Delete_Statement]^^357^358^^^^355^359^collectPropertyNames ( props ) ; return props;^[CLASS] ObjectType  [METHOD] getPropertyNames [RETURN_TYPE] Set   [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  Set  props  
[P8_Replace_Mix]^return visitor.caseObjectType ( null ) ;^368^^^^^367^369^return visitor.caseObjectType ( this ) ;^[CLASS] ObjectType  [METHOD] visit [RETURN_TYPE] <T>   Visitor<T> visitor [VARIABLES] JSDocInfo  docInfo  info  Visitor  visitor  boolean  inExterns  inferred  unknown  visited  
[P14_Delete_Statement]^^368^^^^^367^369^return visitor.caseObjectType ( this ) ;^[CLASS] ObjectType  [METHOD] visit [RETURN_TYPE] <T>   Visitor<T> visitor [VARIABLES] JSDocInfo  docInfo  info  Visitor  visitor  boolean  inExterns  inferred  unknown  visited  
[P5_Replace_Variable]^if  ( prototype.equals ( current )  )  {^385^^^^^381^390^if  ( current.equals ( prototype )  )  {^[CLASS] ObjectType  [METHOD] isImplicitPrototype [RETURN_TYPE] boolean   ObjectType prototype [VARIABLES] JSDocInfo  docInfo  info  ObjectType  current  prototype  boolean  inExterns  inferred  unknown  visited  
[P15_Unwrap_Block]^return true;^385^386^387^^^381^390^if  ( current.equals ( prototype )  )  { return true; }^[CLASS] ObjectType  [METHOD] isImplicitPrototype [RETURN_TYPE] boolean   ObjectType prototype [VARIABLES] JSDocInfo  docInfo  info  ObjectType  current  prototype  boolean  inExterns  inferred  unknown  visited  
[P16_Remove_Block]^^385^386^387^^^381^390^if  ( current.equals ( prototype )  )  { return true; }^[CLASS] ObjectType  [METHOD] isImplicitPrototype [RETURN_TYPE] boolean   ObjectType prototype [VARIABLES] JSDocInfo  docInfo  info  ObjectType  current  prototype  boolean  inExterns  inferred  unknown  visited  
[P3_Replace_Literal]^return false;^386^^^^^381^390^return true;^[CLASS] ObjectType  [METHOD] isImplicitPrototype [RETURN_TYPE] boolean   ObjectType prototype [VARIABLES] JSDocInfo  docInfo  info  ObjectType  current  prototype  boolean  inExterns  inferred  unknown  visited  
[P5_Replace_Variable]^for  ( ObjectType prototype = this;^382^^^^^381^390^for  ( ObjectType current = this;^[CLASS] ObjectType  [METHOD] isImplicitPrototype [RETURN_TYPE] boolean   ObjectType prototype [VARIABLES] JSDocInfo  docInfo  info  ObjectType  current  prototype  boolean  inExterns  inferred  unknown  visited  
[P5_Replace_Variable]^current = prototype.getImplicitPrototype (  )  )  {^384^^^^^381^390^current = current.getImplicitPrototype (  )  )  {^[CLASS] ObjectType  [METHOD] isImplicitPrototype [RETURN_TYPE] boolean   ObjectType prototype [VARIABLES] JSDocInfo  docInfo  info  ObjectType  current  prototype  boolean  inExterns  inferred  unknown  visited  
[P7_Replace_Invocation]^current = current.getPropertyType (  )  )  {^384^^^^^381^390^current = current.getImplicitPrototype (  )  )  {^[CLASS] ObjectType  [METHOD] isImplicitPrototype [RETURN_TYPE] boolean   ObjectType prototype [VARIABLES] JSDocInfo  docInfo  info  ObjectType  current  prototype  boolean  inExterns  inferred  unknown  visited  
[P14_Delete_Statement]^^384^385^386^^^381^390^current = current.getImplicitPrototype (  )  )  { if  ( current.equals ( prototype )  )  { return true;^[CLASS] ObjectType  [METHOD] isImplicitPrototype [RETURN_TYPE] boolean   ObjectType prototype [VARIABLES] JSDocInfo  docInfo  info  ObjectType  current  prototype  boolean  inExterns  inferred  unknown  visited  
[P3_Replace_Literal]^return true;^389^^^^^381^390^return false;^[CLASS] ObjectType  [METHOD] isImplicitPrototype [RETURN_TYPE] boolean   ObjectType prototype [VARIABLES] JSDocInfo  docInfo  info  ObjectType  current  prototype  boolean  inExterns  inferred  unknown  visited  
[P5_Replace_Variable]^if  ( visited )  {^405^^^^^402^415^if  ( unknown )  {^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P6_Replace_Expression]^if  ( implicitProto == null )  {^405^^^^^402^415^if  ( unknown )  {^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P2_Replace_Operator]^if  ( implicitProto == null && implicitProto.isNativeObjectType (  )  )  {^407^408^^^^402^415^if  ( implicitProto == null || implicitProto.isNativeObjectType (  )  )  {^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P2_Replace_Operator]^if  ( implicitProto != null || implicitProto.isNativeObjectType (  )  )  {^407^408^^^^402^415^if  ( implicitProto == null || implicitProto.isNativeObjectType (  )  )  {^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P6_Replace_Expression]^if  ( implicitProto == null ) {^407^408^^^^402^415^if  ( implicitProto == null || implicitProto.isNativeObjectType (  )  )  {^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P6_Replace_Expression]^if  (  implicitProto.isNativeObjectType (  )  )  {^407^408^^^^402^415^if  ( implicitProto == null || implicitProto.isNativeObjectType (  )  )  {^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P7_Replace_Invocation]^if  ( implicitProto == null || implicitProto.hasProperty (  )  )  {^407^408^^^^402^415^if  ( implicitProto == null || implicitProto.isNativeObjectType (  )  )  {^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P8_Replace_Mix]^if  ( implicitProto == false || implicitProto.isNativeObjectType (  )  )  {^407^408^^^^402^415^if  ( implicitProto == null || implicitProto.isNativeObjectType (  )  )  {^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P15_Unwrap_Block]^unknown = false;^407^408^409^410^411^402^415^if  ( implicitProto == null || implicitProto.isNativeObjectType (  )  )  { unknown = false; } else { unknown = implicitProto.isUnknownType (  ) ; }^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P16_Remove_Block]^^407^408^409^410^411^402^415^if  ( implicitProto == null || implicitProto.isNativeObjectType (  )  )  { unknown = false; } else { unknown = implicitProto.isUnknownType (  ) ; }^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P13_Insert_Block]^if  ( unknown )  {     ObjectType implicitProto = getImplicitPrototype (  ) ;     if  (  ( implicitProto == null )  ||  ( implicitProto.isNativeObjectType (  )  )  )  {         unknown = false;     }else {         unknown = implicitProto.isUnknownType (  ) ;     } }^407^^^^^402^415^[Delete]^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P7_Replace_Invocation]^unknown = implicitProto.hasProperty (  ) ;^411^^^^^402^415^unknown = implicitProto.isUnknownType (  ) ;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P8_Replace_Mix]^unknown =  null.isUnknownType (  ) ;^411^^^^^402^415^unknown = implicitProto.isUnknownType (  ) ;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P11_Insert_Donor_Statement]^p = p.getImplicitPrototype (  ) ;unknown = implicitProto.isUnknownType (  ) ;^411^^^^^402^415^unknown = implicitProto.isUnknownType (  ) ;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P14_Delete_Statement]^^411^^^^^402^415^unknown = implicitProto.isUnknownType (  ) ;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P3_Replace_Literal]^unknown = true;^409^^^^^402^415^unknown = false;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P7_Replace_Invocation]^ObjectType implicitProto = getJSDocInfo (  ) ;^406^^^^^402^415^ObjectType implicitProto = getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P11_Insert_Donor_Statement]^ObjectType p = getImplicitPrototype (  ) ;ObjectType implicitProto = getImplicitPrototype (  ) ;^406^^^^^402^415^ObjectType implicitProto = getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P14_Delete_Statement]^^406^^^^^402^415^ObjectType implicitProto = getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P11_Insert_Donor_Statement]^p = p.getImplicitPrototype (  ) ;ObjectType implicitProto = getImplicitPrototype (  ) ;^406^^^^^402^415^ObjectType implicitProto = getImplicitPrototype (  ) ;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P7_Replace_Invocation]^implicitProto.hasProperty (  )  )  {^408^^^^^402^415^implicitProto.isNativeObjectType (  )  )  {^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P14_Delete_Statement]^^408^409^^^^402^415^implicitProto.isNativeObjectType (  )  )  { unknown = false;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P8_Replace_Mix]^if  ( implicitProto == true ) {^407^408^^^^402^415^if  ( implicitProto == null || implicitProto.isNativeObjectType (  )  )  {^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P8_Replace_Mix]^unknown = implicitProto .isNativeObjectType (  )  ;^411^^^^^402^415^unknown = implicitProto.isUnknownType (  ) ;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P5_Replace_Variable]^return visited;^414^^^^^402^415^return unknown;^[CLASS] ObjectType  [METHOD] isUnknownType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  ObjectType  implicitProto  boolean  inExterns  inferred  unknown  visited  
[P3_Replace_Literal]^return false;^419^^^^^418^420^return true;^[CLASS] ObjectType  [METHOD] isObject [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  
[P3_Replace_Literal]^return true;^433^^^^^432^434^return false;^[CLASS] ObjectType  [METHOD] isNativeObjectType [RETURN_TYPE] boolean   [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  
[P2_Replace_Operator]^return type != null ? null : type.toObjectType (  ) ;^440^^^^^439^441^return type == null ? null : type.toObjectType (  ) ;^[CLASS] ObjectType  [METHOD] cast [RETURN_TYPE] ObjectType   JSType type [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  JSType  type  
[P6_Replace_Expression]^return type ( type.toObjectType (  ) ;^440^^^^^439^441^return type == null ? null : type.toObjectType (  ) ;^[CLASS] ObjectType  [METHOD] cast [RETURN_TYPE] ObjectType   JSType type [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  JSType  type  
[P7_Replace_Invocation]^return type == null ? null : type.testForEquality (  ) ;^440^^^^^439^441^return type == null ? null : type.toObjectType (  ) ;^[CLASS] ObjectType  [METHOD] cast [RETURN_TYPE] ObjectType   JSType type [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  JSType  type  
[P8_Replace_Mix]^return type == false ? false : type.testForEquality (  ) ;^440^^^^^439^441^return type == null ? null : type.toObjectType (  ) ;^[CLASS] ObjectType  [METHOD] cast [RETURN_TYPE] ObjectType   JSType type [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  JSType  type  
[P14_Delete_Statement]^^440^^^^^439^441^return type == null ? null : type.toObjectType (  ) ;^[CLASS] ObjectType  [METHOD] cast [RETURN_TYPE] ObjectType   JSType type [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  JSType  type  
[P14_Delete_Statement]^^448^^^^^447^449^return ImmutableSet.of (  ) ;^[CLASS] ObjectType  [METHOD] getCtorImplementedInterfaces [RETURN_TYPE] Iterable   [VARIABLES] JSDocInfo  docInfo  info  boolean  inExterns  inferred  unknown  visited  
