[REPLACE]^private static final String DECL_KEY  = null ;^8^^^^^^^[REPLACE] private static final String DECL_KEY = "declaration";^ [CLASS] XmlDeclaration  
[REPLACE]^super ( data ) ;^18^^^^^17^21^[REPLACE] super ( baseUri ) ;^[METHOD] <init> [TYPE] String,boolean) [PARAMETER] String data String baseUri boolean isProcessingInstruction [CLASS] XmlDeclaration   [TYPE]  boolean false  isProcessingInstruction  true  [TYPE]  String DECL_KEY  baseUri  data 
[ADD]^^18^^^^^17^21^[ADD] super ( baseUri ) ;^[METHOD] <init> [TYPE] String,boolean) [PARAMETER] String data String baseUri boolean isProcessingInstruction [CLASS] XmlDeclaration   [TYPE]  boolean false  isProcessingInstruction  true  [TYPE]  String DECL_KEY  baseUri  data 
[REPLACE]^attributes.put ( DECL_KEY, baseUri ) ;^19^^^^^17^21^[REPLACE] attributes.put ( DECL_KEY, data ) ;^[METHOD] <init> [TYPE] String,boolean) [PARAMETER] String data String baseUri boolean isProcessingInstruction [CLASS] XmlDeclaration   [TYPE]  boolean false  isProcessingInstruction  true  [TYPE]  String DECL_KEY  baseUri  data 
[REPLACE]^this.isProcessingInstruction =  true;^20^^^^^17^21^[REPLACE] this.isProcessingInstruction = isProcessingInstruction;^[METHOD] <init> [TYPE] String,boolean) [PARAMETER] String data String baseUri boolean isProcessingInstruction [CLASS] XmlDeclaration   [TYPE]  boolean false  isProcessingInstruction  true  [TYPE]  String DECL_KEY  baseUri  data 
[REPLACE]^return outerHtml (  ) ;^24^^^^^23^25^[REPLACE] return "#declaration";^[METHOD] nodeName [TYPE] String [PARAMETER] [CLASS] XmlDeclaration   [TYPE]  boolean false  isProcessingInstruction  true  [TYPE]  String DECL_KEY  baseUri  data 
[REPLACE]^return   DECL_KEY   ;^32^^^^^31^33^[REPLACE] return attributes.get ( DECL_KEY ) ;^[METHOD] getWholeDeclaration [TYPE] String [PARAMETER] [CLASS] XmlDeclaration   [TYPE]  boolean false  isProcessingInstruction  true  [TYPE]  String DECL_KEY  baseUri  data 
[REPLACE]^return outerHtml (  ) ;^36^^^^^35^37^[REPLACE] accum.append ( String.format ( "<%s%s>", isProcessingInstruction ? "!" : "?", getWholeDeclaration (  )  )  ) ;^[METHOD] outerHtml [TYPE] void [PARAMETER] StringBuilder accum [CLASS] XmlDeclaration   [TYPE]  StringBuilder accum  [TYPE]  boolean false  isProcessingInstruction  true  [TYPE]  String DECL_KEY  baseUri  data 
[ADD]^^36^37^^^^35^37^[ADD] accum.append ( String.format ( "<%s%s>", isProcessingInstruction ? "!" : "?", getWholeDeclaration (  )  )  ) ; }^[METHOD] outerHtml [TYPE] void [PARAMETER] StringBuilder accum [CLASS] XmlDeclaration   [TYPE]  StringBuilder accum  [TYPE]  boolean false  isProcessingInstruction  true  [TYPE]  String DECL_KEY  baseUri  data 
[REPLACE]^return "#declaration";^40^^^^^39^41^[REPLACE] return outerHtml (  ) ;^[METHOD] toString [TYPE] String [PARAMETER] [CLASS] XmlDeclaration   [TYPE]  boolean false  isProcessingInstruction  true  [TYPE]  String DECL_KEY  baseUri  data 
