[buglab_swap_variables]^return  ( Stroke )  key.get ( this.store ) ;^96^^^^^92^97^return  ( Stroke )  this.store.get ( key ) ;^[CLASS] StrokeMap  [METHOD] getStroke [RETURN_TYPE] Stroke   Comparable key [VARIABLES] Map  store  Comparable  key  boolean  
[buglab_swap_variables]^return key.containsKey ( this.store ) ;^109^^^^^108^110^return this.store.containsKey ( key ) ;^[CLASS] StrokeMap  [METHOD] containsKey [RETURN_TYPE] boolean   Comparable key [VARIABLES] Map  store  Comparable  key  boolean  
[buglab_swap_variables]^this.store.put ( stroke, key ) ;^123^^^^^119^124^this.store.put ( key, stroke ) ;^[CLASS] StrokeMap  [METHOD] put [RETURN_TYPE] void   Comparable key Stroke stroke [VARIABLES] Comparable  key  Stroke  stroke  boolean  Map  store  
[buglab_swap_variables]^this.store.put (  stroke ) ;^123^^^^^119^124^this.store.put ( key, stroke ) ;^[CLASS] StrokeMap  [METHOD] put [RETURN_TYPE] void   Comparable key Stroke stroke [VARIABLES] Comparable  key  Stroke  stroke  boolean  Map  store  
[buglab_swap_variables]^this.store.put ( key ) ;^123^^^^^119^124^this.store.put ( key, stroke ) ;^[CLASS] StrokeMap  [METHOD] put [RETURN_TYPE] void   Comparable key Stroke stroke [VARIABLES] Comparable  key  Stroke  stroke  boolean  Map  store  
[buglab_swap_variables]^if  ( that.size (  )  != this.store.store.size (  )  )  {^148^^^^^140^162^if  ( this.store.size (  )  != that.store.size (  )  )  {^[CLASS] StrokeMap  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Comparable  key  Stroke  s1  s2  Set  keys  boolean  Iterator  iterator  Object  obj  Map  store  StrokeMap  that  
[buglab_swap_variables]^if  ( that.store.size (  )  != this.store.size (  )  )  {^148^^^^^140^162^if  ( this.store.size (  )  != that.store.size (  )  )  {^[CLASS] StrokeMap  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Comparable  key  Stroke  s1  s2  Set  keys  boolean  Iterator  iterator  Object  obj  Map  store  StrokeMap  that  
[buglab_swap_variables]^if  ( this.store.size (  )  != that.store.store.size (  )  )  {^148^^^^^140^162^if  ( this.store.size (  )  != that.store.size (  )  )  {^[CLASS] StrokeMap  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Comparable  key  Stroke  s1  s2  Set  keys  boolean  Iterator  iterator  Object  obj  Map  store  StrokeMap  that  
[buglab_swap_variables]^if  ( this.store.size (  )  != that.size (  )  )  {^148^^^^^140^162^if  ( this.store.size (  )  != that.store.size (  )  )  {^[CLASS] StrokeMap  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Comparable  key  Stroke  s1  s2  Set  keys  boolean  Iterator  iterator  Object  obj  Map  store  StrokeMap  that  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( s2, s1 )  )  {^157^^^^^140^162^if  ( !ObjectUtilities.equal ( s1, s2 )  )  {^[CLASS] StrokeMap  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Comparable  key  Stroke  s1  s2  Set  keys  boolean  Iterator  iterator  Object  obj  Map  store  StrokeMap  that  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal (  s2 )  )  {^157^^^^^140^162^if  ( !ObjectUtilities.equal ( s1, s2 )  )  {^[CLASS] StrokeMap  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Comparable  key  Stroke  s1  s2  Set  keys  boolean  Iterator  iterator  Object  obj  Map  store  StrokeMap  that  
[buglab_swap_variables]^if  ( !ObjectUtilities.equal ( s1 )  )  {^157^^^^^140^162^if  ( !ObjectUtilities.equal ( s1, s2 )  )  {^[CLASS] StrokeMap  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Comparable  key  Stroke  s1  s2  Set  keys  boolean  Iterator  iterator  Object  obj  Map  store  StrokeMap  that  
[buglab_swap_variables]^Stroke s2 = key.getStroke ( that ) ;^156^^^^^140^162^Stroke s2 = that.getStroke ( key ) ;^[CLASS] StrokeMap  [METHOD] equals [RETURN_TYPE] boolean   Object obj [VARIABLES] Comparable  key  Stroke  s1  s2  Set  keys  boolean  Iterator  iterator  Object  obj  Map  store  StrokeMap  that  
[buglab_swap_variables]^SerialUtilities.writeStroke ( stream, stroke ) ;^193^^^^^184^195^SerialUtilities.writeStroke ( stroke, stream ) ;^[CLASS] StrokeMap  [METHOD] writeObject [RETURN_TYPE] void   ObjectOutputStream stream [VARIABLES] Comparable  key  Stroke  stroke  Set  keys  boolean  Iterator  iterator  ObjectOutputStream  stream  Map  store  
[buglab_swap_variables]^SerialUtilities.writeStroke (  stream ) ;^193^^^^^184^195^SerialUtilities.writeStroke ( stroke, stream ) ;^[CLASS] StrokeMap  [METHOD] writeObject [RETURN_TYPE] void   ObjectOutputStream stream [VARIABLES] Comparable  key  Stroke  stroke  Set  keys  boolean  Iterator  iterator  ObjectOutputStream  stream  Map  store  
[buglab_swap_variables]^SerialUtilities.writeStroke ( stroke ) ;^193^^^^^184^195^SerialUtilities.writeStroke ( stroke, stream ) ;^[CLASS] StrokeMap  [METHOD] writeObject [RETURN_TYPE] void   ObjectOutputStream stream [VARIABLES] Comparable  key  Stroke  stroke  Set  keys  boolean  Iterator  iterator  ObjectOutputStream  stream  Map  store  
[buglab_swap_variables]^for  ( keyCountnt i = 0; i < i; i++ )  {^210^^^^^205^215^for  ( int i = 0; i < keyCount; i++ )  {^[CLASS] StrokeMap  [METHOD] readObject [RETURN_TYPE] void   ObjectInputStream stream [VARIABLES] Comparable  key  Stroke  stroke  boolean  Map  store  int  i  keyCount  ObjectInputStream  stream  
[buglab_swap_variables]^for  ( int i = 0; i < key; i++ )  {^210^^^^^205^215^for  ( int i = 0; i < keyCount; i++ )  {^[CLASS] StrokeMap  [METHOD] readObject [RETURN_TYPE] void   ObjectInputStream stream [VARIABLES] Comparable  key  Stroke  stroke  boolean  Map  store  int  i  keyCount  ObjectInputStream  stream  
[buglab_swap_variables]^this.store.put ( stroke, key ) ;^213^^^^^205^215^this.store.put ( key, stroke ) ;^[CLASS] StrokeMap  [METHOD] readObject [RETURN_TYPE] void   ObjectInputStream stream [VARIABLES] Comparable  key  Stroke  stroke  boolean  Map  store  int  i  keyCount  ObjectInputStream  stream  
[buglab_swap_variables]^this.store.put (  stroke ) ;^213^^^^^205^215^this.store.put ( key, stroke ) ;^[CLASS] StrokeMap  [METHOD] readObject [RETURN_TYPE] void   ObjectInputStream stream [VARIABLES] Comparable  key  Stroke  stroke  boolean  Map  store  int  i  keyCount  ObjectInputStream  stream  
[buglab_swap_variables]^this.store.put ( key ) ;^213^^^^^205^215^this.store.put ( key, stroke ) ;^[CLASS] StrokeMap  [METHOD] readObject [RETURN_TYPE] void   ObjectInputStream stream [VARIABLES] Comparable  key  Stroke  stroke  boolean  Map  store  int  i  keyCount  ObjectInputStream  stream  
