[BugLab_Variable_Misuse]^if  ( v instanceof byte[] )  {^43^^^^^41^47^if  ( _value instanceof byte[] )  {^[CLASS] POJONode  [METHOD] binaryValue [RETURN_TYPE] byte[]   [VARIABLES] Object  _value  v  boolean  
[BugLab_Wrong_Operator]^if  ( _value  ==  byte[] )  {^43^^^^^41^47^if  ( _value instanceof byte[] )  {^[CLASS] POJONode  [METHOD] binaryValue [RETURN_TYPE] byte[]   [VARIABLES] Object  _value  v  boolean  
[BugLab_Variable_Misuse]^return  ( v == null )  ? "null" : _value.toString (  ) ;^57^^^^^56^58^return  ( _value == null )  ? "null" : _value.toString (  ) ;^[CLASS] POJONode  [METHOD] asText [RETURN_TYPE] String   [VARIABLES] Object  _value  v  boolean  
[BugLab_Wrong_Operator]^return  ( _value != null )  ? "null" : _value.toString (  ) ;^57^^^^^56^58^return  ( _value == null )  ? "null" : _value.toString (  ) ;^[CLASS] POJONode  [METHOD] asText [RETURN_TYPE] String   [VARIABLES] Object  _value  v  boolean  
[BugLab_Wrong_Operator]^if  ( _value != null || _value instanceof Boolean )  {^63^^^^^61^67^if  ( _value != null && _value instanceof Boolean )  {^[CLASS] POJONode  [METHOD] asBoolean [RETURN_TYPE] boolean   boolean defaultValue [VARIABLES] Object  _value  v  boolean  defaultValue  
[BugLab_Wrong_Operator]^if  ( _value == null && _value instanceof Boolean )  {^63^^^^^61^67^if  ( _value != null && _value instanceof Boolean )  {^[CLASS] POJONode  [METHOD] asBoolean [RETURN_TYPE] boolean   boolean defaultValue [VARIABLES] Object  _value  v  boolean  defaultValue  
[BugLab_Wrong_Operator]^if  ( _value != null && _value  ==  Boolean )  {^63^^^^^61^67^if  ( _value != null && _value instanceof Boolean )  {^[CLASS] POJONode  [METHOD] asBoolean [RETURN_TYPE] boolean   boolean defaultValue [VARIABLES] Object  _value  v  boolean  defaultValue  
[BugLab_Variable_Misuse]^if  ( v instanceof Number )  {^72^^^^^70^76^if  ( _value instanceof Number )  {^[CLASS] POJONode  [METHOD] asInt [RETURN_TYPE] int   int defaultValue [VARIABLES] Object  _value  v  int  defaultValue  boolean  
[BugLab_Wrong_Operator]^if  ( _value  <=  Number )  {^72^^^^^70^76^if  ( _value instanceof Number )  {^[CLASS] POJONode  [METHOD] asInt [RETURN_TYPE] int   int defaultValue [VARIABLES] Object  _value  v  int  defaultValue  boolean  
[BugLab_Variable_Misuse]^if  ( v instanceof Number )  {^81^^^^^79^85^if  ( _value instanceof Number )  {^[CLASS] POJONode  [METHOD] asLong [RETURN_TYPE] long   long defaultValue [VARIABLES] Object  _value  v  long  defaultValue  boolean  
[BugLab_Wrong_Operator]^if  ( _value  >=  Number )  {^81^^^^^79^85^if  ( _value instanceof Number )  {^[CLASS] POJONode  [METHOD] asLong [RETURN_TYPE] long   long defaultValue [VARIABLES] Object  _value  v  long  defaultValue  boolean  
[BugLab_Variable_Misuse]^if  ( v instanceof Number )  {^90^^^^^88^94^if  ( _value instanceof Number )  {^[CLASS] POJONode  [METHOD] asDouble [RETURN_TYPE] double   double defaultValue [VARIABLES] Object  _value  v  double  defaultValue  boolean  
[BugLab_Wrong_Operator]^if  ( _value  &  Number )  {^90^^^^^88^94^if  ( _value instanceof Number )  {^[CLASS] POJONode  [METHOD] asDouble [RETURN_TYPE] double   double defaultValue [VARIABLES] Object  _value  v  double  defaultValue  boolean  
[BugLab_Variable_Misuse]^if  ( v == null )  {^106^^^^^103^111^if  ( _value == null )  {^[CLASS] POJONode  [METHOD] serialize [RETURN_TYPE] void   JsonGenerator jg SerializerProvider provider [VARIABLES] JsonGenerator  jg  Object  _value  v  boolean  SerializerProvider  provider  
[BugLab_Wrong_Operator]^if  ( _value != null )  {^106^^^^^103^111^if  ( _value == null )  {^[CLASS] POJONode  [METHOD] serialize [RETURN_TYPE] void   JsonGenerator jg SerializerProvider provider [VARIABLES] JsonGenerator  jg  Object  _value  v  boolean  SerializerProvider  provider  
[BugLab_Variable_Misuse]^jg.writeObject ( v ) ;^109^^^^^103^111^jg.writeObject ( _value ) ;^[CLASS] POJONode  [METHOD] serialize [RETURN_TYPE] void   JsonGenerator jg SerializerProvider provider [VARIABLES] JsonGenerator  jg  Object  _value  v  boolean  SerializerProvider  provider  
[BugLab_Variable_Misuse]^if  ( v == this )  return true;^133^^^^^131^143^if  ( o == this )  return true;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Wrong_Operator]^if  ( o != this )  return true;^133^^^^^131^143^if  ( o == this )  return true;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Wrong_Literal]^if  ( o == this )  return false;^133^^^^^131^143^if  ( o == this )  return true;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Variable_Misuse]^if  ( v == null )  return false;^134^^^^^131^143^if  ( o == null )  return false;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Wrong_Operator]^if  ( o != null )  return false;^134^^^^^131^143^if  ( o == null )  return false;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Wrong_Literal]^if  ( o == null )  return true;^134^^^^^131^143^if  ( o == null )  return false;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Variable_Misuse]^if  ( v.getClass (  )  != getClass (  )  )  {^135^^^^^131^143^if  ( o.getClass (  )  != getClass (  )  )  {^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Wrong_Operator]^if  ( o.getClass (  )  == getClass (  )  )  {^135^^^^^131^143^if  ( o.getClass (  )  != getClass (  )  )  {^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Wrong_Literal]^return true;^136^^^^^131^143^return false;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Variable_Misuse]^if  ( v == null )  {^139^^^^^131^143^if  ( _value == null )  {^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Wrong_Operator]^if  ( _value != null )  {^139^^^^^131^143^if  ( _value == null )  {^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Variable_Misuse]^return v == null;^140^^^^^131^143^return other._value == null;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Argument_Swapping]^return other._value._value == null;^140^^^^^131^143^return other._value == null;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Argument_Swapping]^return other == null;^140^^^^^131^143^return other._value == null;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Wrong_Operator]^return other._value != null;^140^^^^^131^143^return other._value == null;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Variable_Misuse]^return v.equals ( other._value ) ;^142^^^^^131^143^return _value.equals ( other._value ) ;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Variable_Misuse]^return _value.equals ( v ) ;^142^^^^^131^143^return _value.equals ( other._value ) ;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Argument_Swapping]^return _value.equals ( other._value._value ) ;^142^^^^^131^143^return _value.equals ( other._value ) ;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Argument_Swapping]^return other._value.equals ( _value ) ;^142^^^^^131^143^return _value.equals ( other._value ) ;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Variable_Misuse]^return _value.equals ( o ) ;^142^^^^^131^143^return _value.equals ( other._value ) ;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Argument_Swapping]^return other.equals ( _value._value ) ;^142^^^^^131^143^return _value.equals ( other._value ) ;^[CLASS] POJONode  [METHOD] equals [RETURN_TYPE] boolean   Object o [VARIABLES] POJONode  other  Object  _value  o  v  boolean  
[BugLab_Variable_Misuse]^public int hashCode (  )  { return v.hashCode (  ) ; }^146^^^^^141^151^public int hashCode (  )  { return _value.hashCode (  ) ; }^[CLASS] POJONode  [METHOD] hashCode [RETURN_TYPE] int   [VARIABLES] Object  _value  o  v  boolean  
[BugLab_Variable_Misuse]^return String.valueOf ( v ) ;^151^^^^^149^152^return String.valueOf ( _value ) ;^[CLASS] POJONode  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] Object  _value  o  v  boolean  
