[buglab_swap_variables]^int amount = BaseSingleFieldPeriod.between ( end, start, DurationFieldType.months (  )  ) ;^137^^^^^136^139^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.months (  )  ) ;^[CLASS] Months  [METHOD] monthsBetween [RETURN_TYPE] Months   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  boolean  Months  EIGHT  ELEVEN  FIVE  FOUR  MAX_VALUE  MIN_VALUE  NINE  ONE  SEVEN  SIX  TEN  THREE  TWELVE  TWO  ZERO  long  serialVersionUID  int  amount  
[buglab_swap_variables]^int amount = BaseSingleFieldPeriod.between (  end, DurationFieldType.months (  )  ) ;^137^^^^^136^139^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.months (  )  ) ;^[CLASS] Months  [METHOD] monthsBetween [RETURN_TYPE] Months   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  boolean  Months  EIGHT  ELEVEN  FIVE  FOUR  MAX_VALUE  MIN_VALUE  NINE  ONE  SEVEN  SIX  TEN  THREE  TWELVE  TWO  ZERO  long  serialVersionUID  int  amount  
[buglab_swap_variables]^int amount = BaseSingleFieldPeriod.between ( start,  DurationFieldType.months (  )  ) ;^137^^^^^136^139^int amount = BaseSingleFieldPeriod.between ( start, end, DurationFieldType.months (  )  ) ;^[CLASS] Months  [METHOD] monthsBetween [RETURN_TYPE] Months   ReadableInstant start ReadableInstant end [VARIABLES] ReadableInstant  end  start  boolean  Months  EIGHT  ELEVEN  FIVE  FOUR  MAX_VALUE  MIN_VALUE  NINE  ONE  SEVEN  SIX  TEN  THREE  TWELVE  TWO  ZERO  long  serialVersionUID  int  amount  
[buglab_swap_variables]^if  ( end instanceof LocalDate && start instanceof LocalDate )    {^154^^^^^153^162^if  ( start instanceof LocalDate && end instanceof LocalDate )    {^[CLASS] Months  [METHOD] monthsBetween [RETURN_TYPE] Months   ReadablePartial start ReadablePartial end [VARIABLES] ReadablePartial  end  start  Chronology  chrono  boolean  Months  EIGHT  ELEVEN  FIVE  FOUR  MAX_VALUE  MIN_VALUE  NINE  ONE  SEVEN  SIX  TEN  THREE  TWELVE  TWO  ZERO  long  serialVersionUID  int  amount  months  
[buglab_swap_variables]^int amount = BaseSingleFieldPeriod.between ( end, start, ZERO ) ;^160^^^^^153^162^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Months  [METHOD] monthsBetween [RETURN_TYPE] Months   ReadablePartial start ReadablePartial end [VARIABLES] ReadablePartial  end  start  Chronology  chrono  boolean  Months  EIGHT  ELEVEN  FIVE  FOUR  MAX_VALUE  MIN_VALUE  NINE  ONE  SEVEN  SIX  TEN  THREE  TWELVE  TWO  ZERO  long  serialVersionUID  int  amount  months  
[buglab_swap_variables]^int amount = BaseSingleFieldPeriod.between (  end, ZERO ) ;^160^^^^^153^162^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Months  [METHOD] monthsBetween [RETURN_TYPE] Months   ReadablePartial start ReadablePartial end [VARIABLES] ReadablePartial  end  start  Chronology  chrono  boolean  Months  EIGHT  ELEVEN  FIVE  FOUR  MAX_VALUE  MIN_VALUE  NINE  ONE  SEVEN  SIX  TEN  THREE  TWELVE  TWO  ZERO  long  serialVersionUID  int  amount  months  
[buglab_swap_variables]^int amount = BaseSingleFieldPeriod.between ( start,  ZERO ) ;^160^^^^^153^162^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Months  [METHOD] monthsBetween [RETURN_TYPE] Months   ReadablePartial start ReadablePartial end [VARIABLES] ReadablePartial  end  start  Chronology  chrono  boolean  Months  EIGHT  ELEVEN  FIVE  FOUR  MAX_VALUE  MIN_VALUE  NINE  ONE  SEVEN  SIX  TEN  THREE  TWELVE  TWO  ZERO  long  serialVersionUID  int  amount  months  
[buglab_swap_variables]^int amount = BaseSingleFieldPeriod.between ( start, ZERO, end ) ;^160^^^^^153^162^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Months  [METHOD] monthsBetween [RETURN_TYPE] Months   ReadablePartial start ReadablePartial end [VARIABLES] ReadablePartial  end  start  Chronology  chrono  boolean  Months  EIGHT  ELEVEN  FIVE  FOUR  MAX_VALUE  MIN_VALUE  NINE  ONE  SEVEN  SIX  TEN  THREE  TWELVE  TWO  ZERO  long  serialVersionUID  int  amount  months  
[buglab_swap_variables]^int amount = BaseSingleFieldPeriod.between ( start, end ) ;^160^^^^^153^162^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Months  [METHOD] monthsBetween [RETURN_TYPE] Months   ReadablePartial start ReadablePartial end [VARIABLES] ReadablePartial  end  start  Chronology  chrono  boolean  Months  EIGHT  ELEVEN  FIVE  FOUR  MAX_VALUE  MIN_VALUE  NINE  ONE  SEVEN  SIX  TEN  THREE  TWELVE  TWO  ZERO  long  serialVersionUID  int  amount  months  
[buglab_swap_variables]^int amount = BaseSingleFieldPeriod.between ( ZERO, end, start ) ;^160^^^^^153^162^int amount = BaseSingleFieldPeriod.between ( start, end, ZERO ) ;^[CLASS] Months  [METHOD] monthsBetween [RETURN_TYPE] Months   ReadablePartial start ReadablePartial end [VARIABLES] ReadablePartial  end  start  Chronology  chrono  boolean  Months  EIGHT  ELEVEN  FIVE  FOUR  MAX_VALUE  MIN_VALUE  NINE  ONE  SEVEN  SIX  TEN  THREE  TWELVE  TWO  ZERO  long  serialVersionUID  int  amount  months  
