[REPLACE]^private Reporter reporter  = null ;^13^^^^^^^[REPLACE] private Reporter reporter = new Reporter (  ) ;^ [CLASS] AnswersValidator  
[REPLACE]^if  ( ! answer instanceof ThrowsException )  {^16^^^^^15^27^[REPLACE] if  ( answer instanceof ThrowsException )  {^[METHOD] validate [TYPE] void [PARAMETER] Answer<?> answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Answer answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^validateDoNothing (  ( DoesNothing )  answer, invocation ) ;^17^^^^^15^27^[REPLACE] validateException (  ( ThrowsException )  answer, invocation ) ;^[METHOD] validate [TYPE] void [PARAMETER] Answer<?> answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Answer answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^if  ( ! answer instanceof Returns )  {^20^^^^^15^27^[REPLACE] if  ( answer instanceof Returns )  {^[METHOD] validate [TYPE] void [PARAMETER] Answer<?> answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Answer answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , "null", invocation.getMethodName (  )  ) ;^21^^^^^15^27^[REPLACE] validateReturnValue (  ( Returns )  answer, invocation ) ;^[METHOD] validate [TYPE] void [PARAMETER] Answer<?> answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Answer answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^if  ( ! answer instanceof DoesNothing )  {^24^^^^^15^27^[REPLACE] if  ( answer instanceof DoesNothing )  {^[METHOD] validate [TYPE] void [PARAMETER] Answer<?> answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Answer answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^validateReturnValue (  ( Returns )  answer, invocation ) ;^25^^^^^15^27^[REPLACE] validateDoNothing (  ( DoesNothing )  answer, invocation ) ;^[METHOD] validate [TYPE] void [PARAMETER] Answer<?> answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Answer answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^if  ( !invocation.isValidException (  )  )  {^30^^^^^29^33^[REPLACE] if  ( !invocation.isVoid (  )  )  {^[METHOD] validateDoNothing [TYPE] void [PARAMETER] DoesNothing answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  DoesNothing answer  [TYPE]  Reporter reporter 
[REPLACE]^reporter.cannotStubVoidMethodWithAReturnValue (  ) ;^31^^^^^29^33^[REPLACE] reporter.onlyVoidMethodsCanBeSetToDoNothing (  ) ;^[METHOD] validateDoNothing [TYPE] void [PARAMETER] DoesNothing answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  DoesNothing answer  [TYPE]  Reporter reporter 
[REPLACE]^if  ( !invocation.isVoid (  )  )  {^36^^^^^35^47^[REPLACE] if  ( invocation.isVoid (  )  )  {^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^reporter.cannotStubWithNullThrowable (  ) ;^37^^^^^35^47^[REPLACE] reporter.cannotStubVoidMethodWithAReturnValue (  ) ;^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^if  (  invocation.returnsPrimitive (  )  )  {^40^^^^^35^47^[REPLACE] if  ( answer.returnsNull (  )  && invocation.returnsPrimitive (  )  )  {^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[ADD]^reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , "null", invocation.getMethodName (  )  ) ;^40^41^42^^^35^47^[ADD] if  ( answer.returnsNull (  )  && invocation.returnsPrimitive (  )  )  { reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , "null", invocation.getMethodName (  )  ) ; }^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , "false", invocation.printMethodReturnType (  )  ) ;^41^^^^^35^47^[REPLACE] reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , "null", invocation.getMethodName (  )  ) ;^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^reporter.wrongTypeOfReturnValue ( invocation.isValidReturnType (  ) , "null", invocation.getMethodName (  )  ) ;^41^^^^^35^47^[REPLACE] reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , "null", invocation.getMethodName (  )  ) ;^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REMOVE]^validateDoNothing (  ( DoesNothing )  answer, invocation ) ;^41^^^^^35^47^[REMOVE] ^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , "null", invocation.printMethodReturnType (  )  ) ;^41^^^^^35^47^[REPLACE] reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , "null", invocation.getMethodName (  )  ) ;^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^if  (  !invocation.isValidReturnType ( answer.getReturnType (  )  )  )  {^44^^^^^35^47^[REPLACE] if  ( !answer.returnsNull (  )  && !invocation.isValidReturnType ( answer.getReturnType (  )  )  )  {^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , answer.printReturnType (  ) , invocation.printMethodReturnType (  )  ) ;^45^^^^^35^47^[REPLACE] reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , answer.printReturnType (  ) , invocation.getMethodName (  )  ) ;^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^reporter.wrongTypeOfReturnValue ( invocation .isValidReturnType (  )  , answer.printReturnType (  ) , invocation.getMethodName (  )  ) ;^45^^^^^35^47^[REPLACE] reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , answer.printReturnType (  ) , invocation.getMethodName (  )  ) ;^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , answer.getReturnType (  ) , invocation.getMethodName (  )  ) ;^45^^^^^35^47^[REPLACE] reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , answer.printReturnType (  ) , invocation.getMethodName (  )  ) ;^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REMOVE]^reporter.wrongTypeOfReturnValue ( invocation.printMethodReturnType (  ) , "null", invocation.getMethodName (  )  ) ;^45^^^^^35^47^[REMOVE] ^[METHOD] validateReturnValue [TYPE] void [PARAMETER] Returns answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Returns answer  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  Reporter reporter 
[REPLACE]^if  ( throwable != null )  {^51^^^^^49^62^[REPLACE] if  ( throwable == null )  {^[METHOD] validateException [TYPE] void [PARAMETER] ThrowsException answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Throwable throwable  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  ThrowsException answer  [TYPE]  Reporter reporter 
[ADD]^^51^52^53^^^49^62^[ADD] if  ( throwable == null )  { reporter.cannotStubWithNullThrowable (  ) ; }^[METHOD] validateException [TYPE] void [PARAMETER] ThrowsException answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Throwable throwable  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  ThrowsException answer  [TYPE]  Reporter reporter 
[REPLACE]^reporter.cannotStubVoidMethodWithAReturnValue (  ) ;^52^^^^^49^62^[REPLACE] reporter.cannotStubWithNullThrowable (  ) ;^[METHOD] validateException [TYPE] void [PARAMETER] ThrowsException answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Throwable throwable  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  ThrowsException answer  [TYPE]  Reporter reporter 
[REPLACE]^if  (  throwable instanceof Error )  {^55^^^^^49^62^[REPLACE] if  ( throwable instanceof RuntimeException || throwable instanceof Error )  {^[METHOD] validateException [TYPE] void [PARAMETER] ThrowsException answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Throwable throwable  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  ThrowsException answer  [TYPE]  Reporter reporter 
[REPLACE]^if  ( answer instanceof Returns )  {^59^^^^^49^62^[REPLACE] if   (" ")   {^[METHOD] validateException [TYPE] void [PARAMETER] ThrowsException answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Throwable throwable  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  ThrowsException answer  [TYPE]  Reporter reporter 
[REMOVE]^if  ( ! ( invocation.isVoid (  )  )  )  {     reporter.onlyVoidMethodsCanBeSetToDoNothing (  ) ; }^59^^^^^49^62^[REMOVE] ^[METHOD] validateException [TYPE] void [PARAMETER] ThrowsException answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Throwable throwable  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  ThrowsException answer  [TYPE]  Reporter reporter 
[REPLACE]^reporter .onlyVoidMethodsCanBeSetToDoNothing (  )  ;^60^^^^^49^62^[REPLACE] reporter.checkedExceptionInvalid ( throwable ) ;^[METHOD] validateException [TYPE] void [PARAMETER] ThrowsException answer Invocation invocation [CLASS] AnswersValidator   [TYPE]  Throwable throwable  [TYPE]  boolean false  true  [TYPE]  Invocation invocation  [TYPE]  ThrowsException answer  [TYPE]  Reporter reporter 
