[BugLab_Variable_Misuse]^iValue = iValue;^122^^^^^120^123^iValue = value;^[CLASS] ValuedEnum  [METHOD] <init> [RETURN_TYPE] String,int)   String name int value [VARIABLES] String  name  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^if  ( enumClass != null )  {^138^^^^^137^149^if  ( enumClass == null )  {^[CLASS] ValuedEnum  [METHOD] getEnum [RETURN_TYPE] Enum   Class enumClass int value [VARIABLES] Iterator  it  Class  enumClass  List  list  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Variable_Misuse]^return value -  (  ( ValuedEnum )  other ) .iValue;^174^^^^^173^175^return iValue -  (  ( ValuedEnum )  other ) .iValue;^[CLASS] ValuedEnum  [METHOD] compareTo [RETURN_TYPE] int   Object other [VARIABLES] Object  other  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^return iValue  &&   (  ( ValuedEnum )  other ) .iValue;^174^^^^^173^175^return iValue -  (  ( ValuedEnum )  other ) .iValue;^[CLASS] ValuedEnum  [METHOD] compareTo [RETURN_TYPE] int   Object other [VARIABLES] Object  other  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^if  ( iToString != null )  {^185^^^^^184^190^if  ( iToString == null )  {^[CLASS] ValuedEnum  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] String  shortName  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^iToString = shortName + "[" + getName (  !=  )  + "=" + getValue (  )  + "]";^187^^^^^184^190^iToString = shortName + "[" + getName (  )  + "=" + getValue (  )  + "]";^[CLASS] ValuedEnum  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] String  shortName  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^iToString = shortName + "[" + getName (  >=  )  + "=" + getValue (  )  + "]";^187^^^^^184^190^iToString = shortName + "[" + getName (  )  + "=" + getValue (  )  + "]";^[CLASS] ValuedEnum  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] String  shortName  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^iToString = shortName + "[" + getName (  <<  )  + "=" + getValue (  )  + "]";^187^^^^^184^190^iToString = shortName + "[" + getName (  )  + "=" + getValue (  )  + "]";^[CLASS] ValuedEnum  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] String  shortName  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^iToString = shortName  &&  "["  &&  getName (  )  + "=" + getValue (  )  + "]";^187^^^^^184^190^iToString = shortName + "[" + getName (  )  + "=" + getValue (  )  + "]";^[CLASS] ValuedEnum  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] String  shortName  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^iToString = shortName  >  "[" + getName (  )  + "=" + getValue (  )  + "]";^187^^^^^184^190^iToString = shortName + "[" + getName (  )  + "=" + getValue (  )  + "]";^[CLASS] ValuedEnum  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] String  shortName  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^iToString = shortName + "[" + getName (  >>  )  + "=" + getValue (  )  + "]";^187^^^^^184^190^iToString = shortName + "[" + getName (  )  + "=" + getValue (  )  + "]";^[CLASS] ValuedEnum  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] String  shortName  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^iToString = shortName + "[" + getName (  <  )  + "=" + getValue (  )  + "]";^187^^^^^184^190^iToString = shortName + "[" + getName (  )  + "=" + getValue (  )  + "]";^[CLASS] ValuedEnum  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] String  shortName  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^iToString = shortName + "[" + getName (  ||  )  + "=" + getValue (  )  + "]";^187^^^^^184^190^iToString = shortName + "[" + getName (  )  + "=" + getValue (  )  + "]";^[CLASS] ValuedEnum  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] String  shortName  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^iToString = shortName  >  "["  >  getName (  )  + "=" + getValue (  )  + "]";^187^^^^^184^190^iToString = shortName + "[" + getName (  )  + "=" + getValue (  )  + "]";^[CLASS] ValuedEnum  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] String  shortName  boolean  long  serialVersionUID  int  iValue  value  
[BugLab_Wrong_Operator]^iToString = shortName  >>  "[" + getName (  )  + "=" + getValue (  )  + "]";^187^^^^^184^190^iToString = shortName + "[" + getName (  )  + "=" + getValue (  )  + "]";^[CLASS] ValuedEnum  [METHOD] toString [RETURN_TYPE] String   [VARIABLES] String  shortName  boolean  long  serialVersionUID  int  iValue  value  
