[buglab_swap_variables]^return findRootName ( config.getRawClass (  ) , rootType ) ;^41^^^^^40^42^return findRootName ( rootType.getRawClass (  ) , config ) ;^[CLASS] XmlRootNameLookup  [METHOD] findRootName [RETURN_TYPE] QName   JavaType rootType MapperConfig<?> config [VARIABLES] MapperConfig  config  JavaType  rootType  boolean  LRUMap  _rootNames  long  serialVersionUID  
[buglab_swap_variables]^return findRootName ( rootType.getRawClass (  )  ) ;^41^^^^^40^42^return findRootName ( rootType.getRawClass (  ) , config ) ;^[CLASS] XmlRootNameLookup  [METHOD] findRootName [RETURN_TYPE] QName   JavaType rootType MapperConfig<?> config [VARIABLES] MapperConfig  config  JavaType  rootType  boolean  LRUMap  _rootNames  long  serialVersionUID  
[buglab_swap_variables]^name = key.get ( _rootNames ) ;^49^^^^^44^59^name = _rootNames.get ( key ) ;^[CLASS] XmlRootNameLookup  [METHOD] findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] boolean  LRUMap  _rootNames  QName  name  ClassKey  key  MapperConfig  config  Class  rootType  long  serialVersionUID  
[buglab_swap_variables]^name = _findRootName ( config, rootType ) ;^54^^^^^44^59^name = _findRootName ( rootType, config ) ;^[CLASS] XmlRootNameLookup  [METHOD] findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] boolean  LRUMap  _rootNames  QName  name  ClassKey  key  MapperConfig  config  Class  rootType  long  serialVersionUID  
[buglab_swap_variables]^name = _findRootName (  config ) ;^54^^^^^44^59^name = _findRootName ( rootType, config ) ;^[CLASS] XmlRootNameLookup  [METHOD] findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] boolean  LRUMap  _rootNames  QName  name  ClassKey  key  MapperConfig  config  Class  rootType  long  serialVersionUID  
[buglab_swap_variables]^name = _findRootName ( rootType ) ;^54^^^^^44^59^name = _findRootName ( rootType, config ) ;^[CLASS] XmlRootNameLookup  [METHOD] findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] boolean  LRUMap  _rootNames  QName  name  ClassKey  key  MapperConfig  config  Class  rootType  long  serialVersionUID  
[buglab_swap_variables]^_rootNames.put (  name ) ;^56^^^^^44^59^_rootNames.put ( key, name ) ;^[CLASS] XmlRootNameLookup  [METHOD] findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] boolean  LRUMap  _rootNames  QName  name  ClassKey  key  MapperConfig  config  Class  rootType  long  serialVersionUID  
[buglab_swap_variables]^_rootNames.put ( key ) ;^56^^^^^44^59^_rootNames.put ( key, name ) ;^[CLASS] XmlRootNameLookup  [METHOD] findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] boolean  LRUMap  _rootNames  QName  name  ClassKey  key  MapperConfig  config  Class  rootType  long  serialVersionUID  
[buglab_swap_variables]^BeanDescription beanDesc = rootType.introspectClassAnnotations ( config ) ;^65^^^^^64^91^BeanDescription beanDesc = config.introspectClassAnnotations ( rootType ) ;^[CLASS] XmlRootNameLookup  [METHOD] _findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] PropertyName  root  boolean  AnnotatedClass  ac  LRUMap  _rootNames  BeanDescription  beanDesc  AnnotationIntrospector  intr  MapperConfig  config  Class  rootType  String  localName  ns  long  serialVersionUID  
[buglab_swap_variables]^PropertyName root = ac.findRootName ( intr ) ;^71^^^^^64^91^PropertyName root = intr.findRootName ( ac ) ;^[CLASS] XmlRootNameLookup  [METHOD] _findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] PropertyName  root  boolean  AnnotatedClass  ac  LRUMap  _rootNames  BeanDescription  beanDesc  AnnotationIntrospector  intr  MapperConfig  config  Class  rootType  String  localName  ns  long  serialVersionUID  
[buglab_swap_variables]^ns = findNamespace ( ac, intr ) ;^85^^^^^64^91^ns = findNamespace ( intr, ac ) ;^[CLASS] XmlRootNameLookup  [METHOD] _findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] PropertyName  root  boolean  AnnotatedClass  ac  LRUMap  _rootNames  BeanDescription  beanDesc  AnnotationIntrospector  intr  MapperConfig  config  Class  rootType  String  localName  ns  long  serialVersionUID  
[buglab_swap_variables]^ns = findNamespace (  ac ) ;^85^^^^^64^91^ns = findNamespace ( intr, ac ) ;^[CLASS] XmlRootNameLookup  [METHOD] _findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] PropertyName  root  boolean  AnnotatedClass  ac  LRUMap  _rootNames  BeanDescription  beanDesc  AnnotationIntrospector  intr  MapperConfig  config  Class  rootType  String  localName  ns  long  serialVersionUID  
[buglab_swap_variables]^ns = findNamespace ( intr ) ;^85^^^^^64^91^ns = findNamespace ( intr, ac ) ;^[CLASS] XmlRootNameLookup  [METHOD] _findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] PropertyName  root  boolean  AnnotatedClass  ac  LRUMap  _rootNames  BeanDescription  beanDesc  AnnotationIntrospector  intr  MapperConfig  config  Class  rootType  String  localName  ns  long  serialVersionUID  
[buglab_swap_variables]^return new QName ( localName, ns ) ;^90^^^^^64^91^return new QName ( ns, localName ) ;^[CLASS] XmlRootNameLookup  [METHOD] _findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] PropertyName  root  boolean  AnnotatedClass  ac  LRUMap  _rootNames  BeanDescription  beanDesc  AnnotationIntrospector  intr  MapperConfig  config  Class  rootType  String  localName  ns  long  serialVersionUID  
[buglab_swap_variables]^return new QName (  localName ) ;^90^^^^^64^91^return new QName ( ns, localName ) ;^[CLASS] XmlRootNameLookup  [METHOD] _findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] PropertyName  root  boolean  AnnotatedClass  ac  LRUMap  _rootNames  BeanDescription  beanDesc  AnnotationIntrospector  intr  MapperConfig  config  Class  rootType  String  localName  ns  long  serialVersionUID  
[buglab_swap_variables]^return new QName ( ns ) ;^90^^^^^64^91^return new QName ( ns, localName ) ;^[CLASS] XmlRootNameLookup  [METHOD] _findRootName [RETURN_TYPE] QName   Class<?> rootType MapperConfig<?> config [VARIABLES] PropertyName  root  boolean  AnnotatedClass  ac  LRUMap  _rootNames  BeanDescription  beanDesc  AnnotationIntrospector  intr  MapperConfig  config  Class  rootType  String  localName  ns  long  serialVersionUID  
